### ISSUE TITLE
VV Error

### ISSUE THREAD

**Issue by Yapperyapps** [ViaVersion/ViaVersion#1293]
**Describe the bug, provide any errors**
Unknown bug. 
Error:
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: String, Source #0: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous), Data: [Pair{Type|VarInt, 0}], Packet ID: 0}
Actual Error:
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(47) exceeds writerIndex(3): UnpooledSlicedByteBuf(ridx: 3, widx: 3, cap: 3/3, unwrapped: PooledUnsafeDirectByteBuf(ridx: 4, widx: 47, cap: 47))
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1392)
at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:872)
at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:880)
at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:19)
at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:8)
at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:145)
at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:94)
at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:149)
at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:93)
at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:425)
at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82)
at us.myles.ViaVersion.bungee.handlers.BungeeDecodeHandler.decode(BungeeDecodeHandler.java:53)
at us.myles.ViaVersion.bungee.handlers.BungeeDecodeHandler.decode(BungeeDecodeHandler.java:17)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:236)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:494)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)

**How can we reproduce it?**
Unknown

**Expected behaviour**
Unknown

**Screenshots**
Null

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.

**Additional server info**
Do you use a proxy (eg. BungeeCord)? Yes

**Comment by MylesIsCool** [comment]
This is someone sending bad data to your bungee, you can firewall them or just ignore.
