### ISSUE TITLE
1 14

### ISSUE THREAD

**Issue by DenisJ9798** [ViaVersion/ViaVersion#1307]
12:38:56 [SEVERE] [XaTTaBlIc] <-> InitialHandler - encountered exception
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Source #1: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$10 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$10$2 (Anonymous), Data: [Pair{Type|Integer, 91434990}, Pair{Type|Unsigned Byte, 2}, Pair{Type|Integer, 0}, Pair{Type|Unsigned Byte, 4}], Packet ID: 37}
Actual Error: 
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1061)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:299)
	at ru.leymooo.botfilter.caching.PacketUtils.spawnPlayer(PacketUtils.java:258)
	at ru.leymooo.botfilter.Connector.<init>(Connector.java:80)
	at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:548)
	at net.md_5.bungee.connection.InitialHandler.access$700(InitialHandler.java:76)
	at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:409)
	at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:390)
	at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:40)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
	at net.md_5.bungee.connection.InitialHandler.delayedHandleOfLoginRequset(InitialHandler.java:425)
	at ru.leymooo.botfilter.BotFilter.checkAsyncIfNeeded(BotFilter.java:299)
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:356)
	at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)

**Comment by krusic22** [comment]
Update all your Via* plugins.
