### ISSUE TITLE
BungeeServerHandler.checkServerChange - java.lang.NullPointerException

### ISSUE THREAD

**Issue by xXSchrandXx** [ViaVersion/ViaVersion#1371]
**How can we reproduce it?**
1. Running Server with [BungeeTablistPlus](https://www.spigotmc.org/resources/bungeetablistplus.313/)
2. Join the Server

**Expected behaviour**
No Error and a working TabList

**ViaVersion Dump:**
[/viaversion dump](https://dump.viaversion.com/12063d8c7515acd5584177b62d1b67bcc5e1ee292f099327146731e40e239009)

**Startup Error**
``` ERROR
[17:34:50] [ViaVersion/INFO] > Loading 1.12.2 -> 1.13 block mapping...
[17:34:50] [ViaVersion/WARN] > You are running a development version, please report any bugs to GitHub.
[17:34:50] [ViaVersion/INFO] > Loading 1.12.2 -> 1.13 item mapping...
[17:34:50] [ViaVersion/INFO] > Loading new 1.13 tags...
[17:34:50] [ViaVersion/INFO] > Loading 1.12.2 -> 1.13 enchantment mapping...
[17:34:50] [ViaVersion/INFO] > Loading 1.12.2 -> 1.13 sound mapping...
[17:34:50] [ViaVersion/INFO] > Loading translation mappping
[17:34:50] [ViaVersion/INFO] > Loading block connection mappings ...
[17:34:50] [ViaVersion/INFO] > Loading 1.13.2 -> 1.14 blockstate mapping...
[17:34:51] [ViaVersion/INFO] > Loading 1.13.2 -> 1.14 block mapping...
[17:34:51] [ViaVersion/INFO] > Loading 1.13.2 -> 1.14 item mapping...
[17:34:51] [ViaVersion/INFO] > Loading 1.13.2 -> 1.14 sound mapping...
[17:34:51] [ViaVersion/INFO] > Loading 1.14 blockstates...
[17:34:51] [ViaVersion/INFO] > Loading 1.14 heightmap data...
[17:34:51] [ViaVersion/INFO] > ViaVersion detected server version: 1.7-1.7.5(4)
[17:34:51] [ViaVersion/WARN] > ViaVersion does not have any compatible versions for this server version, please read our resource page carefully.
[17:34:51] [ViaVersion/ERROR] > java.lang.NoSuchFieldException: ch
[17:34:51] [ViaVersion/ERROR] > 	at java.lang.Class.getDeclaredField(Class.java:2070)
[17:34:51] [ViaVersion/ERROR] > 	at us.myles.ViaVersion.bungee.handlers.BungeeServerHandler.<clinit>(BungeeServerHandler.java:57)
[17:34:51] [ViaVersion/ERROR] > 	at us.myles.ViaVersion.bungee.platform.BungeeViaLoader.load(BungeeViaLoader.java:44)
[17:34:51] [ViaVersion/ERROR] > 	at us.myles.ViaVersion.ViaManager.onServerLoaded(ViaManager.java:90)
[17:34:51] [ViaVersion/ERROR] > 	at us.myles.ViaVersion.ViaManager$1.run(ViaManager.java:65)
[17:34:51] [ViaVersion/ERROR] > 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
[17:34:51] [ViaVersion/ERROR] > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[17:34:51] [ViaVersion/ERROR] > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[17:34:51] [ViaVersion/ERROR] > 	at java.lang.Thread.run(Thread.java:748)
```

**Onjoin Error**

``` ERROR
[17:35:46] [ViaVersion/ERROR] > java.lang.NullPointerException
[17:35:46] [ViaVersion/ERROR] > 	at us.myles.ViaVersion.bungee.handlers.BungeeServerHandler.checkServerChange(BungeeServerHandler.java:243)
[17:35:46] [ViaVersion/ERROR] > 	at us.myles.ViaVersion.bungee.handlers.BungeeServerHandler.onServerConnected(BungeeServerHandler.java:91)
[17:35:46] [ViaVersion/ERROR] > 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:35:46] [ViaVersion/ERROR] > 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:35:46] [ViaVersion/ERROR] > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:35:46] [ViaVersion/ERROR] > 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:35:46] [ViaVersion/ERROR] > 	at net.md_5.bungee.event.EventBus$1.run(EventBus.java:88)
[17:35:46] [ViaVersion/ERROR] > 	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
[17:35:46] [ViaVersion/ERROR] > 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:35:46] [ViaVersion/ERROR] > 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:35:46] [ViaVersion/ERROR] > 	at net.ME1312.Galaxi.Plugin.PluginManager.executeEvent(PluginManager.java:237)
[17:35:46] [ViaVersion/ERROR] > 	at net.ME1312.Galaxi.Plugin.PluginManager.executeEvent(PluginManager.java:202)
[17:35:46] [ViaVersion/ERROR] > 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:406)
[17:35:46] [ViaVersion/ERROR] > 	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:202)
[17:35:46] [ViaVersion/ERROR] > 	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:87)
[17:35:46] [ViaVersion/ERROR] > 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
[17:35:46] [ViaVersion/ERROR] > 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
[17:35:46] [ViaVersion/ERROR] > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MylesIsCool** [comment]
ViaVersion doesn't support your modified bungee.
