### ISSUE TITLE
onEnable error.

### ISSUE THREAD

**Issue by TheGaming999** [ViaVersion/ViaVersion#1381]
I use the plugin in 1.8 paperspigot server. Edit: this also happens in 1.8.8 spigot server.
`s/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/InventoryPackets$1 initializing ViaVersion v2.1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: us/myles/ViaVersion/protocols/protocol1_14to1_13_2/packets/InventoryPackets$1
at us.myles.ViaVersion.protocols.protocol1_14to1_13_2.Protocol1_14To1_13_2.registerPackets(Protocol1_14To1_13_2.java:27) ~[?:?]
at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:25) ~[?:?]
at us.myles.ViaVersion.protocols.protocol1_14to1_13_2.Protocol1_14To1_13_2.<init>(Protocol1_14To1_13_2.java:19) ~[?:?]
at us.myles.ViaVersion.api.protocol.ProtocolRegistry.<clinit>(ProtocolRegistry.java:67) ~[?:?]
at us.myles.ViaVersion.ViaManager.init(ViaManager.java:50) ~[?:?]
at us.myles.ViaVersion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:93) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.InventoryPackets$1
at java.net.URLClassLoader$1.run(URLClassLoader.java:371) ~[?:1.8.0_212]
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_212]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 10 more
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
at java.util.zip.ZipFile.read(Native Method) ~[?:1.8.0_212]
at java.util.zip.ZipFile.access$1400(ZipFile.java:60) ~[?:1.8.0_212]
at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734) ~[?:1.8.0_212]
at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434) ~[?:1.8.0_212]
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_212]
at sun.misc.Resource.getBytes(Resource.java:124) ~[?:1.8.0_212]
at java.net.URLClassLoader.defineClass(URLClassLoader.java:463) ~[?:1.8.0_212]
at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_212]
at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_212]
at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_212]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 10 more`

**Comment by MylesIsCool** [comment]
Redownload ViaVersion, your jar is corrupt
