### ISSUE TITLE
Crash After Moving to Multicraft

### ISSUE THREAD

**Issue by sean-perryman** [ViaVersion/ViaVersion#1394]
I believe this is not a bug but rather something I am doing wrong. I was hosting my BungeeCord servers on VPS', and recently decided to move them to being managed by my Multicraft install. Now I am getting this message when I boot them up. 

```
08.07 14:50:26 [Server] WARNING [ViaVersion] This is most likely down to one of your plugins sending bad datawatchers. Please test if this occurs without any plugins except ViaVersion before reporting it on GitHub
08.07 14:50:26 [Server] WARNING [ViaVersion] Also make sure that all your plugins are compatible with your server version.
08.07 14:50:26 [Server] SEVERE [ViaVersion] An error occurred with entity meta data for PLAYER OldID: 31
08.07 14:50:26 [Server] SEVERE java.lang.Exception: Could not find valid metadata
08.07 14:50:26 [Server] SEVERE at us.myles.ViaVersion.protocols.protocol1_9to1_8.metadata.MetadataRewriter.transform(MetadataRewriter.java:132)
08.07 14:50:26 [Server] SEVERE at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.EntityPackets$7$1.handle(EntityPackets.java:190)
08.07 14:50:26 [Server] SEVERE at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
08.07 14:50:26 [Server] SEVERE at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
08.07 14:50:26 [Server] SEVERE at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:169)
08.07 14:50:26 [Server] SEVERE at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:433)
08.07 14:50:26 [Server] SEVERE at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82)
08.07 14:50:26 [Server] SEVERE at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:62)
08.07 14:50:26 [Server] SEVERE at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:19)
08.07 14:50:26 [Server] SEVERE at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
08.07 14:50:26 [Server] SEVERE at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706)
```

Of particular interest is this message:

08.07 14:50:26 [Server] SEVERE [ViaVersion] An error occurred with entity meta data for PLAYER OldID: 31

I just can't find anywhere that would hold this meta data on either of the BungeeCord servers. Thoughts? 

Also, your discord link comes up as invalid when I try and join.

**Comment by MylesIsCool** [comment]
Could you specify which discord link youre using?

The metadata error is usually down to a plugin.

**Comment by sean-perryman** [comment]
Discord might have been a problem with my browser. Tried a different one and it worked.

I am reporting this issue after one-by-one disabling all the plugins on the BungeeCord and restarting each time. The problem occurs as soon as I log in.

**Comment by MylesIsCool** [comment]
It's most likely spigot plugins

**Comment by sean-perryman** [comment]
Ahh, I had not considered that. I will look there next. Thanks!
