### ISSUE TITLE
Lingering potions forcing exit of server

### ISSUE THREAD

**Issue by NoFace851** [ViaVersion/ViaVersion#1408]
**Describe the bug, provide any errors**
So, the error is that when you thrown a lingering potion, the player who threw it exits the server with an error

**How can we reproduce it?**
1. Login on 1.14.3 on a 1.14 server (spigot)
2. get a lingering potion and throw it
3. done 
obs: the server HAS to be 1.14, and the client HAS to be 1.14.2, 1.14.3 or 1.14.4. If the client is 1.14, this error doesn't happen

**Expected behaviour**
When you throw a lingering potion you are kicked out of the server, the server doesn't crash though, nor does the client.

**Screenshots**
https://imgur.com/a/YEnIbJf

**ViaVersion Dump:**
https://dump.viaversion.com/7789f5813de6fa4dd80eabd0562d730030ce6c0f64e0fe53ef4fb0ad697d9423

**Additional server info**
I'm not using BungeeCord, currently only on localhost.

**Comment by NoFace851** [comment]
att: If you continue to do this the server will crash

**Comment by KennyTV** [comment]
We need the error that's printed in the console.
Also, you're running an ancient 1.14 build, it might just be down to that 👀

**Comment by NoFace851** [comment]
the console doesn't print an error most of the time, only if you keep doing it multiple times. I'll post that when i get home in 5 hours

**Comment by NoFace851** [comment]
[19:05:05] [Server thread/ERROR]: Could not pass event LingeringPotionSplashEven
t to WorldGuard v7.0.0;02b731f
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:320) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:70) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:520) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:505) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callLingering
PotionSplashEvent(CraftEventFactory.java:638) ~[spigot-1.14.jar:git-Spigot-4d24e
36-5193f76]
        at net.minecraft.server.v1_14_R1.EntityPotion.a(EntityPotion.java:215) ~
[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.EntityPotion.a(EntityPotion.java:90) ~[
spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.EntityProjectile.tick(EntityProjectile.
java:109) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServ
er.java:578) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.World.a(World.java:743) [spigot-1.14.ja
r:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:355
) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:
1054) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:
396) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:
953) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.jav
a:798) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.LingeringPotionS
plashEvent.getEntity()Lorg/bukkit/entity/LingeringPotion;
        at com.sk89q.worldguard.bukkit.listener.EventAbstractionListener.onLinge
ringSplash(EventAbstractionListener.java:948) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:316) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        ... 15 more
[19:05:05] [Server thread/INFO]: NoFace lost connection: Internal Exception: io.
netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeE
xception: Please post this error to http://github.com/ViaVersion/ViaVersion/issu
es
{Type: MetaData List, Source #0: us.myles.ViaVersion.protocols.protocol1_14_1to1
_14.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 490}], Packet
ID: 67}
Actual Error:
[19:05:05] [Server thread/INFO]: NoFace left the game

Here is the error in the console

**Comment by MylesIsCool** [comment]
Your WorldGuard isn't compatible with your spigot version and causes it to interrupt ViaVersion.

The error provided indicates WorldGuard can't find a certain method, I could be wrong but if you're able to replicate without WorldGuard I'll happily reopen.

**Comment by NoFace851** [comment]
i removed worldguard.jar and it's folder and tried again. Same thing happened but with this error the first time i tried:

[20:27:27] [Server thread/INFO]: NoFace lost connection: Internal Exception: io.
netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeE
xception: Please post this error to http://github.com/ViaVersion/ViaVersion/issu
es
{Type: MetaData List, Source #0: us.myles.ViaVersion.protocols.protocol1_14_1to1
_14.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 250}], Packet
ID: 67}
Actual Error:
[20:27:27] [Server thread/INFO]: NoFace left the game

then i logged in and tried with a different lingering potion:

[20:30:13] [Server thread/INFO]: NoFace lost connection: Internal Exception: io.
netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeE
xception: Please post this error to http://github.com/ViaVersion/ViaVersion/issu
es
{Type: MetaData List, Source #0: us.myles.ViaVersion.protocols.protocol1_14_1to1
_14.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 511}], Packet
ID: 67}
Actual Error:
[20:30:13] [Server thread/INFO]: NoFace left the game

here is a new dump, so you can see i'm not using worldguard now

https://dump.viaversion.com/fca71985a4f7f8ed0361aff912ef9a6d640f19ce1ad3d939734cd83ebb2d3254

**Comment by NoFace851** [comment]
anyone has a fix?

**Comment by NoFace851** [comment]
bump

**Comment by MylesIsCool** [comment]
No need to bump, it'll be fixed when someone knows how.

**Comment by NoFace851** [comment]
oh ok sorry. I removed all plugins and left only viaversion and the error is still there, so it's not another plugin incompatibility.

**Comment by NoahvdAa** [comment]
> oh ok sorry. I removed all plugins and left only viaversion and the error is still there, so it's not another plugin incompatibility.

Have you updated your spigot build with BuildTools so you use the latest version?

**Comment by NoFace851** [comment]
i changed to paper and i'm using 1.14.4 now.

**Comment by KennyTV** [comment]
A fix in reading particle packets has been done at the end of the year, I assume this should be resolved
