### ISSUE TITLE
lingering_potion

### ISSUE THREAD

**Issue by 0opser** [ViaVersion/ViaVersion#1444]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.8.8-1.13
2. Click on 'lingering_potion' and kick on server

[10:16:54] [Netty Epoll Server IO #2/WARN]: [ViaBackwards] Ignoring plugin channel in incoming REGISTER: SkinsRestorer
[10:16:55] [Server thread/INFO]: MercureOR[/195.43.70.227:41743] logged in with entity id 2382 at ([world]68.3929511656914, 70.0, 155.69477825081208)
[10:17:25] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[10:17:25] [Netty Epoll Server IO #2/WARN]: {Type: MetaData List, Source #0: nl.matsv.viabackwards.protocol.protocol1_14to1_14_1.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 2388}], Packet ID: 67}
[10:17:25] [Netty Epoll Server IO #2/WARN]: Actual Error: 
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at me.neznamy.tab.bukkit.Main$7.write(Main.java:313)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_14_R1.NetworkManager.lambda$b$4(NetworkManager.java:205)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:17:25] [Netty Epoll Server IO #2/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[10:17:25] [Netty Epoll Server IO #2/WARN]: {Type: MetaData List, Source #0: nl.matsv.viabackwards.protocol.protocol1_14to1_14_1.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 2388}], Packet ID: 67}
[10:17:25] [Netty Epoll Server IO #2/WARN]: Actual Error: 
[10:17:25] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: -84
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.minecraft.metadata.types.MetaType1_14.byId(MetaType1_14.java:37)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.version.Metadata1_14Type.read(Metadata1_14Type.java:14)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.version.Metadata1_14Type.read(Metadata1_14Type.java:8)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.version.MetadataList1_14Type.read(MetadataList1_14Type.java:16)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.version.MetadataList1_14Type.read(MetadataList1_14Type.java:10)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:147)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:94)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:169)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:433)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at me.neznamy.tab.bukkit.Main$7.write(Main.java:313)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_14_R1.NetworkManager.lambda$b$4(NetworkManager.java:205)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:17:25] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[10:17:25] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[10:17:25] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[10:17:25] [Server thread/INFO]: MercureOR left the game

**Comment by MylesIsCool** [comment]
This concerns ViaBackwards not VV (and is already a reported issue AFAIK).
