### ISSUE TITLE
io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException

### ISSUE THREAD

**Issue by x1p** [ViaVersion/ViaVersion#1498]
**Describe the bug, provide any errors**
```
io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Source #0: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous), Data: [Pair{Type|VarInt, 0}], Packet ID: 0}
Actual Error: 
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Source #0: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous), Data: [Pair{Type|VarInt, 0}], Packet ID: 0}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(47) exceeds writerIndex(3): PooledSlicedByteBuf(ridx: 3, widx: 3, cap: 3/3, unwrapped: PooledUnsafeDirectByteBuf(ridx: 4, widx: 47, cap: 47))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1411) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:888) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:896) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:25) ~[?:?]
	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:8) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:147) ~[?:?]
	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:94) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:169) ~[?:?]
	at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:93) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:433) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82) ~[?:?]
	at us.myles.ViaVersion.bungee.handlers.BungeeDecodeHandler.decode(BungeeDecodeHandler.java:53) ~[?:?]
	at us.myles.ViaVersion.bungee.handlers.BungeeDecodeHandler.decode(BungeeDecodeHandler.java:17) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	... 30 more
```

**How can we reproduce it?**
1. I have no idea. It happend out of the blue

**Expected behaviour**
No errors...? :-)

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/74e23feb45483b97e8e16e1afce5c4f02d02e8c9ba88789105d1caa3ca53dd79

**Additional server info**
Waterfall

**Comment by MylesIsCool** [comment]
Something is sending your server bad data, there is nothing we can do about this. I'd suggest working out what / firewalling etc.
