### ISSUE TITLE
I have this error when i throw that type of item pls i need help

### ISSUE THREAD

**Issue by losmatanza** [ViaVersion/ViaVersion#1522]
Login on 1.14.4 spigot
Description: Whe i throw that type of item to the floor it just crash and type that error om the screen.
Version of plugin: ViaVersion-2.1.3
screenshot: ![Captura](https://user-images.githubusercontent.com/20968511/68992410-4af03300-086b-11ea-826d-3602c3e4af27.PNG)
---------------------------------
Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: MetaData List, Source #0: us.myles.ViaVersion.protocols.protocol1_14_1to1_14.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 320}], Packet ID: 67}
----------------------------------------
debug 
---------------------------------
[12:15:23] [Netty Server IO #1/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: MetaData List, Source #0: us.myles.ViaVersion.protocols.protocol1_14_1to1_14.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 266}], Packet ID: 67}
Actual Error:
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[12:15:23] [Netty Server IO #1/WARN]:   at net.minecraft.server.v1_14_R1.NetworkManager.lambda$4(NetworkManager.java:198)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[12:15:23] [Netty Server IO #1/WARN]:   at java.lang.Thread.run(Unknown Source)
[12:15:23] [Netty Server IO #1/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: MetaData List, Source #0: us.myles.ViaVersion.protocols.protocol1_14_1to1_14.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 266}], Packet ID: 67}
Actual Error:
[12:15:23] [Netty Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(43) + length(1) exceeds writerIndex(43): PooledUnsafeDirectByteBuf(ridx: 43, widx: 43, cap: 43)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.type.types.VarIntType.read(VarIntType.java:38)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.type.types.VarIntType.read(VarIntType.java:7)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.protocols.protocol1_13_2to1_13_1.types.Particle1_13_2Type.read(Particle1_13_2Type.java:28)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.protocols.protocol1_13_2to1_13_1.types.Particle1_13_2Type.read(Particle1_13_2Type.java:7)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.type.types.version.Metadata1_14Type.read(Metadata1_14Type.java:16)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.type.types.version.Metadata1_14Type.read(Metadata1_14Type.java:8)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.type.types.version.MetadataList1_14Type.read(MetadataList1_14Type.java:16)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.type.types.version.MetadataList1_14Type.read(MetadataList1_14Type.java:10)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:147)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:94)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:169)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:433)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[12:15:23] [Netty Server IO #1/WARN]:   at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[12:15:23] [Netty Server IO #1/WARN]:   at net.minecraft.server.v1_14_R1.NetworkManager.lambda$4(NetworkManager.java:198)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[12:15:23] [Netty Server IO #1/WARN]:   at java.lang.Thread.run(Unknown Source)
[12:15:23] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[12:15:23] [Netty Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[12:15:23] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[12:15:23] [Server thread/INFO]: losmatanza lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: MetaData List, Source #0: us.myles.ViaVersion.protocols.protocol1_14_1to1_14.packets.EntityPackets$3 (Anonymous), Data: [Pair{Type|VarInt, 266}], Packet ID: 67}
-------------------------------------

**Comment by MylesIsCool** [comment]
This report doesn't contain enough info to replicate it, if you have more info / steps we'll happily look into it.
