### ISSUE TITLE
Players get kicked (mostly 1.8 clients)

### ISSUE THREAD

**Issue by shadowpikachu** [ViaVersion/ViaVersion#1596]
**Describe the bug, provide any errors**
`[09:08:45] [Netty Epoll Server IO #3/WARN]: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2142105 into 3
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.tinyprotocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:550)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:08:45] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.IllegalArgumentException: unable to fit 2142105 into 3
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPrepender.a(SourceFile:19)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPrepender.encode(SourceFile:9)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[09:08:45] [Netty Epoll Server IO #3/WARN]: 	... 31 more
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Netty Epoll Server IO #3/WARN]: java.nio.channels.ClosedChannelException
[09:08:45] [Server thread/INFO]: KANAPECZKI786 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2142105 into 3`

**How can we reproduce it?**
1. Login on 1.12'
3. The '....' is displayed wrong

**Expected behaviour**
not kicking

**Screenshots**
-

**ViaVersion Dump:**
-

**Additional server info**
bungee

**Comment by MylesIsCool** [comment]
There isn't enough info here to do anything, see the issue template https://github.com/ViaVersion/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

You can enable debug=true in server.properties too to get full exceptions

**Comment by shadowpikachu** [comment]
@MylesIsCool what can cause this? I think this is the error with debug enabled.

**Comment by MylesIsCool** [comment]
I have no idea, there is not enough information provided

**Comment by shadowpikachu** [comment]
@MylesIsCool should I use this ProtocolLib on 1.8 server? http://ci.dmulloy2.net/job/ProtocolLib/429/
 I will change Plib tomorrow and enable debug messages.

**Comment by assasin541** [comment]
@MylesIsCool ```
[09:59:51] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2142105 into 3
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:235)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.tinyprotocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:550)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:307)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:59:51] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.IllegalArgumentException: unable to fit 2142105 into 3
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPrepender.a(SourceFile:19)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPrepender.encode(SourceFile:9)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[09:59:51] [Netty Epoll Server IO #2/WARN]: 	... 31 more
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[09:59:51] [Server thread/INFO]: player lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 2142105 into 3
```
