### ISSUE TITLE
internal exception kick

### ISSUE THREAD

**Issue by PhanaticD** [ViaVersion/ViaVersion#1606]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?
players cannot log on, Internal exception. I have to restart the server to fix this. it happens maybe 50% of the time after a restart

```
[13:00:40] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_13_R2.NetworkManager.lambda$b$4(NetworkManager.java:214)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at java.lang.Thread.run(Thread.java:748)
[13:00:40] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:458)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:66)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:232)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     ... 21 more
[13:00:40] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.LinkageError: loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "us/myles/ViaVersion/api/entities/Entity1_13Types"
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at java.lang.ClassLoader.defineClass1(Native Method)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at nl.matsv.viabackwards.protocol.protocol1_13to1_13_1.packets.EntityPackets1_13_1$1$1.handle(EntityPackets1_13_1.java:43)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:127)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:198)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at java.lang.reflect.Method.invoke(Method.java:498)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[13:00:40] [Netty Epoll Server IO #1/WARN]:     ... 25 more
[13:00:40] [Netty Epoll Server IO #1/WARN]: [ViaBackwards] Metadata for entity id: 11 not sent because the entity doesn't exist. MetaStorage(metaDataList=[Metadata(id=0, metaType=Byte, value=0), Metadata(id=2, metaType=OptChat, value=null), Metadata(id=6, metaType=Byte, value=0), Metadata(id=4, metaType=Boolean, value=false), Metadata(id=8, metaType=VarInt, value=-1), Metadata(id=1, metaType=VarInt, value=300), Metadata(id=3, metaType=Boolean, value=false), Metadata(id=7, metaType=OptUUID, value=null), Metadata(id=5, metaType=Boolean, value=false)])
[13:00:40] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[13:00:40] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[13:00:40] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[13:00:40] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[13:00:40] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[13:00:40] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[13:00:40] [Server thread/INFO]: marvales lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
```

**How can we reproduce it?**
start server and it happens randomly

**Expected behaviour**
not to be kicked
**Screenshots**
none

**ViaVersion Dump:**
https://dump.viaversion.com/cea8c32ce27c49be3aeaaabf5020f1d50b09fa6d3c02b25e21d6834693d000ed

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Comment by MylesIsCool** [comment]
Corrupt jar, not solvable by us

**Comment by PhanaticD** [comment]
i downloaded the jar from your ci lol..

**Comment by PhanaticD** [comment]
```
8cfcef21b5ba7191a9c0ba55ec70449855914242  ViaBackwards.jar
eed89dea429250e4a47a1d66b1046f8506568347  ViaRewind.jar
02c5d18a612e9cf77c115978ee75464e1ecb1d9b  ViaRewindLegacySupport.jar
44d837988731a1985b443386c59f0135a4d4e529  ViaVersion.jar
```
let me know if they do not match sha1sum, if they do match please re-open this

**Comment by MylesIsCool** [comment]
You should ideally use https://ci.viaversion.com/fingerprintCheck to check

**Comment by PhanaticD** [comment]
i literally just downloaded viabackwards-abstraction on my PC right now and tested it and it said no match, also viaversion says the file is too large.

**Comment by PhanaticD** [comment]
please this is driving me crazy, the server was fine for months then all I did was update viaversion to abstraction builds

**Comment by Xernium** [comment]
Did you update all three plugins accordingly? Also if you have any plugins that heavily rely on ProtocolLib it’s always best while troubleshooting to disable those. If you didn’t update/ replace all three plugins be sure to do it with these versions:    
     
https://ci.viaversion.com/job/ViaVersion-Abstraction/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.0.0-SNAPSHOT.jar

https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Abstraction/lastSuccessfulBuild/artifact/all/target/viabackwards-all-3.0.0-SNAPSHOT.jar

https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/lastSuccessfulBuild/artifact/all/target/viarewind-all-1.5.0-SNAPSHOT.jar
