### ISSUE TITLE
Player crash

### ISSUE THREAD

**Issue by mastabaaudio** [ViaVersion/ViaVersion#1616]
[15:48:27] [Netty Worker IO Thread #4/ERROR]: [/XXXXXXX:50719|noob] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Double, Source #0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.SpawnPackets$2 (Anonymous), Data: [Pair{Type|VarInt, 0}, Pair{Type|Integer, 0}], Packet ID: 17}
Actual Error: 
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:762) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:788) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:756) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:154) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:250) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:105) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:303) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:417) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Double, Source #0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.SpawnPackets$2 (Anonymous), Data: [Pair{Type|VarInt, 0}, Pair{Type|Integer, 0}], Packet ID: 17}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(8) exceeds writerIndex(14): PooledUnsafeDirectByteBuf(ridx: 9, widx: 14, cap: 14)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:836) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at io.netty.buffer.AbstractByteBuf.readDouble(AbstractByteBuf.java:862) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	at us.myles.ViaVersion.api.type.types.DoubleType.read(DoubleType.java:14) ~[?:?]
	at us.myles.ViaVersion.api.type.types.DoubleType.read(DoubleType.java:7) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:144) ~[?:?]
	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:94) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:169) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82) ~[?:?]
	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:62) ~[?:?]
	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:19) ~[?:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[Travertine.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:8b7a57c:120]
	... 44 more
[15:48:27] [Netty Worker IO Thread #4/INFO]: [noob] disconnected with: EncoderException : us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Double, Source #0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.SpawnPackets$2 (Anonymous), Data: [Pair{Type|VarInt, 0}, Pair{Type|Integer, 0}], Packet ID: 17}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:107

**Comment by MylesIsCool** [comment]
Post this issue to https://github.com/ViaVersion/ViaRewind/issues/144 and ensure you provide full information
