### ISSUE TITLE
ConnectionOpenEvent Error

### ISSUE THREAD

**Issue by NotStarRift** [ViaVersion/ViaVersion#1661]
ViaVersion v3.0.0-SNAPSHOT

Spigot 1.15.2

Problem: Server boots normally but players cannot connect.

https://dump.viaversion.com/8b0f5abdc64c4a8fffb912b05ba3436e2cc925f1a6ccdde4e99fc40a3f5231d4

[Netty Epoll Server IO #3/ERROR]: Could not pass event ConnectionOpenEvent to ViaVersion v3.0.0-SNAPSHOT
--
java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener.onPacketReceiving(Lprotocolsupport/api/Connection$PacketListener$PacketEvent;)V @22: istore_3
Reason:
Type 'net/minecraft/server/v1_15_R1/EnumProtocol' (current frame, stack[0]) is not assignable to integer
Current Frame:
bci: @22
flags: { }
locals: { 'us/myles/ViaVersion/classgenerator/generated/ProtocolSupportConnectListener', 'protocolsupport/api/Connection$PacketListener$PacketEvent', 'net/minecraft/server/v1_15_R1/PacketHandshakingInSetProtocol' }
stack: { 'net/minecraft/server/v1_15_R1/EnumProtocol' }
Bytecode:
0x0000000: 2bb6 001a c100 1c99 0034 2bb6 001a c000
0x0000010: 1c4d 2cb6 0020 3e2a b400 11b6 0026 b200
0x0000020: 2ca6 000a 1db2 0032 9f00 06a7 0010 2ab4
0x0000030: 0011 b200 38b8 003c b600 422a b400 112a
0x0000040: b600 46b1
Stackmap Table:
append_frame(@43,Object[#28],Integer)
same_frame(@46)
chop_frame(@59,2)
 
at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_242]
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_242]
at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_242]
at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_242]
at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator$3.execute(ClassGenerator.java:240) ~[?:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:541) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:528) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at protocolsupport.protocol.pipeline.common.LogicHandler.channelActive(LogicHandler.java:81) [ProtocolSupport.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelActive(SimpleReadTimeoutHandler.java:28) [ProtocolSupport.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1422) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:941) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:518) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.15.2.jar:git-Spigot-c574e08-37f32da]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by electronicboy** [comment]
You need paper for ViaVersion + PS

**Comment by MylesIsCool** [comment]
^^
