### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Arlind-A** [ViaVersion/ViaVersion#1727]
java.lang.NoSuchMethodError: us.myles.ViaVersion.bukkit.listeners.ViaBukkitListener.<init>(Lus/myles/ViaVersion/ViaVersionPlugin;Ljava/lang/Class;)V
at nl.matsv.viabackwards.listener.LecternInteractListener.<init>(LecternInteractListener.java:19) ~[?:?]
at nl.matsv.viabackwards.BukkitPlugin.onServerLoaded(BukkitPlugin.java:32) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-112]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-112]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-112]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

Get this error on startup.
Using Latest Successful build for: ViaVersion-Abstraction,ViaBackwards-Abstraction, ViaRewind-DEV
Minecraft Version: 1.15.2

**Comment by KennyTV** [comment]
Redownload the latest ViaBackwards build, maybe you got an old one due to caching.

**Comment by Arlind-A** [comment]
Redownloaded the latest ViaBackwards-Abstraction build but it still gives me that error.

**Comment by KennyTV** [comment]
143 failed to build yesterday, 144 should work now

**Comment by Arlind-A** [comment]
Error is gone, works good. Thank you.
