### ISSUE TITLE
lost connection: Internal Exception

### ISSUE THREAD

**Issue by rafalohaki** [ViaVersion/ViaVersion#1757]
Login on 1.15.2 and 1.14.4 (1.12.2 working fine)

<user> lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$8 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$8$1 (Anonymous), Data: [], Packet ID: 34}
Actual Error:

https://dump.viaversion.com/a16f8b3003d172a933275b71661f8e804bd13fd332931adc545c344d618c00a5

**Comment by rafalohaki** [comment]
is it my fault or?

**Comment by KennyTV** [comment]
Set `debug=true` in your server.properties and try to recreate the error

**Comment by ray27890** [comment]
I get this issue too, no idea why, worked fine just yesterday.

**Comment by Peeraboon** [comment]
I also get this issue today.

**Comment by KennyTV** [comment]
Did you update any of your plugins? The 2.2.3 version of VV hasn't been touched in months, so it is unlikely a newfound issue would suddenly pop up and explode like that

**Comment by rafalohaki** [comment]
my latest updated plugins: 
![image](https://user-images.githubusercontent.com/20607107/80913995-ee190400-8d48-11ea-8751-e34ef84b84e2.png)

**Comment by rafalohaki** [comment]
ok. problem is solved by itself. probably new version protocollib fixed it but im not sure

**Comment by KennyTV** [comment]
Changing that setting has nothing to do with functionality of the server or Via, it just enables some stacktrace printing

**Comment by rafalohaki** [comment]
Idk why but its now working... Idk what is happening.

**Comment by rafalohaki** [comment]
after like 5mins, its not working again... kekk

**Comment by rafalohaki** [comment]
`logged in with entity id 24 at ([island_normal_world]1205.353798804848, 72.0, 4794.920456503421)
[15:00:59] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[15:00:59] [Netty Epoll Server IO #2/WARN]: {Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$8 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$8$1 (Anonymous), Data: [], Packet ID: 34}
[15:00:59] [Netty Epoll Server IO #2/WARN]: Actual Error: 
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at primal.bukkit.nms.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:509)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at gyurix.protocol.manager.ProtocolImpl$ClientChannelHook.write(ProtocolImpl.java:214)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:102)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:00:59] [Netty Epoll Server IO #2/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[15:00:59] [Netty Epoll Server IO #2/WARN]: {Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$8 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$8$1 (Anonymous), Data: [], Packet ID: 34}
[15:00:59] [Netty Epoll Server IO #2/WARN]: Actual Error: 
[15:00:59] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.RuntimeException: VarInt too big
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.VarIntType.read(VarIntType.java:43)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.VarIntType.read(VarIntType.java:7)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.version.ChunkSectionType1_9.read(ChunkSectionType1_9.java:32)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.version.ChunkSectionType1_9.read(ChunkSectionType1_9.java:7)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_9_1_2to1_9_3_4.types.Chunk1_9_3_4Type.read(Chunk1_9_3_4Type.java:48)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_9_1_2to1_9_3_4.types.Chunk1_9_3_4Type.read(Chunk1_9_3_4Type.java:21)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.PartialType.read(PartialType.java:19)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:144)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$8$1.handle(WorldPackets.java:301)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:169)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:82)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:77)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at primal.bukkit.nms.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:509)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at gyurix.protocol.manager.ProtocolImpl$ClientChannelHook.write(ProtocolImpl.java:214)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:102)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[15:00:59] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:00:59] [Server thread/INFO]: rafalohaki lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$8 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$8$1 (Anonymous), Data: [], Packet ID: 34}
Actual Error: `

**Comment by KennyTV** [comment]
Can you revert all your plugin updates from the last few days on some test server and see if the issue persists? By the number of people suddenly having the same problem in the same area without any changes on our side, I'd suspect a plugin messing with chunk data or sending chunk packets

**Comment by rafalohaki** [comment]
I think its beacause of SkinsRestorer. Yesterday night was update and already had problem with skins when log in. However it still create some collisions with viaversion and skinsrestorer on 1.15.2 client 1.12.2 server. Client 1.12.2 doesnt have those problems.  Thats my opinion.

**Comment by ray27890** [comment]
It's SkinsRestorer.

**Comment by YellowZaki** [comment]
The error comes from SkinsRestorer 13.7.6 (13.7.5 doesn't have the issue)

**Comment by KennyTV** [comment]
Can you try the latest CI build of SkinsRestorer? A dev responsed there with "I just reverted a change made with 13.7.6 wich maybe caused the issues"

**Comment by rafalohaki** [comment]
sorry for long awaiting. I think its fixed.

**Comment by KennyTV** [comment]
I'll close this, since another person also responded positive at SR's issue

**Comment by ray27890** [comment]
SkinsRestorer's latest patch has fixed this issue.
