### ISSUE TITLE
2.2.3 / 3.0.0-SNAPSHOT does not support 1.15.2 PaperSpigot

### ISSUE THREAD

**Issue by k-jiang** [ViaVersion/ViaVersion#1808]
Player can not join the 1.15.2 PaperSpigot server through BungeeCord. Getting "Kicked whilst connecting to xxxx: Ip forwarding is enabled but spoofed data can't be decoded or is missing".

Exception during server startup:
```
[21:36:35 WARN]: us.myles.viaversion.libs.javassist.CannotCompileException: [source error] no such class: PacketHandshakingInSetProtocol
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:79)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:45)
[21:36:35 WARN]: 	at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator.makePSConnectListener(ClassGenerator.java:202)
[21:36:35 WARN]: 	at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator.generate(ClassGenerator.java:48)
[21:36:35 WARN]: 	at us.myles.ViaVersion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:87)
[21:36:35 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:365)
[21:36:35 WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234)
[21:36:35 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908)
[21:36:35 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[21:36:35 WARN]: Caused by: compile error: no such class: PacketHandshakingInSetProtocol
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.MemberResolver.searchImports(MemberResolver.java:468)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.MemberResolver.lookupClassByName(MemberResolver.java:315)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.MemberResolver.resolveClassName(MemberResolver.java:502)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.MemberCodeGen.resolveClassName(MemberCodeGen.java:1151)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.CodeGen.atInstanceOfExpr(CodeGen.java:1407)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.ast.InstanceOfExpr.accept(InstanceOfExpr.java:38)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.CodeGen.booleanExpr(CodeGen.java:1159)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.CodeGen.compileBooleanExpr(CodeGen.java:237)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:384)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.Javac.compileMethod(Javac.java:169)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.compiler.Javac.compile(Javac.java:95)
[21:36:35 WARN]: 	at us.myles.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:74)
[21:36:35 WARN]: 	... 8 more
```

Tested on PaperSpigot 1.15.2 build [365](https://papermc.io/ci/job/Paper-1.15/365/)
[Waterfall](https://papermc.io/ci/job/Waterfall/) (BungeeCord equivalent)
ViaVersion [3.0.0-SNAPSHOT build 116](https://ci.viaversion.com/job/ViaVersion-Abstraction/116/)
ViaVersion 2.2.3

**Comment by krusic22** [comment]
Please follow the bug report template.
