### ISSUE TITLE
1.16.rc1 [Index 69 out of bounds for length 1] 

### ISSUE THREAD

**Issue by mrfloris** [ViaVersion/ViaVersion#1813]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

https://hasteb.in/ipavubib.md

**How can we reproduce it?**
1. Login on 1.15.2 server with 1.16.rc1 using vv-a build 117'
User seems to be fine, used /warp to a guardian farm and it spit that out and poof offline.

**Expected behaviour**
Didn't expect it to break

**Screenshots**

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
```
>viaversion dump
[18:51:03] [Craft Scheduler Thread - 81/INFO]: Failed to dump, please check the console for more information
[18:51:03] [Craft Scheduler Thread - 81/WARN]: [ViaVersion] Could not paste ViaVersion dump to Hastebin
javax.net.ssl.SSLException: Received fatal alert: record_overflow
        at sun.security.ssl.Alert.createSSLException(Alert.java:129) ~[?:?]
        at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279) ~[?:?]
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823) ~[?:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:292) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329) ~[?:?]
        at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:77) [ViaVersion-3.0.0-SNAPSHOT.jar:git-ViaVersion-3.0.0-SNAPSHOT:9f10486]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[18:51:03] [Craft Scheduler Thread - 81/WARN]: [ViaVersion] Failed to capture further info
javax.net.ssl.SSLException: Received fatal alert: record_overflow
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1963) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1958) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1957) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1525) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329) ~[?:?]
        at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:95) [ViaVersion-3.0.0-SNAPSHOT.jar:git-ViaVersion-3.0.0-SNAPSHOT:9f10486]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: javax.net.ssl.SSLException: Received fatal alert: record_overflow
        at sun.security.ssl.Alert.createSSLException(Alert.java:129) ~[?:?]
        at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:308) ~[?:?]
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279) ~[?:?]
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:181) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823) ~[?:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:292) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:351) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[?:?]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329) ~[?:?]
        at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:77) ~[?:?]
        ... 5 more
>
```
**Additional server info**

```
>ver
[18:51:18] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a99063f-8ea9b13 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[18:51:18] [Server thread/INFO]: Checking version, please wait...
[18:51:18] [Thread-124/INFO]: You are running the latest version
>ver ViaVersion
[18:51:21] [Server thread/INFO]: ViaVersion version 3.0.0-SNAPSHOT
[18:51:21] [Server thread/INFO]: Allow newer clients to join older server versions.
[18:51:21] [Server thread/INFO]: Authors: _MylesC, creeper123123321, Gerrygames, KennyTV and Matsv
>
```

**Comment by KennyTV** [comment]
The error should be unrelated to the teleport, as they are quite apart on a timescale. Looks like someone is sending faulty packet data, but it's not caused by Via itself (a reason for why you never saw this before could be that Via enables netty codec error printing, which are usually hidden)
