### ISSUE TITLE
Instant kick when joining server

### ISSUE THREAD

**Issue by hylkekingma** [ViaVersion/ViaVersion#1835]
We use a Waterfall network, with approx. 8 Tunity servers. Recently installed ViaVersion.
One of our builders joined the construction server, and was immidiately kicked. A debug gives the following information:

[18:42:11] [Server thread/INFO]: [USER] joined the game
[18:42:11] [Server thread/INFO]: [USER][/IP] logged in with entity id 895 at ([Quests]-187.43079278416835, 131.04325244455455, -15.191610396111411)
[18:42:12] [Netty Epoll Server IO #0/WARN]: **[ViaVersion] ERROR IN Protocol1_16To1_15_2 IN REMAP OF CHUNK_DATA (0x22)**
[18:42:12] [Netty Epoll Server IO #0/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[18:42:12] [Netty Epoll Server IO #0/WARN]: {Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_16to1_15_2.packets.WorldPackets$2 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_16to1_15_2.packets.WorldPackets$2$$Lambda$2964/1284026399, Data: [], Packet ID: 33}
[18:42:12] [Netty Epoll Server IO #0/WARN]: Actual Error: 
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_15_R1.NetworkManager.lambda$writePacket$7(NetworkManager.java:341)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:42:12] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:42:12] [Netty Epoll Server IO #0/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[18:42:12] [Netty Epoll Server IO #0/WARN]: {Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_16to1_15_2.packets.WorldPackets$2 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_16

User was using 1.15.2, and our server is too. Our developer doesn't know what causes the failure. A restart fixes the problem.

Hoping this is enough information, if not, hit me up.

FindMyFriends,
Scouting NL Minecraft Server

**Comment by KennyTV** [comment]
You excluded the actually important part, also please follow the issue template.
