### ISSUE TITLE
ERROR IN BaseProtocol IN REMAP OF 0x00->0x00

### ISSUE THREAD

**Issue by moribellamy** [ViaVersion/ViaVersion#1865]
stderr told me to "please post this error" so here it is :). 3.01 ViaVersion, 1.16 client, 1.15 server.

```minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]: [ViaVersion] ERROR IN BaseProtocol IN REMAP OF 0x00->0x00
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.
com/ViaVersion/ViaVersion/issues
minecraft_1  | {Type: String, Source #0: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous), Data: [Pair{Type|VarInt, 0}], Packet ID: 0}
minecraft_1  | Actual Error:
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at net.minecraft.server.v1_15_R1.LegacyPingHandler.channelRead(LegacyPingHandler.java:88)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
minecraft_1  | [10:17:11] [Netty Epoll Server IO #2/WARN]:      at java.lang.Thread.run(Thread.java:748)```

**Comment by moribellamy** [comment]
FYI this was immediately preceeding a crash

**Comment by moribellamy** [comment]
dupe of https://github.com/ViaVersion/ViaVersion/issues/1820
