### ISSUE TITLE
ERROR IN Protocol 1_13 To 1_12_2 IN REMAP OF CHUNK_DATA

### ISSUE THREAD

**Issue by Luky584** [ViaVersion/ViaVersion#1877]
**Describe the bug, provide any errors**
Hey there, just have seen this bug in console. 

`
[00:05:39 WARN] [ViaVersion]: ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)
>.... [00:05:39 ERROR]: [/109.202.74.184:50249|Lupenator401] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9$1 (Anonymous), Data: [], Packet ID: 34}
Actual Error:
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:183) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:144) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:113) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9$1 (Anonymous), Data: [], Packet ID: 34}
Actual Error:
Caused by: java.lang.RuntimeException: VarInt too big
at us.myles.ViaVersion.api.type.types.VarIntType.readPrimitive(VarIntType.java:23) ~[?:?]
at us.myles.ViaVersion.api.type.types.version.ChunkSectionType1_9.read(ChunkSectionType1_9.java:32) ~[?:?]
at us.myles.ViaVersion.api.type.types.version.ChunkSectionType1_9.read(ChunkSectionType1_9.java:8) ~[?:?]
at us.myles.ViaVersion.protocols.protocol1_9_1_2to1_9_3_4.types.Chunk1_9_3_4Type.read(Chunk1_9_3_4Type.java:40) ~[?:?]
at us.myles.ViaVersion.protocols.protocol1_9_1_2to1_9_3_4.types.Chunk1_9_3_4Type.read(Chunk1_9_3_4Type.java:20) ~[?:?]
at us.myles.ViaVersion.api.type.PartialType.read(PartialType.java:19) ~[?:?]
at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:144) ~[?:?]
at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9$1.handle(WorldPackets.java:337) ~[?:?]
at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19) ~[?:?]
at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:127) ~[?:?]
at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:419) ~[?:?]
at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:432) ~[?:?]
at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81) ~[?:?]
at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:323) ~[?:?]
at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:301) ~[?:?]
at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:34) ~[?:?]
at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:14) ~[?:?]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:54d1f4a:360]
... 51 more
>.... [00:05:39 INFO]: [Lupenator401] disconnected with: EncoderException : us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9$1 (Anonymous), Data: [], Packet ID: 34}
Actual Error: @ io.netty.handler.codec.MessageToMessageEncoder:104`

**How can we reproduce it?**
PaperSpigotServer: git-Paper-1615 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Bungee latest Waterfall: https://papermc.io/ci/job/Waterfall/lastSuccessfulBuild/artifact/Waterfall-Proxy/bootstrap/target/Waterfall.jar 

ViaVersion is installed only on Bungee-Waterfall.

**ViaVersion Dump:**
https://dump.viaversion.com/9925f97e815de22f6731c1bae6073278326d9bb1df97fc8baf92b55048a27732

Hope it helps, I will provide more info if needed.

**Comment by FormallyMyles** [comment]
Remove / update / downgrade skinrestorer

**Comment by JimmyEstrada** [comment]
I have the same problem!

**Comment by JimmyEstrada** [comment]
and i dont have skinrestorer
