### ISSUE TITLE
Unknown Error in Console

### ISSUE THREAD

**Issue by kylewilk567** [ViaVersion/ViaVersion#1896]
[12:43:42 WARN]: [ViaVersion] ERROR IN BaseProtocol IN REMAP OF 0x00->0x00
[12:43:42 WARN]: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[12:43:42 WARN]: {Type: String, Source #0: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous), Data: [Pair{Type|VarInt, 0}], Packet ID: 0}
[12:43:42 WARN]: Actual Error:
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at net.minecraft.server.v1_12_R1.LegacyPingHandler.channelRead(LegacyPingHandler.java:121)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[12:43:42 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[12:43:42 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
[12:43:42 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
[12:43:42 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[12:43:42 WARN]: at java.lang.Thread.run(Thread.java:748)
[12:43:42 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[12:43:42 WARN]: {Type: String, Source #0: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous), Data: [Pair{Type|VarInt, 0}], Packet ID: 0}
[12:43:42 WARN]: Actual Error:
[12:43:42 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(47) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 256)
[12:43:42 WARN]: at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
[12:43:42 WARN]: at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1392)
[12:43:42 WARN]: at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:946)
[12:43:42 WARN]: at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:32)
[12:43:42 WARN]: at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[12:43:42 WARN]: at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:144)
[12:43:42 WARN]: at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[12:43:42 WARN]: at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:125)
[12:43:42 WARN]: at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:419)
[12:43:42 WARN]: at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:96)
[12:43:42 WARN]: at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:432)
[12:43:42 WARN]: at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
[12:43:42 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:323)
[12:43:42 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:314)
[12:43:42 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:36)
[12:43:42 WARN]: at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
[12:43:42 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:43:42 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[12:43:42 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:513)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[12:43:42 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at net.minecraft.server.v1_12_R1.LegacyPingHandler.channelRead(LegacyPingHandler.java:121)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:43:42 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:43:42 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:43:42 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[12:43:42 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[12:43:42 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
[12:43:42 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
[12:43:42 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[12:43:42 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by KennyTV** [comment]
Update to https://ci.viaversion.com/ (and the issue template also has feelings, it doesn't like being ignored :()
