### ISSUE TITLE
RPG items cause crashes

### ISSUE THREAD

**Issue by jiazhengkun** [ViaVersion/ViaVersion#1912]
![(RI`4{LWY2CG6G{Z {}CDGK](https://user-images.githubusercontent.com/42143735/87390180-e6909980-c5da-11ea-91d0-942c7be003fe.jpg)

**Comment by Xernium** [comment]
Please follow the issue template format or this issue will be closed and marked as invalid.

**Comment by jiazhengkun** [comment]
**Describe the bug, provide any errors**
`[12:47:03] [Netty Worker IO Thread #45/ERROR]: [/115.148.44.170:23563|wujie] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: FlatVarIntItem, Source #1: us.myles.ViaVersion.api.rewriters.BlockRewriter$5 (Anonymous), Source #0: us.myles.ViaVersion.api.rewriters.BlockRewriter$5$$Lambda$86/178658894, Data: [Pair{Type|Integer, 32}, Pair{Type|Boolean, false}, Pair{Type|Double, 316.96014404296875}, Pair{Type|Double, 105.01524353027344}, Pair{Type|Double, 44.206478118896484}, Pair{Type|Float, 1.0}, Pair{Type|Float, 1.0}, Pair{Type|Float, 1.0}, Pair{Type|Float, 1.0E-5}, Pair{Type|Integer, 1000}], Packet ID: 36}
Actual Error: 
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:183) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:143) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:113) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: FlatVarIntItem, Source #1: us.myles.ViaVersion.api.rewriters.BlockRewriter$5 (Anonymous), Source #0: us.myles.ViaVersion.api.rewriters.BlockRewriter$5$$Lambda$86/178658894, Data: [Pair{Type|Integer, 32}, Pair{Type|Boolean, false}, Pair{Type|Double, 316.96014404296875}, Pair{Type|Double, 105.01524353027344}, Pair{Type|Double, 44.206478118896484}, Pair{Type|Float, 1.0}, Pair{Type|Float, 1.0}, Pair{Type|Float, 1.0}, Pair{Type|Float, 1.0E-5}, Pair{Type|Integer, 1000}], Packet ID: 36}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(50) + length(1) exceeds writerIndex(50): PooledUnsafeDirectByteBuf(ridx: 50, widx: 50, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:731) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:740) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	at us.myles.ViaVersion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:14) ~[?:?]
	at us.myles.ViaVersion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:7) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:144) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:194) ~[?:?]
	at us.myles.ViaVersion.api.rewriters.BlockRewriter$5.lambda$registerMap$0(BlockRewriter.java:129) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19) ~[?:?]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:127) ~[?:?]
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:419) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:432) ~[?:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:323) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:301) ~[?:?]
	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:34) ~[?:?]
	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:14) ~[?:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[zCore.jar:git:Waterfall-Bootstrap:1.16-R0.1-SNAPSHOT:6bfefea:357]
	... 49 more
[12:47:03] [Netty Worker IO Thread #45/INFO]: [wujie] disconnected with: EncoderException : us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: FlatVarIntItem, Source #1: us.myles.ViaVersion.api.rewriters.BlockRewriter$5 (Anonymous), Source #0: us.myles.ViaVersion.api.rewriters.BlockRewriter$5$$Lambda$86/178658894, Data: [Pair{Type|Integer, 32}, Pair{Type|Boolean, false}, Pair{Type|Double, 316.96014404296875}, Pair{Type|Double, 105.01524353027344}, Pair{Type|Double, 44.206478118896484}, Pair{Type|Float, 1.0}, Pair{Type|Float, 1.0}, Pair{Type|Float, 1.0}, Pair{Type|Float, 1.0E-5}, Pair{Type|Integer, 1000}], Packet ID: 36}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104
[12:47:03] [Netty Worker IO Thread #45/INFO]: [/115.148.44.170:23563|wujie] -> UpstreamBridge has disconnected
[12:47:03] [Netty Worker IO Thread #45/INFO]: [/115.148.44.170:23563|wujie] <-> DownstreamBridge <-> [VoidCrush] has disconnected`
**How can we reproduce it?**
This problem was reported by the player, no more details are available at the moment, this error message is excerpted from Waterfall

**Comment by jiazhengkun** [comment]
**ViaVersion Dump:**
https://dump.viaversion.com/4257ff33e94a00286e8131376ba69ca7e2985605c9741b530336fdb48f6ab0b3

**Comment by jiazhengkun** [comment]
OK.



At 2020-07-14 14:08:13, "FivePB (Xer)" <notifications@github.com> wrote:

Please follow the issue template format or this issue will be closed and marked as invalid.

**Comment by jiazhengkun** [comment]
plugins:
BC:
![批注 2020-07-14 1418531](https://user-images.githubusercontent.com/42143735/87391468-6ae41c00-c5dd-11ea-9a94-6cd954a52963.png)
![批注 2020-07-14 141853](https://user-images.githubusercontent.com/42143735/87391459-661f6800-c5dd-11ea-9378-533ae77b5335.png)
Bukkit:
![批注 2020-07-14 142312133](https://user-images.githubusercontent.com/42143735/87391678-c57d7800-c5dd-11ea-96c3-989726794d1a.png)
![批注 2020-07-14 142312](https://user-images.githubusercontent.com/42143735/87391684-c7dfd200-c5dd-11ea-840e-57b4d5eed737.png)
![批注 2020-07-14 1423121](https://user-images.githubusercontent.com/42143735/87391690-c910ff00-c5dd-11ea-976c-62de83340604.png)
![Uploading 批注 2020-07-14 14231213.png…]()

**Comment by jiazhengkun** [comment]
![批注 2020-07-14 142312133](https://user-images.githubusercontent.com/42143735/87391763-eba31800-c5dd-11ea-932c-63d0bcb967e0.png)

**Comment by jiazhengkun** [comment]
**The problem has been solved. Delete ViaBackwards and ViaRewind and you can play normally**
