### ISSUE TITLE
Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues {Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$8 (Anonymous)}

### ISSUE THREAD

**Issue by Saynni** [ViaVersion/ViaVersion#1965]
[12:41:36] [Server Thread/INFO]: imbadsry[/37.167.120.152:57193] logged in with entity id 27 at ([world]0.5, 53.0, 0.5)
[12:41:36] [Netty Server IO #3/WARN]: [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x2B->0x2B
[12:41:36] [Netty Server IO #3/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$8 (Anonymous)}
Actual Error: 
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:41:36] [Netty Server IO #3/WARN]: 	at net.brwserv.spigotapi.utils.packets.Packets$1.write(Packets.java:97)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:104)
[12:41:36] [Netty Server IO #3/WARN]: 	at fr.nitriz_dev.haireth.packet.listeners.PacketEncoder.write(PacketEncoder.java:33)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:41:36] [Netty Server IO #3/WARN]: 	at hamsterapi.handlers.PacketHandler.write(PacketHandler.java:52)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[12:41:36] [Netty Server IO #3/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.lambda$a$2(SourceFile:205)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[12:41:36] [Netty Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[12:41:36] [Netty Server IO #3/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$8 (Anonymous)}
Actual Error: 
[12:41:36] [Netty Server IO #3/WARN]: Caused by: java.lang.NullPointerException
[12:41:36] [Netty Server IO #3/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$8$1.handle(PlayerPackets.java:267)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:420)
[12:41:36] [Netty Server IO #3/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.Protocol1_7_6_10TO1_8.transform(Protocol1_7_6_10TO1_8.java:143)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:41:36] [Netty Server IO #3/WARN]: 	at net.brwserv.spigotapi.utils.packets.Packets$1.write(Packets.java:97)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:104)
[12:41:36] [Netty Server IO #3/WARN]: 	at fr.nitriz_dev.haireth.packet.listeners.PacketEncoder.write(PacketEncoder.java:33)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:41:36] [Netty Server IO #3/WARN]: 	at hamsterapi.handlers.PacketHandler.write(PacketHandler.java:52)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[12:41:36] [Netty Server IO #3/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.lambda$a$2(SourceFile:205)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[12:41:36] [Netty Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[12:41:36] [Netty Server IO #3/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$8 (Anonymous)}
Actual Error: 
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:41:36] [Netty Server IO #3/WARN]: 	at net.brwserv.spigotapi.utils.packets.Packets$1.write(Packets.java:97)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:104)
[12:41:36] [Netty Server IO #3/WARN]: 	at fr.nitriz_dev.haireth.packet.listeners.PacketEncoder.write(PacketEncoder.java:33)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:41:36] [Netty Server IO #3/WARN]: 	at hamsterapi.handlers.PacketHandler.write(PacketHandler.java:52)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[12:41:36] [Netty Server IO #3/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.lambda$a$2(SourceFile:205)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[12:41:36] [Netty Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[12:41:36] [Netty Server IO #3/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$8 (Anonymous)}
Actual Error: 
[12:41:36] [Netty Server IO #3/WARN]: Caused by: java.lang.NullPointerException
[12:41:36] [Netty Server IO #3/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$8$1.handle(PlayerPackets.java:267)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:420)
[12:41:36] [Netty Server IO #3/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.Protocol1_7_6_10TO1_8.transform(Protocol1_7_6_10TO1_8.java:143)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[12:41:36] [Netty Server IO #3/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:41:36] [Netty Server IO #3/WARN]: 	at net.brwserv.spigotapi.utils.packets.Packets$1.write(Packets.java:97)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:104)
[12:41:36] [Netty Server IO #3/WARN]: 	at fr.nitriz_dev.haireth.packet.listeners.PacketEncoder.write(PacketEncoder.java:33)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:41:36] [Netty Server IO #3/WARN]: 	at hamsterapi.handlers.PacketHandler.write(PacketHandler.java:52)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[12:41:36] [Netty Server IO #3/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.lambda$a$2(SourceFile:205)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[12:41:36] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[12:41:36] [Netty Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[12:41:36] [Server Thread/INFO]: imbadsry lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$8 (Anonymous)}
Actual Error:

**Comment by KennyTV** [comment]
That's a ViaRewind issue; please also don't discard the issue template.
