### ISSUE TITLE
error when joining with 1.8.* client

### ISSUE THREAD

**Issue by Vinyljackers** [ViaVersion/ViaVersion#1981]
[20:31:45 WARN]: [ViaVersion] ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x0C->0xFFFFFFFF
[20:31:45 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[20:31:45 WARN]: {Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}
[20:31:45 WARN]: Actual Error:
[20:31:45 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:31:45 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[20:31:45 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[20:31:45 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:31:45 WARN]: at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[20:31:45 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[20:31:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[20:31:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[20:31:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[20:31:45 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:31:45 WARN]: at java.lang.Thread.run(Thread.java:748)
[20:31:45 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[20:31:45 WARN]: {Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}
[20:31:45 WARN]: Actual Error:
[20:31:45 WARN]: Caused by: java.io.IOException: Unable to read type String, found JsonElement
[20:31:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:156)
[20:31:45 WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1.handle(PlayerPackets.java:57)
[20:31:45 WARN]: at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[20:31:45 WARN]: at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[20:31:45 WARN]: at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:420)
[20:31:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[20:31:45 WARN]: at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
[20:31:45 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
[20:31:45 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304)
[20:31:45 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[20:31:45 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[20:31:45 WARN]: at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
[20:31:45 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:31:45 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:477)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:247)
[20:31:45 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:31:45 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[20:31:45 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[20:31:45 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:31:45 WARN]: at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[20:31:45 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[20:31:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[20:31:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[20:31:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[20:31:45 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:31:45 WARN]: at java.lang.Thread.run(Thread.java:748)
[20:31:45 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[20:31:45 WARN]: {Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}
[20:31:45 WARN]: Actual Error:
[20:31:45 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:31:45 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[20:31:45 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[20:31:45 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:31:45 WARN]: at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[20:31:45 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[20:31:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[20:31:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[20:31:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[20:31:45 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:31:45 WARN]: at java.lang.Thread.run(Thread.java:748)
[20:31:45 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[20:31:45 WARN]: {Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}
[20:31:45 WARN]: Actual Error:
[20:31:45 WARN]: Caused by: java.io.IOException: Unable to read type String, found JsonElement
[20:31:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:156)
[20:31:45 WARN]: at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1.handle(PlayerPackets.java:57)
[20:31:45 WARN]: at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[20:31:45 WARN]: at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[20:31:45 WARN]: at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:420)
[20:31:45 WARN]: at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[20:31:45 WARN]: at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
[20:31:45 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
[20:31:45 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304)
[20:31:45 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[20:31:45 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[20:31:45 WARN]: at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
[20:31:45 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:31:45 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:477)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:247)
[20:31:45 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:253)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:31:45 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:31:45 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[20:31:45 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[20:31:45 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:31:45 WARN]: at net.minecraft.server.v1_16_R1.NetworkManager.lambda$b$6(NetworkManager.java:300)
[20:31:45 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:325)
[20:31:45 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[20:31:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[20:31:45 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[20:31:45 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[20:31:45 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:31:45 WARN]: at java.lang.Thread.run(Thread.java:748)
[20:31:46 INFO]: Vinyljackers lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}

**Comment by krusic22** [comment]
Please follow the template.
