### ISSUE TITLE
Players on 1.16 can't see other players but older versions (1.8+ (but not 1.16.x)) can see all players.

### ISSUE THREAD

**Issue by ktg5** [ViaVersion/ViaVersion#1994]
**Describe the bug, provide any errors**
My issue on my server is that players on 1.16 can't see any players on my server, but players using older versions of Minecraft can see all players.
My server is running the latest version of Spigot 1.8.8

**How can we reproduce it?**
Have one user login to the server on 1.8
Have another user login to the same server on 1.16
See if you can see each other.

**Expected behavior**
What is expected is to be able all players on any version of Minecraft.

**Screenshots**
Here are lists of screenshots from 3 tests I've done on my server with 2 of my accounts (ktg5, and ktg6)
[Test 1 - Client 1+2 are on 1.8](https://imgur.com/a/ad9Epww)
[Test 2 - Client 1 is on 1.8 and client 2 is on 1.16](https://imgur.com/a/jMf8zOX)
[Test 3 - Client 1+2 are on 1.16](https://imgur.com/a/rt9EUTp)

**ViaVersion Dump**
[Dump](https://dump.viaversion.com/b04054fabf9f5ce77eefda2f1c22e37127d2c094c44dc61bc9fa5c2d85d2bfb9)

**Additional server info**
- BungeeCord is installed on the server.
- [All plugins are listed here](https://i.imgur.com/bOZassI.png).

**Checklist**
- [check.] I have included a Viaversion dump.
- [didn't get any error in console.] If applicable, I have included a paste (not a screenshot) of the error.
- [both latest DEV and SNAPSHOT] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Can you try without TAB/other plugins and see if the issue persists?

**Comment by ktg5** [comment]
I've tried removing all plugins except ViaVersion, and the problem still goes on. Looks like it's a problem with ViaVersion?

**Comment by ktg5** [comment]
So I've actually created a new fresh server with BuildTools and did the following:
- Added only ViaVersion (saw others players on 1.8 and 1.16)
- Added all the other plugins I used on my other server (saw others players on 1.8 and 1.16)
And somehow when I connected the server to BungeeCord, it wasn't able to see any other players on 1.16.
So it's actually a BungeeCord problem I guess. Should I report this to BungeeCord? or is this something you all will be able to fix?

**Comment by KennyTV** [comment]
Did you try without Bungee plugins as well + with the standard 1.16.2 Bungee (no fork of it)?

**Comment by ktg5** [comment]
Yep, still the same problem. Also I've been already using the latest version of BungeeCord from Jenkins.

**Comment by rjammet** [comment]
Yop!
I have exactly this problem, no players view.. But in other server on 1.14 can see. But in 1.16 server no

**Comment by avaruus1** [comment]
I am having the same issue. It only occurs on one of the three servers on my bungeecord network and all of these three servers are running the same version of paper spigot and the same version of ViaVersion (3.1.0). I've tried removing all plugins except for ViaVersion, but the issue still persists.

It appears that when a player comes in to the render distance of a 1.16 player, the following stracktrace is logged in the 1.16 user's client log.
```
Error executing task on Client
java.lang.NullPointerException
	at dwm.a(SourceFile:581)
	at or.a(SourceFile:57)
	at or.a(SourceFile:11)
	at ol.a(SourceFile:21)
	at any.c(SourceFile:144)
	at aoc.c(SourceFile:23)
	at any.y(SourceFile:118)
	at any.bk(SourceFile:103)
	at djw.e(SourceFile:990)
	at djw.e(SourceFile:656)
	at net.minecraft.client.main.Main.main(SourceFile:215)```

**Comment by KennyTV** [comment]
Would you be able to get the deobfuscated trace with that? (e.g. Fabric w https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes, or getting those through Yarn/Moj mappings manually)

**Comment by avaruus1** [comment]
Sure, here it is:
```
Error executing task on Client
java.lang.NullPointerException
	at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.26)
	at net.minecraft.client.network.ClientPlayNetworkHandler.onPlayerSpawn(ClientPlayNetworkHandler:581)
	at net.minecraft.network.packet.s2c.play.PlayerSpawnS2CPacket.apply(PlayerSpawnS2CPacket:57)
	at net.minecraft.network.packet.s2c.play.PlayerSpawnS2CPacket.apply(PlayerSpawnS2CPacket:11)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:990)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

**Comment by KennyTV** [comment]
Hmm, the code around player info adding/player adding has not changed at all from 1.15, so that's a dead end.

**Comment by Wumfie** [comment]
I am also getting the same issue. Would really love to see a fix as this has been bugging me for a while. I can provide info if you would like. Not happening on my lobby server but it is hapenning on the minigame server. Only affects 1.16 to 1.16.2 servers not a problem on 1.15.2. Could be a world issue? The lobby and the minigame server run the same paper version and the plugins are the same other than NoteBlockAPI (on Minigames). The only other differences are that it is using a different world name.

**Comment by Wumfie** [comment]
Update. Copied my lobby then deleted all of the unused plugins and worlds and loaded all the settings from the minigames server and now its working flawlessly. Really don't know what happened here.

**Comment by KennyTV** [comment]
Thank you for your testing!
Another guess is that it *might* have something to do with server switching under Bungee
