### ISSUE TITLE
client crash on spawn entity EntityAreaEffectCloud on 1.13 client and 1.12.2 server

### ISSUE THREAD

**Issue by lokha** [ViaVersion/ViaVersion#2016]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

paperspigot 1.12.2
client version 1.13 vanilla

the client crashes when spawning the EntityAreaEffectCloud mob. the minecraft client program is shutting down

I have a command to test viaversion errors  
this command will spawn all mobs on the server as follows:
```java
Iterator<EntityType> iterator = Stream.of(EntityType.values()).iterator();
final AtomicReference<Entity> entity = new AtomicReference<>();

// start timer every tick
			
EntityType next = iterator.next();
if(entity.get() != null && entity.get().isValid()) {
	entity.get().remove();
}

Entity spawnEntity = player.getWorld().spawnEntity(player.getLocation(), next);
	if(spawnEntity != null) {
		entity.set(spawnEntity);
	}

if(!iterator.hasNext()) {
	// end timer
}
```

using it I will check for errors in your plugin

on version 1.13 of the minecraft client, when the EntityAreaEffectCloud spawns, the client crashes.  
the problem is present only on version `1.13`, on other versions everything is ok.  
I have an error from minecraft logs:  

```
[09:49:17] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.crash.ReportedException: Ticking entity
	at net.minecraft.world.World.tickEntities(World.java:1014) ~[main/:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1171) ~[main/:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:754) ~[main/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:355) [main/:?]
	at net.minecraft.client.main.Main.main(Main.java:117) [main/:?]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to net.minecraft.particles.IParticleData
	at net.minecraft.entity.EntityAreaEffectCloud.func_195058_l(EntityAreaEffectCloud.java:129) ~[main/:?]
	at net.minecraft.entity.EntityAreaEffectCloud.tick(EntityAreaEffectCloud.java:157) ~[main/:?]
	at net.minecraft.world.World.tickEntity(World.java:1155) ~[main/:?]
	at net.minecraft.world.World.tickEntity(World.java:1129) ~[main/:?]
	at net.minecraft.world.World.tickEntities(World.java:1009) ~[main/:?]
	... 4 more
```

![image](https://user-images.githubusercontent.com/32991511/90481127-ef284280-e139-11ea-819a-91211324234e.png)

**How can we reproduce it?**
1. Login on '1.13'
2. Spawn EntityAreaEffectCloud 
3. And game crash..

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.  

https://dump.viaversion.com/9cb16f5903cee72724f8ba891289a1841889a4377f15bca24f4e462af54586ff

**Additional server info**
regardless of the presence of a proxy, the problem is reproducible

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [ ] I have tried a build from https://ci.viaversion.com/ and the issue still persists

*sorry my english*

**Comment by KennyTV** [comment]
Don't use 1.13.0, we won't fix such client quirks for outdated patch releases.

**Comment by lokha** [comment]
outdated?

isn't it the purpose of viaversion to make it possible to support future versions on older versions of spigot?

![image](https://user-images.githubusercontent.com/32991511/90488610-d6715a00-e144-11ea-859d-dcd7b0d08324.png)

**Comment by Justsnoopy30** [comment]
Yes, but you need to use the last patch release for your server version (e.g 1.13.2).
