### ISSUE TITLE
Adding item to inventory BUG, lost items

### ISSUE THREAD

**Issue by JH3Y50N** [ViaVersion/ViaVersion#2019]
**Describe the bug, provide any errors**
Pastebin: https://pastebin.com/n4qw38hW
`[02:07:47 INFO]: Negative index in crash report handler (0/20)
[02:07:47 WARN]: java.lang.reflect.InvocationTargetException
[02:07:47 WARN]:        at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
[02:07:47 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:07:47 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[02:07:47 WARN]:        at us.myles.ViaVersion.bukkit.providers.BukkitViaMovementTransmitter.sendPlayer(BukkitViaMovementTransmitter.java:91)
[02:07:47 WARN]:        at us.myles.ViaVersion.protocols.protocol1_9to1_8.ViaIdleThread.run(ViaIdleThread.java:22)
[02:07:47 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[02:07:47 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
[02:07:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
[02:07:47 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[02:07:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[02:07:47 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[02:07:47 WARN]:        at java.lang.Thread.run(Thread.java:748)
[02:07:47 WARN]: Caused by: net.minecraft.server.v1_8_R3.ReportedException: Adding item to inventory
[02:07:47 WARN]:        at net.minecraft.server.v1_8_R3.EntityPlayer.l(EntityPlayer.java:358)
[02:07:47 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:385)
[02:07:47 WARN]:        ... 12 more
[02:07:47 WARN]: Caused by: java.lang.NullPointerException
`

**How can we reproduce it?**
Add items to a player's inventory with a plugin, like full inventory.. See the print how to do
![image](https://user-images.githubusercontent.com/29031972/90594461-db73ef00-e1c0-11ea-8b83-7412e445af8d.png)

**Expected behaviour**
Items should go to the player's inventory, but are not going and are being lost

**Screenshots**
![image](https://user-images.githubusercontent.com/29031972/90594189-36f1ad00-e1c0-11ea-9909-291a2f3ac13f.png)

**ViaVersion Dump**
https://dump.viaversion.com/dda60d5fedacf625d36cea91cc578c103b59e9a075ef1942d88b3cb2043c70f7

**Additional server info**
I use bungeecord but the ViaVersion i use on spigot servers.. Main version 1.8

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by FormallyMyles** [comment]
What versions are clients which are affected by this bug? Have you tried on a fresh paper server?

**Comment by JH3Y50N** [comment]
> What versions are clients which are affected by this bug? Have you tried on a fresh paper server?

All versões is affected, "new paper" no.. i have only updated the ViaVersion and this bug happens, started happens

**Comment by FormallyMyles** [comment]
Does it happen on 1.8.8?

**Comment by JH3Y50N** [comment]
> Does it happen on 1.8.8?
yes

**Comment by FormallyMyles** [comment]
ViaVersion doesn't modify data for your server version, this will be down to your server

**Comment by JH3Y50N** [comment]
> ViaVersion doesn't modify data for your server version, this will be down to your server

the bug continues, when items are added too quickly to the player's inventory the items are not added and ViaVersion sends an error message in the console.

Remembering that this does not always happen, there are times that it works normally other hours it bugs
