### ISSUE TITLE
ViaVersion bug

### ISSUE THREAD

**Issue by NonSwag** [ViaVersion/ViaVersion#2050]
[ViaVersion] ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x0C->0xFFFFFFFF
[13:02:38 WARN]: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
[13:02:38 WARN]: {Type: JsonElement, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}
[13:02:38 WARN]: Actual Error: 
[13:02:38 WARN]: Caused by: java.io.IOException: Unable to read type JsonElement, found String
[13:02:38 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:156)
[13:02:38 WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1.handle(PlayerPackets.java:57)
[13:02:38 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[13:02:38 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[13:02:38 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:420)
[13:02:38 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[13:02:38 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:339)
[13:02:38 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)
[13:02:38 WARN]:        at de.gerrygames.viarewind.utils.PacketUtil.sendPacket(PacketUtil.java:37)
[13:02:38 WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.sendBossBar(Cooldown.java:108)
[13:02:38 WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.showCooldown(Cooldown.java:69)
[13:02:38 WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.tick(Cooldown.java:59)
[13:02:38 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[13:02:38 WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[13:02:38 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[13:02:38 WARN]:        at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566)
[13:02:38 WARN]:        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[13:02:38 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[13:02:38 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[13:02:38 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[13:02:38 WARN]:        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[13:02:38 WARN]:        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
[13:02:38 WARN]:        at de.gerrygames.viarewind.utils.Ticker.lambda$null$0(Ticker.java:16)
[13:02:38 WARN]:        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
[13:02:38 WARN]:        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
[13:02:38 WARN]:        at de.gerrygames.viarewind.utils.Ticker.lambda$init$1(Ticker.java:15)
[13:02:38 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[13:02:38 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[13:02:38 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1325)
[13:02:38 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432)
[13:02:38 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1240)
[13:02:38 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971)
[13:02:38 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by KennyTV** [comment]
Use Via* builds from ci.viaversion.com
