### ISSUE TITLE
%s bug?

### ISSUE THREAD

**Issue by chickiyeah** [ViaVersion/ViaVersion#2053]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.8'
2. type:/uecon

**Expected behaviour**

**Screenshots**
[19:35:18 INFO]: chickiyeah issued server command: /uecon
[19:35:18 WARN]: [ViaVersion] ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x13->0x2D
[19:35:18 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [Pair{Type|Unsigned Byte, 1}, Pair{Type|String, minecraft:container}], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$2 (Anonymous), Packet ID: 45}
Actual Error: 
[19:35:18 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[19:35:18 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[19:35:18 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[19:35:18 WARN]: 	at net.minecraft.server.v1_16_R2.NetworkManager.lambda$4(NetworkManager.java:189)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[19:35:18 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[19:35:18 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[19:35:18 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[19:35:18 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:35:18 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[19:35:18 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [Pair{Type|Unsigned Byte, 1}, Pair{Type|String, minecraft:container}], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$2 (Anonymous), Packet ID: 45}
Actual Error: 
[19:35:18 WARN]: Caused by: java.io.IOException: Unable to read type String, found JsonElement
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:156)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:129)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:420)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304)
[19:35:18 WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[19:35:18 WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[19:35:18 WARN]: 	at sun.reflect.GeneratedMethodAccessor678.invoke(Unknown Source)
[19:35:18 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:35:18 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[19:35:18 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[19:35:18 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[19:35:18 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[19:35:18 WARN]: 	at net.minecraft.server.v1_16_R2.NetworkManager.lambda$4(NetworkManager.java:189)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[19:35:18 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[19:35:18 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[19:35:18 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[19:35:18 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:35:18 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[19:35:18 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [Pair{Type|Unsigned Byte, 1}, Pair{Type|String, minecraft:container}], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$2 (Anonymous), Packet ID: 45}
Actual Error: 
[19:35:18 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[19:35:18 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[19:35:18 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[19:35:18 WARN]: 	at net.minecraft.server.v1_16_R2.NetworkManager.lambda$4(NetworkManager.java:189)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[19:35:18 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[19:35:18 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[19:35:18 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[19:35:18 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:35:18 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[19:35:18 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [Pair{Type|Unsigned Byte, 1}, Pair{Type|String, minecraft:container}], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$2 (Anonymous), Packet ID: 45}
Actual Error: 
[19:35:18 WARN]: Caused by: java.io.IOException: Unable to read type String, found JsonElement
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:156)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:129)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:420)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
[19:35:18 WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304)
[19:35:18 WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[19:35:18 WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[19:35:18 WARN]: 	at sun.reflect.GeneratedMethodAccessor678.invoke(Unknown Source)
[19:35:18 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:35:18 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[19:35:18 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[19:35:18 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[19:35:18 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[19:35:18 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[19:35:18 WARN]: 	at net.minecraft.server.v1_16_R2.NetworkManager.lambda$4(NetworkManager.java:189)
[19:35:18 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[19:35:18 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[19:35:18 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[19:35:18 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[19:35:18 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:35:18 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[19:35:18 INFO]: chickiyeah lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [Pair{Type|Unsigned Byte, 1}, Pair{Type|String, minecraft:container}], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$2 (Anonymous), Packet ID: 45}
Actual Error: 
[19:35:18 INFO]: chickiyeah left the game

**ViaVersion Dump**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/0cc1e954108e2ceef89046532b195aa7481ea6d2ebfb6e9e4452422780cefc0b

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Checklist**
- [x] I have included a Viaversion dump
- [x] If applicable, I have included a paste (not a screenshot) of the error
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by chickiyeah** [comment]
https://paste.gg/p/anonymous/8d87b360b6e041a4a0f041e34d78bdcb

**Comment by KennyTV** [comment]
This is a ViaRewind issue.
