### ISSUE TITLE
ViaVersion 3.1.1 spam errors in console

### ISSUE THREAD

**Issue by Misha1Nurmuhametov** [ViaVersion/ViaVersion#2101]
[12:37:15 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[12:37:15 WARN]: {Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$1 (Anonymous), Packet ID: 0}
[12:37:15 WARN]: Actual Error:
[12:37:15 WARN]: Caused by: java.lang.IllegalArgumentException: Cannot receive string longer than Short.MAX_VALUE characters (got 34875 bytes)
[12:37:15 WARN]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
[12:37:15 WARN]: at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:34)
[12:37:15 WARN]: at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[12:37:15 WARN]: at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[12:37:15 WARN]: at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[12:37:15 WARN]: at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:129)
[12:37:15 WARN]: at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:418)
[12:37:15 WARN]: at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[12:37:15 WARN]: at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
[12:37:15 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
[12:37:15 WARN]: at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304)
[12:37:15 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[12:37:15 WARN]: at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[12:37:15 WARN]: at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
[12:37:15 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:37:15 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[12:37:15 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[12:37:15 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[12:37:15 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[12:37:15 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[12:37:15 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[12:37:15 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[12:37:15 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[12:37:15 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[12:37:15 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:37:15 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:201)
[12:37:15 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157)
[12:37:15 WARN]: at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:109)
[12:37:15 WARN]: at net.minecraft.server.v1_12_R1.PacketStatusListener.a(PacketStatusListener.java:131)
[12:37:15 WARN]: at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:23)
[12:37:15 WARN]: at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:8)
[12:37:15 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:140)
[12:37:15 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:370)
[12:37:15 WARN]: at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:31)
[12:37:15 WARN]: at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:37:15 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:37:15 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[12:37:15 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:37:15 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:37:15 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[12:37:15 WARN]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:37:15 WARN]: at net.minecraft.server.v1_12_R1.LegacyPingHandler.channelRead(LegacyPingHandler.java:121)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:37:15 WARN]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[12:37:15 WARN]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[12:37:15 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[12:37:15 WARN]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[12:37:15 WARN]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[12:37:15 WARN]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
[12:37:15 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
[12:37:15 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[12:37:15 WARN]: at java.lang.Thread.run(Thread.java:748)
[12:37:16 WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[12:37:16 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[12:37:16 WARN]: {Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$1 (Anonymous), Packet ID: 0}

**Comment by KennyTV** [comment]
Follow the issue template.
