### ISSUE TITLE
REMAP OF TEAMS, error.

### ISSUE THREAD

**Issue by Tauchet** [ViaVersion/ViaVersion#2129]
[13:46:16] [Netty Epoll Server IO #2/WARN]: [ViaVersion] ERROR IN Protocol1_9To1_8 IN REMAP OF TEAMS (0x3E)
[13:46:16] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at me.levansj01.verus.compat.v1_8_R3.PacketHandler.write(Unknown Source)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:46:16] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:458)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:66)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:232)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	... 23 more
[13:46:16] [Netty Epoll Server IO #2/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String Array, Data: [Pair{Type|String, ZVX_E1}, Pair{Type|Byte, 0}, Pair{Type|String, ZVX_E1}, Pair{Type|String, §f}, Pair{Type|String, §f}, Pair{Type|Byte, 1}, Pair{Type|String, always}, Pair{Type|String, never}, Pair{Type|Byte, -1}], Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$6$1 (Anonymous), Packet ID: 65, Source 1: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$6 (Anonymous)}
Actual Error: 
[13:46:16] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(50) + length(1) exceeds writerIndex(50): UnpooledUnsafeDirectByteBuf(ridx: 50, widx: 50, cap: 256)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.VarIntType.readPrimitive(VarIntType.java:18)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:26)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.ArrayType.read(ArrayType.java:27)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.ArrayType.read(ArrayType.java:8)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:193)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$6$1.handle(PlayerPackets.java:126)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:418)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:458)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:66)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:232)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at me.levansj01.verus.compat.v1_8_R3.PacketHandler.write(Unknown Source)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:46:16] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at me.levansj01.verus.compat.v1_8_R3.PacketHandler.write(Unknown Source)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:46:16] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:458)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:66)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:232)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:46:16] [Netty Epoll Server IO #2/WARN]: 	... 23 more

**Comment by KennyTV** [comment]
Follow the issue template.
