### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Y3ko** [ViaVersion/ViaVersion#2157]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.15.2'
2. Click on 'Connect'
3. The 'Login' is displayed wrong

**Expected behaviour**
Login

**Screenshots**
```
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.api.rewriters.TagRewriter$1 (Anonymous), Source 2: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$12 (Anonymous), Source 1: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$1 (Anonymous), Source 4: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$7 (Anonymous), Source 3: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$7$4 (Anonymous)}
Actual Error: 
Caused by: java.lang.NullPointerException
	at us.myles.ViaVersion.protocols.protocol1_15to1_14_4.Protocol1_15To1_14_4.getNewBlockId(Protocol1_15To1_14_4.java:79)
	at us.myles.ViaVersion.api.rewriters.TagRewriter.handle(TagRewriter.java:89)
	at us.myles.ViaVersion.api.rewriters.TagRewriter.access$300(TagRewriter.java:14)
	at us.myles.ViaVersion.api.rewriters.TagRewriter$1.lambda$registerMap$0(TagRewriter.java:61)
	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:418)
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
	at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:339)
	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)
	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:285)
	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:356)
	at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$1.handle(Protocol1_13To1_12_2.java:107)
	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:418)
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
	at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:339)
	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)
	at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$7$4.handle(PlayerPackets.java:213)
	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:418)
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:81)
	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:328)
	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:304)
	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:34)
	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:14)
	at io.netty.handler.codec.MessageToMessageEncoder.write(:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(:758)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(:1020)
	at io.netty.channel.AbstractChannel.writeAndFlush(:299)
	at net.md_5.bungee.netty.ChannelWrapper.write(:60)
	at net.md_5.bungee.UserConnection$1.sendPacket(:145)
	at net.md_5.bungee.ServerConnector.handle(:250)
	at net.md_5.bungee.protocol.packet.Login.handle(:201)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(:475)
	at io.netty.channel.epoll.EpollEventLoop.run(:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(:74)
	at java.lang.Thread.run(Thread.java:748)
```

**ViaVersion Dump**
- https://dump.viaversion.com/7b892d06f77f4abea70b0c5cbcd9305bbd95ebe5358a8824d44380a0013c5189

**Additional server info**
Bungeecord

**Checklist**
- [ yes] I have included a Viaversion dump
- [ yes] If applicable, I have included a paste (not a screenshot) of the error
- [ no] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by KennyTV** [comment]
Use the ci builds as the checklist suggests.
