### ISSUE TITLE
This is the error

### ISSUE THREAD

**Issue by GoT-HiM** [ViaVersion/ViaVersion#2178]
Actual Error: 
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1618]
	at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:505) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1618]
	at LPX.ac.write(Unknown Source) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1618]
	at me.neznamy.tab.platforms.bukkit.Injector$1.write(Injector.java:75) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1618]
	at kernitus.plugin.OldCombatMechanics.utilities.packet.PacketInjector.write(PacketInjector.java:176) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) ~[patched_1.12.2.jar:git-Paper-1618]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@57dca8e}], Packet ID: 33}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
	at us.myles.viaversion.libs.fastutil.ints.IntArrayList.getInt(IntArrayList.java:267) ~[?:?]
	at us.myles.ViaVersion.api.minecraft.chunks.ChunkSection.getFlatBlock(ChunkSection.java:73) ~[?:?]
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.ChunkSectionType1_8.write(ChunkSectionType1_8.java:38) ~[?:?]
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.ChunkSectionType1_8.write(ChunkSectionType1_8.java:11) ~[?:?]
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.write(Chunk1_8Type.java:92) ~[?:?]
	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.write(Chunk1_8Type.java:16) ~[?:?]
	at us.myles.ViaVersion.api.type.PartialType.write(PartialType.java:24) ~[?:?]
	at us.myles.ViaVersion.api.PacketWrapper.writeToBuffer(PacketWrapper.java:242) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:411) ~[?:?]
	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379) ~[?:?]
	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66) ~[?:?]
	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243) ~[?:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[patched_1.12.2.jar:git-Paper-1618]
	... 45 more

**Comment by KennyTV** [comment]
Follow the issue template.

**Comment by GoT-HiM** [comment]
What does that mean?

**Comment by Earthcomputer** [comment]
When you create a new issue, there is text already there. Don't delete it all, and actually follow that template.
