### ISSUE TITLE
Can't join server

### ISSUE THREAD

**Issue by Jack0217dev** [ViaVersion/ViaVersion#2188]
Hi! I get this error everytime i try to join my server

```
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$2$1 (Anonymous), Packet ID: 2, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$2 (Anonymous)}
Actual Error:
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at net.md_5.bungee.connection.InitialHandler$1.sendPacket(InitialHandler.java:92) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:541) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$2$1 (Anonymous), Packet ID: 2, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$2 (Anonymous)}
Actual Error:
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(100) exceeds writerIndex(26): PooledUnsafeDirectByteBuf(ridx: 2, widx: 26, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1463) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:972) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:32) ~[?:?]
        at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9) ~[?:?]
        at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143) ~[?:?]
        at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:193) ~[?:?]
        at us.myles.ViaVersion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:196) ~[?:?]
        at us.myles.ViaVersion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:124) ~[?:?]
        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19) ~[?:?]
        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131) ~[?:?]
        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407) ~[?:?]
        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449) ~[?:?]
        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435) ~[?:?]
        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75) ~[?:?]
        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404) ~[?:?]
        at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379) ~[?:?]
        at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:34) ~[?:?]
        at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:14) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:691ffb1:379]
        ... 25 more``
```

**Comment by KennyTV** [comment]
Follow the issue template.
