### ISSUE TITLE
io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues

### ISSUE THREAD

**Issue by YamiOdymel** [ViaVersion/ViaVersion#2194]
> The server is limited to allow 1.13 - 1.16.4 to play.

**Server version**

```
[Fri, 13. Nov 2020 19:19:26 GMT INFO] This server is running Paper version git-Paper-266 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[Fri, 13. Nov 2020 19:19:26 GMT INFO] Checking version, please wait...
[Fri, 13. Nov 2020 19:19:28 GMT INFO] Previous version: git-Paper-262 (MC: 1.16.4)
[Fri, 13. Nov 2020 19:19:28 GMT INFO] You are 10 version(s) behind
```

**Installed plugins**

```
Plugins (19): AutorunCommands*, BetterSleeping*, ChopTree2, Citizens, CoreProtect, DiscordSRV, dynmap*, LitePlaytimeRewards, LuckPerms, LuckPermsGUI*, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, ProtocolLib, TitleManager, ViaBackwards, ViaVersion, WorldEdit, WorldGuard
```

**Error logs**

```
[Fri, 13. Nov 2020 19:02:33 GMT WARN] io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[Fri, 13. Nov 2020 19:02:33 GMT WARN] {Type: String, Data: [Pair{Type|VarInt, 0}], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol$1$$Lambda$3918/0x00000008015e0440, Packet ID: 0, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)}
[Fri, 13. Nov 2020 19:02:33 GMT WARN] Actual Error:
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at java.base/java.lang.Thread.run(Thread.java:830)
```

```
[Fri, 13. Nov 2020 19:02:33 GMT WARN] Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[Fri, 13. Nov 2020 19:02:33 GMT WARN] {Type: String, Data: [Pair{Type|VarInt, 0}], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol$1$$Lambda$3918/0x00000008015e0440, Packet ID: 0, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)}
[Fri, 13. Nov 2020 19:02:33 GMT WARN] Actual Error:
[Fri, 13. Nov 2020 19:02:33 GMT WARN] Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(47) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 256)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1392)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:946)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:32)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:193)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.protocols.base.BaseProtocol$1.lambda$registerMap$0(BaseProtocol.java:32)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:94)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:454)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at jdk.internal.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:518)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at java.base/java.lang.Thread.run(Thread.java:830)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 96
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at java.base/java.lang.Thread.run(Thread.java:830)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] Caused by: java.io.IOException: Bad packet id 96
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at net.minecraft.server.v1_16_R3.PacketDecoder.decode(SourceFile:37)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.util.PipelineUtil.callDecode(PipelineUtil.java:53)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:42)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at jdk.internal.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:518)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[Fri, 13. Nov 2020 19:02:33 GMT WARN] ... 34 more
```

**Comment by KennyTV** [comment]
Follow the issue template.
