### ISSUE TITLE
Please post this error to https://github.com/ViaVersion/ViaVersion/issues

### ISSUE THREAD

**Issue by xcraftman52** [ViaVersion/ViaVersion#2220]
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$2$1 (Anonymous), Packet ID: 2, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$2 (Anonymous)}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(31) exceeds writerIndex(29): PooledUnsafeDirectByteBuf(ridx: 2, widx: 29, cap: 256)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1464)
    at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:973)
    at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:32)
    at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
    at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
    at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:193)
    at us.myles.ViaVersion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:196)
    at us.myles.ViaVersion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:124)
    at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
    at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
    at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
    at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
    at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
    at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
    at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
    at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
    at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:34)
    at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:14)
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
    at net.md_5.bungee.connection.InitialHandler$1.sendPacket(InitialHandler.java:90)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:532)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Thread.java:748)
19:09:45 [WARNING] Event PostLoginEvent(player=XCraftMan52) took 284ms to process!

**Comment by KennyTV** [comment]
Follow the issue template.
