### ISSUE TITLE
Filled to inject 1.17 (using java15)

### ISSUE THREAD

**Issue by whydesd** [ViaVersion/ViaVersion#2223]
[17:21:14 ERROR] [ViaVersion]: Unable to inject ViaVersion, please post these details on our GitHub and ensure you're using a compatible server version.
[17:21:14 ERROR] [ViaVersion]: ViaVersion failed to inject:
[17:21:14 ERROR]: java.lang.NoSuchMethodException: java.lang.Class.getDeclaredFields0(boolean)
[17:21:14 ERROR]:       at java.base/java.lang.Class.newNoSuchMethodException(Class.java:647)
[17:21:14 ERROR]:       at java.base/java.lang.Class.throwExceptionOrReturnNull(Class.java:1375)
[17:21:14 ERROR]:       at java.base/java.lang.Class.getMethodHelper(Class.java:1461)
[17:21:14 ERROR]:       at java.base/java.lang.Class.getDeclaredMethod(Class.java:1089)
[17:21:14 ERROR]:       at us.myles.ViaVersion.bungee.platform.BungeeViaInjector.inject(BungeeViaInjector.java:34)
[17:21:14 ERROR]:       at us.myles.ViaVersion.ViaManager.init(ViaManager.java:64)
[17:21:14 ERROR]:       at us.myles.ViaVersion.BungeePlugin.onEnable(BungeePlugin.java:75)
[17:21:14 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300)
[17:21:14 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)
[17:21:14 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[17:21:14 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
**Additional server info**
Using Waterfall 1.8-1.16.4
**Checklist**
- [*] I have included a Viaversion dump
- [*] If applicable, I have included a paste (not a screenshot) of the error
- [*] I have tried a build from https://ci.viaversion.com/ and the issue still persists

**Comment by Xernium** [comment]
Via* isn’t compatible with java 15. Use java 11 for now.
