### ISSUE TITLE
About ProBlem

### ISSUE THREAD

**Issue by dianwangwin** [ViaVersion/ViaVersion#2235]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. If present, can you paste the error to https://paste.gg/?

**How can we reproduce it?**
1. Login on 1.12'
2. join in mc.hypixel.net and then join in a game.'
3.Then you will be kick by under problem\
o.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.api.rewriters.ItemRewriter$3 (Anonymous)}
Actual Error: 
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [ReadTimeoutHandler.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:4.0.23.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [AbstractNioByteChannel$NioByteUnsafe.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.api.rewriters.ItemRewriter$3 (Anonymous)}
Actual Error: 
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Short
	at nl.matsv.viabackwards.api.rewriters.LegacyEnchantmentRewriter.rewriteEnchantmentsToClient(LegacyEnchantmentRewriter.java:27) ~[LegacyEnchantmentRewriter.class:git-ViaBackwards-3.3.0-20w45a:0f0aecb]
	at nl.matsv.viabackwards.protocol.protocol1_11to1_11_1.packets.ItemPackets1_11_1.handleItemToClient(ItemPackets1_11_1.java:106) ~[ItemPackets1_11_1.class:git-ViaBackwards-3.3.0-20w45a:0f0aecb]
	at us.myles.ViaVersion.api.rewriters.ItemRewriter.lambda$itemToClientHandler$1(ItemRewriter.java:240) ~[ItemRewriter.class:git-ViaVersion-3.3.0-20w45a:fb8108e]
	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19) ~[PacketHandler.class:git-ViaVersion-3.3.0-20w45a:fb8108e]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131) ~[PacketRemapper.class:git-ViaVersion-3.3.0-20w45a:fb8108e]
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407) ~[Protocol.class:git-ViaVersion-3.3.0-20w45a:fb8108e]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449) ~[PacketWrapper.class:git-ViaVersion-3.3.0-20w45a:fb8108e]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435) ~[PacketWrapper.class:git-ViaVersion-3.3.0-20w45a:fb8108e]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75) ~[ProtocolPipeline.class:git-ViaVersion-3.3.0-20w45a:fb8108e]
	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404) ~[UserConnection.class:git-ViaVersion-3.3.0-20w45a:fb8108e]
	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379) ~[UserConnection.class:git-ViaVersion-3.3.0-20w45a:fb8108e]
	at com.github.creeper123123321.viafabric.handler.clientside.VRDecodeHandler.decode(VRDecodeHandler.java:54) ~[VRDecodeHandler.class:?]
	at com.github.creeper123123321.viafabric.handler.clientside.VRDecodeHandler.decode(VRDecodeHandler.java:37) ~[VRDecodeHandler.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:4.0.23.Final]
	... 22 more
[10:16:27] [Client thread/INFO]: Applying holder lookups
[10:16:27] [Client thread/INFO]: Holder lookups applied

**Comment by Xernium** [comment]
Follow the issue template and also please actually use the paste service described in the issue template.
