### ISSUE TITLE
java.lang.IndexOutOfBoundsException: readerIndex(2) + length(24)

### ISSUE THREAD

**Issue by 1CAMOU** [ViaVersion/ViaVersion#2262]
[ViaVersion] ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x15->0x04
[16:36:16] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[16:36:16] [Netty Epoll Server IO #1/WARN]: {Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$22 (Anonymous), Packet ID: 4}
[16:36:16] [Netty Epoll Server IO #1/WARN]: Actual Error: 
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:36:16] [Netty Epoll Server IO #1/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[16:36:16] [Netty Epoll Server IO #1/WARN]: {Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$22 (Anonymous), Packet ID: 4}
[16:36:16] [Netty Epoll Server IO #1/WARN]: Actual Error: 
[16:36:16] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(24) exceeds writerIndex(22): PooledUnsafeDirectByteBuf(ridx: 2, widx: 22, cap: 256)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1463)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:972)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:32)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:129)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:454)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:518)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:36:16] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[16:36:16] [Netty Epoll Server IO #1/WARN]: {Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$22 (Anonymous), Packet ID: 4}
[16:36:16] [Netty Epoll Server IO #1/WARN]: Actual Error: 
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:36:16] [Netty Epoll Server IO #1/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[16:36:16] [Netty Epoll Server IO #1/WARN]: {Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$22 (Anonymous), Packet ID: 4}
[16:36:16] [Netty Epoll Server IO #1/WARN]: Actual Error: 
[16:36:16] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(24) exceeds writerIndex(22): PooledUnsafeDirectByteBuf(ridx: 2, widx: 22, cap: 256)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1463)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:972)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:32)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:129)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:454)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:518)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:36:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:36:16] [Server thread/INFO]: KaasPlakAlt lost connection: Internal Exception: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: String, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$22 (Anonymous), Packet ID: 4}
Actual Error:

**Comment by KennyTV** [comment]
Follow the issue template, likely has already been fixed.
