### ISSUE TITLE
Crashing everyone when someone dies in bedwars for some reason the cause is viaversion

### ISSUE THREAD

**Issue by MyPreciousGollum** [ViaVersion/ViaVersion#2266]
This is one of many of the errors I am getting in console
`14:05:30 [SEVERE] [Toady09] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: nl.matsv.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$6 (Anonymous)}
Actual Error:
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at me.limeglass.skungee.bungeecord.protocol.channel.ChannelHandler.write(ChannelHandler.java:26)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299)
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:145)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListLogic.sendPacket(TabListLogic.java:74)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.AbstractTabListLogic.removePlayerFromTeam(AbstractTabListLogic.java:538)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.AbstractTabListLogic.useFakePlayerForSlot(AbstractTabListLogic.java:402)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.AbstractTabListLogic.onPlayerListPacketInternal(AbstractTabListLogic.java:361)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.AbstractTabListLogic.onServerSwitch(AbstractTabListLogic.java:771)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListLogic.onServerSwitch(TabListLogic.java:131)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.LowMemoryTabListLogic.onServerSwitch(LowMemoryTabListLogic.java:49)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListHandler.onServerSwitch(TabListHandler.java:64)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.TabListHandler.onServerSwitch(TabListHandler.java:64)
        at codecrafter47.bungeetablistplus.tablisthandler.logic.RewriteLogic.onServerSwitch(RewriteLogic.java:100)
        at codecrafter47.bungeetablistplus.protocol.ProtocolManager.onServerConnected(ProtocolManager.java:63)
        at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
        at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:399)
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:318)
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:201)
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
`

**I am using BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:281aece:1538 by md_5**

I am getting errors like this constantly in my console.
`7:54:01 [WARNING] [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:block.anvil.hit
17:54:03 [WARNING] [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:block.anvil.place
17:54:07 [WARNING] [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:block.glass.break
17:57:01 [WARNING] [ViaBackwards] Unknown named sound in 1.13->1.12 protocol: minecraft:entity.ender_dragon.death
`

**Comment by KennyTV** [comment]
Follow the issue template.
