### ISSUE TITLE
Starting error reporting on version 1.12.2

### ISSUE THREAD

**Issue by bopoboopoooo** [ViaVersion/ViaVersion#2289]
[20:06:35] [Server thread/WARN]: [ViaVersion] ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x0C->0xFFFFFFFF
[20:06:35] [Server thread/WARN]: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: JsonElement, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}
Actual Error: 
[20:06:35] [Server thread/WARN]: Caused by: java.io.IOException: Unable to read type JsonElement, found String
[20:06:35] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:156)
[20:06:35] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1.handle(PlayerPackets.java:58)
[20:06:35] [Server thread/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[20:06:35] [Server thread/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[20:06:35] [Server thread/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:418)
[20:06:35] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:431)
[20:06:35] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:339)
[20:06:35] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)
[20:06:35] [Server thread/WARN]: 	at de.gerrygames.viarewind.utils.PacketUtil.sendPacket(PacketUtil.java:37)
[20:06:35] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.sendBossBar(Cooldown.java:108)
[20:06:35] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.showCooldown(Cooldown.java:69)
[20:06:35] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.tick(Cooldown.java:59)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3612)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[20:06:35] [Server thread/WARN]: 	at de.gerrygames.viarewind.utils.Ticker.lambda$init$0(Ticker.java:16)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)
[20:06:35] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)
[20:06:35] [Server thread/WARN]: 	at de.gerrygames.viarewind.utils.Ticker.lambda$init$1(Ticker.java:15)
[20:06:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[20:06:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[20:06:35] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[20:06:35] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:06:35] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:06:35] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:06:35] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by KennyTV** [comment]
Update ViaRewind / look at their tracker.
