### ISSUE TITLE
1.16.4 Server, clients on 1.12.2 Can't connect

### ISSUE THREAD

**Issue by Reuortten** [ViaVersion/ViaVersion#2292]
I have 1.16.4 Paper server.  Running the latest version.  
I am trying to connect with 1.12.2 client and keep getting kicked automatically when i join.
https://dump.viaversion.com/5ebdb6f4be750ac33e03c8f9c191a0c71fd1ae5e26827aaee0a34a6406d0e436

I have tried the latest stable version and snapshot version of ViaVersion and ViaBackwards
This is the error message I always get.

15:03:30 WARN]: [ViaVersion] ERROR IN Protocol1_15_2To1_16 IN REMAP OF ADVANCEMENTS (0x57)
[15:03:30 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[15:03:30 WARN]: {Source 0: us.myles.ViaVersion.api.rewriters.ItemRewriter$9 (Anonymous)}
[15:03:30 WARN]: Actual Error:
[15:03:30 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[15:03:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[15:03:30 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:305)
[15:03:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[15:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[15:03:30 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[15:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[15:03:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[15:03:30 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[15:03:30 WARN]: {Source 0: us.myles.ViaVersion.api.rewriters.ItemRewriter$9 (Anonymous)}
[15:03:30 WARN]: Actual Error:
[15:03:30 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "us.myles.viaversion.libs.opennbt.tag.builtin.Tag.getValue()" because the return value of "us.myles.viaversion.libs.opennbt.tag.builtin.CompoundTag.get(String)" is null
[15:03:30 WARN]:        at nl.matsv.viabackwards.api.rewriters.EnchantmentRewriter.rewriteEnchantmentsToClient(EnchantmentRewriter.java:66)
[15:03:30 WARN]:        at nl.matsv.viabackwards.api.rewriters.EnchantmentRewriter.handleToClient(EnchantmentRewriter.java:41)
[15:03:30 WARN]:        at nl.matsv.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16.handleItemToClient(BlockItemPackets1_16.java:320)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.rewriters.ItemRewriter$9.lambda$registerMap$0(ItemRewriter.java:171)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[15:03:30 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[15:03:30 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[15:03:30 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[15:03:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[15:03:30 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:305)
[15:03:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[15:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[15:03:30 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[15:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[15:03:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[15:03:30 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[15:03:30 WARN]: {Source 0: us.myles.ViaVersion.api.rewriters.ItemRewriter$9 (Anonymous)}
[15:03:30 WARN]: Actual Error:
[15:03:30 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[15:03:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[15:03:30 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:305)
[15:03:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[15:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[15:03:30 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[15:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[15:03:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[15:03:30 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[15:03:30 WARN]: {Source 0: us.myles.ViaVersion.api.rewriters.ItemRewriter$9 (Anonymous)}
[15:03:30 WARN]: Actual Error:
[15:03:30 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "us.myles.viaversion.libs.opennbt.tag.builtin.Tag.getValue()" because the return value of "us.myles.viaversion.libs.opennbt.tag.builtin.CompoundTag.get(String)" is null
[15:03:30 WARN]:        at nl.matsv.viabackwards.api.rewriters.EnchantmentRewriter.rewriteEnchantmentsToClient(EnchantmentRewriter.java:66)
[15:03:30 WARN]:        at nl.matsv.viabackwards.api.rewriters.EnchantmentRewriter.handleToClient(EnchantmentRewriter.java:41)
[15:03:30 WARN]:        at nl.matsv.viabackwards.protocol.protocol1_15_2to1_16.packets.BlockItemPackets1_16.handleItemToClient(BlockItemPackets1_16.java:320)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.rewriters.ItemRewriter$9.lambda$registerMap$0(ItemRewriter.java:171)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[15:03:30 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[15:03:30 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[15:03:30 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[15:03:30 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[15:03:30 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[15:03:30 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[15:03:30 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[15:03:30 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:305)
[15:03:30 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[15:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[15:03:30 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[15:03:30 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[15:03:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by KennyTV** [comment]
Follow the issue template.
