### ISSUE TITLE
Error in console, asked to post here

### ISSUE THREAD

**Issue by hokudan** [ViaVersion/ViaVersion#2310]
**Describe the bug, provide any errors**
Not sure what happened, I woke up and checked my console and found the following error. The timestamp is roughly 30 minutes after an automated backup of the minecraft directory would occur via a cron job.

02:36:49] [Netty Server IO #2/WARN]: Actual Error: 
[02:36:49] [Netty Server IO #2/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(43) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 256)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1463)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:972)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:32)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:193)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.base.BaseProtocol$1.lambda$registerMap$0(BaseProtocol.java:32)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:94)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:454)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:36:49] [Netty Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:36:49] [Netty Server IO #2/WARN]: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 96
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:120)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:36:49] [Netty Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[02:36:49] [Netty Server IO #2/WARN]: Caused by: java.io.IOException: Bad packet id 96
[02:36:49] [Netty Server IO #2/WARN]: 	at net.minecraft.server.v1_16_R3.PacketDecoder.decode(SourceFile:37)
[02:36:49] [Netty Server IO #2/WARN]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[02:36:49] [Netty Server IO #2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:36:49] [Netty Server IO #2/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.util.PipelineUtil.callDecode(PipelineUtil.java:53)
[02:36:49] [Netty Server IO #2/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:42)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[02:36:49] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[02:36:49] [Netty Server IO #2/WARN]: 	... 33 more

**Comment by KennyTV** [comment]
Someone is sending bad packets.

**Comment by hokudan** [comment]
@KennyTV is it possible to see who or what client is sending bad packets? The timing of the errors is when no one would have been on.

**Comment by Seanoo1** [comment]
@hokudan reopen the issue with following the checklist.

**Comment by KennyTV** [comment]
No don't do that. Well, if noone is on, there wouldn't be any packet sent. 😛 Else it can only be before login/ping, so nothing you can really do about that.
