### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DenisJ9798** [ViaVersion/ViaVersion#2318]
[16:04:01] [Netty Epoll Server IO #0/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[16:04:01] [Netty Epoll Server IO #0/WARN]: {Type: MetaData List, Index: 1, Data: [Pair{Type|VarInt, 658716}, Pair{Type|MetaData List, [Metadata{id=0, metaType=Byte, value=64}, Metadata{id=2, metaType=OptChat, value=null}, Metadata{id=7, metaType=Byte, value=0}, Metadata{id=4, metaType=Boolean, value=false}, Metadata{id=17, metaType=Byte, value=1}, Metadata{id=15, metaType=VarInt, value=51862}, Metadata{id=16, metaType=Byte, value=127}, Metadata{id=9, metaType=VarInt, value=0}, Metadata{id=10, metaType=Boolean, value=false}, Metadata{id=14, metaType=Float, value=0}, Metadata{id=11, metaType=VarInt, value=0}, Metadata{id=1, metaType=VarInt, value=300}, Metadata{id=3, metaType=Boolean, value=false}, Metadata{id=8, metaType=Float, value=40.0}, Metadata{id=5, metaType=Boolean, value=false}, Metadata{id=18, metaType=NBTTag, value=CompoundTag { {} }}]}], Packet ID: 68}
[16:04:01] [Netty Epoll Server IO #0/WARN]: Actual Error: 
[16:04:01] [Netty Epoll Server IO #0/WARN]: Caused by: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Float
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.api.type.types.FloatType.write(FloatType.java:7)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.ModernMetaType.write(ModernMetaType.java:26)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.ModernMetaType.write(ModernMetaType.java:7)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.AbstractMetaListType.write(AbstractMetaListType.java:32)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.api.type.types.minecraft.AbstractMetaListType.write(AbstractMetaListType.java:10)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.writeToBuffer(PacketWrapper.java:242)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:411)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$1.write(BukkitPipelineInjector.java:53)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at com.ruinscraft.panilla.api.io.dplx.PacketInspectorDplx.write(PacketInspectorDplx.java:47)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at me.MrGraycat.eGlow.Util.Packets.PacketInjector$1.write(PacketInjector.java:64)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:04:01] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:04:01] [Server thread/INFO]: Neron_Denisok lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues

**Comment by KennyTV** [comment]
Follow the issue template.
