### ISSUE TITLE
One Player erroring my serv when moving. But he can stand still and type

### ISSUE THREAD

**Issue by Gertjan300** [ViaVersion/ViaVersion#2327]
`Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Chunk, Data: [], Source 0: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$7$1 (Anonymous), Packet ID: 33, Source 1: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$7 (Anonymous)}
Actual Error: 
Caused by: java.lang.RuntimeException: VarInt too big
    at us.myles.ViaVersion.api.type.types.VarIntType.readPrimitive(VarIntType.java:23)
    at us.myles.ViaVersion.api.type.types.version.ChunkSectionType1_13.read(ChunkSectionType1_13.java:38)
    at us.myles.ViaVersion.api.type.types.version.ChunkSectionType1_13.read(ChunkSectionType1_13.java:8)
    at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.types.Chunk1_13Type.read(Chunk1_13Type.java:41)
    at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.types.Chunk1_13Type.read(Chunk1_13Type.java:21)
    at us.myles.ViaVersion.api.type.PartialType.read(PartialType.java:19)
    at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
    at us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$7$1.handle(WorldPackets.java:131)
    at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
    at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
    at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
    at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
    at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
    at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
    at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
    at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
    at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:34)
    at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:14)
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57)
    at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:172)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:128)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:113)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Thread.java:748)
19:00:21 [INFO] [moonlight619] disconnected with: EncoderException : us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Chunk, Data: [], Source 0: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$7$1 (Anonymous), Packet ID: 33, Source 1: us.myles.ViaVersion.protocols.protocol1_14to1_13_2.packets.WorldPackets$7 (Anonymous)}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104`

This guy is able to join my lobby. But when he is joining a other server he is getting this error when moving
But he can talk/stand still

**Comment by KennyTV** [comment]
Follow the issue template.
