### ISSUE TITLE
Bug I cant join my server

### ISSUE THREAD

**Issue by WalidKiller** [ViaVersion/ViaVersion#2332]
[14:42:21 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[14:42:21 WARN]: {Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@4f4fbf18}], Packet ID: 33}
[14:42:21 WARN]: Actual Error: 
[14:42:21 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[14:42:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[14:42:21 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[14:42:21 WARN]:        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$1.write(BukkitPipelineInjector.java:53)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[14:42:21 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[14:42:21 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[14:42:21 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[14:42:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[14:42:21 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[14:42:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[14:42:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[14:42:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[14:42:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
[14:42:21 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[14:42:21 WARN]: {Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, us.myles.ViaVersion.api.minecraft.chunks.Chunk1_8@4f4fbf18}], Packet ID: 33}
[14:42:21 WARN]: Actual Error: 
[14:42:21 WARN]: Caused by: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
[14:42:21 WARN]:        at us.myles.viaversion.libs.fastutil.ints.IntArrayList.getInt(IntArrayList.java:267)
[14:42:21 WARN]:        at us.myles.ViaVersion.api.minecraft.chunks.ChunkSection.getFlatBlock(ChunkSection.java:73)
[14:42:21 WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.ChunkSectionType1_8.write(ChunkSectionType1_8.java:38)
[14:42:21 WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.ChunkSectionType1_8.write(ChunkSectionType1_8.java:11)
[14:42:21 WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.write(Chunk1_8Type.java:92)
[14:42:21 WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.types.Chunk1_8Type.write(Chunk1_8Type.java:16)
[14:42:21 WARN]:        at us.myles.ViaVersion.api.type.PartialType.write(PartialType.java:24)
[14:42:21 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.writeToBuffer(PacketWrapper.java:242)
[14:42:21 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:411)
[14:42:21 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[14:42:21 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[14:42:21 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[14:42:21 WARN]:        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[14:42:21 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:42:21 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[14:42:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[14:42:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[14:42:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[14:42:21 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[14:42:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[14:42:21 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[14:42:21 WARN]:        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$1.write(BukkitPipelineInjector.java:53)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[14:42:21 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[14:42:21 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[14:42:21 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[14:42:21 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[14:42:21 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[14:42:21 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[14:42:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[14:42:21 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[14:42:21 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[14:42:21 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by KennyTV** [comment]
Follow the issue template, likely outdated plugins.
