### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by bopoboopoooo** [ViaVersion/ViaVersion#2338]
[All the text comes from Baidu/Google translation]
***Plug in owned***
[V][KBBDown1.7]ViaRewind-1.5.3.jar
[V][KBBDown1.8]ViaBackwards-3.2.0.jar
[V][KuaBanBenUP1.16.4]ViaVersion-3.2.1.jar

***Error reporting environment information***
1.Check all cross version plug-ins for updates, and www.spigotmc.org All of them are up to date
2.Ask all players what version of the game they are using(1.8/1.8.1/1.9)
[latest.log](https://github.com/ViaVersion/ViaVersion/files/5963080/latest.log)
[latest.log](https://github.com/ViaVersion/ViaVersion/files/5963082/latest.log)

***Error output text***
[11:52:45] [Server thread/WARN]: [ViaVersion] ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x0C->0xFFFFFFFF
[11:52:45] [Server thread/WARN]: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: JsonElement, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}
Actual Error: 

[11:52:45] [Server thread/WARN]: Caused by: java.io.IOException: Unable to read type JsonElement, found String

[11:52:45] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:156)

[11:52:45] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1.handle(PlayerPackets.java:58)

[11:52:45] [Server thread/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)

[11:52:45] [Server thread/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)

[11:52:45] [Server thread/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)

[11:52:45] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)

[11:52:45] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:344)

[11:52:45] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)

[11:52:45] [Server thread/WARN]: 	at de.gerrygames.viarewind.utils.PacketUtil.sendPacket(PacketUtil.java:37)

[11:52:45] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.sendBossBar(Cooldown.java:108)

[11:52:45] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.showCooldown(Cooldown.java:69)

[11:52:45] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.tick(Cooldown.java:59)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3612)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)

[11:52:45] [Server thread/WARN]: 	at de.gerrygames.viarewind.utils.Ticker.lambda$init$0(Ticker.java:16)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)

[11:52:45] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)

[11:52:45] [Server thread/WARN]: 	at de.gerrygames.viarewind.utils.Ticker.lambda$init$1(Ticker.java:15)

[11:52:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)

[11:52:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)

[11:52:45] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)

[11:52:45] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)

[11:52:45] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)

[11:52:45] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)

[11:52:45] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by bopoboopoooo** [comment]
服务器版本Spigot1.12.2
RAM: 3.8GB
Server version spigot1.12.2
RAM: 3.8GB

**Comment by Seanoo1** [comment]
Follow the checklist.

**Comment by bopoboopoooo** [comment]
我不是很清楚您的意思，可否请您详细解释或者指导我该如何操作？
I'm not very clear about what you mean. Could you please explain in detail or guide me how to operate？

**Comment by Seanoo1** [comment]
Close this issue and recreate the issue with follow the checklist.
