### ISSUE TITLE
A strange error message一个奇怪的错误信息

### ISSUE THREAD

**Issue by bopoboopoooo** [ViaVersion/ViaVersion#2339]
[All English are from Baidu translation]

**Error description**
玩家使用1.8.X 1.9.X的版本加入服务器后，服务器后台疯狂报错
After players join the server with the version of 1.8. X 1.9.X, the server's backstage reports crazy errors

**How can we reproduce it?**
1. Log in to [Spigot1.12.2 server] with 1.8.X
2. Perform any action within the game server
3. The server console displays an error message

**Expected behaviour**
Hope to get a solution.

**Screenshots**
![image](https://user-images.githubusercontent.com/77537531/107608418-e347b400-6c76-11eb-8b9c-343322d91771.png)

**ViaVersion Dump**
https://dump.viaversion.com/f3b8a33b7c414fdaf3e69dc25c1e7007aaeecb5b0185f42904de008a2ed73632

**Additional server info**
[Spigot-1.12.2 Server]
Plugins Use:
[V][KBBDown1.7]ViaRewind-1.5.3.jar
[V][KBBDown1.8]ViaBackwards-3.2.0.jar
[V][KuaBanBenUP1.16.4]ViaVersion-3.2.1.jar

**Checklist**
[11:44:25] [Server thread/WARN]: [ViaVersion] ERROR IN Protocol1_8TO1_9 IN REMAP OF 0x0C->0xFFFFFFFF
[11:44:25] [Server thread/WARN]: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: JsonElement, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1 (Anonymous), Packet ID: -1, Source 1: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous)}
Actual Error: 

[11:44:25] [Server thread/WARN]: Caused by: java.io.IOException: Unable to read type JsonElement, found String

[11:44:25] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:156)

[11:44:25] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1$1.handle(PlayerPackets.java:58)

[11:44:25] [Server thread/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)

[11:44:25] [Server thread/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)

[11:44:25] [Server thread/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)

[11:44:25] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)

[11:44:25] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:344)

[11:44:25] [Server thread/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)

[11:44:25] [Server thread/WARN]: 	at de.gerrygames.viarewind.utils.PacketUtil.sendPacket(PacketUtil.java:37)

[11:44:25] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.sendBossBar(Cooldown.java:108)

[11:44:25] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.showCooldown(Cooldown.java:69)

[11:44:25] [Server thread/WARN]: 	at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.tick(Cooldown.java:59)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3612)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)

[11:44:25] [Server thread/WARN]: 	at de.gerrygames.viarewind.utils.Ticker.lambda$init$0(Ticker.java:16)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)

[11:44:25] [Server thread/WARN]: 	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)

[11:44:25] [Server thread/WARN]: 	at de.gerrygames.viarewind.utils.Ticker.lambda$init$1(Ticker.java:15)

[11:44:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)

[11:44:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)

[11:44:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)

[11:44:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)

[11:44:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)

[11:44:25] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)

[11:44:25] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by FormallyMyles** [comment]
Delete 3 Via jars.

Download:
ViaVersion - https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-3.2.2-SNAPSHOT.jar
ViaBackwards - https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/all/target/ViaBackwards-3.2.1-SNAPSHOT.jar
ViaRewind - https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-1.5.3.jar

Otherwise, copy this issue and open at https://github.com/ViaVersion/ViaRewind/issues/new/choose and also describe how to replicate it (maybe try a server with no other plugins).
