### ISSUE TITLE
viaversion 3.2.1 can not surppot 1.16.3

### ISSUE THREAD

**Issue by cateast222** [ViaVersion/ViaVersion#2341]
20:16:28 [信息] [ViaVersion] Loading 1.12 -> 1.13 mappings...
20:16:28 [信息] [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
20:16:28 [信息] [ViaVersion] Loading block connection mappings ...
20:16:28 [信息] [ViaVersion] Loading 1.14 -> 1.15 mappings...
20:16:28 [信息] [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
20:16:28 [信息] [ViaVersion] Loading 1.15 -> 1.16 mappings...
20:16:28 [信息] [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
20:16:28 [信息] [ViaBackwards] Loading translations...
20:16:29 [信息] [ViaBackwards] Registering protocols...
20:16:29 [警告] Exception encountered when loading plugin: ViaVersion
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.protocol.Protocol.<init>(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;Z)V
    at nl.matsv.viabackwards.api.BackwardsProtocol.<init>(BackwardsProtocol.java:21)
    at nl.matsv.viabackwards.protocol.protocol1_9_4to1_10.Protocol1_9_4To1_10.<init>(Protocol1_9_4To1_10.java:31)
    at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:68)
    at nl.matsv.viabackwards.BungeePlugin.lambda$onLoad$0(BungeePlugin.java:21)
    at us.myles.ViaVersion.ViaManager.init(ViaManager.java:75)
    at us.myles.ViaVersion.BungeePlugin.onEnable(BungeePlugin.java:76)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

use viaversion3.2.1

**Comment by FormallyMyles** [comment]
See issue template.
