### ISSUE TITLE
us.myles.ViaVersion.exception.InformativeException

### ISSUE THREAD

**Issue by carlni2008** [ViaVersion/ViaVersion#2346]
[18:17:29] [Netty Server IO #2/WARN]: [ViaVersion] ERROR IN Protocol1_13To1_13_1 IN REMAP OF TAGS (0x55)
[18:17:29] [Netty Server IO #2/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[18:17:29] [Netty Server IO #2/WARN]: {Source 0: us.myles.ViaVersion.api.rewriters.TagRewriter$1 (Anonymous)}
[18:17:29] [Netty Server IO #2/WARN]: Actual Error:
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[18:17:29] [Netty Server IO #2/WARN]:   at net.minecraft.server.v1_16_R3.NetworkManager.lambda$4(NetworkManager.java:189)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[18:17:29] [Netty Server IO #2/WARN]:   at java.lang.Thread.run(Unknown Source)
[18:17:29] [Netty Server IO #2/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[18:17:29] [Netty Server IO #2/WARN]: {Source 0: us.myles.ViaVersion.api.rewriters.TagRewriter$1 (Anonymous)}
[18:17:29] [Netty Server IO #2/WARN]: Actual Error:
[18:17:29] [Netty Server IO #2/WARN]: Caused by: java.lang.NullPointerException
[18:17:29] [Netty Server IO #2/WARN]:   at nl.matsv.viabackwards.api.data.BackwardsMappings.getNewItemId(BackwardsMappings.java:94)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.rewriters.TagRewriter$1.lambda$null$1(TagRewriter.java:61)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.rewriters.TagRewriter.handle(TagRewriter.java:88)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.rewriters.TagRewriter.access$300(TagRewriter.java:16)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.rewriters.TagRewriter$1.lambda$registerMap$2(TagRewriter.java:61)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[18:17:29] [Netty Server IO #2/WARN]:   at net.minecraft.server.v1_16_R3.NetworkManager.lambda$4(NetworkManager.java:189)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[18:17:29] [Netty Server IO #2/WARN]:   at java.lang.Thread.run(Unknown Source)
[18:17:29] [Netty Server IO #2/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[18:17:29] [Netty Server IO #2/WARN]: {Source 0: us.myles.ViaVersion.api.rewriters.TagRewriter$1 (Anonymous)}
[18:17:29] [Netty Server IO #2/WARN]: Actual Error:
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[18:17:29] [Netty Server IO #2/WARN]:   at net.minecraft.server.v1_16_R3.NetworkManager.lambda$4(NetworkManager.java:189)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[18:17:29] [Netty Server IO #2/WARN]:   at java.lang.Thread.run(Unknown Source)
[18:17:29] [Netty Server IO #2/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[18:17:29] [Netty Server IO #2/WARN]: {Source 0: us.myles.ViaVersion.api.rewriters.TagRewriter$1 (Anonymous)}
[18:17:29] [Netty Server IO #2/WARN]: Actual Error:
[18:17:29] [Netty Server IO #2/WARN]: Caused by: java.lang.NullPointerException
[18:17:29] [Netty Server IO #2/WARN]:   at nl.matsv.viabackwards.api.data.BackwardsMappings.getNewItemId(BackwardsMappings.java:94)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.rewriters.TagRewriter$1.lambda$null$1(TagRewriter.java:61)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.rewriters.TagRewriter.handle(TagRewriter.java:88)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.rewriters.TagRewriter.access$300(TagRewriter.java:16)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.rewriters.TagRewriter$1.lambda$registerMap$2(TagRewriter.java:61)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[18:17:29] [Netty Server IO #2/WARN]:   at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[18:17:29] [Netty Server IO #2/WARN]:   at net.minecraft.server.v1_16_R3.NetworkManager.lambda$4(NetworkManager.java:189)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[18:17:29] [Netty Server IO #2/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[18:17:29] [Netty Server IO #2/WARN]:   at java.lang.Thread.run(Unknown Source)
[18:17:29] [Server thread/INFO]: Scratchycarl[/127.0.0.1:57461] logged in with entity id 631 at ([lobby]-2470.0921199069357, 32.0, 720.2214446925375)
[18:17:29] [Server thread/INFO]: Scratchycarl lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.api.rewriters.TagRewriter$1 (Anonymous)}
Actual Error:

someone help me pls.
[latest.log](https://github.com/ViaVersion/ViaVersion/files/5976893/latest.log)

**Comment by KennyTV** [comment]
Follow the issue template.d
