### ISSUE TITLE
console spam error is reported at startup

### ISSUE THREAD

**Issue by MeowRay** [ViaVersion/ViaVersion#2368]
spigot : 1.8.8 
viaversion: 3.2.2-latest

```
[13:28:35] [Netty Epoll Server IO #1/ERROR]: java.lang.NullPointerException
[13:28:35] [Netty Epoll Server IO #0/ERROR]: java.lang.NullPointerException
[13:28:35] [Netty Epoll Server IO #3/ERROR]: java.lang.NullPointerException
[13:28:35] [Netty Epoll Server IO #7/ERROR]: java.lang.NullPointerException
[13:28:35] [Netty Epoll Server IO #4/ERROR]: java.lang.NullPointerException
[13:28:35] [Netty Epoll Server IO #2/ERROR]: java.lang.NullPointerException
[13:28:35] [Netty Epoll Server IO #3/WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[13:28:35] [Netty Epoll Server IO #2/WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[13:28:35] [Netty Epoll Server IO #7/WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[13:28:35] [Netty Epoll Server IO #1/WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[13:28:35] [Netty Epoll Server IO #0/WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[13:28:35] [Netty Epoll Server IO #4/WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[13:28:35] [Netty Epoll Server IO #4/WARN]: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:184)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.PacketStatusListener.a(PacketStatusListener.java:126)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.PacketStatusInStart.a(SourceFile:23)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.PacketStatusInStart.a(SourceFile:8)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:124)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:325)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:1)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(SourceFile:94)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:28:35] [Netty Epoll Server IO #4/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:458)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:66)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:232)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	... 47 more
[13:28:35] [Netty Epoll Server IO #4/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$1 (Anonymous), Packet ID: 0}
Actual Error: 
[13:28:35] [Netty Epoll Server IO #4/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.type.types.VarIntType.readPrimitive(VarIntType.java:18)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:26)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:129)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:68)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:61)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:458)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:66)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:232)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:184)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.PacketStatusListener.a(PacketStatusListener.java:126)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.PacketStatusInStart.a(SourceFile:23)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.PacketStatusInStart.a(SourceFile:8)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:124)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:325)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:1)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(SourceFile:94)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:28:35] [Netty Epoll Server IO #4/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:28:35] [Netty Epoll Server IO #0/WARN]: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:184)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.PacketStatusListener.a(PacketStatusListener.java:126)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.PacketStatusInStart.a(SourceFile:23)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.PacketStatusInStart.a(SourceFile:8)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:124)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:325)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.channelRead0(NetworkManager.java:1)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(SourceFile:94)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:28:35] [Netty Epoll Server IO #0/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:458)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:66)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:232)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:28:35] [Netty Epoll Server IO #0/WARN]: 	... 47 more
[13:28:35] [Netty Epoll Server IO #0/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: String, Data: [], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol1_7$1 (Anonymous), Packet ID: 0}
Actual Error: 
```

**Comment by Xernium** [comment]
Hello there! Your issue is invalid because you didn’t follow the issue template and will be closed because of this. If you still experience your problem you may open a new issue. If you do, please follow both follow the issue template and use a paste site for logs (like https://paste.gg) or it will be flagged as invalid again.
Thank you, the ViaVersion Team.
