### ISSUE TITLE
ViaVersion Bug report 

### ISSUE THREAD

**Issue by FLASH341** [ViaVersion/ViaVersion#2392]
Comment puis-je corriger cette erreur ? Merci grandement pour votre aide !

Caused by: us.myles.ViaVersion.exception.InformativeException
io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[09:36:22] [Netty Epoll Server IO #3/WARN]: {Type: String, Data: [Pair{Type|VarInt, 0}], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol$1$$Lambda$3452/1458837311, Packet ID: 0, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)}
[09:36:22] [Netty Epoll Server IO #3/WARN]: Actual Error: 
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:88)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:36:22] [Netty Epoll Server IO #3/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
[09:36:22] [Netty Epoll Server IO #3/WARN]: {Type: String, Data: [Pair{Type|VarInt, 0}], Source 0: us.myles.ViaVersion.protocols.base.BaseProtocol$1$$Lambda$3452/1458837311, Packet ID: 0, Source 1: us.myles.ViaVersion.protocols.base.BaseProtocol$1 (Anonymous)}
[09:36:22] [Netty Epoll Server IO #3/WARN]: Actual Error: 
[09:36:22] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(47) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 256)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1392)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:946)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:32)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.type.types.StringType.read(StringType.java:9)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.passthrough(PacketWrapper.java:193)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.protocols.base.BaseProtocol$1.lambda$registerMap$0(BaseProtocol.java:32)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.protocols.base.BaseProtocol.transform(BaseProtocol.java:94)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:454)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:38)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:88)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:36:22] [Netty Epoll Server IO #3/WARN]: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index: 96, Size: 48
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:88)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:36:22] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.IndexOutOfBoundsException: Index: 96, Size: 48
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at java.util.ArrayList.get(ArrayList.java:433)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_16_R3.EnumProtocol$a.a(SourceFile:387)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_16_R3.EnumProtocol.a(SourceFile:429)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.server.v1_16_R3.PacketDecoder.decode(SourceFile:34)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.util.PipelineUtil.callDecode(PipelineUtil.java:53)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:42)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[09:36:22] [Netty Epoll Server IO #3/WARN]: 	... 26 more

**Comment by KennyTV** [comment]
Ne supprimez pas le texte lors de la création du rapport (et en anglais, s'il te plait).

**Comment by FLASH341** [comment]
Pas de soucis 🙃.

Cela change quoi de ne pas supprimer le texte ?

—
Bien à vous,

Jules Charlet-Somlette
2nd Lycée La Merci Montpellier
Baillargues
34670
