### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Cryptics1999** [ViaVersion/ViaVersion#2410]
### '/viaversion dump' Output

https://dump.viaversion.com/58933e461c3cf9dd73baa78169f6c50ee13761a40bf41bf881040003d480fe90

### Console Error

[20:41:24 WARN]:        at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.EntityPackets$7$2.handle(EntityPackets.java:211)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[20:41:24 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[20:41:24 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[20:41:24 WARN]:        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
[20:41:24 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:41:24 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:529)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:71)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:269)
[20:41:24 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:275)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:41:24 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:41:24 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[20:41:24 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:41:24 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352)
[20:41:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[20:41:24 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[20:41:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[20:41:24 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:41:24 WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:41:24 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:275)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:41:24 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:41:24 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[20:41:24 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:41:24 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352)
[20:41:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[20:41:24 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[20:41:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[20:41:24 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:41:24 WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:41:24 WARN]: Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 1
[20:41:24 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
[20:41:24 WARN]:        at us.myles.ViaVersion.boss.CommonBoss.setHealth(CommonBoss.java:51)
[20:41:24 WARN]:        at us.myles.ViaVersion.protocols.protocol1_9to1_8.storage.EntityTracker1_9.handleMetadata(EntityTracker1_9.java:228)
[20:41:24 WARN]:        at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.EntityPackets$7$2.handle(EntityPackets.java:211)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[20:41:24 WARN]:        at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[20:41:24 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[20:41:24 WARN]:        at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[20:41:24 WARN]:        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
[20:41:24 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:41:24 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:529)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:71)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:269)
[20:41:24 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:275)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:41:24 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:41:24 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[20:41:24 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[20:41:24 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:41:24 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[20:41:24 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352)
[20:41:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[20:41:24 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[20:41:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[20:41:24 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:41:24 INFO]: MadMallu left the game.
[20:41:24 INFO]: _Cryptics lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:41:24 INFO]: _Cryptics left the game.
[20:41:24 INFO]: zibbyboo lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:41:24 INFO]: zibbyboo left the game.
[20:41:24 INFO]: Paul lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:41:24 INFO]: Paul left the game.
[20:41:24 INFO]: Fuse53 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:41:24 INFO]: Fuse53 left the game.
[20:41:27 INFO]: UUID of player MadMallu is e33d09f7-1389-3104-a670-4c0c42b3cb99
[20:41:27 WARN]: [ViaVersion] Ignoring plugin channel in outgoing REGISTER: WECUI
[20:41:27 INFO]: MadMallu[/103.160.194.63:46952] logged in with entity id 306085 at ([world]292.0505674190201, 34.0, 159.90972155479915)

### Bug Description

I was going into a arena called MiniWalls, and then it kicked me out of the server

### Steps to Reproduce

Example:
Login with 1.16 account
Start MiniWalls game
Get sent out of server

### Expected Behavior

Kicks you out of server

### Additional Server Info

I use SSBungeecord and Paper on the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Please update to a build from https://ci.viaversion.com/job/ViaVersion-DEV/. If the error still occurs, comment the new (!) error here and we will reopen this.
