### ISSUE TITLE
Dev Build bug?

### ISSUE THREAD

**Issue by Cryptics1999** [ViaVersion/ViaVersion#2420]
### '/viaversion dump' Output

https://dump.viaversion.com/78fa48ece5e5f652e94b40cf90ab294a416f8110daba8859c5e6fa3671903dc5

### Console Error

[15:40:14 ERROR]: Could not pass event PlayerJoinEvent to LuckPerms v5.3.3
java.lang.IncompatibleClassChangeError: Found interface us.myles.ViaVersion.ViaManager, but class was expected
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:346) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:343) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.findConnection(ViaFacet.java:92) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.findProtocol(ViaFacet.java:96) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:88) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.Facet.of(Facet.java:97) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:85) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:78) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:76) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_282]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:75) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:318) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:176) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:232) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1101) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:891) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:785) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:684) [server.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[15:40:14 INFO]: cooldude12829[/219.91.213.65:57643] logged in with entity id 53 at ([world]-5.5, 86.0, -1.5)
[15:40:18 INFO]: UUID of player Kaecilus is 05d3839f-4419-497e-869b-d818a015412b
[15:40:18 ERROR]: Could not pass event PlayerJoinEvent to LuckPerms v5.3.3
java.lang.IncompatibleClassChangeError: Found interface us.myles.ViaVersion.ViaManager, but class was expected
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:346) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:343) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.findConnection(ViaFacet.java:92) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.findProtocol(ViaFacet.java:96) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:88) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.Facet.of(Facet.java:97) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:85) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:78) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:76) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_282]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:75) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [server.jar:git-TacoSpigot-04511af6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:318) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:176) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:232) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1101) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:891) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:785) [server.jar:git-TacoSpigot-04511af6]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:684) [server.jar:git-TacoSpigot-04511af6]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

### Bug Description

I used the dev build and this error come, I use dev build cause it fixed a other issue

### Steps to Reproduce

Use dev build and latest Luckperms plugin

### Expected Behavior

Error will come

### Additional Server Info

I use a Bungeecord server with multiple spigot server. And I use StellarSpigot as jar for my 1.8.8 

### Checklist

Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
I have included a ViaVersion dump.
If applicable, I have included a paste (**not a screenshot**) of the error.
I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
ViaVersion has had a breaking api change in the dev builds, adventure will have to update its hook. For the time being, you can keep using the last ViaVersion release.
