### ISSUE TITLE
Building bug (1.9+ players on 1.8 servers)

### ISSUE THREAD

**Issue by andreasdc** [ViaVersion/ViaVersion#2454]
### '/viaversion dump' Output

-

### Console Error

-

### Bug Description

Sorry for not filling the template, but there are no errors. If you really want more informations, just tell me, I will add them. This bug is crucial.

### Steps to Reproduce

1. Login on 1.9+ client, for example 1.16.5.
2. Your building patch is bugged, but even if you disable it and change paper patch to block placing inside yourself, you get more troubles.
3. Very often placing is cancelled, it's the most frustrating when you are bridging while fast clicking.
4. This happens probably, because you spam place packets to location where you are standing, which causes some werid interactions cancellations.

### Expected Behavior

On Hypixel, for example, you don't have this problem, you can place very clearly.

### Additional Server Info

BungeeCord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
The dev builds have more mitigation towards that, otherwise see https://github.com/ViaVersion/ViaVersion/issues/1087

**Comment by andreasdc** [comment]
@KennyTV #1087 is different issue. Please read carefully. Let me check dev builds.

**Comment by KennyTV** [comment]
I am aware, block place issues with high click rates were fixed in https://github.com/ViaVersion/ViaVersion/pull/2437

**Comment by andreasdc** [comment]
@KennyTV wow that works really good! Finally I can bridge <3 
But I have this problem:
[20:12:26] [Server thread/WARN]: [ViaRewind-Legacy-Support] Task #26 for ViaRewind-Legacy-Support v1.3.3 generated an exception
java.lang.NoClassDefFoundError: us/myles/ViaVersion/api/protocol/ProtocolRegistry
	at de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:30) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:64) ~[spigot.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:410) [spigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:835) [spigot.jar:?]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:410) [spigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:764) [spigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:653) [spigot.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: us.myles.ViaVersion.api.protocol.ProtocolRegistry
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[spigot.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 8 more

**Comment by KennyTV** [comment]
Ah we forgot to update something there - we will do that at the latest tomorrow (and will then be available under https://ci.viaversion.com/view/ViaRewind/job/ViaRewind%20Legacy%20Support/). I will respond here again if it is updated.

**Comment by andreasdc** [comment]
@KennyTV sure thing, I'm waiting! Glad that I can help a little. Good job with building update, keep up the good work! :)

**Comment by KennyTV** [comment]
Thank you! It's updated now https://ci.viaversion.com/view/ViaRewind/job/ViaRewind%20Legacy%20Support/11/

**Comment by andreasdc** [comment]
> Thank you! It's updated now https://ci.viaversion.com/view/ViaRewind/job/ViaRewind%20Legacy%20Support/11/

Great, I will check that in couple minutes. :)

**Comment by andreasdc** [comment]
@KennyTV 
java.lang.IncompatibleClassChangeError: Found interface us.myles.ViaVersion.ViaManager, but class was expected
	at de.gerrygames.viarewind.api.ViaRewindPlatform.init(ViaRewindPlatform.java:19) ~[?:?]
	at de.gerrygames.viarewind.BukkitPlugin.onEnable(BukkitPlugin.java:14) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:320) [spigot.jar:?]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:209) [spigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:596) [spigot.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by andreasdc** [comment]
@KennyTV 
Caused by: java.lang.NoSuchFieldError: DOUBLE
Line is on sendArmorUpdate: wrapper.write(Type.DOUBLE, 0D); //default 0 armor

**Comment by KennyTV** [comment]
Update ViaRewind when the re-build is complete https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/

**Comment by andreasdc** [comment]
@KennyTV Caused by: java.lang.NoSuchFieldError: DOUBLE is still there

**Comment by KennyTV** [comment]
Then you probably downloaded the file before it rebuilt

**Comment by andreasdc** [comment]
@KennyTV still.
Caused by: java.lang.NoSuchFieldError: DOUBLE
Error is with this method. I have my own sendArmorUpdate method and it looks like that:
`    public static void sendArmorUpdate(Player player) {
        // Ensure that the player is on our pipe
        if (!ViaVersionPlugin.getInstance().getApi().isInjected(player.getUniqueId())) return;
        
        if (getVersion(player) <= 47) return;

        int armor = 0;
        for (ItemStack stack : player.getInventory().getArmorContents()) {
            armor += ArmorType.findById(stack.getTypeId()).getArmorPoints();
        }

        PacketWrapper wrapper = new PacketWrapper(0x4B, null, ViaVersionPlugin.getInstance().getConnectionManager().getConnectedClient(player.getUniqueId()));
        try {
            wrapper.write(Type.VAR_INT, player.getEntityId()); // Player ID
            wrapper.write(Type.INT, 1); // only 1 property
            wrapper.write(Type.STRING, "generic.armor");
            wrapper.write(Type.DOUBLE, 0D); //default 0 armor
            wrapper.write(Type.VAR_INT, 1); // 1 modifier
            wrapper.write(Type.UUID, ARMOR_ATTRIBUTE); // armor modifier uuid
            wrapper.write(Type.DOUBLE, (double) armor); // the modifier value
            wrapper.write(Type.BYTE, (byte) 0);// the modifier operation, 0 is add number

            wrapper.send(Protocol1_9To1_8.class);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }`

**Comment by KennyTV** [comment]
Right, then you have to update your plugin/code to be compatible with 3.3.0

**Comment by andreasdc** [comment]
> Right, then you have to update your plugin/code to be compatible with 3.3.0

I updated it to use 4.0.0, there were no errors.

**Comment by KennyTV** [comment]
Field/method signature changed, you still have to recompile it against that new version.

**Comment by andreasdc** [comment]
@KennyTV that's right, it works now. ❤️

**Comment by andreasdc** [comment]
@KennyTV I'm so amazed about fixed building bug, after 3 years you can build normally. Good job, really. :)
