### ISSUE TITLE
Java 16 incompatible

### ISSUE THREAD

**Issue by x9nico** [ViaVersion/ViaVersion#2473]
### '/viaversion dump' Output

How can I execute the command if it does crash my server ?

### Console Error

[14:55:34] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v3.2.1
[14:55:34] [Server thread/WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4377a4e5
[14:55:34] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[14:55:34] [Server thread/WARN]: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[14:55:34] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[14:55:34] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[14:55:34] [Server thread/WARN]: 	at us.myles.viaversion.libs.javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:159)
[14:55:34] [Server thread/WARN]: 	at us.myles.viaversion.libs.javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:213)
[14:55:34] [Server thread/WARN]: 	at us.myles.viaversion.libs.javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:52)
[14:55:34] [Server thread/WARN]: 	at us.myles.viaversion.libs.javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
[14:55:34] [Server thread/WARN]: 	at us.myles.viaversion.libs.javassist.ClassPool.toClass(ClassPool.java:1240)
[14:55:34] [Server thread/WARN]: 	at us.myles.viaversion.libs.javassist.CtClass.toClass(CtClass.java:1408)
[14:55:34] [Server thread/WARN]: 	at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator.makePSConnectListener(ClassGenerator.java:226)
[14:55:34] [Server thread/WARN]: 	at us.myles.ViaVersion.bukkit.classgenerator.ClassGenerator.generate(ClassGenerator.java:50)
[14:55:34] [Server thread/WARN]: 	at us.myles.ViaVersion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:104)
[14:55:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394)
[14:55:34] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252)
[14:55:34] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066)
[14:55:34] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[14:55:34] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

### Bug Description

I'm running a Minecraft server with Java 16, and the plugin are not working

### Steps to Reproduce

1. Set Java 16 for your server
2. Start your server

### Expected Behavior

Starting my server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Follow the issue template / update to dev builds.
