### ISSUE TITLE
ViaVersion Console Error

### ISSUE THREAD

**Issue by CamManCraft2001** [ViaVersion/ViaVersion#2479]
### '/viaversion dump' Output

https://dump.viaversion.com/6701e4377342db24e494d79e5af254108ec54bef8b56f01ea7d1dbe23f99dcc0

### Console Error

```
Put the paste.gg link or text here.
```
[20:39:18] [Netty Epoll Server IO #2/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[20:39:18] [Netty Epoll Server IO #2/WARN]: {Type: VarInt, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol$1$$Lambda$3471/0x0000000840a08440, Packet ID: 0, Source 1: com.viaversion.viaversion.protocols.base.BaseProtocol$1 (Anonymous)}
[20:39:18] [Netty Epoll Server IO #2/WARN]: Actual Error: 
[20:39:18] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:731)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:40)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:73)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:129)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:168)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.protocols.base.BaseProtocol$1.lambda$registerMap$0(BaseProtocol.java:50)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandler.write(PacketHandler.java:41)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:153)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:273)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.protocols.base.BaseProtocol.transform(BaseProtocol.java:123)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:360)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:343)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:259)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformServerbound(UserConnectionImpl.java:243)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:55)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:570)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_16_R3.LegacyPingHandler.channelRead(LegacyPingHandler.java:121)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:39:18] [Netty Epoll Server IO #2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)

### Bug Description

This error pops up everytime a player joins the server, the console also spams this message every so often: "io.netty.handler.timeout.ReadTimeoutException" 

### Steps to Reproduce

Player joins server

### Expected Behavior

Error shouldn't appear

### Additional Server Info

Plugins that I use on my Server:
![Capture](https://user-images.githubusercontent.com/41654159/118554623-b00e3880-b72f-11eb-95cc-03603599d1c6.PNG)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
You're outdated (otherwise someone sending bad packets or something unexpectedly closing a connection).
