### ISSUE TITLE
Error reading NBT in show_item

### ISSUE THREAD

**Issue by sergservis** [ViaVersion/ViaVersion#2490]
### '/viaversion dump' Output

https://dump.viaversion.com/fbb76d3c8624757479b3391b911b9a973d224351fc5dc4ca87f83ef2feec2d03

### Console Error

```
[16:32:41] [Netty Epoll Server IO #0/WARN]: [ViaVersion] Error reading NBT in show_item:{id:spawn_egg,tag:{display:{Name:"Parrot",Lore:[a:"Hunger: 99",a:"Health: 20,00",a:"Опыт: 0,00",a:"A type: Parrot",a:"Skill tree: Ride"]}}}
[16:32:41] [Netty Epoll Server IO #0/WARN]: java.io.IOException: com.viaversion.viaversion.api.minecraft.nbt.StringTagParseException: Expected character ',' but got ':'(at position 50)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.BinaryTagIO.readString(BinaryTagIO.java:194)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.data.ComponentRewriter1_13.handleHoverEvent(ComponentRewriter1_13.java:59)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.rewriter.ComponentRewriter.processText(ComponentRewriter.java:168)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.rewriter.ComponentRewriter.processAsArray(ComponentRewriter.java:196)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.rewriter.ComponentRewriter.processText(ComponentRewriter.java:163)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.ChatRewriter.processTranslate(ChatRewriter.java:67)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.Protocol1_13To1_12_2$7.lambda$registerMap$0(Protocol1_13To1_12_2.java:291)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandler.write(PacketHandler.java:41)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:153)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:273)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:356)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:344)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:259)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:238)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:85)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:78)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at protocolsupport.protocol.pipeline.common.LogicHandler.write(LogicHandler.java:56)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at LPX.au.write(Unknown Source)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.ruinscraft.panilla.api.io.dplx.PacketInspectorDplx.write(PacketInspectorDplx.java:48)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:32:41] [Netty Epoll Server IO #0/WARN]: Caused by: com.viaversion.viaversion.api.minecraft.nbt.StringTagParseException: Expected character ',' but got ':'(at position 50)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.CharBuffer.makeError(CharBuffer.java:118)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.CharBuffer.expect(CharBuffer.java:106)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.TagStringReader.separatorOrCompleteWith(TagStringReader.java:285)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.TagStringReader.list(TagStringReader.java:91)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.TagStringReader.tag(TagStringReader.java:203)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.TagStringReader.compound(TagStringReader.java:65)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.TagStringReader.tag(TagStringReader.java:198)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.TagStringReader.compound(TagStringReader.java:65)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.TagStringReader.tag(TagStringReader.java:198)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.TagStringReader.compound(TagStringReader.java:65)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.minecraft.nbt.BinaryTagIO.readString(BinaryTagIO.java:188)
[16:32:41] [Netty Epoll Server IO #0/WARN]: 	... 64 more
```

### Bug Description

Possibly related to the LibsDisguises plugin

### Steps to Reproduce

Papper spigot 1.12.2

### Expected Behavior

Eliminate the error

### Additional Server Info

I don't know the exact problem

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Added to #2429
