### ISSUE TITLE
 PLAYERS KICKED WHILE TELEPORTING PAPER-1.12.2

### ISSUE THREAD

**Issue by Kr1S-D** [ViaVersion/ViaVersion#2496]
### '/viaversion dump' Output

https://dump.viaversion.com/755ce1ba034b38fcede25241791073df206c8e6ab795b1271518afd13d8c9e98

### Console Error

```
Internal Exception: io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
```

### Bug Description

1.8 clients (not all are kicked out if teleported with / warp or teleported by other plugins, kicked off the server if killed by a mythic mobs boss (in 1.12.2))

### Steps to Reproduce

login 1.12.2
install mythic mobs 
get killed by a mob with powerful weapons or (if the server has an average of 20/40 players start teleporting at random)

### Expected Behavior

People are not to be thrown out at random

### Additional Server Info

I use Waterfall otherwise the server kicks 20 to 40 random online players while running, PLUGIN IN BUNGEE:  AuthmeBungee, botsentry, litebans, bungeequeue, bungeereport, cleanmotd, craftingstorem , Nyx, redirectplus, staffcaht, skinrestorer.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to -DEV builds from https://ci.viaversion.com/

**Comment by Kr1S-D** [comment]
?

**Comment by Kr1S-D** [comment]
I tried the dev builds

**Comment by KennyTV** [comment]
Nope, you didn't. Download them from https://ci.viaversion.com/job/ViaVersion-DEV/ https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/ and https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/

**Comment by Kr1S-D** [comment]
`[20:00:02] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to LuckPerms v5.2.49
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.Via.getManager()Lus/myles/ViaVersion/ViaManager;
	at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:346) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:343) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.findConnection(ViaFacet.java:92) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.findProtocol(ViaFacet.java:96) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:88) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.facet.Facet.of(Facet.java:97) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:90) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:78) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:76) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_292]
	at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:75) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
	at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[20:00:02] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to VoteParty v2.24
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.Via.getManager()Lus/myles/ViaVersion/ViaManager;
	at me.clip.voteparty.libs.kyori.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:347) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.bukkit.BukkitFacet$ViaHook.apply(BukkitFacet.java:344) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.viaversion.ViaFacet.findConnection(ViaFacet.java:96) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.viaversion.ViaFacet.findProtocol(ViaFacet.java:100) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.viaversion.ViaFacet.isApplicable(ViaFacet.java:92) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.facet.Facet.of(Facet.java:100) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.facet.FacetAudience.<init>(FacetAudience.java:109) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.bukkit.BukkitAudience.<init>(BukkitAudience.java:85) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:162) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:71) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:89) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_292]
	at me.clip.voteparty.libs.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:88) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$new$3(BukkitAudiencesImpl.java:101) ~[?:?]
	at me.clip.voteparty.libs.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.lambda$registerEvent$5(BukkitAudiencesImpl.java:215) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
`

**Comment by KennyTV** [comment]
Update LuckPerms, otherwise you have to wait for to update.

**Comment by Kr1S-D** [comment]
I'm willing to pay for the version that doesn't kick players! Because it's stressful

**Comment by Kr1S-D** [comment]
please

**Comment by Camotoy** [comment]
Did you update LuckPerms?

**Comment by Kr1S-D** [comment]
yep

**Comment by Camotoy** [comment]
You also need to update VoteParty, or ask them for an update. Regardless, the error no longer resides with ViaVersion; your plugins need to update to support the latest changes.

**Comment by Kr1S-D** [comment]
Luckperms and voteparty are at the latest version!
