### ISSUE TITLE
When connecting to a 1.13- server, an error occurs in the client.

### ISSUE THREAD

**Issue by LemonCaramel** [ViaVersion/ViaVersion#2502]
### '/viaversion dump' Output

https://dump.viaversion.com/94d368df38423f6674c0a0b94f30dac450f243b913027acabd461a7ef6b0585c

### Console Error

1.17-pre Fabric
```
[13:44:53] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_2935()" because "this.field_3699" is null
	at net.minecraft.class_634.method_20203(class_634.java:2197) ~[intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.class_4273.method_20205(class_4273.java:24) ~[intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.class_4273.method_11054(class_4273.java:6) ~[intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1077) [intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-minecraft-1.17-pre1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17-pre1-client.jar:?]
```

1.17-pre Vanilla
```
[03:03:01] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "ejh.f()" because "this.g" is null
    at eji.a(SourceFile:2197) ~[1.17-pre1.jar:?]
    at si.a(SourceFile:24) ~[1.17-pre1.jar:?]
    at si.a(SourceFile:6) ~[1.17-pre1.jar:?]
    at pm.a(SourceFile:21) ~[1.17-pre1.jar:?]
    at aqu.c(SourceFile:151) [1.17-pre1.jar:?]
    at aqy.c(SourceFile:23) [1.17-pre1.jar:?]
    at aqu.z(SourceFile:125) [1.17-pre1.jar:?]
    at aqu.bq(SourceFile:110) [1.17-pre1.jar:?]
    at dvo.f(SourceFile:1077) [1.17-pre1.jar:?]
    at dvo.e(SourceFile:730) [1.17-pre1.jar:?]
    at net.minecraft.client.main.Main.main(SourceFile:217) [1.17-pre1.jar:?]
```

1.16.5 Fabric
```
[13:49:13] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at net.minecraft.class_634.method_20203(class_634.java:2272) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_4273.method_20205(class_4273.java:30) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_4273.method_11054(class_4273.java:8) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1015) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.5-client.jar:?]
```

1.15.2
```
[13:59:25] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at dnp.a(SourceFile:2233) ~[minecraft.jar:?]
	at oi.a(SourceFile:30) ~[minecraft.jar:?]
	at oi.a(SourceFile:8) ~[minecraft.jar:?]
	at lv.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[minecraft.jar:?]
	at ais.c(ThreadTaskExecutor.java:173) [minecraft.jar:?]
	at aiw.c(SourceFile:23) [minecraft.jar:?]
	at ais.w(ThreadTaskExecutor.java:135) [minecraft.jar:?]
	at ais.bk(ThreadTaskExecutor.java:115) [minecraft.jar:?]
	at dbn.d(SourceFile:956) [minecraft.jar:?]
	at dbn.d(SourceFile:619) [minecraft.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [minecraft.jar:?]
```

### Bug Description

I checked that the problem did not occur on the server 1.14+.

I couldn't properly check the obfuscation map because I didn't have time. :cry:
I think this problem might be related to chunk rewriters.

### Steps to Reproduce

1. Login as a 1.14 or later client.
2. See the error

### Expected Behavior

No errors should occur.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Thank you for providing the different error messages, it is fixed now.
