### ISSUE TITLE
Unable to inject ViaVersion - Error in console - Waterfall 1.16.5

### ISSUE THREAD

**Issue by REXAGONE** [ViaVersion/ViaVersion#2509]
### '/viaversion dump' Output

https://dump.viaversion.com/6a985c78c6de1ceb147e45ec02a127db81f7eb766cf4792ea00235fa48b422ac

### Console Error

[23:06:39 WARN] [ViaVersion]: You are running a development version, please report any bugs to GitHub.
[23:06:39 INFO] [ViaVersion]: Loading 1.12 -> 1.13 mappings...
[23:06:39 INFO] [ViaVersion]: Loading 1.13 -> 1.13.2 mappings...
[23:06:39 INFO] [ViaVersion]: Loading 1.13.2 -> 1.14 mappings...
[23:06:39 INFO] [ViaVersion]: Loading 1.14 -> 1.15 mappings...
[23:06:39 INFO] [ViaVersion]: Loading 1.15 -> 1.16 mappings...
[23:06:39 INFO] [ViaVersion]: Loading 1.16 -> 1.16.2 mappings...
[23:06:39 ERROR] [ViaVersion]: Unable to inject ViaVersion, please post these details on our GitHub and ensure you're using a compatible server version.
[23:06:39 ERROR] [ViaVersion]: ViaVersion failed to inject:
[23:06:39 ERROR]: java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @2220c5f7
[23:06:39 ERROR]:       at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[23:06:39 ERROR]:       at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[23:06:39 ERROR]:       at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[23:06:39 ERROR]:       at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[23:06:39 ERROR]:       at us.myles.ViaVersion.bungee.platform.BungeeViaInjector.inject(BungeeViaInjector.java:35)
[23:06:39 ERROR]:       at us.myles.ViaVersion.ViaManager.init(ViaManager.java:64)
[23:06:39 ERROR]:       at us.myles.ViaVersion.BungeePlugin.onEnable(BungeePlugin.java:76)
[23:06:39 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315)
[23:06:39 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[23:06:39 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:80)
[23:06:39 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[23:06:39 INFO]: Enabled plugin ViaVersion version 3.2.2-SNAPSHOT by _MylesC, creeper123123321, Gerrygames, KennyTV, Matsv
[23:06:39 INFO]: Enabled plugin cmd_server version git:cmd_server:1.16-R0.5-SNAPSHOT:12d5e24:423 by WaterfallMC
[23:06:39 INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.16-R0.5-SNAPSHOT:12d5e24:423 by WaterfallMC
[23:06:39 INFO]: Enabled plugin cmd_send version git:cmd_send:1.16-R0.5-SNAPSHOT:12d5e24:423 by WaterfallMC
[23:06:39 INFO] [PremiumConnector]: Debug level set to INFO
[23:06:39 INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[23:06:39 INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[23:06:39 INFO] [PremiumConnector]: AuthMe hook enabled.
[23:06:39 INFO]: Enabled plugin PremiumConnector version 2.3.2 by LLIcocoman_Hrz
[23:06:39 INFO] [ViaVersion]: Loading block connection mappings ...

### Bug Description

When I start my Waterfall server, this message appears (also on Bungeecord). It doesn't affect Java players but I suspect it prevents Bedrock players from being able to come in with the Geyser plugin.

### Steps to Reproduce

1. Install ViaVersion 3.2.1 or a new build
2. Run the proxy on Waterfall 1.16.5 Build#427
3. Check the console

### Expected Behavior

I hope this error can be fixed and hope that this error is the cause of my Bedrock players not being able to join my server.

### Additional Server Info

I use Waterfall
I tested on Waterfall and on Bungeecord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to dev builds on the ci.
