### ISSUE TITLE
When I join my server

### ISSUE THREAD

**Issue by Xiaojin-serv** [ViaVersion/ViaVersion#2514]
### `/viaversion dump` Output

https://dump.viaversion.com/66be7524539fd4fb4c2fefe8c884273a0b2dbf6d9e9d474d4ec972a7263e1cea

### Console Error

[13:36:48 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[13:36:48 WARN]: {Type: Chunk, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.BlockItemPackets1_12$4 (Anonymous), Packet ID: 32}
[13:36:48 WARN]: Actual Error:
[13:36:48 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:36:48 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:36:48 WARN]:        at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:36:48 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:36:48 WARN]:        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$1.write(BukkitPipelineInjector.java:55)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[13:36:48 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[13:36:48 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[13:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[13:36:48 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[13:36:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[13:36:48 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[13:36:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[13:36:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:36:48 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[13:36:48 WARN]: {Type: Chunk, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.BlockItemPackets1_12$4 (Anonymous), Packet ID: 32}
[13:36:48 WARN]: Actual Error:
[13:36:48 WARN]: Caused by: java.lang.IllegalStateException: Block data length (2224) does not match expected length (832)! bitsPerBlock=13, originalBitsPerBlock=160
[13:36:48 WARN]:        at com.viaversion.viaversion.api.type.types.version.ChunkSectionType1_9.read(ChunkSectionType1_9.java:70)
[13:36:48 WARN]:        at com.viaversion.viaversion.api.type.types.version.ChunkSectionType1_9.read(ChunkSectionType1_9.java:31)
[13:36:48 WARN]:        at com.viaversion.viaversion.protocols.protocol1_9_1_2to1_9_3_4.types.Chunk1_9_3_4Type.read(Chunk1_9_3_4Type.java:57)
[13:36:48 WARN]:        at com.viaversion.viaversion.protocols.protocol1_9_1_2to1_9_3_4.types.Chunk1_9_3_4Type.read(Chunk1_9_3_4Type.java:37)
[13:36:48 WARN]:        at com.viaversion.viaversion.api.type.PartialType.read(PartialType.java:41)
[13:36:48 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125)
[13:36:48 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:171)
[13:36:48 WARN]:        at com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.BlockItemPackets1_12$4$1.handle(BlockItemPackets1_12.java:176)
[13:36:48 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[13:36:48 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[13:36:48 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[13:36:48 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[13:36:48 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[13:36:48 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[13:36:48 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:289)
[13:36:48 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:268)
[13:36:48 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:85)
[13:36:48 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:78)
[13:36:48 WARN]:        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
[13:36:48 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:36:48 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:473)
[13:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:64)
[13:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:243)
[13:36:48 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:36:48 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:36:48 WARN]:        at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.write(INCChannel.java:143)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:36:48 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:36:48 WARN]:        at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$1.write(BukkitPipelineInjector.java:55)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[13:36:48 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[13:36:48 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[13:36:48 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[13:36:48 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[13:36:48 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[13:36:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[13:36:48 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[13:36:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[13:36:48 WARN]:        at java.lang.Thread.run(Unknown Source)

### Bug Description

When I join my server, I will get kicked

### Steps to Reproduce

1. Login with a 1.8 client

### Expected Behavior

Get kicked

### Additional Server Info

Proxy: Waterfall (without any via plugin)
Server: Paper 1.12.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Something is sending weird chunk packets (likely FAWE)
