### ISSUE TITLE
ViaVersion does not work with Skript

### ISSUE THREAD

**Issue by Comstepr** [ViaVersion/ViaVersion#2531]
### `/viaversion dump` Output

https://dump.viaversion.com/a97b0d6336ccc7e84ee48a39b0e6c333afbf1f351a74edf55114308167cb2398

### Console Error

```
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[08:32:19] [Server thread/ERROR]: #!#! Could not load discord/give.sk
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[08:32:19] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[08:32:19] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[08:32:19] [Server thread/ERROR]: #!#! Here is full list of them:
[08:32:19] [Server thread/ERROR]: #!#! skRayFall v1.9.23 (https://sk.rayfall.net/) Vixio v2.0.7 (http://vixio.space) TuSKe v1.8.2-Pikachu-Patch-3 (github.com/Tuke-Nuke/TuSKe) ThatPacketAddon v1.0-BETA.3 (tlatoani.us/thatpacketaddon) Skellett v1.9.9 (https://forums.skunity.com/resources/skellett.24/) Reqn v1.2.1 skript-votifier-hook v1.1.0 DiscordSRV v1.22.0 (https://github.com/DiscordSRV/DiscordSRV) skript-mirror v2.0.0-SNAPSHOT (https://github.com/btk5h/skript-mirror) Skungee v1.0.15 skUtilities v0.9.2 (https://tim740.github.io/) SkQuery v4.1.5 SkUniversal v2.11.5 
[08:32:19] [Server thread/ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[08:32:19] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[08:32:19] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[08:32:19] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[08:32:19] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[08:32:19] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Stack trace:
[08:32:19] [Server thread/ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for customenchantment
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:262)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.createExprInfo(SkriptParser.java:1837)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1804)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1552)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:501)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:839)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1568)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1525)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1491)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1525)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1564)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:223)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:178)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:58)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1030)
[08:32:19] [Server thread/ERROR]: #!#!     at me.iblitzkriegi.vixio.commands.DiscordCommandFactory.add(DiscordCommandFactory.java:263)
[08:32:19] [Server thread/ERROR]: #!#!     at me.iblitzkriegi.vixio.commands.DiscordCommandRegistry.init(DiscordCommandRegistry.java:130)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1263)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1234)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:669)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$4(ScriptLoader.java:401)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:420)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$3(ScriptLoader.java:337)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:370)
[08:32:19] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript$2.run(Skript.java:601)
[08:32:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[08:32:19] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[08:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:945)
[08:32:19] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[08:32:19] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:832)
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Version Information:
[08:32:19] [Server thread/ERROR]: #!#!   Skript: 2.5.3 (latest)
[08:32:19] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[08:32:19] [Server thread/ERROR]: #!#!     Date: 2020-12-11
[08:32:19] [Server thread/ERROR]: #!#!   Bukkit: 1.16.5-R0.1-SNAPSHOT
[08:32:19] [Server thread/ERROR]: #!#!   Minecraft: 1.16.5
[08:32:19] [Server thread/ERROR]: #!#!   Java: 15.0.3 (OpenJDK 64-Bit Server VM 15.0.3+3-Ubuntu-120.10)
[08:32:19] [Server thread/ERROR]: #!#!   OS: Linux amd64 5.8.0-55-generic
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Server platform: Paper
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Current node: set {discord.lang::role.leader} to role with id "842383464874377247" (discord/give.sk, line 3)
[08:32:19] [Server thread/ERROR]: #!#! Current item: null
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Thread: Server thread
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! Language: english
[08:32:19] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[08:32:19] [Server thread/ERROR]: #!#! 
[08:32:19] [Server thread/ERROR]: #!#! End of Error.
```

### Bug Description

When using ViaVersion and Skript combined, Skript fails to load certain scripts. I'm posting this issue here because I believe ViaVersion is causing a conflict. Without VV installed, Skript loads successfully and all Skripts work.

### Steps to Reproduce

1. Install Skript
2. Install ViaVersion
3. Install Paper (latest version)
4. Skripts will fail to load.

### Expected Behavior

Skripts are supposed to load correctly, rather than having a harmless plugin cause a conflict.

### Additional Server Info

I do use BungeeCord but it only has the lobby and the server itself. Plugins are Geyser and Waterfall.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Camotoy** [comment]
From Minehut's updates channel:

`servers [using TuSKe] should still try to migrate to a newer plugin like skript-gui if possible.`

Seems like that might have ViaVersion integration that is now outdated.

**Comment by Comstepr** [comment]
Hey Camotoy! Nice to see you here as well. Would it help if I remove TuSKe?

**Comment by Comstepr** [comment]
Also, I'm not using Minehut.

**Comment by Camotoy** [comment]
Hello!

I assumed as much about your hosting provider, but I shared the snippet to imply that TuSKe could be the issue here. Let me attach their full update:

```
TuSKe Fix

An update for TuSKe has been released which should fix the issues that servers were experiencing running it alongside ViaVersion. If you were affected by this, simply restart your server and the plugin should start working again. Keep in mind that this is a temporary solution, and servers should still try to migrate to a newer plugin like skript-gui if possible.
```

I'm thinking they created their own TuSKe fork to work around ViaVersion's API update.

**Comment by Comstepr** [comment]
Oh right. Then it's probably my plugins then. Let me try a clean version of Skript.

**Comment by Comstepr** [comment]
Well it turns out that it was just one of my Skript addons. Thanks @Camotoy for the help!

**Comment by KaptanINO** [comment]
> Hello!
> 
> I assumed as much about your hosting provider, but I shared the snippet to imply that TuSKe could be the issue here. Let me attach their full update:
> 
> ```
> TuSKe Fix
> 
> An update for TuSKe has been released which should fix the issues that servers were experiencing running it alongside ViaVersion. If you were affected by this, simply restart your server and the plugin should start working again. Keep in mind that this is a temporary solution, and servers should still try to migrate to a newer plugin like skript-gui if possible.
> ```
> 
> I'm thinking they created their own TuSKe fork to work around ViaVersion's API update.

Where is this release? Can you give me link?

**Comment by Camotoy** [comment]
I am not aware of a release for it (though I do not follow the Skript community). It sounds like Minehut recommends another option:

`servers should still try to migrate to a newer plugin like skript-gui if possible.`
