### ISSUE TITLE
Console Error when switching the hotbar slot

### ISSUE THREAD

**Issue by nmauer** [ViaVersion/ViaVersion#2535]
### `/viaversion dump` Output

https://dump.viaversion.com/57724eff169e0c4f9324f0496c910f728210a586aec80d587ee9dfb87835a405

### Console Error

[19:49:11] [Server thread/WARN]: [ViaVersion] ERROR IN Protocol1_8TO1_9 IN REMAP OF BOSSBAR (0x0C)
[19:49:11] [Server thread/WARN]: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[19:49:11] [Server thread/WARN]: {Type: JsonElement, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1 (Anonymous), Packet ID: -1}
[19:49:11] [Server thread/WARN]: Actual Error:
[19:49:11] [Server thread/WARN]: Caused by: java.io.IOException: Unable to read type JsonElement, found String
[19:49:11] [Server thread/WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[19:49:11] [Server thread/WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$1.lambda$registerMap$0(PlayerPackets.java:51)
[19:49:11] [Server thread/WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[19:49:11] [Server thread/WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[19:49:11] [Server thread/WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[19:49:11] [Server thread/WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.constructPacket(PacketWrapperImpl.java:289)
[19:49:11] [Server thread/WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:243)
[19:49:11] [Server thread/WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send(PacketWrapperImpl.java:231)
[19:49:11] [Server thread/WARN]:        at de.gerrygames.viarewind.utils.PacketUtil.sendPacket(PacketUtil.java:42)
[19:49:11] [Server thread/WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.sendBossBar(Cooldown.java:108)
[19:49:11] [Server thread/WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.showCooldown(Cooldown.java:69)
[19:49:11] [Server thread/WARN]:        at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.tick(Cooldown.java:59)
[19:49:11] [Server thread/WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[19:49:11] [Server thread/WARN]:        at de.gerrygames.viarewind.utils.Ticker.lambda$null$0(Ticker.java:19)
[19:49:11] [Server thread/WARN]:        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.Collections$SetFromMap.forEach(Unknown Source)
[19:49:11] [Server thread/WARN]:        at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
[19:49:11] [Server thread/WARN]:        at de.gerrygames.viarewind.utils.Ticker.lambda$init$1(Ticker.java:15)
[19:49:11] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[19:49:11] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[19:49:11] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060)
[19:49:11] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355)
[19:49:11] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
[19:49:11] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
[19:49:11] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[19:49:11] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

### Bug Description

Every time I switch the slot in the hotbar or press the left mouse buttom, the error appears the error in the console.

### Steps to Reproduce

1. Connect with an 1.8.9 Client on an 1.16.5 Server (with ViaBackwards and ViaRewind)
2. Switch the hotbarslot or press the left mouse button

### Expected Behavior

I didn't expected an error

### Additional Server Info

I am running an single spigot 1.16.5 Server with ViaBackwards and ViaRewind

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update ViaRewind to ci builds

**Comment by nmauer** [comment]
I already updated it to ci build, but it didn't change anything
