### ISSUE TITLE
SkinsRestorer

### ISSUE THREAD

**Issue by AirCraze** [ViaVersion/ViaVersion#2537]
### `/viaversion dump` Output

https://dump.viaversion.com/d9b6d9968b9b85cd4f6ecdbcc7ec63a71119a867b9228a7bf36f25bdd1a28ef2

### Console Error

```
Put the paste.gg link or text here.
```
[20:35:30 WARN]: [SkinsRestorer] Task #1725 for SkinsRestorer v14.0.2 generated an exception
java.lang.NoSuchMethodError: us.myles.ViaVersion.api.Via.getManager()Lus/myles/ViaVersion/ViaManager;
        at net.skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:279) ~[?:?]
        at net.skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:50) ~[?:?]
        at net.skinsrestorer.bukkit.skinfactory.UniversalSkinFactory.lambda$updateSkin$1(UniversalSkinFactory.java:126) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1163]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1163]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

### Bug Description

When I have SkinsRestorer I get this issue.

### Steps to Reproduce

1. 1.16 Paper Spigot (any)
2. Add Skins Restorer (latest)
3. Add ViaVersion
4. You recieve this error

### Expected Behavior

Load skins, and not show the error
(I tried the latest build, however it works with 3.2.1)

### Additional Server Info

Plugins:
SkinsRestorer
ViaVerison

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Camotoy** [comment]
You need to update your SkinsRestorer build. Check for a dev version if there's not a merged release - they merged a pull request to fix ViaVersion 4.0.0 support.
