### ISSUE TITLE
Console error causing server to crash: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.api.minecraft.entities.EntityType.isOrHasParent(com.viaversion.viaversion.api.minecraft.entities.EntityType)" because "type" is null

### ISSUE THREAD

**Issue by AlecMcQuarrie** [ViaVersion/ViaVersion#2549]
### `/viaversion dump` Output

https://dump.viaversion.com/d48e8b6f0b8ac8c9de4d3e7aa7d12f8f3e0f05dce3681d2c98d85b754f818a33

### Console Error

[15:13:16] [Netty Epoll Server IO #1/WARN]: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.api.minecraft.entities.EntityType.isOrHasParent(com.viaversion.viaversion.api.minecraft.entities.EntityType)" because "type" is null
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viabackwards.protocol.protocol1_13_2to1_14.packets.EntityPackets1_14.lambda$registerRewrites$1(EntityPackets1_14.java:396)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:118)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.handleMetadata(EntityRewriterBase.java:67)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viabackwards.api.rewriters.LegacyEntityRewriter$3.lambda$registerMap$0(LegacyEntityRewriter.java:106)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:289)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:268)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:85)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:78)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:529)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:71)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:269)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:275)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$1.write(BukkitPipelineInjector.java:53)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager$1.run(NetworkManager.java:455)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:13:16] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

### Bug Description

Using Yatopia 1.16.5 with the newest version of  geyser and floodgate. I believe this error is crashing my server. It logs this error about a thousand times and then shuts down.

### Steps to Reproduce

Use yatopia 1.16.5 with the latest version of geyser and floodtate, and I'm not sure what happens from there.

### Expected Behavior

I expect it to perform normally. I am using the DEV build 4.0.1 snapshot

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Camotoy** [comment]
Have you tried testing with a server software such as Paper?

**Comment by KennyTV** [comment]
Thanks for the report, but please note that we do not support servers running Yatopia, at all - as the large warning on startup already says.

**Comment by AlecMcQuarrie** [comment]
Do you guys support purpur?

**Comment by AlecMcQuarrie** [comment]
I'm slightly new at all of this, and I didn't know if paper was optimized that well.

**Comment by KennyTV** [comment]
Paper is already optimized well, but if you need more than that, we recommend Tuinity (or forks of Tuinity like Purpur, Airplaine), yeah.

**Comment by AlecMcQuarrie** [comment]
Okay, thank you.

**Comment by AlecMcQuarrie** [comment]
Guys
It happened again on purpur

**Comment by AlecMcQuarrie** [comment]
[20:11:52] [Netty Epoll Server IO #2/WARN]: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.api.minecraft.entities.EntityType.isOrHasParent(com.viaversion.viaversion.api.minecraft.entities.EntityType)" because "type" is null

**Comment by Camotoy** [comment]
Did you update your ViaBackwards build from ci.viaversion.com? Kenny made a fix for that.

**Comment by AlecMcQuarrie** [comment]
I have 4.0.0 and 2.0.0

**Comment by AlecMcQuarrie** [comment]
Are there new ones now?
