### ISSUE TITLE
ViaVersion not works with TusKe

### ISSUE THREAD

**Issue by KaptanINO** [ViaVersion/ViaVersion#2553]
### `/viaversion dump` Output

https://dump.viaversion.com/7dbe8ddfcdf6c1c13f08279e6b29963d2b3091027977e039bc783e6372ea3b00

### Console Error

[11:11:51 WARN]: Unexpected exception while parsing console command "TUSKE"
org.bukkit.command.CommandException: Cannot execute command 'tuske' in plugin TuSKe v1.8.2 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.5.jar:git-Paper-777]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-777]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-777]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-777]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

### Bug Description

On Paper 1.16.5 i can't use ViaVersion with TusKe.

### Steps to Reproduce

1.Open 1.16.5 server.
2.Install TusKe, Skript and ViaVersion 4.0.0 or 4.0.1
3. You can't use TusKe and some Skript's anymore.

### Expected Behavior

Normally i can use my Skripts without any error but some of my skripts are not working because viaversion.

### Additional Server Info

I use this plugins:
lugins (41): §aAdvancedBan§f, §aAuctionMaster§f, §aAutoSaveWorld*§f, §aBentoBox§f, §aCitizens§f, §aDeluxeChat§f, §aDeluxeMenus§f, §aEssentials§f, §aEssentialsSpawn§f, §aeZProtector§f, §afloodgate§f, §aGeyser-Spigot§f, §aGoldenCrates§f, §aHolographicDisplays§f, §aJakesRTP§f, §aJetsMinions§f, §aMultiverse-Core§f, §aNexEngine§f, §aPlaceholderAPI§f, §aPrisonRanksX*§f, §aProtocolLib§f, §aQuests*§f, §aShopGUIPlus§f, §aShopkeepers§f, §aSilkSpawners§f, §aSK-NBeeT§f, §aSkBee§f, §aSkQuery§f, §askRayFall§f, §aSkript§f, §aTAB§f, §aTitleManager§f, §cTuSKe*§f, §aUltraPermissions§f, §aVault§f, §aViaVersion§f, §aWebSender*§f, §aWorldBorderAPI§f, §aWorldEdit§f, §aWorldGuard§f, §azAuctionHouseV3.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KaptanINO** [comment]
I use ViaVersion beacause Geyser and Floodgate.

**Comment by Camotoy** [comment]
It's very likely that TuSKe needs to update its ViaVersion integration. See also: https://github.com/ViaVersion/ViaVersion/issues/2531

Closing as this is not a ViaVersion issue. Thank you!
