### ISSUE TITLE
Error When i set creative mode

### ISSUE THREAD

**Issue by zMaddHax** [ViaVersion/ViaVersion#2555]
### `/viaversion dump` Output

 https://dump.viaversion.com/f5980e38715b7e888f38281f0467ec97ae63f407a6ee50cbac5fe7bfe92d4e46

### Console Error

```
Put the paste.gg link or text here.
```
[02:22:30] [Server thread/INFO]: NotMaddii issued server command: /gamemode creative
[02:22:30] [Server thread/INFO]: [NotMaddii: Set own game mode to Creative Mode]
[02:22:30] [Netty Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_11_1To1_12 IN REMAP OF CHAT_MESSAGE (0x0F)
[02:22:30] [Netty Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_11_1To1_12 IN REMAP OF CHAT_MESSAGE (0x0F)
[02:22:30] [Netty Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[02:22:30] [Netty Server IO #1/WARN]: {Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$2 (Anonymous)}
[02:22:30] [Netty Server IO #1/WARN]: Actual Error:
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[02:22:30] [Netty Server IO #1/WARN]:   at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:186)
[02:22:30] [Netty Server IO #1/WARN]:   at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:164)
[02:22:30] [Netty Server IO #1/WARN]:   at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1683)
[02:22:30] [Netty Server IO #1/WARN]:   at net.minecraft.server.v1_16_R3.PlayerConnection.sendPacket(PlayerConnection.java:1656)
[02:22:30] [Netty Server IO #1/WARN]:   at net.minecraft.server.v1_16_R3.EntityPlayer.lambda$17(EntityPlayer.java:1675)
[02:22:30] [Netty Server IO #1/WARN]:   at net.minecraft.server.v1_16_R3.NetworkManager.lambda$4(NetworkManager.java:199)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[02:22:30] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[02:22:30] [Netty Server IO #1/WARN]:   at java.base/java.lang.Thread.run(Unknown Source)
[02:22:30] [Server thread/INFO]: NotMaddii lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$2 (Anonymous)}
Actual Error:
[02:22:30] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to LitePlaytimeRewards v2.4.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:487) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1637) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:331) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:163) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1246) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.TreeMap.remove(Object)" is null
        at com.backtobedrock.LitePlaytimeRewards.eventHandlers.LitePlaytimeRewardsEventHandlers.onPlayerQuitEvent(LitePlaytimeRewardsEventHandlers.java:74) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        ... 13 more

### Bug Description

Set Gamemode version 1.8.9 [lunar client] spigot 1.16.5

### Steps to Reproduce

login with 1.8.9
do /gamemode creative

and you have the error 

### Expected Behavior

the gamemode work but when i do the server send errors

### Additional Server Info

LitePlaytimeRewards, when i put that plugin the server givved the error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
That's likely the fault of LitePlaytimeRewards, not ViaBackwards.
