### ISSUE TITLE
ViaVersion does not work on Velocity

### ISSUE THREAD

**Issue by PhoenixmitX** [ViaVersion/ViaVersion#2557]
### `/viaversion dump` Output

https://dump.viaversion.com/ca6c361bc01475145a913f7c5ba6a1559f8ee7df8637ca620929ccde502b3d09

### Console Error

No error, only join message:
[22:59:26 INFO]: [connected player] PhoenixmitX (/1.2.3.4:56789) has connected

When running with dev builds:
```
[23:13:01] [main/INFO]: Booting up Velocity 1.1.8...
[23:13:02] [main/INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[23:13:02] [main/INFO]: Loading plugins...
[23:13:02] [main/INFO]: Loaded plugin viaversion 4.0.1-1.17.1-pre1-SNAPSHOT by _MylesC, creeper123123321, Gerrygames, KennyTV, Matsv
[23:13:02] [main/INFO]: Loaded plugin viabackwards 4.0.1-1.17.1-pre1-SNAPSHOT by Matsv, KennyTV, Gerrygames, creeper123123321, ForceUpdate1
[23:13:02] [main/INFO]: Loaded 2 plugins
[23:13:02] [Via-Mappingloader-0/INFO]: Loading 1.12 -> 1.13 mappings...
[23:13:02] [Via-Mappingloader-1/INFO]: Loading 1.13 -> 1.13.2 mappings...
[23:13:02] [Via-Mappingloader-2/INFO]: Loading 1.13.2 -> 1.14 mappings...
[23:13:02] [Via-Mappingloader-3/INFO]: Loading 1.14 -> 1.15 mappings...
[23:13:02] [Via-Mappingloader-4/INFO]: Loading 1.15 -> 1.16 mappings...
[23:13:02] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[23:13:02] [Via-Mappingloader-1/INFO]: Loading 1.16 -> 1.16.2 mappings...
[23:13:02] [Via-Mappingloader-3/INFO]: Loading 1.16.2 -> 1.17 mappings...
[23:13:02] [Velocity Task Scheduler - #0/WARN]: You are running a newer version of the plugin than is released!
[23:13:02] [Velocity Event Executor - #0/ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[23:13:02] [Velocity Event Executor - #0/ERROR]: #1: 

java.lang.ExceptionInInitializerError: null
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:184) ~[?:?]
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173) ~[?:?]
	at com.viaversion.viaversion.velocity.platform.VelocityViaInjector.inject(VelocityViaInjector.java:63) ~[?:?]
	at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:94) ~[?:?]
	at com.viaversion.viaversion.VelocityPlugin.onProxyLateInit(VelocityPlugin.java:104) ~[?:?]
	at net.kyori.event.asm.generated.4031b983c5.VelocityPlugin-onProxyLateInit-ProxyInitializeEvent-2.invoke(Unknown Source) ~[?:?]
	at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.1.8]
	at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.1.8]
	at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:154) ~[velocity.jar:1.1.8]
	at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$1(VelocityEventManager.java:136) ~[velocity.jar:1.1.8]
	at com.velocitypowered.proxy.plugin.VelocityEventManager$$Lambda$243/0x00000000c8f93f70.get(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:853) [?:?]
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.VelocityConnectionEvent
	at com.viaversion.viaversion.velocity.handlers.VelocityChannelInitializer.<clinit>(VelocityChannelInitializer.java:47) ~[?:?]
	... 13 more
Caused by: java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.VelocityConnectionEvent
	at java.lang.Class.forNameImpl(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:350) ~[?:?]
	at com.viaversion.viaversion.velocity.handlers.VelocityChannelInitializer.<clinit>(VelocityChannelInitializer.java:44) ~[?:?]
	... 13 more
[23:13:02] [Netty epoll Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25565
[23:13:02] [main/INFO]: Done (1.35s)!
```

### Bug Description

ViaVersion 4.0.0 does not work on Velocity 1.1.8
with and without ViaBackwards 4.0.0

### Steps to Reproduce

1. Put ViaVersion 4.0.0 on Velocity 1.1.8
2. stat proxy
3. try joining
4. [disconnected message](https://prnt.sc/15uhuht)

### Expected Behavior

Join to a subserver via proxy

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Jo0001** [comment]
You have to wait for the new velocity version. For the meantime use Via on your backend servers instead
