### ISSUE TITLE
1.12.2 clients can't connect to a server with via-version 4.0.0 and 4.0.1-dev.

### ISSUE THREAD

**Issue by alex-ritter** [ViaVersion/ViaVersion#2565]
### `/viaversion dump` Output

https://dump.viaversion.com/1bb10b898f13aae93aabe9d38987e001c01d3ef6309a178be69273e7dcf49e12

### Console Error

[20.06 17:22:02] [Server] io.netty.handler.codec.EncoderExceptioncom.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[20.06 17:22:02] [Server] {TypeByte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
[20.06 17:22:02] [Server] Actual Error
[20.06 17:22:02] [Server] at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20.06 17:22:02] [Server] at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20.06 17:22:02] [Server] at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[20.06 17:22:02] [Server] at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57)
[20.06 17:22:02] [Server] at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:175)
[20.06 17:22:02] [Server] at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:128)
[20.06 17:22:02] [Server] at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:119)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20.06 17:22:02] [Server] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20.06 17:22:02] [Server] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20.06 17:22:02] [Server] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[20.06 17:22:02] [Server] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20.06 17:22:02] [Server] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20.06 17:22:02] [Server] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20.06 17:22:02] [Server] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[20.06 17:22:02] [Server] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[20.06 17:22:02] [Server] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[20.06 17:22:02] [Server] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[20.06 17:22:02] [Server] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20.06 17:22:02] [Server] at java.lang.Thread.run(Thread.java:748)
[20.06 17:22:02] [Server] Caused bycom.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[20.06 17:22:02] [Server] {TypeByte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
[20.06 17:22:02] [Server] Actual Error
[20.06 17:22:02] [Server] Caused byjava.io.IOException: Unable to read type Byte, found Unsigned Byte
[20.06 17:22:02] [Server] at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:289)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:268)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:55)
[20.06 17:22:02] [Server] at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:31)
[20.06 17:22:02] [Server] at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20.06 17:22:02] [Server] at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20.06 17:22:02] [Server] at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[20.06 17:22:02] [Server] at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57)
[20.06 17:22:02] [Server] at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:175)
[20.06 17:22:02] [Server] at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:128)
[20.06 17:22:02] [Server] at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:119)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20.06 17:22:02] [Server] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20.06 17:22:02] [Server] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20.06 17:22:02] [Server] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[20.06 17:22:02] [Server] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20.06 17:22:02] [Server] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20.06 17:22:02] [Server] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

### Bug Description

I haven't tried this on a vanilla client, but on 1.12.2 kami blue when a player connects to the server, the player immediately disconnects from the server.

### Steps to Reproduce

1. Login as a 1.12.2 client
2. Connect to a server with ViaVersion 4.0.0 or 4.0.1-dev, ViaBackwards 4.0.0 and ViaRewind 2.0.0 or 2.0.1-dev.

The client will fail step 3 of the expected behavior and will be unable to connect to the server.

### Expected Behavior

1. Login as a 1.12.2 client
2. Connect to a server with ViaVersion 4.0.0 or 4.0.1-dev, ViaBackwards 4.0.0 and ViaRewind 2.0.0 or 2.0.1-dev.
3. The client should be able to connect to the server and play on the server as expect as before.

### Additional Server Info

I'm currently using bungeecord with ViaVersion 4.0.1-dev, ViaBackwards 4.0.0, ViaRewind 2.0.0, and this bungeecord server is trying to connect to a 1.17 paper server. Viaversion is not on the 1.17 paper server, only on the bungeecord server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by alex-ritter** [comment]
Confirmed to work on Vanilla clients too
![image](https://user-images.githubusercontent.com/48510521/122692264-9e6df400-d1f9-11eb-91d6-2033ec421ca8.png)

**Comment by KennyTV** [comment]
You didn't update ViaBackwards to 4.0.1-SNAPSHOT
