### ISSUE TITLE
Happened when stopping the server.

### ISSUE THREAD

**Issue by AirCraze** [ViaVersion/ViaVersion#2569]
### `/viaversion dump` Output

unknown

### Console Error

```
Put the paste.gg link or text here.
```
[17:50:46 WARN]: [ViaVersion] ERROR IN Protocol1_11_1To1_12 IN REMAP OF CHAT_MESSAGE (0x0F)
[17:50:46 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[17:50:46 WARN]: {Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$2 (Anonymous)}
[17:50:46 WARN]: Actual Error:
[17:50:46 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[17:50:46 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[17:50:46 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager$1.run(NetworkManager.java:450)
[17:50:46 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:50:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[17:50:46 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[17:50:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:50:46 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:50:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:50:46 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[17:50:46 WARN]: {Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$2 (Anonymous)}
[17:50:46 WARN]: Actual Error:
[17:50:46 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[17:50:46 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[17:50:46 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[17:50:46 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[17:50:46 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[17:50:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167)
[17:50:46 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[17:50:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[17:50:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[17:50:46 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[17:50:46 WARN]:        at com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$1.handleTranslate(ChatPackets1_12.java:36)
[17:50:46 WARN]:        at com.viaversion.viaversion.rewriter.ComponentRewriter.processText(ComponentRewriter.java:153)
[17:50:46 WARN]:        at com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$2.lambda$registerMap$0(ChatPackets1_12.java:54)
[17:50:46 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[17:50:46 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[17:50:46 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[17:50:46 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[17:50:46 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[17:50:46 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[17:50:46 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[17:50:46 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[17:50:46 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[17:50:46 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[17:50:46 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[17:50:46 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[17:50:46 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager$1.run(NetworkManager.java:450)
[17:50:46 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:50:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[17:50:46 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[17:50:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:50:46 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:50:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:50:46 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[17:50:46 WARN]: {Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$2 (Anonymous)}
[17:50:46 WARN]: Actual Error:
[17:50:46 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[17:50:46 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[17:50:46 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager$1.run(NetworkManager.java:450)
[17:50:46 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:50:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[17:50:46 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[17:50:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:50:46 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:50:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:50:46 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[17:50:46 WARN]: {Source 0: com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$2 (Anonymous)}
[17:50:46 WARN]: Actual Error:
[17:50:46 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[17:50:46 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[17:50:46 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[17:50:46 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[17:50:46 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[17:50:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167)
[17:50:46 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[17:50:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119)
[17:50:46 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[17:50:46 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[17:50:46 WARN]:        at com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$1.handleTranslate(ChatPackets1_12.java:36)
[17:50:46 WARN]:        at com.viaversion.viaversion.rewriter.ComponentRewriter.processText(ComponentRewriter.java:153)
[17:50:46 WARN]:        at com.viaversion.viabackwards.protocol.protocol1_11_1to1_12.packets.ChatPackets1_12$2.lambda$registerMap$0(ChatPackets1_12.java:54)
[17:50:46 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[17:50:46 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[17:50:46 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[17:50:46 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[17:50:46 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[17:50:46 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[17:50:46 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[17:50:46 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[17:50:46 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[17:50:46 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[17:50:46 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[17:50:46 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[17:50:46 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[17:50:46 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager$1.run(NetworkManager.java:450)
[17:50:46 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:50:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[17:50:46 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[17:50:46 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:50:46 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:50:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:50:46 INFO]: Babaganoosh30 left the game

### Bug Description

Happened when I left the game. (on 1.8)

### Steps to Reproduce

Server: 1.16.5 Paper
Add the development builds (6/21/2021)

### Expected Behavior

Not to receive this error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
You have a broken jar/changed jar while running.
