### ISSUE TITLE
Reporting REMAP OF SPAWN_PARTICLE error

### ISSUE THREAD

**Issue by Brickwrath** [ViaVersion/ViaVersion#2571]
### `/viaversion dump` Output

 https://dump.viaversion.com/b062ed7816bc9c47042fe31ec94fdafdc3e4c263c580e33360b610e7d9400673

### Console Error

```
[09:18:33 WARN]: [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF SPAWN_PARTICLE (0x24)
[09:18:33 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[09:18:33 WARN]: {Type: Float, Data: [Pair{Type|Integer, 15}, Pair{Type|Boolean, true}, Pair{Type|Double, -32.5}, Pair{Type|Double, 42.07393957002299}, Pair{Type|Double, 86.68092213764227}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 1}, Pair{Type|Float, 1.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 1.0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$3 (Anonymous), Packet ID: 34}
[09:18:33 WARN]: Actual Error:
[09:18:33 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[09:18:33 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[09:18:33 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[09:18:33 WARN]:        at de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[09:18:33 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[09:18:33 WARN]:        at de.codingair.warpsystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:72)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[09:18:33 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[09:18:33 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[09:18:33 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[09:18:33 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[09:18:33 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[09:18:33 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[09:18:33 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[09:18:33 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[09:18:33 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[09:18:33 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[09:18:33 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[09:18:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[09:18:33 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
```

### Bug Description

Player receiving the error cannot join after this occurs.

### Steps to Reproduce

Honestly, no clue.
Closest guess I have is a player punches and worldguard spawns some torch smoke to inform "can't do that here", but other than that can't find any other particles spawning in the area.

### Expected Behavior

Not kicking/crashing?

### Additional Server Info

Waterfall for 1.17
Paper for 1.17
Viaversion, Viabackwards and ViaRewind
ProtocolLib
Various other plugins.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Update to ci builds.
