### ISSUE TITLE
1.17 Viaversion not working with latest spgot built.

### ISSUE THREAD

**Issue by T3g4nTheCoder** [ViaVersion/ViaVersion#2574]
### `/viaversion dump` Output

https://dump.viaversion.com/e72100de6737241440e838c0401167829537b96d3527722e188920ca99854d6f

### Console Error

```
[23:28:09] [Server thread/ERROR]: [ViaVersion] Unable to inject ViaVersion, please post these details on our GitHub and ensure you're using a compatible server version.
[23:28:09] [Server thread/ERROR]: [ViaVersion] ViaVersion failed to inject:
[23:28:09] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer
[23:28:09] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
[23:28:09] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[23:28:09] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[23:28:09] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[23:28:09] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[23:28:09] [Server thread/WARN]:        at com.viaversion.viaversion.bukkit.util.NMSUtil.nms(NMSUtil.java:38)
[23:28:09] [Server thread/WARN]:        at com.viaversion.viaversion.bukkit.platform.BukkitViaInjector.getServerConnection(BukkitViaInjector.java:262)
[23:28:09] [Server thread/WARN]:        at com.viaversion.viaversion.bukkit.platform.BukkitViaInjector.inject(BukkitViaInjector.java:58)
[23:28:09] [Server thread/WARN]:        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:94)
[23:28:09] [Server thread/WARN]:        at com.viaversion.viaversion.ViaVersionPlugin.onEnable(ViaVersionPlugin.java:135)
[23:28:09] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:28:09] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[23:28:09] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[23:28:09] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[23:28:09] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[23:28:09] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:608)
[23:28:09] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[23:28:09] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987)
[23:28:09] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[23:28:09] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

### Bug Description

Server starts but viaversion seems to do nothing. I cannot join on 1.16.5 of anything under 1.17.

### Steps to Reproduce

1. get viaversion on 1.17 spigot build
2. start the server
3. get the error? idk might just be me but help pls

P.S. it has default config.

### Expected Behavior

no errors in console and i should be able to connect through 1.16.5

### Additional Server Info

Plugins: Healthbar, SkinsRestorer, ViaRewind V2.0, ViaBackwards V4.0, and ViaVersion V4.0

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Camotoy** [comment]
Please download the latest build from https://ci.viaversion.com/job/ViaVersion/. Thank you!

**Comment by KennyTV** [comment]
As the tick box you ticked says; use ci builds.

**Comment by T3g4nTheCoder** [comment]
fricking hell that was fast...
