### ISSUE TITLE
Console Spam - Use JsonReader.setLenient(true)

### ISSUE THREAD

**Issue by d2k11** [ViaVersion/ViaVersion#2578]
### `/viaversion dump` Output

https://dump.viaversion.com/3608096664377c079f4b17612ce02b9e7bdb2d1433160170de8d1de1089eef1d

### Console Error

```
[18:45:19] [Netty Epoll Server IO #0/ERROR]: [ViaBackwards] Error converting hover event component: {"color":"dark_red","hoverEvent":{"action":"show_entity","value":[{"text":"{\"name\":\"XtraMelon\",\"id\":\"9d141312-618b-402d-be36-3f6bbaae92fd\",\"type\":\"minecraft:player\"}"}]},"extra":[{"color":"dark_red","text":"XtraMelon"}],"text":""}
[18:45:19] [Netty Epoll Server IO #0/WARN]: com.viaversion.viaversion.libs.gson.JsonSyntaxException: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.internal.Streams.parse(Streams.java:60)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.StyleSerializer.lambda$decoder$0(StyleSerializer.java:200)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.legacyimpl.NBTLegacyHoverEventSerializerImpl.deserializeShowEntity(NBTLegacyHoverEventSerializerImpl.java:75)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.StyleSerializer.legacyHoverEventContents(StyleSerializer.java:185)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:156)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:98)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:53)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:932)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:1003)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:161)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:75)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:55)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:932)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:1003)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:975)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserializeFromTree(GsonComponentSerializerImpl.java:113)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.chat.TranslatableRewriter1_16.processText(TranslatableRewriter1_16.java:77)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.rewriter.ComponentRewriter.processAsArray(ComponentRewriter.java:196)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.rewriter.ComponentRewriter.processText(ComponentRewriter.java:163)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.chat.TranslatableRewriter1_16.processText(TranslatableRewriter1_16.java:56)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.rewriter.ComponentRewriter.processAsArray(ComponentRewriter.java:196)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.rewriter.ComponentRewriter.processText(ComponentRewriter.java:163)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.chat.TranslatableRewriter1_16.processText(TranslatableRewriter1_16.java:56)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viabackwards.protocol.protocol1_15_2to1_16.Protocol1_15_2To1_16$2.lambda$registerMap$0(Protocol1_15_2To1_16.java:98)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:289)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:268)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:450)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[18:45:19] [Netty Epoll Server IO #0/WARN]: Caused by: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.stream.JsonReader.checkLenient(JsonReader.java:1403)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.stream.JsonReader.doPeek(JsonReader.java:592)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.stream.JsonReader.peek(JsonReader.java:424)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.libs.gson.internal.Streams.parse(Streams.java:46)
[18:45:19] [Netty Epoll Server IO #0/WARN]: 	... 67 more
```

### Bug Description

ViaVersion spams this error in Console, but doesn't actually cause any issues in game to my knowledge.

### Steps to Reproduce

Unknown

### Expected Behavior

I expect this error not to spam.

### Additional Server Info

Java 16, Purpur (also reproduced issue on Paper), 1.17

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
We need the full error to tell what's going on

**Comment by gcurtiss** [comment]
Sorry, this is all it says for me in Console.

**Comment by gcurtiss** [comment]
My bad. Updated directly copied from latest.log.

**Comment by d2k11** [comment]
Issue persists on latest version of VV, VB and protocollib, using Airplane 82

**Comment by Camotoy** [comment]
I've also seen this happen on Geyser before, so I assume the root issue is within Adventure.

**Comment by kennytv** [comment]
Should be fixed with https://github.com/ViaVersion/ViaVersion/commit/0a4d08886dc1e13b340d3de512f939c2093bfe1b
