### ISSUE TITLE
Kicked when joining

### ISSUE THREAD

**Issue by ShreyasAyyengar** [ViaVersion/ViaVersion#2587]
### `/viaversion dump` Output

https://dump.viaversion.com/115894b463855c1eb62f8276583b36946d1e44936e7c43c88414e8a7c021f531

### Console Error

Actual Error: 
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[21:15:16] [Netty Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
[21:15:16] [Netty Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[21:15:16] [Netty Server IO #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[21:15:16] [Netty Server IO #3/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[21:15:16] [Netty Server IO #3/WARN]: {Type: Byte, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$4 (Anonymous), Packet ID: 47}
[21:15:16] [Netty Server IO #3/WARN]: Actual Error: 
[21:15:16] [Netty Server IO #3/WARN]: Caused by: java.io.IOException: Unable to read type Byte, found Unsigned Byte
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[21:15:16] [Netty Server IO #3/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[21:15:16] [Netty Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
[21:15:16] [Netty Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[21:15:16] [Netty Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[21:15:16] [Netty Server IO #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[21:15:16] [Server thread/INFO]: Shreyas008 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Byte, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$4 (Anonymous), Packet ID: 47}
Actual Error: 
[21:15:17] [Server thread/INFO]: Shreyas008 left the game

### Bug Description

Getting that error when joining a 1.17 server on a 1.8 client

### Steps to Reproduce

1. Log into a 1.17 server with ViaVersion, Backwards & Rewind
2. You should get disconnected a few seconds after joining on a 1.8 client 

### Expected Behavior

Not get disconnected

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by KennyTV** [comment]
Your ViaRewind is outdated.
