### ISSUE TITLE
Issue with players trying to join a 1.17 server with all versions under

### ISSUE THREAD

**Issue by MiniKLK** [ViaVersion/ViaVersion#2594]
### `/viaversion dump` Output

https://dump.viaversion.com/1cd87d28e57d1340ca4ea0d53bd10f17a4df8aba924dca7a8d1ab11989ca7cd8

### Console Error

```
02.07 14:39:46 [Server] Server thread/WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
02.07 14:39:46 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
02.07 14:39:46 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
02.07 14:39:46 [Server] Server thread/WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
02.07 14:39:46 [Server] Server thread/WARN at java.base/java.lang.Class.forName0(Native Method)
02.07 14:39:46 [Server] Server thread/WARN at java.base/java.lang.Class.forName(Class.java:375)
02.07 14:39:46 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.getNewNBTTag(NBTReflectionUtil.java:128)
02.07 14:39:46 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.hasKey(NBTReflectionUtil.java:890)
02.07 14:39:46 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTCompound.hasKey(NBTCompound.java:138)
02.07 14:39:46 [Server] Server thread/WARN at com.massivecraft.factions.boosters.struct.BoosterManager.isBoosterItem(BoosterManager.java:82)
02.07 14:39:46 [Server] Server thread/WARN at com.massivecraft.factions.boosters.listener.RedemptionListener.onPlayerInteract(RedemptionListener.java:40)
02.07 14:39:46 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02.07 14:39:46 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
02.07 14:39:46 [Server] Server thread/WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.07 14:39:46 [Server] Server thread/WARN at java.base/java.lang.reflect.Method.invoke(Method.java:567)
02.07 14:39:46 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
02.07 14:39:46 [Server] Server thread/WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
02.07 14:39:46 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
02.07 14:39:46 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
02.07 14:39:46 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499)
02.07 14:39:46 [Server] Server thread/WARN at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:485)
02.07 14:39:46 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1540)
02.07 14:39:46 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
02.07 14:39:46 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
02.07 14:39:46 [Server] Server thread/WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
02.07 14:39:46 [Server] Server thread/WARN at net.minecraft.server.TickTask.run(SourceFile:18)
02.07 14:39:46 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
02.07 14:39:46 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
02.07 14:39:46 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
02.07 14:39:47 [Multicraft] Skipped 184 lines due to rate limit (30/s)
02.07 14:39:47 [Server] Server thread/INFO Error in ItemNBTAPI!(Outdated plugin?)
02.07 14:39:47 [Server] Server thread/WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
02.07 14:39:47 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
02.07 14:39:47 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
02.07 14:39:47 [Server] Server thread/WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
02.07 14:39:47 [Server] Server thread/WARN at java.base/java.lang.Class.forName0(Native Method)
02.07 14:39:47 [Server] Server thread/WARN at java.base/java.lang.Class.forName(Class.java:375)
02.07 14:39:47 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.getNewNBTTag(NBTReflectionUtil.java:128)
02.07 14:39:47 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.hasKey(NBTReflectionUtil.java:890)
02.07 14:39:47 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTCompound.hasKey(NBTCompound.java:138)
02.07 14:39:47 [Server] Server thread/WARN at com.massivecraft.factions.boosters.struct.BoosterManager.isBoosterItem(BoosterManager.java:82)
02.07 14:39:47 [Server] Server thread/WARN at com.massivecraft.factions.boosters.listener.RedemptionListener.onPlayerInteract(RedemptionListener.java:40)
02.07 14:39:47 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02.07 14:39:47 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
02.07 14:39:47 [Server] Server thread/WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.07 14:39:47 [Server] Server thread/WARN at java.base/java.lang.reflect.Method.invoke(Method.java:567)
02.07 14:39:47 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
02.07 14:39:47 [Server] Server thread/WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
02.07 14:39:47 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
02.07 14:39:47 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
02.07 14:39:47 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499)
02.07 14:39:47 [Server] Server thread/WARN at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:485)
02.07 14:39:47 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1540)
02.07 14:39:47 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
02.07 14:39:47 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
02.07 14:39:47 [Server] Server thread/WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
02.07 14:39:47 [Server] Server thread/WARN at net.minecraft.server.TickTask.run(SourceFile:18)
02.07 14:39:47 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
02.07 14:39:47 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
02.07 14:39:47 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
02.07 14:39:49 [Multicraft] Skipped 184 lines due to rate limit (30/s)
02.07 14:39:49 [Server] Server thread/INFO Error in ItemNBTAPI!(Outdated plugin?)
02.07 14:39:49 [Server] Server thread/WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
02.07 14:39:49 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
02.07 14:39:49 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
02.07 14:39:49 [Server] Server thread/WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
02.07 14:39:49 [Server] Server thread/WARN at java.base/java.lang.Class.forName0(Native Method)
02.07 14:39:49 [Server] Server thread/WARN at java.base/java.lang.Class.forName(Class.java:375)
02.07 14:39:49 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.getNewNBTTag(NBTReflectionUtil.java:128)
02.07 14:39:49 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.hasKey(NBTReflectionUtil.java:890)
02.07 14:39:49 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTCompound.hasKey(NBTCompound.java:138)
02.07 14:39:49 [Server] Server thread/WARN at com.massivecraft.factions.boosters.struct.BoosterManager.isBoosterItem(BoosterManager.java:82)
02.07 14:39:49 [Server] Server thread/WARN at com.massivecraft.factions.boosters.listener.RedemptionListener.onPlayerInteract(RedemptionListener.java:40)
02.07 14:39:49 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02.07 14:39:49 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
02.07 14:39:49 [Server] Server thread/WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.07 14:39:49 [Server] Server thread/WARN at java.base/java.lang.reflect.Method.invoke(Method.java:567)
02.07 14:39:49 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
02.07 14:39:49 [Server] Server thread/WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
02.07 14:39:49 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
02.07 14:39:49 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
02.07 14:39:49 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499)
02.07 14:39:49 [Server] Server thread/WARN at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:485)
02.07 14:39:49 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1540)
02.07 14:39:49 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
02.07 14:39:49 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
02.07 14:39:49 [Server] Server thread/WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
02.07 14:39:49 [Server] Server thread/WARN at net.minecraft.server.TickTask.run(SourceFile:18)
02.07 14:39:49 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
02.07 14:39:49 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
02.07 14:39:49 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
02.07 14:39:50 [Multicraft] Skipped 291 lines due to rate limit (30/s)
02.07 14:39:50 [Server] Server thread/INFO Error in ItemNBTAPI!(Outdated plugin?)
02.07 14:39:50 [Server] Server thread/WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
02.07 14:39:50 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
02.07 14:39:50 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
02.07 14:39:50 [Server] Server thread/WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
02.07 14:39:50 [Server] Server thread/WARN at java.base/java.lang.Class.forName0(Native Method)
02.07 14:39:50 [Server] Server thread/WARN at java.base/java.lang.Class.forName(Class.java:375)
02.07 14:39:50 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.getNewNBTTag(NBTReflectionUtil.java:128)
02.07 14:39:50 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.hasKey(NBTReflectionUtil.java:890)
02.07 14:39:50 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTCompound.hasKey(NBTCompound.java:138)
02.07 14:39:50 [Server] Server thread/WARN at com.massivecraft.factions.boosters.struct.BoosterManager.isBoosterItem(BoosterManager.java:82)
02.07 14:39:50 [Server] Server thread/WARN at com.massivecraft.factions.boosters.listener.RedemptionListener.onPlayerInteract(RedemptionListener.java:40)
02.07 14:39:50 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02.07 14:39:50 [Server] Server thread/WARN at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
02.07 14:39:50 [Server] Server thread/WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.07 14:39:50 [Server] Server thread/WARN at java.base/java.lang.reflect.Method.invoke(Method.java:567)
02.07 14:39:50 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
02.07 14:39:50 [Server] Server thread/WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
02.07 14:39:50 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
02.07 14:39:50 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
02.07 14:39:50 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499)
02.07 14:39:50 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:466)
02.07 14:39:50 [Server] Server thread/WARN at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:187)
02.07 14:39:50 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1479)
02.07 14:39:50 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:34)
02.07 14:39:50 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8)
02.07 14:39:50 [Server] Server thread/WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
02.07 14:39:50 [Server] Server thread/WARN at net.minecraft.server.TickTask.run(SourceFile:18)
02.07 14:39:50 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
02.07 14:39:50 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
02.07 14:39:51 [Multicraft] Skipped 294 lines due to rate limit (30/s)
02.07 14:39:51 [Server] Server thread/INFO Error in ItemNBTAPI!(Outdated plugin?)
02.07 14:39:51 [Server] Server thread/WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
02.07 14:39:51 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
02.07 14:39:51 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
02.07 14:39:51 [Server] Server thread/WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
02.07 14:39:51 [Server] Server thread/WARN at java.base/java.lang.Class.forName0(Native Method)
02.07 14:39:51 [Server] Server thread/WARN at java.base/java.lang.Class.forName(Class.java:375)
02.07 14:39:51 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.getNewNBTTag(NBTReflectionUtil.java:128)
02.07 14:39:51 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.hasKey(NBTReflectionUtil.java:890)
02.07 14:39:51 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTCompound.hasKey(NBTCompound.java:138)
02.07 14:39:51 [Server] Server thread/WARN at com.massivecraft.factions.boosters.struct.BoosterManager.isBoosterItem(BoosterManager.java:82)
02.07 14:39:51 [Server] Server thread/WARN at com.massivecraft.factions.boosters.listener.RedemptionListener.onPlayerInteract(RedemptionListener.java:40)
02.07 14:39:51 [Server] Server thread/WARN at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
02.07 14:39:51 [Server] Server thread/WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.07 14:39:51 [Server] Server thread/WARN at java.base/java.lang.reflect.Method.invoke(Method.java:567)
02.07 14:39:51 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
02.07 14:39:51 [Server] Server thread/WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
02.07 14:39:51 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
02.07 14:39:51 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
02.07 14:39:51 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499)
02.07 14:39:51 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:466)
02.07 14:39:51 [Server] Server thread/WARN at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:187)
02.07 14:39:51 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1479)
02.07 14:39:51 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:34)
02.07 14:39:51 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8)
02.07 14:39:51 [Server] Server thread/WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
02.07 14:39:51 [Server] Server thread/WARN at net.minecraft.server.TickTask.run(SourceFile:18)
02.07 14:39:51 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
02.07 14:39:51 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
02.07 14:39:51 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
02.07 14:39:53 [Multicraft] Skipped 291 lines due to rate limit (30/s)
02.07 14:39:53 [Server] Server thread/INFO Error in ItemNBTAPI!(Outdated plugin?)
02.07 14:39:53 [Server] Server thread/WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
02.07 14:39:53 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142)
02.07 14:39:53 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
02.07 14:39:53 [Server] Server thread/WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
02.07 14:39:53 [Server] Server thread/WARN at java.base/java.lang.Class.forName0(Native Method)
02.07 14:39:53 [Server] Server thread/WARN at java.base/java.lang.Class.forName(Class.java:375)
02.07 14:39:53 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.getNewNBTTag(NBTReflectionUtil.java:128)
02.07 14:39:53 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTReflectionUtil.hasKey(NBTReflectionUtil.java:890)
02.07 14:39:53 [Server] Server thread/WARN at com.massivecraft.factions.zcore.nbtapi.NBTCompound.hasKey(NBTCompound.java:138)
02.07 14:39:53 [Server] Server thread/WARN at com.massivecraft.factions.boosters.struct.BoosterManager.isBoosterItem(BoosterManager.java:82)
02.07 14:39:53 [Server] Server thread/WARN at com.massivecraft.factions.boosters.listener.RedemptionListener.onPlayerInteract(RedemptionListener.java:40)
02.07 14:39:53 [Server] Server thread/WARN at jdk.internal.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
02.07 14:39:53 [Server] Server thread/WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.07 14:39:53 [Server] Server thread/WARN at java.base/java.lang.reflect.Method.invoke(Method.java:567)
02.07 14:39:53 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
02.07 14:39:53 [Server] Server thread/WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
02.07 14:39:53 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
02.07 14:39:53 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
02.07 14:39:53 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:499)
02.07 14:39:53 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:466)
02.07 14:39:53 [Server] Server thread/WARN at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:187)
02.07 14:39:53 [Server] Server thread/WARN at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1479)
02.07 14:39:53 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:34)
02.07 14:39:53 [Server] Server thread/WARN at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(SourceFile:8)
02.07 14:39:53 [Server] Server thread/WARN at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
02.07 14:39:53 [Server] Server thread/WARN at net.minecraft.server.TickTask.run(SourceFile:18)
02.07 14:39:53 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
02.07 14:39:53 [Server] Server thread/WARN at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
02.07 14:39:53 [Server] Server thread/WARN at 
```

### Bug Description

All clients under 1.17 can't enter.
![Captura](https://user-images.githubusercontent.com/86431839/124318048-5e532d80-db78-11eb-8fcc-fa45c896f515.PNG)
![Captura](https://user-images.githubusercontent.com/86431839/124318133-7925a200-db78-11eb-8553-520d49e6efa6.PNG)
![Captura](https://user-images.githubusercontent.com/86431839/124318221-9d817e80-db78-11eb-8e82-72c1b88859d3.PNG)

### Steps to Reproduce

Can't login with any version under 1.17

### Expected Behavior

All clients from 1.7 to 1.17 can connect

### Additional Server Info

I don't have any ItemNBTAPI and anything like some texts appear on console, this are all my plugins, I don't know whats happening... please help. I have good Backwards ViaVersion and ViaRewind versions...

Only 1.17 clients can enter.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3164-Spigot-f773da8-b069f22 (MC: 1.17)](https://img.shields.io/badge/Platform-3164%20Spigot%20f773da8%20b069f22%20%28MC%3A%201.17%29-3498db) <br />![ViaVersion: Even with master](https://img.shields.io/badge/ViaVersion-Even%20with%20master-brightgreen)<br />![ViaRewind: 7 commits behind master](https://img.shields.io/badge/ViaRewind-7%20commit(s)%20behind%20master-yellow)<br />![ViaBackwards: 14 commits behind master](https://img.shields.io/badge/ViaBackwards-14%20commit(s)%20behind%20master-yellow)

**Comment by kennytv** [comment]
That has nothing to do with Via.
