### ISSUE TITLE
I done what you told me, put ViaVersion version good and everything, and still need help with this please...

### ISSUE THREAD

**Issue by MiniKLK** [ViaVersion/ViaVersion#2596]
### `/viaversion dump` Output

https://dump.viaversion.com/984d49b6be0551047800548bb8568ced2436095ab2948ee853e6b7724dd6bf1e

### Console Error

```
02.07 16:43:43 [Server] User Authenticator #1/INFO UUID of player BOBO is 7a2affdd-26a5-3ed2-9778-15e6301c6e07
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN ERROR IN Protocol1_13_1To1_13_2 IN REMAP OF SET_SLOT (0x17)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN {Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN Actual Error: 
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN at java.base/java.lang.Thread.run(Thread.java:831)
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
02.07 16:43:44 [Server] Netty Epoll Server IO #1/WARN {Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
02.07 16:44:02 [Multicraft] Skipped 134 lines due to rate limit (30/s)
02.07 16:44:02 [Server] Server thread/INFO CONSOLE issued server command: /list 
02.07 16:44:02 [Server] Server thread/INFO Hay 0 jugadores de un máximo de 100 jugadores en linea.
02.07 16:44:11 [Server] User Authenticator #2/INFO UUID of player BOBO is 7a2affdd-26a5-3ed2-9778-15e6301c6e07
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN ERROR IN Protocol1_13_1To1_13_2 IN REMAP OF SET_SLOT (0x17)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN {Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN Actual Error: 
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN at java.base/java.lang.Thread.run(Thread.java:831)
02.07 16:44:11 [Server] Netty Epoll Server IO #3/WARN Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
02.07 16:44:12 [Multicraft] Skipped 5392 lines due to rate limit (30/s)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at jdk.internal.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at java.base/java.lang.reflect.Method.invoke(Method.java:567)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
02.07 16:44:12 [Server] Netty Epoll Server IO #3/WARN at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
02.07 16:44:32 [Multicraft] Skipped 290 lines due to rate limit (30/s)
02.07 16:44:32 [Server] Craft Scheduler Thread - 43/INFO Sending 4 analytic events
02.07 16:44:33 [Server] Craft Scheduler Thread - 43/INFO Fetching all due players...
02.07 16:44:33 [Server] Craft Scheduler Thread - 43/INFO Fetched due players (0 found).
02.07 16:44:35 [Server] Server thread/INFO CONSOLE issued server command: /list 
02.07 16:44:35 [Server] Server thread/INFO Hay 0 jugadores de un máximo de 100 jugadores en linea.
02.07 16:45:08 [Server] Server thread/INFO CONSOLE issued server command: /list 
02.07 16:45:08 [Server] Server thread/INFO Hay 0 jugadores de un máximo de 100 jugadores en linea.
```

### Bug Description

Any version under 1.17 can enter... I put the errors here.

### Steps to Reproduce

![pal_mini_2](https://user-images.githubusercontent.com/86431839/124326832-6bc3e400-db87-11eb-80ba-ca7fcb5e3811.PNG)
 Always this error on all versions.

### Expected Behavior

All players need to enter on all version, i pay for someone can help me fix, really.... Sorry for being so novice and for ur patience.

### Additional Server Info

![Captura](https://user-images.githubusercontent.com/86431839/124326903-8b5b0c80-db87-11eb-860d-e2daec3d0460.PNG)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3164-Spigot-f773da8-b069f22 (MC: 1.17)](https://img.shields.io/badge/Platform-3164%20Spigot%20f773da8%20b069f22%20%28MC%3A%201.17%29-3498db) <br />![ViaVersion: Even with dev](https://img.shields.io/badge/ViaVersion-Even%20with%20dev-brightgreen)<br />![ViaRewind: 7 commits behind master](https://img.shields.io/badge/ViaRewind-7%20commit(s)%20behind%20master-yellow)<br />![ViaBackwards: 14 commits behind master](https://img.shields.io/badge/ViaBackwards-14%20commit(s)%20behind%20master-yellow)

**Comment by FormallyMyles** [comment]
You can reply to the previous issue, no need to create new issues. We also have a discord for this reason.

You should update your other via plugins as stated in the previous issue.
