### ISSUE TITLE
[ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF SPAWN_PARTICLE (0x24)

### ISSUE THREAD

**Issue by yuankun1** [ViaVersion/ViaVersion#2606]
[14:03:42] [Netty Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF SPAWN_PARTICLE (0x24)
[14:03:42] [Netty Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[14:03:42] [Netty Server IO #1/WARN]: {Type: Float, Data: [Pair{Type|Integer, 15}, Pair{Type|Boolean, true}, Pair{Type|Double, -594.0}, Pair{Type|Double, 65.0}, Pair{Type|Double, -146.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 1}, Pair{Type|Float, 0.78431374}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 1.0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$3 (Anonymous), Packet ID: 34}
[14:03:42] [Netty Server IO #1/WARN]: Actual Error: 
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[14:03:42] [Netty Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[14:03:42] [Netty Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:03:42] [Netty Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:03:42] [Netty Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[14:03:42] [Netty Server IO #1/WARN]: {Type: Float, Data: [Pair{Type|Integer, 15}, Pair{Type|Boolean, true}, Pair{Type|Double, -594.0}, Pair{Type|Double, 65.0}, Pair{Type|Double, -146.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 1}, Pair{Type|Float, 0.78431374}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.0}, Pair{Type|Float, 1.0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$3 (Anonymous), Packet ID: 34}
[14:03:42] [Netty Server IO #1/WARN]: Actual Error: 
[14:03:42] [Netty Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(66) + length(4) exceeds writerIndex(66): PooledUnsafeDirectByteBuf(ridx: 66, widx: 66, cap: 256)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.readFloat(AbstractByteBuf.java:856)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.api.type.types.FloatType.read(FloatType.java:49)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.api.type.types.FloatType.read(FloatType.java:29)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$3.lambda$registerMap$0(BlockItemPackets1_17.java:119)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[14:03:42] [Netty Server IO #1/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
[14:03:42] [Netty Server IO #1/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:03:42] [Netty Server IO #1/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[14:03:42] [Netty Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[14:03:42] [Netty Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[14:03:42] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[14:03:42] [Netty Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:03:42] [Netty Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Barvalg** [comment]
![Platform: git-Paper-79 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Paper--79%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1-1.17.1-rc2-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.0.1--1.17.1--rc2--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.0): 14 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.0)-14%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by yuankun1** [comment]
1.In 1.17server enclosure
2.Use 1.16.5 customer service to enter the circled territory
More Residence plug-in conflicts

**Comment by kennytv** [comment]
Update ViaBackwards.

**Comment by yuankun1** [comment]
> 向后更新。

It's already via backs. 4.0.0

**Comment by kennytv** [comment]
https://ci.viaversion.com/view/ViaBackwards/
