### ISSUE TITLE
WARN: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00 ->0x00

### ISSUE THREAD

**Issue by ReSlay** [ViaVersion/ViaVersion#2612]
### `/viaversion dump` Output

https://dump.viaversion.com/34bea2a91def8da52d9ac33e207bc29eddcdc4ebeebff625674e7d9903a3cfc5

### Console Error

```
[22:36:35] [Server thread/INFO]: Done (16,773s)! For help, type "help" or "?"
[22:36:35] [Server thread/INFO]: Timings Reset
[22:36:35] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.12.2 (340)
[22:36:35] [Server thread/WARN]: [ViaVersion] This version of Minecraft is extremely outdated and support for it has reached its end of life. You will still be able to run Via on this Minecraft version, but we are unlikely to provide any further fixes or help with problems specific to legacy Minecraft versions. Please consider updating to give your players a better experience and to avoid issues that have long been fixed.
[22:36:35] [Server thread/WARN]: [ViaVersion] You are running an outdated Java version, please consider updating it to at least Java 16 (your version is 1.8.0_251). At some point in the future, ViaVersion will no longer be compatible with this version of Java.
[22:36:36] [Server thread/INFO]: 
[22:36:36] [Server thread/INFO]: ------------ AdvancedNMotd Updater ----------
[22:36:36] [Server thread/INFO]: You have the latest version of AdvancedNMotd!
[22:36:36] [Server thread/INFO]: Current version: 9.2.0 for every 1.8+ server!
[22:36:36] [Server thread/INFO]: ---------------------------------------------
[22:36:36] [Server thread/INFO]: 
[22:36:36] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[22:36:36] [Server thread/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[22:36:36] [Server thread/INFO]: No expansions were registered!
[22:40:44] [Netty Server IO #1/ERROR]: java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.ServerPing$Serializer.a(Lnet/minecraft/server/v1_12_R1/ServerPing;Ljava/lang/reflect/Type;Lcom/google/gson/JsonSerializationContext;)Lcom/google/gson/JsonElement;
[22:40:44] [Netty Server IO #1/WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[22:40:44] [Netty Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[22:40:44] [Netty Server IO #1/WARN]: {Type: String, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$1 (Anonymous), Packet ID: 0}
[22:40:44] [Netty Server IO #1/WARN]: Actual Error: 
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[22:40:44] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:275)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[22:40:44] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[22:40:44] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:201)
[22:40:44] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157)
[22:40:44] [Netty Server IO #1/WARN]: 	at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:109)
[22:40:44] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.PacketStatusListener.a(PacketStatusListener.java:131)
[22:40:44] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:23)
[22:40:44] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:8)
[22:40:44] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:140)
[22:40:44] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:370)
[22:40:44] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:31)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[22:40:44] [Netty Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[22:40:44] [Netty Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.LegacyPingHandler.channelRead(LegacyPingHandler.java:121)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
[22:40:44] [Netty Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[22:40:44] [Netty Server IO #1/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

### Bug Description

It sends me an error message that I tried to fix, and it is from blocked versions from what I saw right, blocked versions before auto plug-in change is this:
https://i.imgur.com/dCycZaZ.png

However, later after starting the server, it automatically sets something this
(All when the game refreshes the server list):
https://i.imgur.com/NF5cw11.png

### Steps to Reproduce

1. Download the latest version 1.12.2.
2. Upload to server.
3. Start the server and transfer the latest ViaVersion to the server files.
4. After starting the server, enter the ViaVersion file configuration, then lock it in the same way as I do with other versions of the game. (Block version: 1.17x, 1.11x, 1.10x, 1.9x, 1.8x, 1.7x): https://i.imgur.com/EnhMZBH.png
5. After rewriting the blocked versions of the game, save the file, then turn off the server and turn it on again.
6. Once the server is up, refresh the server list in the game, once you've done it, the error should show the same as me.

I forgot to add in point 5 that the plugin will set the blocked versions by itself, not in the way I set it, but it will set it according to itself and thus I guess that the server crashes.

Sorry for my english, i'm from polish.

### Expected Behavior

I expected that after locking the version data (according to the generator that is available from you) everything will work properly, but after uploading all this and refreshing the server list, suddenly this big error appears, which I showed in one of the screenshots.

### Additional Server Info

I am creating a setup for the lobby that will not have many plugins, and currently only has the following:
https://i.imgur.com/d4eYyXP.png

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-1618 (MC: 1.12.2)](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
I can't reproduce the issue. Can you try without other plugins (and once just without consolespamfixer)?

The auto-change from `block-protocols: [...]` to the expanded list is fine, both represent the same exact value.

**Comment by FormallyMyles** [comment]
See above, with more information we'll be happy to investigate.
