### ISSUE TITLE
kicks when trying to join from lower than 1.16

### ISSUE THREAD

**Issue by DragonWizard975** [ViaVersion/ViaVersion#2613]
### `/viaversion dump` Output

https://dump.viaversion.com/5e164128ab240eb907be89d8969e270eba1f6ed0e5d2fc9e18f8d0662952d65d

### Console Error

```
Put the paste.gg link or text here.
```
{Type: Byte, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$4 (Anonymous), Packet ID: 47}
Actual Error: 
[08:13:03 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[08:13:03 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[08:13:03 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[08:13:03 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[08:13:03 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[08:13:03 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[08:13:03 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[08:13:03 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[08:13:03 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08:13:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[08:13:03 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[08:13:03 WARN]: {Type: Byte, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$4 (Anonymous), Packet ID: 47}
[08:13:03 WARN]: Actual Error: 
[08:13:03 WARN]: Caused by: java.io.IOException: Unable to read type Byte, found Unsigned Byte
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[08:13:03 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47)
[08:13:03 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[08:13:03 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[08:13:03 INFO]: [DiscordSRV] Player DragonPlaysGames quit with silent quitting permission, not sending a quit message
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[08:13:03 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[08:13:03 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[08:13:03 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[08:13:03 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[08:13:03 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[08:13:03 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[08:13:03 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[08:13:03 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[08:13:03 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[08:13:03 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[08:13:03 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[08:13:03 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[08:13:03 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08:13:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[08:13:03 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[08:13:03 WARN]: {Type: Byte, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$4 (Anonymous), Packet ID: 47}
[08:13:03 WARN]: Actual Error: 
[08:13:03 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[08:13:03 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[08:13:03 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[08:13:03 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[08:13:03 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[08:13:03 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[08:13:03 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[08:13:03 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[08:13:03 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08:13:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[08:13:03 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[08:13:03 WARN]: {Type: Byte, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$4 (Anonymous), Packet ID: 47}
[08:13:03 WARN]: Actual Error: 
[08:13:03 WARN]: Caused by: java.io.IOException: Unable to read type Byte, found Unsigned Byte
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[08:13:03 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47)
[08:13:03 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[08:13:03 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[08:13:03 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[08:13:03 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[08:13:03 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[08:13:03 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[08:13:03 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[08:13:03 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[08:13:03 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[08:13:03 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[08:13:03 WARN]:        at net.minecraft.network.NetworkManager.a(NetworkManager.java:315)
[08:13:03 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$4(NetworkManager.java:295)
[08:13:03 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[08:13:03 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[08:13:03 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[08:13:03 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[08:13:03 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08:13:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

### Bug Description

trying to join on 1.8.8

### Steps to Reproduce

1: try to join with a 1.8.8 client
2: gets disconected

### Expected Behavior

join

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-46 (MC: 1.17)](https://img.shields.io/badge/Platform-git--Paper--46%20%28MC%3A%201.17%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.0): 9 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.0)-9%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by FormallyMyles** [comment]
Update your plugins (ViaRewind)
