### ISSUE TITLE
Server displays "coding" name of entities using HoloMobHealth plugin

### ISSUE THREAD

**Issue by TheJoshue** [ViaVersion/ViaVersion#2620]
### `/viaversion dump` Output

https://dump.viaversion.com/789d4dfdea009e0882c0424761fcf4cea1e2f360d3923a780f92ee8195827e02

### Console Error

```
[16:44:36 ERROR]: [ViaVersion] An error occurred in metadata handler EntityPackets1_13 for untracked entity type: Metadata{id=18, metaType=VillagerData, value=com.viaversion.viaversion.api.minecraft.VillagerData@b41a35}
[16:44:36 ERROR]: [ViaVersion] Full metadata: Metadata{id=0, metaType=Byte, value=0}
Metadata{id=1, metaType=VarInt, value=300}
Metadata{id=2, metaType=String, value={"extra":[{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":""},{"color":"aqua","translate":"entity.minecraft.zombie_villager"},{"color":"white","extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"20.0"},{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":"/20.0"}],"text":": "}],"text":""}],"text":""}}
Metadata{id=3, metaType=Boolean, value=true}
Metadata{id=4, metaType=Boolean, value=false}
Metadata{id=5, metaType=Boolean, value=false}
Metadata{id=6, metaType=Byte, value=0}
Metadata{id=7, metaType=Float, value=20.0}
Metadata{id=8, metaType=VarInt, value=0}
Metadata{id=9, metaType=Boolean, value=false}
Metadata{id=10, metaType=VarInt, value=0}
Metadata{id=11, metaType=VarInt, value=0}
Metadata{id=12, metaType=OptPosition, value=null}
Metadata{id=13, metaType=Byte, value=0}
Metadata{id=14, metaType=Boolean, value=false}
Metadata{id=15, metaType=VarInt, value=0}
Metadata{id=16, metaType=Boolean, value=false}
Metadata{id=17, metaType=Boolean, value=false}
Metadata{id=18, metaType=VillagerData, value=com.viaversion.viaversion.api.minecraft.VillagerData@b41a35}
[16:44:36 WARN]: java.lang.ArrayIndexOutOfBoundsException: 15
[16:44:36 WARN]:        at com.viaversion.viaversion.api.minecraft.metadata.types.MetaType1_12.byId(MetaType1_12.java:53)
[16:44:36 WARN]:        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.EntityPackets1_13.lambda$registerRewrites$1(EntityPackets1_13.java:327)
[16:44:36 WARN]:        at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:118)
[16:44:36 WARN]:        at com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.handleMetadata(EntityRewriterBase.java:67)
[16:44:36 WARN]:        at com.viaversion.viabackwards.api.rewriters.LegacyEntityRewriter$3.lambda$registerMap$0(LegacyEntityRewriter.java:106)
[16:44:36 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[16:44:36 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[16:44:36 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[16:44:36 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[16:44:36 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[16:44:36 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[16:44:36 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[16:44:36 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[16:44:36 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[16:44:36 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[16:44:36 WARN]:        at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
[16:44:36 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:44:36 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[16:44:36 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[16:44:36 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[16:44:36 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[16:44:36 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:44:36 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[16:44:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:44:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[16:44:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[16:44:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[16:44:36 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[16:44:36 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[16:44:36 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[16:44:36 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:44:36 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:323)
[16:44:36 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[16:44:36 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[16:44:36 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[16:44:36 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[16:44:36 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[16:44:36 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:44:36 WARN]:        at java.lang.Thread.run(Unknown Source)
```

### Bug Description

Server displays "coding" name of entities using HoloMobHealth plugin.

### Steps to Reproduce

1. Join server
2. Summon/Find any mob entity
3. See error

### Expected Behavior

Show name of mob entity and not "coding" name of it... for example for chicken "Chicken"

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-584 (MC: 1.16.5)](https://img.shields.io/badge/Platform-git--Paper--584%20%28MC%3A%201.16.5%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 2 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
The plugin is sending metadata packets for untracked entities. Mitigated it anyways with https://github.com/ViaVersion/ViaBackwards/commit/fa707e5391c60cd878830c2f8e3730219c037bde

**Comment by LOOHP** [comment]
The proper way to send virtual entities that go through ViaBackwards correctly is to send the packets on the main thread?

**Comment by kennytv** [comment]
Either that or you have to synchronize somewhere else to make sure you don't send metadata after an entity has been removed (or not yet spawned?)... but since the Vanilla client just ignores floating metadata packets, ViaBackwards does now, too.

**Comment by LOOHP** [comment]
I see. However, even metadata packets sent after the entity spawn packet is sent doesn't have the translatable parts of the customname translated from 1.13+ -> 1.12-

**Comment by kennytv** [comment]
That's entirely separate, being missing translation mappings in ViaBackwards, tracked somewhere on its issue tracker.
