### ISSUE TITLE
ViaVersion and ViaBackward Error Velocity 1.16 - 1.8

### ISSUE THREAD

**Issue by vSKAH** [ViaVersion/ViaVersion#2629]
### `/viaversion dump` Output

https://dump.viaversion.com/7c516d4f1d4a7b7210b2e62356e85c512a340ec9ba84cb8ea596d3852d807f36

### Console Error

`Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: String, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
Caused by: java.lang.IllegalArgumentException: Cannot receive string longer than Short.MAX_VALUE * 3 bytes (got 116744257 bytes)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:164) ~[velocity.jar:3.0.0]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:50) ~[?:?]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:171) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:219) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:142) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity.jar:3.0.0]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.0.0]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[velocity.jar:3.0.0]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[velocity.jar:3.0.0]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity.jar:3.0.0]`

### Bug Description

Connect to target server

### Steps to Reproduce

Login with 1.16.5 client ???

### Expected Behavior

Player don't send / connect

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried a build from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3.0.0](https://img.shields.io/badge/Platform-3.0.0-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 5 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-5%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 2 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by vSKAH** [comment]
Same problem with all plugins updated on my velocity proxy.
https://dump.viaversion.com/1aee788f6d9c8900a3b95c837dd07810b0527426a5a78faba4473492c422053c

> Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: String, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
Caused by: java.lang.IllegalArgumentException: Cannot receive string longer than Short.MAX_VALUE * 3 bytes (got 1387189 bytes)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:164) ~[velocity.jar:3.0.0]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:50) ~[?:?]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:125) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:171) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:219) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:142) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity.jar:3.0.0]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.0.0]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.0.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.0.0]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.0.0]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[velocity.jar:3.0.0]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[velocity.jar:3.0.0]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity.jar:3.0.0]
        ... 4 more

**Comment by Barvalg** [comment]
![Platform: 3.0.0](https://img.shields.io/badge/Platform-3.0.0-3498db?style=flat-square) <br />![ViaVersion (4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaRewind(2.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)<br />![ViaBackwards(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square)

**Comment by vSKAH** [comment]
After more tests I come up with the following information.
I have tried putting in different versions of Velocity and the Via plugin but even with older versions the problem persists.

I also tried to connect with different versions of Minecraft.
 - In 1.8.X I can connect ✅
 - In 1.9.X I can connect ✅
 - In 1.12.X I can connect ✅
 - In 1.15.X I can connect  ✅
 - In 1.16.X I can't connect and the error is displayed in console ❌

**Comment by Jo0001** [comment]
![works](https://user-images.githubusercontent.com/47455182/126159177-c1a8a217-4d0d-4b8e-b787-76f072cd66cb.PNG)
Works fine for me (with velocity default config )

**Comment by vSKAH** [comment]
i will test only with via plugins and luckperms

**Comment by vSKAH** [comment]
I have reset my config and it's done ! Thank you
