### ISSUE TITLE
Users get kicked out when joining

### ISSUE THREAD

**Issue by EsissDev** [ViaVersion/ViaVersion#2639]
### `/viaversion dump` Output

https://dump.viaversion.com/8057da2f9aac4d4458f39a2999f59f558042e50e11b3e31830899e5196729dea

### Console Error

[18:20:15 WARN]: {Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
[18:20:15 WARN]: Actual Error: 
[18:20:15 WARN]: Caused by: java.io.IOException: Unable to read type Byte, found Unsigned Byte
[18:20:15 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[18:20:15 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47)
[18:20:15 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[18:20:15 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[18:20:15 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[18:20:15 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[18:20:15 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[18:20:15 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[18:20:15 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[18:20:15 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[18:20:15 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[18:20:15 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[18:20:15 WARN]:        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
[18:20:15 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:20:15 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[18:20:15 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:529)
[18:20:15 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:71)
[18:20:15 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:269)
[18:20:15 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[18:20:15 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:275)
[18:20:15 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:20:15 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[18:20:15 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[18:20:15 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[18:20:15 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[18:20:15 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[18:20:15 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[18:20:15 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[18:20:15 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.lambda$b$6(NetworkManager.java:305)
[18:20:15 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352)
[18:20:15 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[18:20:15 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[18:20:15 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[18:20:15 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[18:20:15 WARN]:        at java.lang.Thread.run(Thread.java:748)
[18:20:15 INFO]: Thiagizorri[/190.1.16.173:60776] logged in with entity id 101 at ([world]0.5767160739340601, 65.0, 0.43650491230068633)
[18:20:15 INFO]: Thiagizorri lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}

### Bug Description

This happens when a user joins, doesn't happen always but most of the time

### Steps to Reproduce

1. Login to the lobby
2. . Gets kicked out

### Expected Behavior

User join normally

### Additional Server Info

only happens in the lobby, i have geyser and floodgate

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Paper-391 (MC: 1.16.4)](https://img.shields.io/badge/Platform-git--Paper--391%20%28MC%3A%201.16.4%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)
