### ISSUE TITLE
Bug on Join.

### ISSUE THREAD

**Issue by Mihguel** [ViaVersion/ViaVersion#2644]
### `/viaversion dump` Output

https://dump.viaversion.com/60b79e1cc957cb59fd23acbf8185c52424aff9e26a969bd0a8c813ca0e74cd79

### Console Error

```

[23:55:09 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException
[23:55:09 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[23:55:09 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[23:55:09 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[23:55:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[23:55:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[23:55:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[23:55:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[23:55:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[23:55:09 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[23:55:09 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[23:55:09 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[23:55:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[23:55:09 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[23:55:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[23:55:09 WARN]:        at java.lang.Thread.run(Thread.java:748)
[23:55:09 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[23:55:09 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException
```

### Bug Description

On Join

### Steps to Reproduce

on join

### Expected Behavior

on join

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)](https://img.shields.io/badge/Platform-git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by Camotoy** [comment]
> I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

Please re-try with the latest version from the CI and if it still persists please reopen the issue with a new dump. Thank you!
