### ISSUE TITLE
 [20:47:01 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException [20:47:01 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template {Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.SpawnPackets$5 (Anonymous)}

### ISSUE THREAD

**Issue by Mihguel** [ViaVersion/ViaVersion#2671]
### `/viaversion dump` Output

 https://dump.viaversion.com/bc79ada170b53b05d689b2c9d12847db97a29831d5a746eda8e05155b8de7f56

### Console Error

[20:47:01 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException
[20:47:01 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.SpawnPackets$5 (Anonymous)}

### Bug Description

[20:47:01 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException
[20:47:01 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.SpawnPackets$5 (Anonymous)}

### Steps to Reproduce

Login with 1.17.1

On join, kick

### Expected Behavior

join

### Additional Server Info

 
[20:47:01 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException
[20:47:01 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.SpawnPackets$5 (Anonymous)}
Actual Error: 
[20:47:01 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[20:47:01 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:47:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[20:47:01 WARN]:        at de.raffi.pluginlib.data.PacketHandler.write(PacketHandler.java:25)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[20:47:01 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[20:47:01 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:47:01 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[20:47:01 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[20:47:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[20:47:01 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[20:47:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[20:47:01 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:47:01 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.SpawnPackets$5 (Anonymous)}
Actual Error: 
[20:47:01 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException
[20:47:01 WARN]: [ViaVersion] ERROR IN Protocol1_9To1_8 IN REMAP OF ENTITY_METADATA (0x1C)
[20:47:01 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:47:01 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[20:47:01 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:47:01 INFO]: Sr_Klemba lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.SpawnPackets$5 (Anonymous)}
Actual Error: 
[20:47:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[20:47:01 WARN]:        at de.raffi.pluginlib.data.PacketHandler.write(PacketHandler.java:25)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[20:47:01 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[20:47:01 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:47:01 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[20:47:01 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[20:47:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[20:47:01 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[20:47:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[20:47:01 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:47:01 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:47:01 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException
[20:47:01 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:47:01 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[20:47:01 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[20:47:01 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[20:47:01 WARN]:        at de.raffi.pluginlib.data.PacketHandler.write(PacketHandler.java:25)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[20:47:01 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[20:47:01 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[20:47:01 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:47:01 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[20:47:01 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[20:47:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[20:47:01 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[20:47:01 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[20:47:01 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:47:01 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}
Actual Error: 
[20:47:01 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException
[20:47:01 WARN]: [ViaVersion] ERROR IN Protocol1_9To1_8 IN REMAP OF ENTITY_METADATA (0x1C)
[20:47:01 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)}

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Spigot-db6de12-18fbb24 (MC: 1.8.8)](https://img.shields.io/badge/Platform-git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 18 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-18%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaBackwards(4.0.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by kennytv** [comment]
Likely another plugin sending bad metadata.
