### ISSUE TITLE
[Error] Bad type on operand stack

### ISSUE THREAD

**Issue by joex92** [ViaVersion/ViaVersion#2685]
### `/viaversion dump` Output

https://dump.viaversion.com/23efa92d240ccf49d7f6e0fda54a2dcfe01ed90d78bdb47c3ae4f05bfacf4a19

### Console Error

```
[22:42:49 INFO]: [ViaVersion] Loading ViaVersion v4.0.1
[22:42:50 ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] Bad type on operand stack
Exception Details:
  Location:
    com/viaversion/viaversion/classgenerator/generated/ProtocolSupportConnectListener.onPacketReceiving(Lprotocolsupport/api/Connection$PacketListener$PacketEvent;)V @22: istore_3
  Reason:
    Type 'net/minecraft/network/EnumProtocol' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @22
    flags: { }
    locals: { 'com/viaversion/viaversion/classgenerator/generated/ProtocolSupportConnectListener', 'protocolsupport/api/Connection$PacketListener$PacketEvent', 'net/minecraft/network/protocol/handshake/PacketHandshakingInSetProtocol' }
    stack: { 'net/minecraft/network/EnumProtocol' }
  Bytecode:
    0000000: 2bb6 001a c100 1c99 003e 2bb6 001a c000
    0000010: 1c4d 2cb6 0020 3e2a b400 11b6 0026 b200
    0000020: 2ca6 0014 1db8 0032 b900 3801 00b9 003e
    0000030: 0100 9f00 06a7 0010 2ab4 0011 b200 44b8
    0000040: 0048 b600 4e2a b400 112a b600 52b1     
  Stackmap Table:
    append_frame(@53,Object[#28],Integer)
    same_frame(@56)
    chop_frame(@69,2)
 initializing ViaVersion v4.0.1 (Is it up to date?)
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/viaversion/viaversion/classgenerator/generated/ProtocolSupportConnectListener.onPacketReceiving(Lprotocolsupport/api/Connection$PacketListener$PacketEvent;)V @22: istore_3
  Reason:
    Type 'net/minecraft/network/EnumProtocol' (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @22
    flags: { }
    locals: { 'com/viaversion/viaversion/classgenerator/generated/ProtocolSupportConnectListener', 'protocolsupport/api/Connection$PacketListener$PacketEvent', 'net/minecraft/network/protocol/handshake/PacketHandshakingInSetProtocol' }
    stack: { 'net/minecraft/network/EnumProtocol' }
  Bytecode:
    0000000: 2bb6 001a c100 1c99 003e 2bb6 001a c000
    0000010: 1c4d 2cb6 0020 3e2a b400 11b6 0026 b200
    0000020: 2ca6 0014 1db8 0032 b900 3801 00b9 003e
    0000030: 0100 9f00 06a7 0010 2ab4 0011 b200 44b8
    0000040: 0048 b600 4e2a b400 112a b600 52b1     
  Stackmap Table:
    append_frame(@53,Object[#28],Integer)
    same_frame(@56)
    chop_frame(@69,2)

        at java.lang.ClassLoader.defineClass0(Native Method) ~[?:?]
        at java.lang.System$2.defineClass(System.java:2193) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2446) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup$ClassDefiner.defineClass(MethodHandles.java:2423) ~[?:?]
        at java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:1850) ~[?:?]
        at com.viaversion.viaversion.libs.javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:295) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viaversion.libs.javassist.ClassPool.toClass(ClassPool.java:1158) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viaversion.libs.javassist.CtClass.toClass(CtClass.java:1325) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viaversion.bukkit.classgenerator.ClassGenerator.toClass(ClassGenerator.java:321) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viaversion.bukkit.classgenerator.ClassGenerator.makePSConnectListener(ClassGenerator.java:246) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viaversion.bukkit.classgenerator.ClassGenerator.generate(ClassGenerator.java:78) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:126) ~[ViaVersion-4.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:416) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1216) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1385]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[22:42:50 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v1.4.3-SNAPSHOT
[22:42:50 INFO]: [ViaBackwards] Loading ViaBackwards v4.0.1
[22:42:50 INFO]: [ViaBackwards] Loading translations...
[22:42:50 INFO]: [ViaBackwards] Loading 1.10 -> 1.9.4 mappings...
[22:42:50 INFO]: [ViaBackwards] Loading 1.11 -> 1.10 mappings...
[22:42:50 ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] Cannot invoke "java.util.concurrent.CompletableFuture.whenCompleteAsync(java.util.function.BiConsumer, java.util.concurrent.Executor)" because the return value of "com.viaversion.viaversion.protocol.ProtocolManagerImpl.getMappingLoaderFuture(java.lang.Class)" is null initializing ViaBackwards v4.0.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CompletableFuture.whenCompleteAsync(java.util.function.BiConsumer, java.util.concurrent.Executor)" because the return value of "com.viaversion.viaversion.protocol.ProtocolManagerImpl.getMappingLoaderFuture(java.lang.Class)" is null
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.addMappingLoaderFuture(ProtocolManagerImpl.java:434) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viabackwards.api.BackwardsProtocol.executeAsyncAfterLoaded(BackwardsProtocol.java:44) ~[ViaBackwards-4.0.1.jar:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.Protocol1_12_2To1_13.registerPackets(Protocol1_12_2To1_13.java:59) ~[ViaBackwards-4.0.1.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:76) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:175) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:169) ~[ViaVersion-4.0.1.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:87) ~[ViaBackwards-4.0.1.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.init(BukkitPlugin.java:48) ~[ViaBackwards-4.0.1.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.onLoad(BukkitPlugin.java:36) ~[ViaBackwards-4.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:416) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1216) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1385]
        at java.lang.Thread.run(Thread.java:831) [?:?]```


### Bug Description

I just updated the plugins and the server to purpur1.17.1 from paper1.16.5

### Steps to Reproduce

Update a 1.16.5 server to 1.17.1

### Expected Behavior

run normally

### Additional Server Info

_No response_

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Purpur-1385 (MC: 1.17.1)](https://img.shields.io/badge/Platform-git--Purpur--1385%20%28MC%3A%201.17.1%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 23 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-23%20commit(s)%20behind%20master-yellow?style=flat-square)<br /> ![PS and ViaBackwards warning](https://img.shields.io/badge/Do%20not%20use%20ProtocolSupport%20and%20ViaBackwards%20together,%20please%20remove%20one%20of%20them-orange?style=flat-square)<br />![ViaBackwards(4.0.1): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-12%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind(2.0.1): 11 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square)

**Comment by joex92** [comment]
I just tried with the latest snapshot, and this doesn't happen anymore...

I tested this while creating this issue... so I´m going to close it, so it would be good for other people to find this...
