### ISSUE TITLE
Joining 1.15.2 server on 1.13.1 doesnt work

### ISSUE THREAD

**Issue by notiamb1** [ViaVersion/ViaVersion#2688]
### `/viaversion dump` Output

https://dump.viaversion.com/e10f89eafe60832f8abd6ee3aca9323443faba2a8efec6eb2e0a852942d08069

### Console Error

[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_15_R1.NetworkManager.lambda$4(NetworkManager.java:190)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at java.base/java.lang.Thread.run(Thread.java:834)
[07:08:09] [Netty Epoll Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
Actual Error: 
[07:08:09] [Netty Epoll Server IO #1/WARN]: Caused by: java.io.IOException: Unable to read type Byte, found Unsigned Byte
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_15_R1.NetworkManager.lambda$4(NetworkManager.java:190)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at java.base/java.lang.Thread.run(Thread.java:834)
[07:08:09] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
Actual Error: 
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_15_R1.NetworkManager.lambda$4(NetworkManager.java:190)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at java.base/java.lang.Thread.run(Thread.java:834)
[07:08:09] [Netty Epoll Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
Actual Error: 
[07:08:09] [Netty Epoll Server IO #1/WARN]: Caused by: java.io.IOException: Unable to read type Byte, found Unsigned Byte
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:338)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:117)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:290)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:269)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at net.minecraft.server.v1_15_R1.NetworkManager.lambda$4(NetworkManager.java:190)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[07:08:09] [Netty Epoll Server IO #1/WARN]:     at java.base/java.lang.Thread.run(Thread.java:834)
[07:08:09] [Server thread/INFO]: NotIamb1 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Byte, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_13_1to1_13_2.packets.InventoryPackets1_13_2$1 (Anonymous), Packet ID: 23}
Actual Error: 
[07:08:09] [Server thread/INFO]: NotIamb1 left the game

### Bug Description

Joining on 1.13.1 doesnt work on 1.15.2 servers
![image](https://user-images.githubusercontent.com/90900969/133959757-75655cfa-f14d-4e75-8340-b140ed9fc220.png)

### Steps to Reproduce

1. Login with a 1.13.1 client
2. Connect to a 1.15.2 server that has ViaBackwards
3. when you join it Kicks you out of the server

### Expected Behavior

joining with 1.13.1 on 1.15.2 server doesnt work

### Additional Server Info

I use spigot and some plugins

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git-Spigot-800b93f-8160e29 (MC: 1.15.2)](https://img.shields.io/badge/Platform-git--Spigot--800b93f--8160e29%20%28MC%3A%201.15.2%29-3498db?style=flat-square) <br />![ViaVersion (4.0.1): 26 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-26%20commit(s)%20behind%20master-yellow?style=flat-square)<br />![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square)<br />![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square)
