### ISSUE TITLE
ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)

### ISSUE THREAD

**Issue by CLD9CLD** [ViaVersion/ViaVersion#2727]
### `/viaversion dump` Output

https://dump.viaversion.com/9e032ace957253b3325a45c6b00323f5d99cb8b65f28c1e3d11112a0d9d9240b

### Console Error

```
https://paste.gg/p/anonymous/abae3db057cd40c0b35a76ab3ec7ffe6
```

### Bug Description

error shuts down the server

### Steps to Reproduce

I don’t know, it happens by accident once every 2-3 days.
But once this error appeared when teleporting to another world

### Expected Behavior

not turn off the server

### Additional Server Info

installed  the latest version of SkinsRestorer on BungeeCord server and Spigot
core: kSpigot

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--33d42c8e%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--33d42c8e%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 58 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-58%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by Camotoy** [comment]
Please try with the latest build from https://ci.viaversion.com/job/ViaVersion/ and if the error still persists, please send a new dump from that version.

**Comment by HowardZHY** [comment]
[13:01:52] [Netty Server IO #0/WARN]: [ViaVersion] ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)
[13:01:52] [Netty Server IO #0/WARN]: [ViaVersion] ERROR IN Protocol1_9To1_8 IN REMAP OF MAP_BULK_CHUNK (0x26)
[13:01:52] [Netty Server IO #0/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source 1: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.WorldPackets$5 (Anonymous)}
Actual Error: 
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:01:52] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:219)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:01:52] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:01:52] [Netty Server IO #0/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source 1: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.WorldPackets$5 (Anonymous)}
Actual Error: 
[13:01:52] [Netty Server IO #0/WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 1264
[13:01:52] [Netty Server IO #0/WARN]: 	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.containsKey(Long2ObjectOpenHashMap.java:461)
[13:01:52] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.isChunkLoaded(ChunkProviderServer.java:52)
[13:01:52] [Netty Server IO #0/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.isChunkLoaded(CraftWorld.java:152)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.bukkit.providers.BukkitBlockConnectionProvider.getWorldBlockData(BukkitBlockConnectionProvider.java:41)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.blockconnections.providers.BlockConnectionProvider.getBlockData(BlockConnectionProvider.java:27)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.blockconnections.ConnectionData.updateBlock(ConnectionData.java:154)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.blockconnections.ConnectionData.updateChunkSectionNeighbours(ConnectionData.java:126)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9$1.handle(WorldPackets.java:486)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.constructPacket(PacketWrapperImpl.java:299)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:253)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send(PacketWrapperImpl.java:241)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.packet.PacketWrapper.send(PacketWrapper.java:179)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.WorldPackets$5.lambda$registerMap$0(WorldPackets.java:210)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.classgenerator.generated.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.classgenerator.generated.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[13:01:52] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
[13:01:52] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:01:52] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:531)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:01:52] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:219)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:01:52] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:01:52] [Netty Server IO #0/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source 1: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.WorldPackets$5 (Anonymous)}
Actual Error: 
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:01:52] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:219)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:01:52] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:01:52] [Netty Server IO #0/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source 1: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.WorldPackets$5 (Anonymous)}
Actual Error: 
[13:01:52] [Netty Server IO #0/WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 1264
[13:01:52] [Netty Server IO #0/WARN]: 	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.containsKey(Long2ObjectOpenHashMap.java:461)
[13:01:52] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.isChunkLoaded(ChunkProviderServer.java:52)
[13:01:52] [Netty Server IO #0/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.isChunkLoaded(CraftWorld.java:152)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.bukkit.providers.BukkitBlockConnectionProvider.getWorldBlockData(BukkitBlockConnectionProvider.java:41)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.blockconnections.providers.BlockConnectionProvider.getBlockData(BlockConnectionProvider.java:27)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.blockconnections.ConnectionData.updateBlock(ConnectionData.java:154)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.blockconnections.ConnectionData.updateChunkSectionNeighbours(ConnectionData.java:126)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9$1.handle(WorldPackets.java:486)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.constructPacket(PacketWrapperImpl.java:299)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:253)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send(PacketWrapperImpl.java:241)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.packet.PacketWrapper.send(PacketWrapper.java:179)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.WorldPackets$5.lambda$registerMap$0(WorldPackets.java:210)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.classgenerator.generated.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.viaversion.viaversion.classgenerator.generated.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[13:01:52] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
[13:01:52] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:01:52] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:531)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:01:52] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:219)
[13:01:52] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[13:01:52] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[13:01:52] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:01:52] [Server thread/INFO]: howardzhy lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source 1: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.WorldPackets$5 (Anonymous)}
Actual Error: 
[13:01:52] [Server thread/INFO]: howardzhy left the game
when 1.18.1 (geyser-standalone) player go to NETHER , this could happen
