### ISSUE TITLE
ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x02->0x02

### ISSUE THREAD

**Issue by smokytek** [ViaVersion/ViaVersion#2728]
### `/viaversion dump` Output

https://dump.viaversion.com/810af96820e9321c5c9bc97d267a35f49b4aa43a93e675616b0d9e5a9eb619e7

### Console Error

[16:17:58 WARN] [ViaVersion]: ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x02->0x02
[16:17:58 ERROR]: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[16:17:58 ERROR]: {Type: JsonElement, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$2 (Anonymous), Packet ID: 2}
[16:17:58 ERROR]: Actual Error: 
[16:17:58 ERROR]: Caused by: java.io.IOException: Unable to read type JsonElement, found String
[16:17:58 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140)
[16:17:58 ERROR]:       at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$0(PacketRemapper.java:47)
[16:17:58 ERROR]:       at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[16:17:58 ERROR]:       at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:287)
[16:17:58 ERROR]:       at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.Protocol1_7_6_10TO1_8.transform(Protocol1_7_6_10TO1_8.java:91)
[16:17:58 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:350)
[16:17:58 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.constructPacket(PacketWrapperImpl.java:289)
[16:17:58 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:243)
[16:17:58 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.scheduleSend(PacketWrapperImpl.java:236)
[16:17:58 ERROR]:       at de.gerrygames.viarewind.utils.PacketUtil.sendPacket(PacketUtil.java:44)
[16:17:58 ERROR]:       at de.gerrygames.viarewind.utils.PacketUtil.sendPacket(PacketUtil.java:36)
[16:17:58 ERROR]:       at de.gerrygames.viarewind.utils.PacketUtil.sendPacket(PacketUtil.java:32)
[16:17:58 ERROR]:       at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.sendActionBar(Cooldown.java:140)
[16:17:58 ERROR]:       at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.showCooldown(Cooldown.java:67)
[16:17:58 ERROR]:       at de.gerrygames.viarewind.protocol.protocol1_8to1_9.storage.Cooldown.tick(Cooldown.java:59)
[16:17:58 ERROR]:       at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[16:17:58 ERROR]:       at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[16:17:58 ERROR]:       at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[16:17:58 ERROR]:       at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605)
[16:17:58 ERROR]:       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[16:17:58 ERROR]:       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[16:17:58 ERROR]:       at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[16:17:58 ERROR]:       at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[16:17:58 ERROR]:       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[16:17:58 ERROR]:       at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[16:17:58 ERROR]:       at de.gerrygames.viarewind.utils.Ticker.lambda$null$0(Ticker.java:19)
[16:17:58 ERROR]:       at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)
[16:17:58 ERROR]:       at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5581)
[16:17:58 ERROR]:       at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
[16:17:58 ERROR]:       at de.gerrygames.viarewind.utils.Ticker.lambda$init$1(Ticker.java:15)
[16:17:58 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[16:17:58 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[16:17:58 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[16:17:58 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:829)

### Bug Description

From  nothing it come to console spamming for 3 minutes , ended like it started

### Steps to Reproduce

Waterfall Proxy, Geyser Standalone, servers from 1.8.9 tu 1.17.1 on the same network, viaversion , viabackwards & via rewind on the proxy.
error came only on proxy

### Expected Behavior

I don't understand this error so here i am

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.17--R0.1--SNAPSHOT%3A9d0ca6a%3A451](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.17--R0.1--SNAPSHOT%3A9d0ca6a%3A451-3498db?style=flat-square) </br>![ViaVersion (4.0.1): 58 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.0.1)-58%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.0.1): 18 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.0.1)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.1): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
