### ISSUE TITLE
server crash when summon 1.17 entity nearby player using 1.12.2 client

### ISSUE THREAD

**Issue by BredyAK** [ViaVersion/ViaVersion#2737]
### `/viaversion dump` Output

https://dump.viaversion.com/9bf9dd12a6e467d26b9bc2227c3c9df8c3508feca2013f1931c500586014cebc

### Console Error

```
04:29:31 [INFO] [player_not_exist] <-> ServerConnector [survival-1] has connected
04:29:31 [INFO] [player_not_exist] <-> DownstreamBridge <-> [lobby-1] has disconnected
04:29:32 [WARNING] [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF ENTITY_METADATA (0x4D)
04:29:32 [SEVERE] [player_not_exist] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous)}
Actual Error: 
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57)
	at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:176)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:128)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous)}
Actual Error: 
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.entityNames" is null
	at com.viaversion.viabackwards.api.data.BackwardsMappings.mappedEntityName(BackwardsMappings.java:157)
	at com.viaversion.viabackwards.api.entities.storage.EntityData.mobName(EntityData.java:79)
	at com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.handleMetadata(EntityRewriterBase.java:83)
	at com.viaversion.viaversion.rewriter.EntityRewriter$6.lambda$registerMap$0(EntityRewriter.java:352)
	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
	at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:55)
	at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:31)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57)
	at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:176)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:128)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
04:29:32 [INFO] [player_not_exist] disconnected with: §fEncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to §fhttps://github.com/ViaVersion/ViaVersion/issues§f and follow the issue template
{Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous)}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104
04:29:32 [INFO] [player_not_exist] -> UpstreamBridge has disconnected
04:29:32 [INFO] [player_not_exist] <-> DownstreamBridge <-> [survival-1] has disconnected
```

### Bug Description

player using 1.12.2 client could safely join my server without 1.17 entities nearby (goat, axolotl), but if there are 1.17 entities exist nearby, he will be kicked out with message `EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to §fhttps://github.com/ViaVersion/ViaVersion/issues§f and follow the issue template
{Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous)}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104`

### Steps to Reproduce

install ViaBackwards and ViaVersion on proxy, then join sever with 1.12.2 client, and summon a goat/axolotl, you'll be kicked and could never join again (be kicked again).

### Expected Behavior

fix this error

### Additional Server Info

Java: 17.0.1
Proxy Software: BungeeCord b1611
Server Software: Paper-1.17.1-388

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
You most likely have custom mappings; you need to update them https://github.com/ViaVersion/ViaBackwards/commit/becba6498e4cc066204b69ec4a9dd312d6ae9e0f
