### ISSUE TITLE
When one specific player logs in, after they move, all players are disconnected. 

### ISSUE THREAD

**Issue by slidedrum** [ViaVersion/ViaVersion#2746]
### `/viaversion dump` Output

https://dump.viaversion.com/b3f3cadec4e89209bf6db912bf69552296f49d3a3a60ffaa691c8c0dcd7157bd

### Console Error

I believe this is the relevant part of the log.  If not, full logs of all servers provided below.  
```
[21:21:42] [Netty NIO Worker #3/INFO]: [server connection] NotSlideDrum -> 117 has connected
[21:21:42] [Netty NIO Worker #3/INFO]: [server connection] NotSlideDrum -> lobby has disconnected
[21:21:42] [Netty NIO Worker #3/WARN]: Unknown block entity: waystones:waystone
[21:21:43] [Netty NIO Worker #3/ERROR]: An error occurred in metadata handler EntityPackets for untracked entity type: Metadata{id=11, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@1678acc, value=com.viaversion.viaversion.api.type.types.Particle@1ba14cf8}
[21:21:43] [Netty NIO Worker #3/ERROR]: Full metadata: Metadata{id=0, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@5d94bc60, value=0}
Metadata{id=0, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@4cc3eedc, value=Position{x=1030, y=1792, z=-20963280}}
Metadata{id=2, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@59ddb15c, value=null}
Metadata{id=4, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@77fc3579, value=false}
Metadata{id=5, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@77fc3579, value=false}
Metadata{id=6, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@ff3e3b1, value=0}
Metadata{id=7, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@ff3e1a2, value=0}
Metadata{id=8, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@5c0e8344, value=0.0}
Metadata{id=9, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@ff3e1a2, value=0}
Metadata{id=11, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@1678acc, value=com.viaversion.viaversion.api.type.types.Particle@1ba14cf8}
[21:21:43] [Netty NIO Worker #3/ERROR]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.rewriteParticle(EntityRewriter.java:483)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.EntityPackets.lambda$registerRewrites$0(EntityPackets.java:94)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:119)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter$6.lambda$registerMap$0(EntityRewriter.java:352)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:21:43] [Netty NIO Worker #3/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:21:56] [Netty NIO Worker #3/ERROR]: An error occurred in metadata handler EntityPackets for untracked entity type: Metadata{id=11, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@1678acc, value=com.viaversion.viaversion.api.type.types.Particle@47d20faa}
[21:21:56] [Netty NIO Worker #3/ERROR]: Full metadata: Metadata{id=0, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@5d94bc60, value=0}
Metadata{id=0, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@4cc3eedc, value=Position{x=1030, y=1792, z=-20963280}}
Metadata{id=2, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@59ddb15c, value=null}
Metadata{id=4, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@77fc3579, value=false}
Metadata{id=5, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@77fc3579, value=false}
Metadata{id=6, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@ff3e3b1, value=0}
Metadata{id=7, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@ff3e1a2, value=0}
Metadata{id=8, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@5c0e8344, value=0.0}
Metadata{id=9, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@ff3e1a2, value=0}
Metadata{id=11, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@1678acc, value=com.viaversion.viaversion.api.type.types.Particle@47d20faa}
[21:21:56] [Netty NIO Worker #3/ERROR]: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at java.base/java.util.Objects.checkIndex(Objects.java:359)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.rewriteParticle(EntityRewriter.java:483)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.EntityPackets.lambda$registerRewrites$0(EntityPackets.java:94)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:119)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.rewriter.EntityRewriter$6.lambda$registerMap$0(EntityRewriter.java:352)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:21:56] [Netty NIO Worker #3/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:21:56] [Netty NIO Worker #3/WARN]: ERROR IN Protocol1_18To1_17_1 IN REMAP OF ENTITY_METADATA (0x4D)
[21:21:56] [Netty NIO Worker #3/ERROR]: [server connection] NotSlideDrum -> 117: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@414fbefb
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: ENTITY_METADATA, Type: MetaData List, Data: [Pair{Type|VarInt, 850}], Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous), Packet ID: 77}
Actual Error: 
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.0]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.0]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.0]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity.jar:3.1.0]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.0]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.0]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.1.0]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity.jar:3.1.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[velocity.jar:3.1.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[velocity.jar:3.1.0]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[velocity.jar:3.1.0]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[velocity.jar:3.1.0]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity.jar:3.1.0]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.0]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.1.0]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: ENTITY_METADATA, Type: MetaData List, Data: [Pair{Type|VarInt, 850}], Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$6 (Anonymous), Packet ID: 77}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(8) + length(1) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity.jar:3.1.0]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[velocity.jar:3.1.0]
	at com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:40) ~[?:?]
	at com.viaversion.viaversion.api.type.types.minecraft.ModernMetaType.read(ModernMetaType.java:37) ~[?:?]
	at com.viaversion.viaversion.api.type.types.minecraft.ModernMetaType.read(ModernMetaType.java:30) ~[?:?]
	at com.viaversion.viaversion.api.type.types.minecraft.MetaListType.read(MetaListType.java:46) ~[?:?]
	at com.viaversion.viaversion.api.type.types.minecraft.MetaListType.read(MetaListType.java:33) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.lambda$map$1(PacketRemapper.java:57) ~[?:?]
	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277) ~[?:?]
	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230) ~[?:?]
	at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
	at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.1.0]
	... 29 more
[21:21:56] [Netty NIO Worker #3/INFO]: [server connection] NotSlideDrum -> 117 has disconnected
[21:21:56] [Netty NIO Worker #3/INFO]: [server connection] NotSlideDrum -> lobby has connected
[21:22:01] [Netty NIO Worker #5/INFO]: [connected player] Slidedrum (/18.217.16.82:54630) has connected
[21:22:01] [Netty NIO Worker #5/INFO]: [server connection] Slidedrum -> lobby has connected
[21:22:04] [Netty NIO Worker #5/INFO]: [server connection] Slidedrum -> 117 has connected
[21:22:04] [Netty NIO Worker #5/INFO]: [server connection] Slidedrum -> lobby has disconnected
[21:22:04] [Netty NIO Worker #5/WARN]: Unknown block entity: waystones:waystone
[21:23:43] [Velocity Task Scheduler - #8/INFO]: We've made a dump with useful information, repor
```

### Bug Description

When I join my 1.17 server on a 1.18 client, on my NotSlideDrum account, and then move, it kicks out everyone on 1.18.  Example of my issue here, along with a little more detail.  https://www.youtube.com/watch?v=yEwJM6CNQCU

### Steps to Reproduce

Join 1.17 server with NotSlideDrum account
Move anywhere.

### Expected Behavior

I would expect it to not kick everyone out, like it does on my SlideDrum account.  and probably? all others.  I am not able to test other accounts as I only have these 2.

### Additional Server Info

Here is the [logs.zip](https://github.com/ViaVersion/ViaVersion/files/7638594/logs.zip) for all 4 servers.  All 4 clients are 100% vanilla 1.17.1 and 1.18.  

I am running Velocity-3.1.0-95
Fabric 0.12.8
MC 1.17.1

I feel like there might be more info needed, if so please let me know. I did look to see if anyone else was having similar problems, but I was not able to find anything through google or this issues page.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.0](https://img.shields.io/badge/Platform-velocity%203.1.0-3498db?style=flat-square) </br>![ViaVersion (4.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.1--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.1.0): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.0)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.1): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
