### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by cjd248153** [ViaVersion/ViaVersion#2762]
### `/viaversion dump` Output

https://dump.viaversion.com/77816d6fa0649200db481031b19e4bab730736fb1aa9e36f8e224a7da33efe62

### Console Error

io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: GAME_PROFILE, Type: String, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.0.1.jar:3.0.1]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.0.1.jar:3.0.1]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: GAME_PROFILE, Type: String, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
Caused by: java.lang.IllegalArgumentException: Cannot receive string longer than Short.MAX_VALUE * 3 bytes (got 243794988 bytes)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:164) ~[velocity-3.0.1.jar:3.0.1]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:50) ~[?:?]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:205) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:137) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity-3.0.1.jar:3.0.1]

### Bug Description

I am trying to connect to server with viaversion. I want to be able to connect Bedrock 1.18 to Java 1.17.1 version.

### Steps to Reproduce

1. Login with 1.17.1 Java version.
2. It gives an error and I can't connect to server with either Java or Bedrock.

### Expected Behavior

Should be able to sign in.
I want to be able to connect Bedrock from 1.18 to my Java 1.17.1 server.

### Additional Server Info

I have a Velocity proxy server with 4 other backend servers.
I use Paper and Purpur versions.
1.17.1 Java 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.0.1](https://img.shields.io/badge/Platform-velocity%203.0.1-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
This is most likely a user sending bad data to your server, you can ignore these.
