### ISSUE TITLE
Console / Player Error

### ISSUE THREAD

**Issue by Generzon** [ViaVersion/ViaVersion#2766]
### `/viaversion dump` Output

https://dump.viaversion.com/6b32526e3dcc37465d55a218408f423196024ca4c951a5a378acc39729d8d4cb

### Console Error

[08.12 22:27:58] [Server] [INFO] [Geyser-Spigot] Y0ngz3 (logged in as: Y0ngz3) has connected to the Java server
[08.12 22:27:58] [Server] [INFO] UUID of player _Y0ngz3 is 00000000-0000-0000-0009-01f5cc3e5188
[08.12 22:27:58] [Server] [INFO] [floodgate] Floodgate player logged in as _Y0ngz3 joined (UUID: 00000000-0000-0000-0009-01f5cc3e5188)
[08.12 22:27:58] [Server] [ERROR] Could not pass event PlayerJoinEvent to GeyserSkinManager v1.5-SNAPSHOT
[08.12 22:27:58] [Server] java.lang.NoSuchMethodError'org.geysermc.connector.network.session.auth.BedrockClientData org.geysermc.connector.network.session.GeyserSession.getClientData()'
[08.12 22:27:58] [Server] 	at com.github.camotoy.geyserskinmanager.common.skinretriever.GeyserSkinRetriever.getBedrockSkin(GeyserSkinRetriever.java:55) ~[GeyserSkinManager-Spigot.jar:?]
[08.12 22:27:58] [Server] 	at com.github.camotoy.geyserskinmanager.spigot.listener.PaperEventListener.onPlayerJoin(PaperEventListener.java:30) ~[GeyserSkinManager-Spigot.jar:?]
[08.12 22:27:58] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor166.execute(Unknown Source) ~[?:?]
[08.12 22:27:58] [Server] 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:360) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:302) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:307) ~[app:?]
[08.12 22:27:58] [Server] 	at net.minecraft.network.Connection.tick(Connection.java:555) ~[app:?]
[08.12 22:27:58] [Server] 	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[app:?]
[08.12 22:27:58] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1656) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-397]
[08.12 22:27:58] [Server] 	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[08.12 22:27:58] [Connect] _Y0ngz3, IP 108.54.156.59
[08.12 22:27:58] [Multicraft] _Y0ngz3 ran command Message of the Day
[08.12 22:27:58] [Server] [INFO] [+] _Y0ngz3
[08.12 22:27:59] [Server] [WARN] java.io.IOException: Unable to read chunk: [CraftWorld{name=world}, -217, -259]
[08.12 22:27:59] [Server] [WARN] 	at orebfuscator-plugin-5.1.6.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:54)
[08.12 22:27:59] [Server] [WARN] 	at orebfuscator-plugin-5.1.6.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer$ReadTask.run(AsyncChunkSerializer.java:154)
[08.12 22:27:59] [Server] [WARN] 	at orebfuscator-plugin-5.1.6.jar//net.imprex.orebfuscator.cache.AsyncChunkSerializer.run(AsyncChunkSerializer.java:95)
[08.12 22:27:59] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:831)
[08.12 22:27:59] [Server] [WARN] Caused by: java.util.zip.ZipException: invalid distance too far back
[08.12 22:27:59] [Server] [WARN] 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
[08.12 22:27:59] [Server] [WARN] 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
[08.12 22:27:59] [Server] [WARN] 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
[08.12 22:27:59] [Server] [WARN] 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
[08.12 22:27:59] [Server] [WARN] 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
[08.12 22:27:59] [Server] [WARN] 	at orebfuscator-plugin-5.1.6.jar//net.imprex.orebfuscator.cache.ChunkSerializer.read(ChunkSerializer.java:37)
[08.12 22:27:59] [Server] [WARN] 	... 3 more
[08.12 22:27:59] [Server] [WARN] io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[08.12 22:27:59] [Server] [WARN] {Packet Type: CHUNK_DATA, Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, com.viaversion.viaversion.api.minecraft.chunks.Chunk1_18@10f8a132}, Pair{Type|Boolean, true}, Pair{Type|long[], [J@1d7e7a17}, Pair{Type|long[], [J@42563571}, Pair{Type|long[], [J@2e396395}, Pair{Type|long[], [J@7b1da651}, Pair{Type|VarInt, 3}, Pair{Type|byte[], [B@155dd5e7}, Pair{Type|byte[], [B@66d39780}, Pair{Type|byte[], [B@3137504}, Pair{Type|VarInt, 1}, Pair{Type|byte[], [B@152a6419}], Packet ID: 34}
[08.12 22:27:59] [Server] [WARN] Actual Error: 
[08.12 22:27:59] [Server] [WARN] 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[08.12 22:27:59] [Server] [WARN] 	at TAB.v2.9.2.jar//me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:108)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[08.12 22:27:59] [Server] [WARN] 	at Geyser-Spigot 4.jar//org.geysermc.geyser.network.netty.ChannelWrapper.writeAndFlush(ChannelWrapper.java:223)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[08.12 22:27:59] [Server] [WARN] 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:450)
[08.12 22:27:59] [Server] [WARN] 	at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[08.12 22:27:59] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:831)
[08.12 22:27:59] [Server] [WARN] Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[08.12 22:27:59] [Server] [WARN] {Packet Type: CHUNK_DATA, Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, com.viaversion.viaversion.api.minecraft.chunks.Chunk1_18@10f8a132}, Pair{Type|Boolean, true}, Pair{Type|long[], [J@1d7e7a17}, Pair{Type|long[], [J@42563571}, Pair{Type|long[], [J@2e396395}, Pair{Type|long[], [J@7b1da651}, Pair{Type|VarInt, 3}, Pair{Type|byte[], [B@155dd5e7}, Pair{Type|byte[], [B@66d39780}, Pair{Type|byte[], [B@3137504}, Pair{Type|VarInt, 1}, Pair{Type|byte[], [B@152a6419}], Packet ID: 34}
[08.12 22:27:59] [Server] [WARN] Actual Error: 
[08.12 22:27:59] [Server] [WARN] Caused by: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.libs.fastutil.ints.IntArrayList.getInt(IntArrayList.java:365)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.api.minecraft.chunks.DataPaletteImpl.idByIndex(DataPaletteImpl.java:90)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.api.type.types.version.PaletteType1_18.write(PaletteType1_18.java:110)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.api.type.types.version.ChunkSectionType1_18.write(ChunkSectionType1_18.java:54)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.protocols.protocol1_18to1_17_1.types.Chunk1_18Type.write(Chunk1_18Type.java:86)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.protocols.protocol1_18to1_17_1.types.Chunk1_18Type.write(Chunk1_18Type.java:36)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.writeToBuffer(PacketWrapperImpl.java:210)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:305)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[08.12 22:27:59] [Server] [WARN] 	at xxOLD-ViaVersion-4.1.0.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[08.12 22:27:59] [Server] [WARN] 	at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
[08.12 22:27:59] [Server] [WARN] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08.12 22:27:59] [Server] [WARN] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[08.12 22:27:59] [Server] [WARN] 	at TAB.v2.9.2.jar//me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:108)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[08.12 22:27:59] [Server] [WARN] 	at Geyser-Spigot 4.jar//org.geysermc.geyser.network.netty.ChannelWrapper.writeAndFlush(ChannelWrapper.java:223)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[08.12 22:27:59] [Server] [WARN] 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:450)
[08.12 22:27:59] [Server] [WARN] 	at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[08.12 22:27:59] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:831)
[08.12 22:27:59] [Server] [WARN] io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[08.12 22:27:59] [Server] [WARN] {Packet Type: CHUNK_DATA, Type: Chunk, Index: 0, Data: [Pair{Type|Chunk, com.viaversion.viaversion.api.minecraft.chunks.Chunk1_18@10f8a132}, Pair{Type|Boolean, true}, Pair{Type|long[], [J@1d7e7a17}, Pair{Type|long[], [J@42563571}, Pair{Type|long[], [J@2e396395}, Pair{Type|long[], [J@7b1da651}, Pair{Type|VarInt, 3}, Pair{Type|byte[], [B@155dd5e7}, Pair{Type|byte[], [B@66d39780}, Pair{Type|byte[], [B@3137504}, Pair{Type|VarInt, 1}, Pair{Type|byte[], [B@152a6419}], Packet ID: 34}
[08.12 22:27:59] [Server] [WARN] Actual Error: 
[08.12 22:27:59] [Server] [WARN] 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[08.12 22:27:59] [Server] [WARN] 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[08.12 22:27:59] [Server] [WARN] 	at TAB.v2.9.2.jar//me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:108)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[08.12 22:27:59] [Server] [WARN] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)

### Bug Description

Joining 1.18 server with Geyser, floodgate & viaversion installed.

### Steps to Reproduce

I have not been able to reproduce myself, but the user has just logged in on an updated Bedrock client on an iPad.

### Expected Behavior

User should be able to join.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--397%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--397%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>

**Comment by Generzon** [comment]
Please can you advise what I need to do to fix this? I have updated ViaVersion to the most recent...
