### ISSUE TITLE
1.7.10 Client Unable To Connect To BungeeCord

### ISSUE THREAD

**Issue by OmenDoesStuff** [ViaVersion/ViaVersion#2773]
### `/viaversion dump` Output

https://dump.viaversion.com/d22338cb8f8624e7f6beb2e3b0f62af2f6bd9ecde0eafcbd1487244a73733329

### Console Error

```
Put the paste.gg link or text here.
```
20:05:52 [WARNING] [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF 0x21->0x21
20:05:52 [SEVERE] [Player796|127.0.0.1] <-> BotFilter - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Type: Chunk, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.WorldPackets$1 (Anonymous), Packet ID: 33}
Actual Error:
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:289)
    at xyz.yooniks.escanorproxy.caching.PacketUtils.spawnPlayer(PacketUtils.java:287)
    at xyz.yooniks.escanorproxy.filter.Connector.spawn(Connector.java:94)
    at xyz.yooniks.escanorproxy.EscanorProxy.connectToBotFilter(EscanorProxy.java:191)
    at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:558)
    at net.md_5.bungee.connection.InitialHandler.access$800(InitialHandler.java:75)
    at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:420)
    at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:401)
    at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:400)
    at net.md_5.bungee.connection.InitialHandler.delayedHandleOfLoginRequset(InitialHandler.java:436)
    at xyz.yooniks.escanorproxy.EscanorProxy.checkAsyncIfNeeded(EscanorProxy.java:369)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:367)
    at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:116)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Unknown Source)

### Bug Description

Cannot join with 1.7.10 client

### Steps to Reproduce

1. Login with a 1.7.10 client to BungeeCord

### Expected Behavior

You shouldnt be kicked

### Additional Server Info

I use Aegis Escanor, i use ViaVersion 4.0.1, ViaRewind 2.0.1 and ViaBackwards 4.0.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.16--R0.4--SNAPSHOT%3Ab59f5bd%3Aunknown](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.16--R0.4--SNAPSHOT%3Ab59f5bd%3Aunknown-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>![ViaRewind: Outdated](https://img.shields.io/badge/ViaRewind-Outdated!-red?style=flat-square) </br>
