### ISSUE TITLE
1.7.10 Client Unable To Connect To BungeeCord

### ISSUE THREAD

**Issue by OmenDoesStuff** [ViaVersion/ViaVersion#2774]
### `/viaversion dump` Output

https://dump.viaversion.com/99ef6df275a39501e27b4fb5fb621440fa12020b08004c6b25692f399a324833

### Console Error

20:15:52 [WARNING] [ViaVersion] ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF CHUNK_DATA (0x21)
20:15:52 [SEVERE] [Player796|127.0.0.1] <-> BotFilter - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: CHUNK_DATA, Type: Chunk, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.WorldPackets$1 (Anonymous), Packet ID: 33}
Actual Error:
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:289)
    at xyz.yooniks.escanorproxy.caching.PacketUtils.spawnPlayer(PacketUtils.java:287)
    at xyz.yooniks.escanorproxy.filter.Connector.spawn(Connector.java:94)
    at xyz.yooniks.escanorproxy.EscanorProxy.connectToBotFilter(EscanorProxy.java:191)
    at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:558)
    at net.md_5.bungee.connection.InitialHandler.access$800(InitialHandler.java:75)
    at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:420)
    at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:401)
    at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:400)
    at net.md_5.bungee.connection.InitialHandler.delayedHandleOfLoginRequset(InitialHandler.java:436)
    at xyz.yooniks.escanorproxy.EscanorProxy.checkAsyncIfNeeded(EscanorProxy.java:369)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:367)
    at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:116)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: CHUNK_DATA, Type: Chunk, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.WorldPackets$1 (Anonymous), Packet ID: 33}
Actual Error:
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(256) + length(2) exceeds writerIndex(256): UnpooledHeapByteBuf(ridx: 256, widx: 256, cap: 256/256)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478)
    at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:751)
    at io.netty.buffer.SwappedByteBuf.readShort(SwappedByteBuf.java:541)
    at com.viaversion.viaversion.api.type.types.version.ChunkSectionType1_8.read(ChunkSectionType1_8.java:47)
    at com.viaversion.viaversion.api.type.types.version.ChunkSectionType1_8.read(ChunkSectionType1_8.java:32)
    at com.viaversion.viaversion.protocols.protocol1_9to1_8.types.Chunk1_8Type.deserialize(Chunk1_8Type.java:84)
    at com.viaversion.viaversion.protocols.protocol1_9to1_8.types.Chunk1_8Type.read(Chunk1_8Type.java:60)
    at com.viaversion.viaversion.protocols.protocol1_9to1_8.types.Chunk1_8Type.read(Chunk1_8Type.java:34)
    at com.viaversion.viaversion.api.type.PartialType.read(PartialType.java:46)
    at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
    at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.WorldPackets$1.lambda$registerMap$0(WorldPackets.java:38)
    at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
    at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
    at de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.Protocol1_7_6_10TO1_8.transform(Protocol1_7_6_10TO1_8.java:89)
    at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
    at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
    at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
    at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
    at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
    at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
    at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:55)
    at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:31)
    at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
    at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
    at io.netty.channel.AbstractChannel.write(AbstractChannel.java:289)
    at xyz.yooniks.escanorproxy.caching.PacketUtils.spawnPlayer(PacketUtils.java:287)
    at xyz.yooniks.escanorproxy.filter.Connector.spawn(Connector.java:94)
    at xyz.yooniks.escanorproxy.EscanorProxy.connectToBotFilter(EscanorProxy.java:191)
    at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:558)
    at net.md_5.bungee.connection.InitialHandler.access$800(InitialHandler.java:75)
    at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:420)
    at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:401)
    at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:400)
    at net.md_5.bungee.connection.InitialHandler.delayedHandleOfLoginRequset(InitialHandler.java:436)
    at xyz.yooniks.escanorproxy.EscanorProxy.checkAsyncIfNeeded(EscanorProxy.java:369)
    at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:367)
    at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:116)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Unknown Source)
20:15:52 [INFO] [Player796] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: CHUNK_DATA, Type: Chunk, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.WorldPackets$1 (Anonymous), Packet ID: 33}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:104

### Bug Description

Cannot join with 1.7.10 client

### Steps to Reproduce

1. Login with a 1.7.10 Client (I used CheatBreaker)

### Expected Behavior

Being sent to the Hub server

### Additional Server Info

I use Aegis Escanor

Client Disconnect Message:
![2021-12-15_20 19 05](https://user-images.githubusercontent.com/89894310/146290215-dccc597c-fa72-4b87-84be-d69d82b2da28.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.16--R0.4--SNAPSHOT%3Ab59f5bd%3Aunknown](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.16--R0.4--SNAPSHOT%3Ab59f5bd%3Aunknown-3498db?style=flat-square) </br>![ViaVersion (4.1.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.1.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaRewind(2.0.2): 3 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.1.1): 4 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.1.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
