### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by Mirko-L** [ViaVersion/ViaVersion#2783]
### `/viaversion dump` Output

https://dump.viaversion.com/986974765c7aeae63b266f411864553ed207c1c4000a25f66948fdfb3824e86c

### Console Error

[12:45:50] [Netty Server IO #2/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: CHAT_MESSAGE, Type: String, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.PlayerPackets$1 (Anonymous), Packet ID: 15}
Actual Error: 
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[12:45:50] [Netty Server IO #2/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:45:50] [Netty Server IO #2/WARN]:     at io.github.repooper.packetevents.Vulcan_iu.write(Vulcan_iu.java:53)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[12:45:50] [Netty Server IO #2/WARN]:     at me.RockinChaos.itemjoin.utils.protocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:509)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[12:45:50] [Netty Server IO #2/WARN]:     at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[12:45:50] [Netty Server IO #2/WARN]:     at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[12:45:50] [Netty Server IO #2/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[12:45:50] [Netty Server IO #2/WARN]:     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[12:45:50] [Netty Server IO #2/WARN]:     at java.lang.Thread.run(Thread.java:748)

### Bug Description

Disconnects users and sends this error to the console

### Steps to Reproduce

Log users off the server every 4-5 minutes

### Expected Behavior

nothing errors

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--%224c7641d%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 8 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-8%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
Not a crash, but likely something sending bad data.
