### ISSUE TITLE
Error on shutdown with restart script from spigot.yml (paper 1.12.2)

### ISSUE THREAD

**Issue by andrewkm** [ViaVersion/ViaVersion#2788]
### `/viaversion dump` Output

On request via discord `andrewkm#0001`

### Console Error

Paper 1.12.2 - Build 1619
ViaVersion - 4.1.2 - Build 599

When running a restart command with spigot.yml settings.restart-script get the following error:
```
[14:29:44] [Server thread/INFO]: [ViaVersion] Disabling ViaVersion v4.1.2-SNAPSHOT
[14:29:44] [Server thread/INFO]: [ViaVersion] ViaVersion is disabling, if this is a reload and you experience issues consider rebooting.
[14:29:44] [Server thread/ERROR]: [ViaVersion] ViaVersion failed to uninject:
[14:29:44] [Server thread/WARN]: java.lang.NullPointerException
[14:29:44] [Server thread/WARN]:     at com.viaversion.viaversion.util.ReflectionUtil.get(ReflectionUtil.java:65)
[14:29:44] [Server thread/WARN]:     at com.viaversion.viaversion.platform.LegacyViaInjector.uninject(LegacyViaInjector.java:119)
[14:29:44] [Server thread/WARN]:     at com.viaversion.viaversion.bukkit.platform.BukkitViaInjector.uninject(BukkitViaInjector.java:57)
[14:29:44] [Server thread/WARN]:     at com.viaversion.viaversion.ViaManagerImpl.destroy(ViaManagerImpl.java:204)
[14:29:44] [Server thread/WARN]:     at com.viaversion.viaversion.ViaVersionPlugin.onDisable(ViaVersionPlugin.java:158)
[14:29:44] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[14:29:44] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350)
[14:29:44] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437)
[14:29:44] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:424)
[14:29:44] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[14:29:44] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:363)
[14:29:44] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486)
[14:29:44] [Server thread/WARN]:     at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:90)
[14:29:44] [Server thread/WARN]:     at org.spigotmc.RestartCommand.restart(RestartCommand.java:60)
[14:29:44] [Server thread/WARN]:     at org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
[14:29:44] [Server thread/WARN]:     at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31)
[14:29:44] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:861)
[14:29:44] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[14:29:44] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[14:29:44] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[14:29:44] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:748)
```

Cannot reproduce on 1.17.1 and 1.18.1

### Bug Description

Info above.

### Steps to Reproduce

Info above.

### Expected Behavior

No error.

### Additional Server Info

Info above.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by andrewkm** [comment]
You can request that via Discord, or let me know what specific information you require.
Not posting that information publicly. It's quite a simple bug lol, no need for it.
