### ISSUE TITLE
Packet Mistake

### ISSUE THREAD

**Issue by melonyrame** [ViaVersion/ViaVersion#2800]
### `/viaversion dump` Output

Slightly

### Console Error

Slightly

### Bug Description

When I entered the server, I clicked the right button, then started to flash back, and then this message appeared

![Uploading image.png…]()

Log:
Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Type: Byte, Data: [], Source 0: de.gerrygames.viarewind.protocol.protocol1_8to1_9.packets.PlayerPackets$14 (Anonymous), Packet ID: 19}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1175) ~[AbstractByteBuf.class:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570) ~[AbstractByteBuf.class:4.0.23.Final]
	at us.myles.ViaVersion.api.type.types.ByteType.read(ByteType.java:14) ~[ByteType.class:?]
	at us.myles.ViaVersion.api.type.types.ByteType.read(ByteType.java:7) ~[ByteType.class:?]
	at us.myles.ViaVersion.api.PacketWrapper.read(PacketWrapper.java:143) ~[PacketWrapper.class:?]
	at us.myles.ViaVersion.api.remapper.TypeRemapper.read(TypeRemapper.java:15) ~[TypeRemapper.class:?]
	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:129) ~[PacketRemapper.class:?]
	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407) ~[Protocol.class:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:454) ~[PacketWrapper.class:?]
	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435) ~[PacketWrapper.class:?]
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75) ~[ProtocolPipeline.class:?]
	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404) ~[UserConnection.class:?]
	at us.myles.ViaVersion.api.data.UserConnection.transformIncoming(UserConnection.java:395) ~[UserConnection.class:?]
	at viaversion.handler.clientside.VREncodeHandler.encode(VREncodeHandler.java:29) ~[VREncodeHandler.class:?]
	at viaversion.handler.clientside.VREncodeHandler.encode(VREncodeHandler.java:12) ~[VREncodeHandler.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:4.0.23.Final]
	... 19 more

### Steps to Reproduce

Slightly

### Expected Behavior

Slightly

### Additional Server Info

Slightly

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
See above / your Via is too old.
