### ISSUE TITLE
ERROR CONSOLE

### ISSUE THREAD

**Issue by Aides123** [ViaVersion/ViaVersion#2803]
### `/viaversion dump` Output

https://dump.viaversion.com/f1fc34fa18f20907b69ac6e13820591e4862b5b61f07ed8df85067e934f3038a

### Console Error

```
[14:32:04 WARN]: [ViaVersion] ERROR IN Protocol1_12_2To1_13 IN REMAP OF PLUGIN_MESSAGE (0x09)
[14:32:04 WARN]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[14:32:04 WARN]: {Packet Type: null, Type: Item, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$11 (Anonymous), Packet ID: 11}
[14:32:04 WARN]: Actual Error: 
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[14:32:04 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[14:32:04 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[14:32:04 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[14:32:04 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[14:32:04 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:32:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:32:04 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[14:32:04 WARN]: {Packet Type: null, Type: Item, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$11 (Anonymous), Packet ID: 11}
[14:32:04 WARN]: Actual Error: 
[14:32:04 WARN]: Caused by: java.io.IOException: Expected root tag to be a CompoundTag, was -116
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.libs.opennbt.NBTIO.readTag(NBTIO.java:181)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:52)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:36)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.minecraft.ItemType.read(ItemType.java:44)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.minecraft.ItemType.read(ItemType.java:29)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[14:32:04 WARN]:        at ViaBackwards-4.2.0-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$11.lambda$registerMap$0(PlayerPacket1_13.java:453)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:376)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformServerbound(UserConnectionImpl.java:282)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:55)
[14:32:04 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
[14:32:04 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:32:04 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[14:32:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:569)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[14:32:04 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[14:32:04 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[14:32:04 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[14:32:04 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[14:32:04 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:32:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:32:04 WARN]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[14:32:04 WARN]: {Packet Type: null, Type: Item, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$11 (Anonymous), Packet ID: 11}
[14:32:04 WARN]: Actual Error: 
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:477)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[14:32:04 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[14:32:04 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[14:32:04 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[14:32:04 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[14:32:04 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:32:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:32:04 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[14:32:04 WARN]: {Packet Type: null, Type: Item, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$11 (Anonymous), Packet ID: 11}
[14:32:04 WARN]: Actual Error: 
[14:32:04 WARN]: Caused by: java.io.IOException: Expected root tag to be a CompoundTag, was -116
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.libs.opennbt.NBTIO.readTag(NBTIO.java:181)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:52)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:36)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.minecraft.ItemType.read(ItemType.java:44)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.minecraft.ItemType.read(ItemType.java:29)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[14:32:04 WARN]:        at ViaBackwards-4.2.0-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$11.lambda$registerMap$0(PlayerPacket1_13.java:453)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:376)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformServerbound(UserConnectionImpl.java:282)
[14:32:04 WARN]:        at ViaVersion-4.2.0-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:55)
[14:32:04 WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
[14:32:04 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:32:04 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[14:32:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:569)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[14:32:04 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[14:32:04 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[14:32:04 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[14:32:04 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[14:32:04 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[14:32:04 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[14:32:04 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[14:32:04 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[14:32:04 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:32:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:32:04 INFO]: Doslenowskigg_YT lost connection: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: null, Type: Item, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$11 (Anonymous), Packet ID: 11}
Actual Error: 
```

### Bug Description

Players after typing the GUI commands /is panel and /is settings get kicked off the server with this error.

Plugin: SuperiorSkyBLock

### Steps to Reproduce

Version: 1.17.1
type command /is panel or /is settings (SUPERIORSKYBLOCK PLUGIN)

### Expected Behavior

Players after typing the GUI commands /is panel and /is settings get kicked off the server with this error.

### Additional Server Info

Bungeecord: Jpremium / minimotd / luckperms

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--20%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Pufferfish--20%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.0-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.0--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.0-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.0--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Something is sending an invalid plugin message
