### ISSUE TITLE
If you place ender dragon spawner, server go brrr

### ISSUE THREAD

**Issue by AzteqDev** [ViaVersion/ViaVersion#2828]
### `/viaversion dump` Output

https://dump.viaversion.com/a5dffb3180c59d1c317f4c9f1dc97cc933e88e76c5855456c8ebcb652eabd6bc

### Console Error

[10:41:34 WARN]: [ViaVersion] ERROR IN Protocol1_18To1_17_1 IN REMAP OF BLOCK_ENTITY_DATA (0x0A)
[10:41:34 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[10:41:34 WARN]: {Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1 (Anonymous)}
[10:41:34 WARN]: Actual Error: 
[10:41:34 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[10:41:34 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[10:41:34 WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:450)
[10:41:34 WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[10:41:34 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[10:41:34 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[10:41:34 WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[10:41:34 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[10:41:34 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:41:34 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:41:34 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[10:41:34 WARN]: {Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1 (Anonymous)}
[10:41:34 WARN]: Actual Error: 
[10:41:34 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[10:41:34 WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[10:41:34 WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[10:41:34 WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[10:41:34 WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[10:41:34 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[10:41:34 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[10:41:34 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[10:41:34 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[10:41:34 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1.lambda$registerMap$0(WorldPackets.java:56)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[10:41:34 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[10:41:34 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[10:41:34 WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:450)
[10:41:34 WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[10:41:34 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[10:41:34 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[10:41:34 WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[10:41:34 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[10:41:34 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:41:34 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:41:34 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[10:41:34 WARN]: {Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1 (Anonymous)}
[10:41:34 WARN]: Actual Error: 
[10:41:34 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[10:41:34 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[10:41:34 WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:450)
[10:41:34 WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[10:41:34 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[10:41:34 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[10:41:34 WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[10:41:34 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[10:41:34 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:41:34 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:41:34 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[10:41:34 WARN]: {Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1 (Anonymous)}
[10:41:34 WARN]: Actual Error: 
[10:41:34 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[10:41:34 WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[10:41:34 WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[10:41:34 WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[10:41:34 WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[10:41:34 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[10:41:34 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[10:41:34 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[10:41:34 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[10:41:34 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1.lambda$registerMap$0(WorldPackets.java:56)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[10:41:34 WARN]: 	at ViaVersion.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[10:41:34 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[10:41:34 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[10:41:34 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[10:41:34 WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:450)
[10:41:34 WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$8(NetworkManager.java:424)
[10:41:34 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[10:41:34 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[10:41:34 WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[10:41:34 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[10:41:34 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:41:34 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:41:34 INFO]: ItzArchiee lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1 (Anonymous)}
Actual Error: 
[10:41:34 INFO]: ItzArchiee left the game

### Bug Description

If you place and ender dragon spawner the server crashes

### Steps to Reproduce

go on your server with essentials
give yourself ender_dragon_cage
and if you place it your server crashes

### Expected Behavior

Summon ender dragon

### Additional Server Info

**i use plugins on minehut (eg. essentials viaver world edit world guard and other stuff)**

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--408%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-git--Paper--408%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.1.1): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.1.1)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a corrupt jar file
