### ISSUE TITLE
org.bukkit.plugin.InvalidPluginException: java.lang.ClassCastException

### ISSUE THREAD

**Issue by h266579110** [ViaVersion/ViaVersion#2840]
### `/viaversion dump` Output

none

### Console Error

```
[00:08:19 ERROR]: Could not load 'plugins\ViaVersion-4.2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:420) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
        at com.viaversion.viaversion.libs.fastutil.ints.AbstractIntCollection.add(AbstractIntCollection.java:35) ~[ViaVersion-4.2.1.jar:?]
        at java.util.AbstractCollection.addAll(AbstractCollection.java:336) ~[?:?]
        at com.viaversion.viaversion.libs.fastutil.ints.AbstractIntCollection.addAll(AbstractIntCollection.java:177) ~[ViaVersion-4.2.1.jar:?]
        at com.viaversion.viaversion.libs.fastutil.ints.IntOpenHashSet.addAll(IntOpenHashSet.java:410) ~[ViaVersion-4.2.1.jar:?]
        at com.viaversion.viaversion.libs.fastutil.ints.IntOpenHashSet.<init>(IntOpenHashSet.java:123) ~[ViaVersion-4.2.1.jar:?]
        at com.viaversion.viaversion.libs.fastutil.ints.IntOpenHashSet.<init>(IntOpenHashSet.java:133) ~[ViaVersion-4.2.1.jar:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.loadBlockedProtocolVersions(AbstractViaConfig.java:163) ~[ViaVersion-4.2.1.jar:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.loadFields(AbstractViaConfig.java:133) ~[ViaVersion-4.2.1.jar:?]
        at com.viaversion.viaversion.bukkit.platform.BukkitViaConfig.loadFields(BukkitViaConfig.java:44) ~[ViaVersion-4.2.1.jar:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.reloadConfig(AbstractViaConfig.java:100) ~[ViaVersion-4.2.1.jar:?]
        at com.viaversion.viaversion.bukkit.platform.BukkitViaConfig.<init>(BukkitViaConfig.java:39) ~[ViaVersion-4.2.1.jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.<init>(ViaVersionPlugin.java:83) ~[ViaVersion-4.2.1.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 7 more
```

### Bug Description

Can't load plugin

Java 17、Paper 1.18.1-216

### Steps to Reproduce

1. Server start.
2. bug appear

### Expected Behavior

work normally.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
You have something bad in your config; delete it and see the diff.
