### ISSUE TITLE
1.19 on 1.18.2 - Packet Type: SPAWN_PARTICLE client disconnect error

### ISSUE THREAD

**Issue by mrfloris** [ViaVersion/ViaVersion#2850]
### `/viaversion dump` Output

https://dump.viaversion.com/b03c08182994569a1ab0863c5d2628a57498184ae7ce10845aa72535ace41105

### Console Error

```
[15:06:39 WARN]: Paprikaatje moved too quickly! 15692.2059115893,-11.0,-15454.51529206135
[15:06:55 WARN]: [ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF SPAWN_PARTICLE (0x24)
[15:06:55 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[15:06:55 WARN]: {Packet Type: SPAWN_PARTICLE, Type: VarInt, Data: [Pair{Type|VarInt, 53}, Pair{Type|Boolean, false}, Pair{Type|Double, 15172.285033609845}, Pair{Type|Double, 63.0}, Pair{Type|Double, -14247.311119360362}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 3}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.InventoryPackets$1 (Anonymous), Packet ID: 36}
[15:06:55 WARN]: Actual Error:
[15:06:55 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:06:55 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:06:55 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[15:06:55 WARN]:        at ClientDetector.jar//de.sportkanone123.clientdetector.spigot.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:54)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[15:06:55 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[15:06:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:215)
[15:06:55 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
[15:06:55 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:436)
[15:06:55 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[15:06:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[15:06:55 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[15:06:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[15:06:55 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:06:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:06:55 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[15:06:55 WARN]: {Packet Type: SPAWN_PARTICLE, Type: VarInt, Data: [Pair{Type|VarInt, 53}, Pair{Type|Boolean, false}, Pair{Type|Double, 15172.285033609845}, Pair{Type|Double, 63.0}, Pair{Type|Double, -14247.311119360362}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 3}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.InventoryPackets$1 (Anonymous), Packet ID: 36}
[15:06:55 WARN]: Actual Error:
[15:06:55 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(50) + length(1) exceeds writerIndex(50): PooledUnsafeDirectByteBuf(ridx: 50, widx: 50, cap: 256)
[15:06:55 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[15:06:55 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:40)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:73)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ItemRewriter.lambda$getSpawnParticleHandler$0(ItemRewriter.java:328)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[15:06:55 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:06:55 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:06:55 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[15:06:55 WARN]:        at ClientDetector.jar//de.sportkanone123.clientdetector.spigot.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:54)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[15:06:55 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[15:06:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:215)
[15:06:55 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
[15:06:55 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:436)
[15:06:55 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[15:06:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[15:06:55 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[15:06:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[15:06:55 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:06:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:06:55 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[15:06:55 WARN]: {Packet Type: SPAWN_PARTICLE, Type: VarInt, Data: [Pair{Type|VarInt, 53}, Pair{Type|Boolean, false}, Pair{Type|Double, 15172.285033609845}, Pair{Type|Double, 63.0}, Pair{Type|Double, -14247.311119360362}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 3}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.InventoryPackets$1 (Anonymous), Packet ID: 36}
[15:06:55 WARN]: Actual Error:
[15:06:55 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:06:55 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:06:55 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[15:06:55 WARN]:        at ClientDetector.jar//de.sportkanone123.clientdetector.spigot.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:54)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[15:06:55 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[15:06:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:215)
[15:06:55 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
[15:06:55 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:436)
[15:06:55 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[15:06:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[15:06:55 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[15:06:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[15:06:55 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:06:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:06:55 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[15:06:55 WARN]: {Packet Type: SPAWN_PARTICLE, Type: VarInt, Data: [Pair{Type|VarInt, 53}, Pair{Type|Boolean, false}, Pair{Type|Double, 15172.285033609845}, Pair{Type|Double, 63.0}, Pair{Type|Double, -14247.311119360362}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 3}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.InventoryPackets$1 (Anonymous), Packet ID: 36}
[15:06:55 WARN]: Actual Error:
[15:06:55 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(50) + length(1) exceeds writerIndex(50): PooledUnsafeDirectByteBuf(ridx: 50, widx: 50, cap: 256)
[15:06:55 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[15:06:55 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:40)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:73)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.ItemRewriter.lambda$getSpawnParticleHandler$0(ItemRewriter.java:328)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[15:06:55 WARN]:        at ViaVersion-4.3.0-22w11a-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[15:06:55 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:06:55 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[15:06:55 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[15:06:55 WARN]:        at ClientDetector.jar//de.sportkanone123.clientdetector.spigot.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:54)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[15:06:55 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[15:06:55 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[15:06:55 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:215)
[15:06:55 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
[15:06:55 WARN]:        at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:436)
[15:06:55 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[15:06:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[15:06:55 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[15:06:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[15:06:55 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:06:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:06:55 INFO]: Paprikaatje lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: SPAWN_PARTICLE, Type: VarInt, Data: [Pair{Type|VarInt, 53}, Pair{Type|Boolean, false}, Pair{Type|Double, 15172.285033609845}, Pair{Type|Double, 63.0}, Pair{Type|Double, -14247.311119360362}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Float, 0.1}, Pair{Type|Float, 0.0}, Pair{Type|Integer, 3}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.InventoryPackets$1 (Anonymous), Packet ID: 36}
Actual Error:
[15:06:55 INFO]:  - Player Paprikaatje left.
```

### Bug Description

User has elytra on and jumped from a stairs over water to a slab in the water, made them 'fly' and disconnects them, reconnecting is no longer possible unless they downgrade back to 1.18.2
<img width="1136" alt="Screenshot 2022-03-19 at 15 07 00" src="https://user-images.githubusercontent.com/28841349/159124496-29068aef-2141-4460-b400-e28c602c0e0d.png">

### Steps to Reproduce

User has elytra on and jumped from a stairs over water to a slab in the water, made them 'fly' and disconnects them,

### Expected Behavior

properly land and continue walking, instead of disconnecting

### Additional Server Info

```
> ver
[15:11:32 INFO]: Checking version, please wait...
[15:11:32 INFO]: This server is running Paper version git-Paper-261 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 855637f)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-260 (MC: 1.18.2)
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--261%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--261%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.3.0-22w11a-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--22w11a--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.0-22w11a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.3.0--22w11a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
