### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by Haydenharr23** [ViaVersion/ViaVersion#2851]
### `/viaversion dump` Output

https://dump.viaversion.com/f7ee06a83cd6cb97d9e89295681edc96f8a02eaca28734f4afbe87df95a24d4a

### Console Error

```
Put the paste.gg link or text here.
```
![image](https://user-images.githubusercontent.com/101309224/159564767-d4b295ab-30d5-48b0-bfd1-42ffa7c0bae5.png)

  [Tue 12:53:24 INFO  Server/PlayerConnection] vmble lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1 (Anonymous)}
Actual Error: 
! [Tue 12:53:24 WARN ]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
! [Tue 12:53:24 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
  [Tue 12:53:24 INFO  ca.tweetzy.auctionhouse.AuctionHouse] [AuctionHouse] Removing Instances for user: vmble
! [Tue 12:53:24 WARN ] Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
! [Tue 12:53:24 WARN ] {Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1 (Anonymous)}
! [Tue 12:53:24 WARN ] Actual Error: 
! [Tue 12:53:24 WARN ] Caused by: java.lang.IllegalStateException: zip file closed
! [Tue 12:53:24 WARN ]     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
! [Tue 12:53:24 WARN ]     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
! [Tue 12:53:24 WARN ]     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
! [Tue 12:53:24 WARN ]     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
! [Tue 12:53:24 WARN ]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159)
! [Tue 12:53:24 WARN ]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
! [Tue 12:53:24 WARN ]     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104)
! [Tue 12:53:24 WARN ]     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
! [Tue 12:53:24 WARN ]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1.lambda$registerMap$0(WorldPackets.java:51)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
! [Tue 12:53:24 WARN ]     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
! [Tue 12:53:24 WARN ]     at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
! [Tue 12:53:24 WARN ]     at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
! [Tue 12:53:24 WARN ]     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
  [Tue 12:53:24 INFO  Server] vmble left the game
! [Tue 12:53:24 WARN ]     at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
! [Tue 12:53:24 WARN ]     at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
! [Tue 12:53:24 WARN ]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
! [Tue 12:53:24 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
! [Tue 12:53:24 WARN ] io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
! [Tue 12:53:24 WARN ] {Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1 (Anonymous)}
! [Tue 12:53:24 WARN ] Actual Error: 
! [Tue 12:53:24 WARN ]     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
! [Tue 12:53:24 WARN ]     at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
! [Tue 12:53:24 WARN ]     at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
! [Tue 12:53:24 WARN ]     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
! [Tue 12:53:24 WARN ]     at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
! [Tue 12:53:24 WARN ]     at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
! [Tue 12:53:24 WARN ]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
! [Tue 12:53:24 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)
! [Tue 12:53:24 WARN ] Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
! [Tue 12:53:24 WARN ] {Source 0: com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1 (Anonymous)}
! [Tue 12:53:24 WARN ] Actual Error: 
! [Tue 12:53:24 WARN ] Caused by: java.lang.IllegalStateException: zip file closed
! [Tue 12:53:24 WARN ]     at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
! [Tue 12:53:24 WARN ]     at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
! [Tue 12:53:24 WARN ]     at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
! [Tue 12:53:24 WARN ]     at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
! [Tue 12:53:24 WARN ]     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159)
! [Tue 12:53:24 WARN ]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
! [Tue 12:53:24 WARN ]     at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104)
! [Tue 12:53:24 WARN ]     at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
! [Tue 12:53:24 WARN ]     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocols.protocol1_18to1_17_1.packets.WorldPackets$1.lambda$registerMap$0(WorldPackets.java:51)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
! [Tue 12:53:24 WARN ]     at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
! [Tue 12:53:24 WARN ]     at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
! [Tue 12:53:24 WARN ]     at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
! [Tue 12:53:24 WARN ]     at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:137)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
! [Tue 12:53:24 WARN ]     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
! [Tue 12:53:24 WARN ]     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
! [Tue 12:53:24 WARN ]     at net.minecraft.network.NetworkManager.a(NetworkManager.java:215)
! [Tue 12:53:24 WARN ]     at net.minecraft.network.NetworkManager.lambda$4(NetworkManager.java:204)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
! [Tue 12:53:24 WARN ]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
! [Tue 12:53:24 WARN ]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
! [Tue 12:53:24 WARN ]     at java.base/java.lang.Thread.run(Thread.java:833)

### Bug Description

no clue just happens randomly

### Steps to Reproduce

no clue just happens randomly

### Expected Behavior

no clue just happens randomly

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3284a--Spigot--3892929--0ab8487%20%28MC%3A%201.17.1%29](https://img.shields.io/badge/Platform-3284a--Spigot--3892929--0ab8487%20%28MC%3A%201.17.1%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>
