### ISSUE TITLE
Cannot receive string longer than Short.MAX_VALUE * 3 bytes

### ISSUE THREAD

**Issue by misterquestions** [ViaVersion/ViaVersion#2853]
### `/viaversion dump` Output

https://dump.viaversion.com/702ef823ec8e55e2663545c5c855964386ac1dabb6f559d639ae0d2ae4215d92

### Console Error

```
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template

{Packet Type: GAME_PROFILE, Type: String, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}

Actual Error: 

Caused by: java.lang.IllegalArgumentException: Cannot receive string longer than Short.MAX_VALUE * 3 bytes (got 84378684 bytes)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:164) ~[velocity-3.1.2-SNAPSHOT-125.jar:3.1.2-SNAPSHOT (git-05d19384-b125)]
at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:50) ~[?:?]
at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181) ~[?:?]
at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:205) ~[?:?]
at com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:137) ~[?:?]
at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118) ~[?:?]
at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298) ~[?:?]
at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277) ~[?:?]
at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230) ~[?:?]
at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity-3.1.2-SNAPSHOT-125.jar:3.1.2-SNAPSHOT (git-05d19384-b125)]

... 23 more
```

### Bug Description

Trying to connect normally to a server when using viaversion in a velocity proxy generates this exception causing the connection to be dropped

### Steps to Reproduce

1. Create a server with velocity and viaversion inside it
2. Login with a 1.18.2 client
3. Issue will appear (I guess?)

### Expected Behavior

Be able to connect normally

### Additional Server Info

The proxy server has the following plugins:
```
[15:38:49 INFO]: Loading plugins...
[15:38:50 INFO]: Loaded plugin botsentry 9.4.2-THANATOS by New Era Studios, Lahuca Software Development
[15:38:50 INFO]: Loaded plugin luckperms 5.4.13 by Luck
[15:38:50 INFO]: Loaded plugin minimotd-velocity 2.0.6 by jmp
[15:38:50 INFO]: Loaded MySQL for Velocity!
[15:38:50 INFO]: Loaded plugin mysqlandconfigurateforvelocity 8.0.20 by Simonsator
[15:38:50 INFO]: Loaded plugin nlogin 10.0.14 by NickUC
[15:38:50 INFO]: Loaded plugin partyandfriends 1.0.228-E by Simonsator
[15:38:50 INFO]: Loaded plugin skinsrestorer 14.1.13 by Blackfire62, McLive
[15:38:50 INFO]: Loaded plugin tcpshield 2.5.6 by TCPShield
[15:38:50 INFO]: Loaded plugin venturechat 3.3.2 by Aust1n46
[15:38:50 INFO]: Loaded plugin viaversion 4.2.1 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[15:38:50 INFO]: Loaded plugin viabackwards 4.2.0 by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
[15:38:50 INFO]: Loaded plugin viarewind 2.0.2 by Gerrygames
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
^ see above, also try without other plugins, old SkinsRestorer versions and similar are also known to cause issues
