### ISSUE TITLE
Mapping 1.12.2 to 1.13 create error on bungeecord

### ISSUE THREAD

**Issue by Elikill58** [ViaVersion/ViaVersion#2860]
### `/viaversion dump` Output

https://dump.viaversion.com/3e4cc3fc97817fc87a9fdf6759f57d1cb7a55e6824dea8bf93021cf27ab6248e

### Console Error

```
[10:48:25 ERROR] [ViaVersion]: Error during mapping loading of Protocol1_12_2To1_13
[10:48:25 ERROR]: java.util.concurrent.CompletionException: java.lang.ClassCastException: com.viaversion.viaversion.libs.gson.JsonArray cannot be cast to com.viaversion.viaversion.libs.gson.JsonObject
[10:48:25 ERROR]:       at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
[10:48:25 ERROR]:       at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
[10:48:25 ERROR]:       at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:783)
[10:48:25 ERROR]:       at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
[10:48:25 ERROR]:       at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
[10:48:25 ERROR]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:48:25 ERROR]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:48:25 ERROR]:       at java.lang.Thread.run(Thread.java:748)
[10:48:25 ERROR]: Caused by: java.lang.ClassCastException: com.viaversion.viaversion.libs.gson.JsonArray cannot be cast to com.viaversion.viaversion.libs.gson.JsonObject
[10:48:25 ERROR]:       at com.viaversion.viaversion.libs.gson.JsonObject.getAsJsonObject(JsonObject.java:192)
[10:48:25 ERROR]:       at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.data.BackwardsMappings.loadVBExtras(BackwardsMappings.java:53)
[10:48:25 ERROR]:       at com.viaversion.viabackwards.api.data.BackwardsMappings.loadExtras(BackwardsMappings.java:78)
[10:48:25 ERROR]:       at com.viaversion.viaversion.api.data.MappingDataBase.load(MappingDataBase.java:111)
[10:48:25 ERROR]:       at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.Protocol1_12_2To1_13.lambda$registerPackets$0(Protocol1_12_2To1_13.java:60)
[10:48:25 ERROR]:       at com.viaversion.viaversion.protocol.ProtocolManagerImpl.lambda$addMappingLoaderFuture$1(ProtocolManagerImpl.java:456)
[10:48:25 ERROR]:       at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
[10:48:25 ERROR]:       ... 5 more
```

### Bug Description

Starting error

### Steps to Reproduce

- use bungeecord
- start server

### Expected Behavior

no error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Ae767b40%3A480](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.18--R0.1--SNAPSHOT%3Ae767b40%3A480-3498db?style=flat-square) </br>![ViaVersion (4.3.0-22w14a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.3.0--22w14a--SNAPSHOT)-Even%20withdev-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>
