### ISSUE TITLE
[ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00

### ISSUE THREAD

**Issue by iftebinjan** [ViaVersion/ViaVersion#2875]
### `/viaversion dump` Output

https://dump.viaversion.com/cf7ca29faab74d68e2acf1580516720464e02db73acd39ba3ea75d610229c447

### Console Error

```
Put the paste.gg link or text here.
```
[18:15:09 ERROR]: java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.ServerPing$Serializer.a(Lnet/minecraft/server/v1_12_R1/ServerPing;Ljava/lang/reflect/Type;Lcom/google/gson/JsonSerializationContext;)Lcom/google/gson/JsonElement;
[18:15:09 WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[18:15:09 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[18:15:09 WARN]: {Packet Type: STATUS_RESPONSE, Type: String, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$1 (Anonymous), Packet ID: 0}
[18:15:09 WARN]: Actual Error: 
[18:15:09 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[18:15:09 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[18:15:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:15:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[18:15:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[18:15:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[18:15:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[18:15:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[18:15:09 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[18:15:09 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[18:15:09 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:201)
[18:15:09 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157)
[18:15:09 WARN]:        at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:109)
[18:15:09 WARN]:        at net.minecraft.server.v1_12_R1.PacketStatusListener.a(PacketStatusListener.java:131)
[18:15:09 WARN]:        at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:23)
[18:15:09 WARN]:        at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:8)
[18:15:09 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:140)
[18:15:20 ERROR]: java.lang.NoSuchMethodError: net.minecraft.server.v1_12_R1.ServerPing$Serializer.a(Lnet/minecraft/server/v1_12_R1/ServerPing;Ljava/lang/reflect/Type;Lcom/google/gson/JsonSerializationContext;)Lcom/google/gson/JsonElement;
[18:15:20 WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF 0x00->0x00
[18:15:20 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[18:15:20 WARN]: {Packet Type: STATUS_RESPONSE, Type: String, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$1 (Anonymous), Packet ID: 0}
[18:15:20 WARN]: Actual Error: 
[18:15:20 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[18:15:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[18:15:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[18:15:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[18:15:20 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:201)
[18:15:20 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157)
[18:15:20 WARN]:        at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:109)
[18:15:20 WARN]:        at net.minecraft.server.v1_12_R1.PacketStatusListener.a(PacketStatusListener.java:131)
[18:15:20 WARN]:        at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:23)
[18:15:20 WARN]:        at net.minecraft.server.v1_12_R1.PacketStatusInStart.a(SourceFile:8)
[18:15:20 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:140)
[18:15:20 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:370)
[18:15:20 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:31)
[18:15:20 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:15:20 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:15:20 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[18:15:20 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:15:20 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:15:20 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[18:15:20 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:15:20 WARN]:        at net.minecraft.server.v1_12_R1.LegacyPingHandler.channelRead(LegacyPingHandler.java:121)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:15:20 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[18:15:20 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[18:15:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[18:15:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[18:15:20 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[18:15:20 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
[18:15:20 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
[18:15:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[18:15:20 WARN]:        at java.lang.Thread.run(Thread.java:748)
[18:15:20 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template

### Bug Description

Its constantly repeating after server start

### Steps to Reproduce

Its constantly repeating after server start. I also Tried deleting viaversions and files. Still the same error 

### Expected Behavior

Its constantly repeating after server start. I also Tried deleting viaversions and files. Still the same error 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by HowardZHY** [comment]
try the latest dev builds from jenkins

**Comment by kennytv** [comment]
Doesn't look like a Via issue
