### ISSUE TITLE
Cant join the server using 1.16.5 and under with latest viaversion & bungeecord

### ISSUE THREAD

**Issue by SukaSingkong** [ViaVersion/ViaVersion#2877]
### `/viaversion dump` Output

https://dump.viaversion.com/98184f73c677aa0a72dd4f1773c20306739953626d6a06c6df65a6b1945ea84f

### Console Error

12:49:15 [SEVERE] [LouisBryan_P] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.TitleTimes in phase GAME with direction TO_CLIENT
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
    at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.TitleTimes in phase GAME with direction TO_CLIENT
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:580)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 9 more
12:49:15 [INFO] [LouisBryan_P] disconnected with: EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.TitleTimes in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125

### Bug Description

Hi! im using latest bungeecord version and using the latest viaversion plugin too... but this message appear when my player join the server using client under the version 1.17.2 (My server is version 1.18.2) im tried to change the protocol version but nothing changed at all.

### Steps to Reproduce

1. Use latest bungeecord & viaversion in your server
2. use 1.16.5 or under to join the server

### Expected Behavior

under version 1.17.2 can join the server

### Additional Server Info

I also use the bungeecord with following plugins: AdvancedBan, AntiBot, AntiBungeePluginSteal, BMsg, bStats, BungeeCommands, BungeeGuard, BungeeReport, ChatSentinel, CountryBlocker, DynamicBungeeAuth, Floodgate, Geyser-BungeeCord, LiteAnnouncer, LuckPerm, Maintenance, ServerListPlus, SkinsRestorer, SlingShot, Strong, ViaBackwards, ViaRewind, ViaVersion

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.18--R0.1--SNAPSHOT%3A862bb2a%3A1636-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.2.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by SukaSingkong** [comment]
Solved, the problem is on "AdvancedBan" plugin...
