### ISSUE TITLE
a lot of ViaBackwards message in console

### ISSUE THREAD

**Issue by TRelymc** [ViaVersion/ViaVersion#2879]
### `/viaversion dump` Output

i entered this command,but it didnt give me any link.....

### Console Error

[17:41:09 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:09 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:10 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:14 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:14 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:16 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:16 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:16 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:16 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:19 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:28 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:28 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:28 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:29 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:40 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:46 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:46 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:46 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:46 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2
[17:41:47 WARN]: [ViaBackwards] Ignoring incoming plugin message with channel: ic2

### Bug Description

how to turn off these message？

### Steps to Reproduce

thank you author，my english not good

### Expected Behavior

im not happy when seeing these

### Additional Server Info

paperspigot 1.16.5

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by TRelymc** [comment]
Result of /viaversion dump

Thank you author

[17:47:10 WARN]: [ViaVersion] Could not paste ViaVersion dump to Hastebin
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
        at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1196) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1105) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:399) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:371) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246) ~[?:?]
        at com.viaversion.viaversion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:88) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-672]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-672]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-672]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Kichura** [comment]
Set `suppress-conversion-warnings` and `suppress-metadata-errors` from false -> true in the ViaVersion configuration file.

**Comment by TRelymc** [comment]
developers team of Viaversion is the best which truly changed minecraft.
Can I use alipay or wechatpay to donate？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ViaVersion/ViaVersion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月3日(星期二) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ViaVersion/ViaVersion] a lot of ViaBackwards message in console (Issue #2879)





 
Set suppress-conversion-warnings and suppress-metadata-errors from false -&gt; true in the ViaVersion configuration file.

**Comment by Kichura** [comment]
https://donorbox.org/viaversion - You can donate to us here.
