### ISSUE TITLE
Causally get kicked from server after running /give command.

### ISSUE THREAD

**Issue by MrLeoOfficial** [ViaVersion/ViaVersion#2882]
### `/viaversion dump` Output

Can't do it as i can't run cmds in the console or in minecraft...

### Console Error

```
[18:11:28] [User Authenticator #1/INFO]: UUID of player Mr_LeoMG is d989edd7-3ad3-484b-bc80-f7f647824657
[18:11:28] [Server thread/INFO]: Mr_LeoMG joined the game
[18:11:28] [Server thread/INFO]: Mr_LeoMG[/101.58.223.117:26274] logged in with entity id 354 at ([world]-724.0757140495807, 111.0, -533.5761206325969)
[18:11:28] [Netty Epoll Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_17_1To1_18 IN REMAP OF WINDOW_ITEMS (0x14)
[18:11:28] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[18:11:28] [Netty Epoll Server IO #1/WARN]: {Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)}
[18:11:28] [Netty Epoll Server IO #1/WARN]: Actual Error: 
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:436)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:11:28] [Netty Epoll Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[18:11:28] [Netty Epoll Server IO #1/WARN]: {Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)}
[18:11:28] [Netty Epoll Server IO #1/WARN]: Actual Error: 
[18:11:28] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.ClassCastException: class com.viaversion.viaversion.libs.opennbt.tag.builtin.ListTag cannot be cast to class com.viaversion.viaversion.libs.opennbt.tag.builtin.StringTag (com.viaversion.viaversion.libs.opennbt.tag.builtin.ListTag and com.viaversion.viaversion.libs.opennbt.tag.builtin.StringTag are in unnamed module of loader 'ViaVersion-4.2.1.jar' @550f8f3a)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaBackwards-4.2.0.jar//com.viaversion.viabackwards.api.rewriters.ItemRewriter.handleItemToClient(ItemRewriter.java:48)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.rewriter.ItemRewriter$2.lambda$registerMap$0(ItemRewriter.java:79)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:436)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:11:28] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[18:11:28] [Netty Epoll Server IO #1/WARN]: {Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)}
[18:11:28] [Netty Epoll Server IO #1/WARN]: Actual Error: 
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:436)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:11:28] [Netty Epoll Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[18:11:28] [Netty Epoll Server IO #1/WARN]: {Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)}
[18:11:28] [Netty Epoll Server IO #1/WARN]: Actual Error: 
[18:11:28] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.ClassCastException: class com.viaversion.viaversion.libs.opennbt.tag.builtin.ListTag cannot be cast to class com.viaversion.viaversion.libs.opennbt.tag.builtin.StringTag (com.viaversion.viaversion.libs.opennbt.tag.builtin.ListTag and com.viaversion.viaversion.libs.opennbt.tag.builtin.StringTag are in unnamed module of loader 'ViaVersion-4.2.1.jar' @550f8f3a)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaBackwards-4.2.0.jar//com.viaversion.viabackwards.api.rewriters.ItemRewriter.handleItemToClient(ItemRewriter.java:48)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.rewriter.ItemRewriter$2.lambda$registerMap$0(ItemRewriter.java:79)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.2.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:462)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:436)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:11:28] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:11:28] [Server thread/INFO]: Mr_LeoMG lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)}
Actual Error: 
[18:11:29] [Server thread/INFO]: Mr_LeoMG left the game

```

### Bug Description

When I run a give command with a wrong flag it got me out of the server. Also tried deleting the via version folders and restarting but it still gave me the same problem.

![image](https://user-images.githubusercontent.com/99419084/167195146-4f2700de-3443-4e65-bdd6-63bd662cbc03.png)

### Steps to Reproduce

1. Started Minecraft 1.17
2. Enter in my 1.18.2 viaversion+viarewind+viabackwards server
3. Started building
4. Needed an item I could only obtain with the give cmd (it had flags)
5. Run a give command with some flags I don't remember and can't reproduce as I didn't copy them
6. I got kicked out of the server with an error
7. Tried restarting the server although it didn't do any difference
8. Reported the problem here on GitHub

### Expected Behavior

Get the item with the flags or name I gave it.

### Additional Server Info

Plugins:
![image](https://user-images.githubusercontent.com/99419084/167195807-6a4e0ae6-dca7-4cb9-9379-90538871375d.png)

Datapacks:
![image](https://user-images.githubusercontent.com/99419084/167195767-4451d37e-6665-4fb0-b929-54db2cf0cfe0.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [x] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by MrLeoOfficial** [comment]
> ![Error: Invalid or missing dump](https://camo.githubusercontent.com/d52699b4f8c5e7e91cb92ecd59b5aa5ed2f9eb37e741b87aa9334b5e364c0512/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)

I can't.....

**Comment by kennytv** [comment]
You have items with bad nbt data in your inventory or opened inventories
