### ISSUE TITLE
If an error occurs, all players will be disconnected

### ISSUE THREAD

**Issue by IPECTER** [ViaVersion/ViaVersion#2883]
### `/viaversion dump` Output

https://dump.viaversion.com/974a43217b3eb8171e972cad9eac782bb061989f8950d407bf782596a6112d45

### Console Error

[20:23:13] [Netty Epoll Server IO #2/ERROR]: Packet encoding of packet ID 77 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.syncher.DataWatcher$Item.a()" because "entry" is null
	at net.minecraft.network.syncher.SynchedEntityData.writeDataItem(SynchedEntityData.java:223) ~[?:?]
	at net.minecraft.network.syncher.SynchedEntityData.pack(SynchedEntityData.java:168) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.write(ClientboundSetEntityDataPacket.java:33) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[prismarine-1.18.2.jar:git-Prismarine-"d609343"]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[prismarine-1.18.2.jar:git-Prismarine-"d609343"]
	at jdk.internal.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.viaversion.viaversion.util.PipelineUtil.callEncode(PipelineUtil.java:93) ~[ViaVersion-4.2.2-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:71) ~[ViaVersion-4.2.2-SNAPSHOT.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at de.sportkanone123.clientdetector.spigot.packetevents.injector.modern.PlayerChannelHandlerModern.write(PlayerChannelHandlerModern.java:54) ~[ClientDetector.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:88) ~[TAB.v3.1.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at xuan.cat.fartherviewdistance.code.branch.v18.Branch_18_Minecraft$1.write(Branch_18_Minecraft.java:102) ~[FartherViewDistance-LATEST-[9.2.3].jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:195) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:462) ~[?:?]
	at net.minecraft.network.Connection.lambda$writePacket$10(Connection.java:431) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Bug Description

If an error occurs, all players will be disconnected

older, 4.2.1, dev 

### Steps to Reproduce

just use viaversion

### Expected Behavior

hmm

### Additional Server Info

There is nothing special

FartherViewDistance, Viabackward, Protocollib 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Prismarine--%22d609343%22%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Prismarine--%22d609343%22%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (4.2.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.2.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.2.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.2.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Not a Via issue

**Comment by IPECTER** [comment]
> Not a Via issue

Then, can you tell me the related problems, solutions, or information? I've been suffering from this for half a year

**Comment by kennytv** [comment]
Probably some plugin sending bad packets directly or with ProtocolLib. do binary search in removing/readding plugins to find which one it is

**Comment by IPECTER** [comment]
> Probably some plugin sending bad packets directly or with ProtocolLib. do binary search in removing/readding plugins to find which one it is

thx!
