### ISSUE TITLE
com.viaversion.viaversion.exception.InformativeException

### ISSUE THREAD

**Issue by xFr33z3** [ViaVersion/ViaVersion#2892]
### `/viaversion dump` Output

https://dump.viaversion.com/525bd14aaaa3efc5b9caa6ca125301bfb1785d7d2b93e11b34d1dc66e73beeee

### Console Error

```
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: GAME_PROFILE, Type: String, Data: [Pair{Type|UUID, 24613662-6332-3036-322d-613033652d33}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.1-98.jar:3.1.1]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: GAME_PROFILE, Type: String, Data: [Pair{Type|UUID, 24613662-6332-3036-322d-613033652d33}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(18) + length(100) exceeds writerIndex(49): PooledUnsafeDirectByteBuf(ridx: 18, widx: 49, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[velocity-3.1.1-98.jar:3.1.1]
        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[velocity-3.1.1-98.jar:3.1.1]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:54) ~[?:?]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:140) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity-3.1.1-98.jar:3.1.1]
        ... 27 more

```

### Bug Description

I cannot connect to the velocity proxy using 1.8 minecraft client.

### Steps to Reproduce

1. Login with 1.8 client

### Expected Behavior

Join

### Additional Server Info

I am using Velocity Proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.1](https://img.shields.io/badge/Platform-velocity%203.1.1-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards-Outdated!-red?style=flat-square) </br>
