### ISSUE TITLE
1.8 client disconnected when connecting to 1.18

### ISSUE THREAD

**Issue by wifi-left** [ViaVersion/ViaVersion#2908]
### `/viaversion dump` Output

https://dump.viaversion.com/27e48ce19e7a4726e18b6db91b5c04f207c7173a31abe11a13364d205d745e3a

### Console Error

```
[00:03:17] [Netty Server IO #5/WARN]: ERROR IN Protocol1_12_2To1_13 IN REMAP OF SET_SLOT (0x17)
[00:03:17] [Netty Server IO #5/INFO]: Failed to sent packet
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$8 (Anonymous)}
Actual Error: 
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:214) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10761(class_2535.java:206) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$8 (Anonymous)}
Actual Error: 
Caused by: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.libs.opennbt.tag.builtin.NumberTag.asInt()" because the return value of "com.viaversion.viaversion.libs.opennbt.tag.builtin.CompoundTag.get(String)" is null
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13.rewriteEnchantmentsToClient(BlockItemPackets1_13.java:660) ~[ViaBackwards-4.2.1.jar:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13.handleItemToClient(BlockItemPackets1_13.java:595) ~[ViaBackwards-4.2.1.jar:?]
        at com.viaversion.viaversion.rewriter.ItemRewriter.lambda$itemToClientHandler$2(ItemRewriter.java:357) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:218) ~[viaversion-4.2.1-df0f35a701265c3.jar:?]
        at com.viaversion.fabric.common.handler.FabricEncodeHandler.encode(FabricEncodeHandler.java:32) ~[viafabric-0.4.6+266-main.jar:?]
        at com.viaversion.fabric.common.handler.FabricEncodeHandler.encode(FabricEncodeHandler.java:14) ~[viafabric-0.4.6+266-main.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[netty-all-4.1.68.Final.jar:?]
        ... 20 more
```

### Bug Description

Get on the pressure plate and trigger the command.

### Steps to Reproduce

1. Login with a 1.8.9 client
2. Get on the pressure plate
3. Server error. Client is kicked out.

### Expected Behavior

Clients should not be kicked out.

### Additional Server Info

Fabric 1.18.2 Server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
Can you try updating viafabric to [latest](https://www.curseforge.com/minecraft/mc-mods/viafabric/files/3808622) to see if it persists?

**Comment by kennytv** [comment]
You have an item with invalid enchantment data somewhere.

**Comment by wifi-left** [comment]
> Can you try updating viafabric to [最新](https://www.curseforge.com/minecraft/mc-mods/viafabric/files/3808622) to see if it persists including [ViaRewind](https://ci.viaversion.com/view/ViaRewind/job/ViaRewind)?
The latest version(
[main] ViaFabric 0.4.7+3-main, ViaRewind-2.0.3-SNAPSHOT.jar, ViaBackwards-4.2.1.jar) cannot run on fabric server.
After he started the server, he reported an error:
```
[08:43:49] [Via-Mappingloader-0/ERROR]: Error during mapping loading of Protocol1_12_2To1_13
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.lang.ClassCastException: class com.viaversion.viaversion.libs.gson.JsonArray cannot be cast to class com.viaversion.viaversion.libs.gson.JsonObject (com.viaversion.viaversion.libs.gson.JsonArray and com.viaversion.viaversion.libs.gson.JsonObject are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @9629756)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at java.base/java.lang.Thread.run(Thread.java:833)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]: Caused by: java.lang.ClassCastException: class com.viaversion.viaversion.libs.gson.JsonArray cannot be cast to class com.viaversion.viaversion.libs.gson.JsonObject (com.viaversion.viaversion.libs.gson.JsonArray and com.viaversion.viaversion.libs.gson.JsonObject are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @9629756)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at com.viaversion.viaversion.libs.gson.JsonObject.getAsJsonObject(JsonObject.java:192)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.data.BackwardsMappings.loadVBExtras(BackwardsMappings.java:53)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at com.viaversion.viabackwards.api.data.BackwardsMappings.loadExtras(BackwardsMappings.java:78)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at com.viaversion.viaversion.api.data.MappingDataBase.load(MappingDataBase.java:111)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.Protocol1_12_2To1_13.lambda$registerPackets$0(Protocol1_12_2To1_13.java:60)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.lambda$addMappingLoaderFuture$1(ProtocolManagerImpl.java:456)
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
[08:43:49] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'viafabric-mc118'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.6.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.NoSuchFieldError: typeMappings
        at com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.mapTypes(EntityRewriterBase.java:149) ~[ViaBackwards-4.2.1.jar:?]
        at com.viaversion.viabackwards.protocol.protocol1_13_2to1_14.packets.EntityPackets1_14.registerRewrites(EntityPackets1_14.java:351) ~[ViaBackwards-4.2.1.jar:?]
        at com.viaversion.viaversion.api.rewriter.RewriterBase.register(RewriterBase.java:37) ~[viaversion-4.3.0-1.19-pre3-SNAPSHOT-11e81fc081033516.jar:?]
        at com.viaversion.viabackwards.protocol.protocol1_13_2to1_14.Protocol1_13_2To1_14.registerPackets(Protocol1_13_2To1_14.java:73) ~[ViaBackwards-4.2.1.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:76) ~[viaversion-4.3.0-1.19-pre3-SNAPSHOT-11e81fc081033516.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:187) ~[viaversion-4.3.0-1.19-pre3-SNAPSHOT-11e81fc081033516.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:181) ~[viaversion-4.3.0-1.19-pre3-SNAPSHOT-11e81fc081033516.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:93) ~[ViaBackwards-4.2.1.jar:?]
        at com.viaversion.viabackwards.ViaFabricAddon.run(ViaFabricAddon.java:38) ~[ViaBackwards-4.2.1.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.viaversion.fabric.mc118.ViaFabric.onInitialize(ViaFabric.java:79) ~[viafabric-mc118-0.4.7+3-main-f58a3ad94899123a.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
        ... 7 more
[08:43:49] [Via-Mappingloader-0/INFO]: [STDERR]:        ... 5 more
```
The dump provided by other mods above is the same.

**Comment by creeper123123321** [comment]
Viabackwards version is incompatible with the bundled viaversion
