### ISSUE TITLE
Kicked from server

### ISSUE THREAD

**Issue by Mathildeuh** [ViaVersion/ViaVersion#2911]
### `/viaversion dump` Output

https://dump.viaversion.com/cd1d23619d1a9c7423a8eab702b9fffed8f4dc33feda55c5715643e3bdc3d8c0

### Console Error

```
[17:08:32 INFO]: [server connection] Mathildeuh -> limbo has connected
[17:08:32 WARN] [viaversion]: ERROR IN BaseProtocol1_16 IN REMAP OF 0x02->0x02
[17:08:32 ERROR]: [server connection] Mathildeuh -> limbo: exception encountered in com.velocitypowered.proxy.connection.backend.LoginSessionHandler@1d5c956e
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: GAME_PROFILE, Type: String, Data: [Pair{Type|UUID, 24323564-3836-6465-312d-313633342d33}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: GAME_PROFILE, Type: String, Data: [Pair{Type|UUID, 24323564-3836-6465-312d-313633342d33}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(18) + length(49) exceeds writerIndex(42): PooledUnsafeDirectByteBuf(ridx: 18, widx: 42, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:54) ~[?:?]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:140) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        ... 25 more
[17:08:32 INFO]: [server connection] Mathildeuh -> limbo has disconnected
[17:08:32 ERROR]: [connected player] Mathildeuh (/81.220.55.37:39199): unable to connect to server limbo
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: GAME_PROFILE, Type: String, Data: [Pair{Type|UUID, 24323564-3836-6465-312d-313633342d33}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: GAME_PROFILE, Type: String, Data: [Pair{Type|UUID, 24323564-3836-6465-312d-313633342d33}], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2}
Actual Error: 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(18) + length(49) exceeds writerIndex(42): PooledUnsafeDirectByteBuf(ridx: 18, widx: 42, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:54) ~[?:?]
        at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:140) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:118) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:298) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:277) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:230) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Velocity.jar:3.1.2-SNAPSHOT (git-377e6b66-b140)]
        ... 25 more
[17:08:32 INFO]: [connected player] Mathildeuh (/81.220.55.37:39199) has disconnected: Unable to connect you to limbo. Please try again later.
```

### Bug Description

Just kicked from the server

### Steps to Reproduce

Install viaversion with velocity and connect with 1.8.8

### Expected Behavior

0

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--377e6b66--b140%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--377e6b66--b140%29-3498db?style=flat-square) </br>![ViaVersion (4.2.1): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.2.1)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>

**Comment by HowardZHY** [comment]
try dev builds

**Comment by FormallyMyles** [comment]
Please try the latest, also can you replicate without other plugins on velocity?
