### ISSUE TITLE
Right clicking interactable items kicks players

### ISSUE THREAD

**Issue by Packsolite** [ViaVersion/ViaVersion#2922]
### `/viaversion dump` Output

https://dump.viaversion.com/bed9669444207b328f7b9d8601cbc5e9a6aa90dc3f6dfc58ab157921f62e332c

### Console Error

```
[01:40:13] [epollEventLoopGroup-3-8/WARN]: [ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF PLAYER_BLOCK_PLACEMENT (0x30)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: PLAYER_BLOCK_PLACEMENT, Type: VarInt, Data: [Pair{Type|VarInt, 0}, Pair{Type|Position, Position{x=73, y=18, z=346}}, Pair{Type|VarInt, 1}, Pair{Type|Float, 0.5818433}, Pair{Type|Float, 0.5}, Pair{Type|Float, 0.016531976}, Pair{Type|Boolean, false}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.InventoryPackets$3 (Anonymous), Packet ID: 46}
Actual Error: 
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: PLAYER_BLOCK_PLACEMENT, Type: VarInt, Data: [Pair{Type|VarInt, 0}, Pair{Type|Position, Position{x=73, y=18, z=346}}, Pair{Type|VarInt, 1}, Pair{Type|Float, 0.5818433}, Pair{Type|Float, 0.5}, Pair{Type|Float, 0.016531976}, Pair{Type|Boolean, false}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.InventoryPackets$3 (Anonymous), Packet ID: 46}
Actual Error: 
[01:40:13] [epollEventLoopGroup-3-8/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(1) exceeds writerIndex(24): PooledUnsafeDirectByteBuf(ridx: 24, widx: 24, cap: 256)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:70)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.InventoryPackets.lambda$sequenceHandler$0(InventoryPackets.java:103)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:376)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformServerbound(UserConnectionImpl.java:297)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(BukkitDecodeHandler.java:55)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[01:40:13] [epollEventLoopGroup-3-8/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Bug Description

Right clicking a block kicks the player on 1.8.9 server behind bungeecord.

### Steps to Reproduce

1. Setup ViaVersion 4.3.1 on 1.8.9 behind bungeecord
2. Set yourself to survival
3. Rightclick any block with any item

### Expected Behavior

To not break the protocol

### Additional Server Info

Waterfall, commit 7d0c0e

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--NachoSpigot--a880946%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--NachoSpigot--a880946%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.3.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
try on Paper, Nacho could break things

**Comment by FormallyMyles** [comment]
Would you be able to copy your server & test without other plugins and confirm whether this still happens?

**Comment by Packsolite** [comment]
> Would you be able to copy your server & test without other plugins and confirm whether this still happens?

Also happens with vanilla spigot (1.8.8-R0.1) and without any plugins except ViaVer.
