### ISSUE TITLE
In bungeerecord, it seems that you can't join the 1.18.2 sub server using 1.8.9

### ISSUE THREAD

**Issue by xiaobao4909** [ViaVersion/ViaVersion#2993]
### `/viaversion dump` Output

> viaversion dump [18:56:20 INFO]: We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/8f8dc477b4ae96aff3873b26868bf232f8fe2d2c652fc40efe82c9609c403544 >

### Console Error

[18:21:36 INFO]: [/hide|hide] <-> DownstreamBridge <-> [Lobby] has disconnected
[18:21:36 WARN] [ViaVersion]: ERROR IN Protocol1_10To1_11 IN REMAP OF TITLE (0x45)
[18:21:36 ERROR]: [/hide|hide] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_10to1_11.packets.PlayerPackets1_11$2 (Anonymous)}
Actual Error:
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:184) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:154) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:122) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viabackwards.protocol.protocol1_10to1_11.packets.PlayerPackets1_11$2 (Anonymous)}
Actual Error:
Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "text" is null
        at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.component(LegacyComponentSerializerImpl.java:365) ~[?:?]
        at com.viaversion.viaversion.libs.kyori.adventure.text.flattener.ComponentFlattenerImpl.lambda$flattener$2(ComponentFlattenerImpl.java:114) ~[?:?]
        at com.viaversion.viaversion.libs.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:92) ~[?:?]
        at com.viaversion.viaversion.libs.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:75) ~[?:?]
        at com.viaversion.viaversion.libs.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:306) ~[?:?]
        at com.viaversion.viabackwards.protocol.protocol1_10to1_11.packets.PlayerPackets1_11$2.lambda$registerMap$0(PlayerPackets1_11.java:57) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:55) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[WaterFall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:e1ad9a5:497]
        ... 49 more
[18:21:36 INFO]: [/hide|hide] -> UpstreamBridge has disconnected

### Bug Description

In bungeerecord, it seems that you can't join the 1.18.2 sub server using 1.8.9

### Steps to Reproduce

Appears when players join the server using 1.8.9

### Expected Behavior

Hope to join normally

### Additional Server Info

![image](https://user-images.githubusercontent.com/92622663/176881860-01a9512a-7559-49ad-b400-585e683dae35.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ae1ad9a5%3A497](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ae1ad9a5%3A497-3498db?style=flat-square) </br>![ViaVersion (4.3.1): 11 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.0): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.3.0)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by xiaobao4909** [comment]
> ![平台： git%3AWaterfall--Bootstrap%3A1.19--R0.1-SNAPSHOT%3Ae1ad9a5%3A497](https://camo.githubusercontent.com/fd0a885c7247f477521ec1f5d039a81e6d33368b0f08f75258ecc7373e1c7da4/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d676974253341576174657266616c6c2d2d426f6f747374726170253341312e31392d2d52302e312d2d534e415053484f54253341653161643961352533413439372d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion （4.3.1）：在 master 后面有 11 个提交](https://camo.githubusercontent.com/a80def3f6508dc8d4c9a6ddc309217506ea4670f54a25554c047c55c13b3340f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e332e31292d3131253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards（4.3.0）：9 个提交在 master 后面](https://camo.githubusercontent.com/205f009b90731be89c529dff1dfd679352e43858e87fe0c4348dc1acc2cda515/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e332e30292d39253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaRewind（2.0.3-SNAPSHOT）：即使使用主站](https://camo.githubusercontent.com/ce783ec7b5bb847f001a9bee0283afa3cea5427d7f4a7dd077cdb04f1f38705b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028322e302e332d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) 请尝试 https://ci.viaversion.com/ **最新版本**

我已经是最新版本了

**Comment by xiaobao4909** [comment]
> ![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Ae1ad9a5%3A497](https://camo.githubusercontent.com/fd0a885c7247f477521ec1f5d039a81e6d33368b0f08f75258ecc7373e1c7da4/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d676974253341576174657266616c6c2d2d426f6f747374726170253341312e31392d2d52302e312d2d534e415053484f54253341653161643961352533413439372d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.3.1): 11 commits behind master](https://camo.githubusercontent.com/a80def3f6508dc8d4c9a6ddc309217506ea4670f54a25554c047c55c13b3340f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e332e31292d3131253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.3.0): 9 commits behind master](https://camo.githubusercontent.com/205f009b90731be89c529dff1dfd679352e43858e87fe0c4348dc1acc2cda515/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e332e30292d39253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://camo.githubusercontent.com/ce783ec7b5bb847f001a9bee0283afa3cea5427d7f4a7dd077cdb04f1f38705b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028322e302e332d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) Please try the **latest** build(s) from https://ci.viaversion.com/

I'm already the latest version

**Comment by Jo0001** [comment]
No you are not. Please download them from https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.3.2-SNAPSHOT.jar
and
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/build/libs/ViaBackwards-4.3.1-SNAPSHOT.jar

Also this issue is caused by a plugin sending invalid data
