### ISSUE TITLE
Error spamming in BungeeCord(Waterfall) server console

### ISSUE THREAD

**Issue by devendrapoonia** [ViaVersion/ViaVersion#3012]
### `/viaversion dump` Output

https://dump.viaversion.com/8ca1b7840b259371c6f26bc65d8be70ff3a799e993ba681a9cc4cedddca7b437

### Console Error

```
[21:08:28 ERROR]: java.lang.IllegalArgumentException: Unhandled metadata: Metadata{id=18, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@4dba2106, value=com.viaversion.viaversion.api.minecraft.VillagerData@1bc5c8f1}
[21:08:28 ERROR]:       at com.viaversion.viabackwards.protocol.protocol1_13_2to1_14.packets.EntityPackets1_14.lambda$registerRewrites$10(EntityPackets1_14.java:494)
[21:08:28 ERROR]:       at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:121)
[21:08:28 ERROR]:       at com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.handleMetadata(EntityRewriterBase.java:67)
[21:08:28 ERROR]:       at com.viaversion.viabackwards.api.rewriters.LegacyEntityRewriter$3.lambda$registerMap$0(LegacyEntityRewriter.java:106)
[21:08:28 ERROR]:       at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[21:08:28 ERROR]:       at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[21:08:28 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[21:08:28 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[21:08:28 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[21:08:28 ERROR]:       at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[21:08:28 ERROR]:       at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[21:08:28 ERROR]:       at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[21:08:28 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:55)
[21:08:28 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:31)
[21:08:28 ERROR]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[21:08:28 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[21:08:28 ERROR]:       at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[21:08:28 ERROR]:       at com.lahuca.botsentry.bungee.n.write(Unknown Source)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[21:08:28 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[21:08:28 ERROR]:       at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57)
[21:08:28 ERROR]:       at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:184)
[21:08:28 ERROR]:       at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:154)
[21:08:28 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:122)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:28 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:28 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:28 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:28 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[21:08:28 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
[21:08:28 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
[21:08:28 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:08:28 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:08:28 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:08:28 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[21:08:28 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[21:08:28 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
[21:08:28 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
[21:08:28 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
[21:08:28 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[21:08:28 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[21:08:28 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:08:28 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

### Bug Description

An error is displaying in console again and again.

### Steps to Reproduce

1. Install Waterfall
2. Install all Via plugins
3. There should be an error

### Expected Behavior

There should be no error in console and everything should run smoothly

### Additional Server Info

Errors are spamming in console of bungeecord server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Afc30291%3A498](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3Afc30291%3A498-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.3.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Most likely a plugin sending bad metadata - try without other plugins to see if it still happens, if so, we'll reopen
