### ISSUE TITLE
ViaBack 4.3.1 & GadgetsMenu

### ISSUE THREAD

**Issue by VozikCZE** [ViaVersion/ViaVersion#3013]
### `/viaversion dump` Output

https://dump.viaversion.com/9a4dd488c229b178791a794881f1df71668c5c6314330cb9d93dd6ab8960666e

### Console Error

```
[12:03:20] [Netty Epoll Server IO #2/WARN]: [ViaVersion] ERROR IN Protocol1_18_2To1_19 IN REMAP OF SYSTEM_CHAT (0x5F)
[12:03:20] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:03:20] [Netty Epoll Server IO #2/WARN]: {Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.Protocol1_18_2To1_19$6 (Anonymous)}
[12:03:20] [Netty Epoll Server IO #2/WARN]: Actual Error: 
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at TAB.v3.1.2.jar//me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:91)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:463)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.lambda$writePacket$11(NetworkManager.java:437)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:03:20] [Netty Epoll Server IO #2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:03:20] [Netty Epoll Server IO #2/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[12:03:20] [Netty Epoll Server IO #2/WARN]: {Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.Protocol1_18_2To1_19$6 (Anonymous)}
```

### Bug Description

Using ViaBackwards 4.3.1 & GadgetsMenu on 1.19 server is causing players kicking when someone open mystery box.

### Steps to Reproduce

1. Use ViaBack 4.3.1
2.  Open mysterybox from gadgets menu

### Expected Behavior

Player shouldn't be kicked, obviously

### Additional Server Info

https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-19-free.10885/

This problem is only with version 4.3.1.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1684%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Purpur--1684%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.3.2-SNAPSHOT): 4 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.3.2--SNAPSHOT)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.3.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.3.1)-Even%20with%20master-brightgreen?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
That's most likely the plugin sending bad chat packets
