### ISSUE TITLE
控制台显示错误 玩家无感觉

### ISSUE THREAD

**Issue by xiaobao4909** [ViaVersion/ViaVersion#3025]
### `/viaversion dump` Output

https://dump.viaversion.com/3ac6718a0b1d042a516797c0587c3c86cc975946f69b14479368a6f23a8f17d5

### Console Error

```
Put the paste.gg link or text here.
```
[20:04:31 ERROR]: java.util.NoSuchElementException: com.viaversion.viaversion.protocols.protocol1_9to1_8.Protocol1_9To1_8
[20:04:31 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.constructPacket(PacketWrapperImpl.java:288)
[20:04:31 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:253)
[20:04:31 ERROR]:       at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send(PacketWrapperImpl.java:241)
[20:04:31 ERROR]:       at com.viaversion.viaversion.api.protocol.packet.PacketWrapper.send(PacketWrapper.java:179)
[20:04:31 ERROR]:       at com.viaversion.viaversion.protocols.protocol1_9to1_8.storage.EntityTracker1_9.sendTeamPacket(EntityTracker1_9.java:321)
[20:04:31 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.checkServerChange(BungeeServerHandler.java:272)
[20:04:31 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.onServerConnected(BungeeServerHandler.java:115)
[20:04:31 ERROR]:       at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
[20:04:31 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:04:31 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[20:04:31 ERROR]:       at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[20:04:31 ERROR]:       at net.md_5.bungee.event.EventBus.post(EventBus.java:50)
[20:04:31 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466)
[20:04:31 ERROR]:       at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:219)
[20:04:31 ERROR]:       at net.md_5.bungee.protocol.packet.Login.handle(Login.java:228)
[20:04:31 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:04:31 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:04:31 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:04:31 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:04:31 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[20:04:31 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:04:31 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:04:31 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:04:31 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20:04:31 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[20:04:31 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
[20:04:31 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
[20:04:31 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
[20:04:31 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[20:04:31 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[20:04:31 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:04:31 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

### Bug Description

后端服务器报此错误

### Steps to Reproduce

未知

### Expected Behavior

错误应该不会显示 玩家正常

### Additional Server Info

![image](https://user-images.githubusercontent.com/92622663/179220790-e3919e10-7fab-453a-a6ab-7dc6935b3067.png)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by HowardZHY** [comment]
Translate: Console error without abnormal ingame behavior. Server console error. Unknown cause.

**Comment by HowardZHY** [comment]
@xiaobao4909 Don't use Chinese to comment things on github.

**Comment by Kichura** [comment]
Very likely bad bungeecord plugins, Do a binary search on those and see if the issues persist.

**Comment by HowardZHY** [comment]
try dev builds and remove some antibot plugin

**Comment by xiaobao4909** [comment]
> @xiaobao4909不要用中文在github上评论事情。

Oh, sorry, I forgot
