### ISSUE TITLE
Error when on Velocity = Kicks on Chat

### ISSUE THREAD

**Issue by Strahilchu** [ViaVersion/ViaVersion#3046]
### `/viaversion dump` Output

https://dump.viaversion.com/40b4d97957daacca2f856e670ec3f93c7ed91816c72c2f846db0cca73058d2a9

### Console Error

```
[19:03:07 INFO]: [connected player] Strahill (/) has disconnected: An internal error occurred in your connection.
[19:03:07 ERROR]: [connected player] Strahill (/): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@50c3b193
java.lang.NullPointerException: Cannot invoke "com.velocitypowered.api.proxy.crypto.IdentifiedKey.getSignedPublicKey()" because "signer" is null
        at com.velocitypowered.proxy.protocol.packet.chat.PlayerCommand.signedContainer(PlayerCommand.java:169) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handle(ClientPlaySessionHandler.java:237) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at com.velocitypowered.proxy.protocol.packet.chat.PlayerCommand.handle(PlayerCommand.java:175) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:142) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Bug Description

When typing a chat message, you get kicked from the game.

### Steps to Reproduce

Put ViaVersion on Velocity proxy, join game, type in chat.

### Expected Behavior

No error/kick

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.0)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by mrfloris** [comment]
Happens without velocity as well. Paper 1.19.0 with 1.19.1 vanilla client. (well, they claim they are vanilla)

**Comment by CircusCow** [comment]
Also experiencing this. Not sure if it's a velocity issue or viaversion.

**Comment by Strahilchu** [comment]
> Also experiencing this. Not sure if it's a velocity issue or viaversion.

I reckon it's a bit of both

**Comment by kennytv** [comment]
Velocity needs to update, else things break

**Comment by Eurphus** [comment]
Can confirm it only occurs on a 1.19.1 client, on a 1.17 it's completely fine. Have latest viaversion and velocity. Does not happen with latest geyser clients. Exact same error pasted above.

**Comment by Fenix5534** [comment]
Please help I can't write chat on grief server

**Comment by Fenix5534** [comment]
Version minecraft 1.12.2

**Comment by Fenix5534** [comment]
Responds to commands, but simply does not respond to text in the chat
