### ISSUE TITLE
Some players seemingly cannot connect with 1.19.1

### ISSUE THREAD

**Issue by mrfloris** [ViaVersion/ViaVersion#3047]
### `/viaversion dump` Output

https://dump.viaversion.com/15bf7e5e04fb553d943d781130c534cb74abfa5cf89117eae1aae623d7348541

### Console Error

```
[21:19:09 WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19 IN REMAP OF 0x00->0x00
[21:19:09 WARN]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
[21:19:09 WARN]: {Packet Type: null, Type: UUID, Data: [Pair{Type|String, dburd126}, Pair{Type|ProfileKey, null}], Source 0: com.viaversion.viaversion.protocols.protocol1_19_1to1_19.Protocol1_19_1To1_19$7 (Anonymous), Packet ID: 0}
[21:19:09 WARN]: Actual Error:
[21:19:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
[21:19:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:19:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[21:19:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:19:09 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:19:09 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[21:19:09 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[21:19:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[21:19:09 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[21:19:09 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[21:19:09 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
[21:19:09 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
[21:19:09 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
[21:19:09 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[21:19:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[21:19:09 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:19:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:19:09 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/

212:54579 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException
```

### Bug Description

some players can connect, others cannot and the console shows the exception errors.

### Steps to Reproduce

i suspect they use modded client, hack clients, whatever, they obviously wont tell me "sure vanilla"

### Expected Behavior

connect without errors

### Additional Server Info

```
This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
You are running the latest version
Previous version: git-Paper-78 (MC: 1.19)
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--81%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-git--Paper--81%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.4.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.0)-Even%20withmaster-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
That might be the people removing their key on purpose, lol.

**Comment by turnolos** [comment]
We have this same error

**Comment by Skjolberg** [comment]
+1

**Comment by zlAquiles** [comment]
+1

**Comment by creeper123123321** [comment]
Is the server using offline mode?

**Comment by mrfloris** [comment]
Mine? No.

**Comment by turnolos** [comment]
> 

No, it is not.

**Comment by kennytv** [comment]
Are you behind TCPShield or any kind of other upper layer? Definitely just looks like bad packet data

**Comment by mrfloris** [comment]
Aaah i've asked around.

- they all say vanilla client 1.19.1 with vanilla launcher
- now that you mention tcpshield, I've asked: they are on the other route via cosmicguard. (using it as alt route, not as a proxy to hide network or servers behind)
(1moreblock.com (direct host) vs play.1moreblock.com (which is cosmic)

**Comment by mrfloris** [comment]
```
[16:26:46 INFO]: /185.199.94.147:60453 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(829) + length(1) exceeds writerIndex(829): PooledUnsafeDirectByteBuf(ridx: 829, widx: 829, cap: 829)
```
Yeah, without viaversion the cosmicguard wont be able to be used when require secure profile is set to true. so it's not really a viaversion issue i guess.

**Comment by mrfloris** [comment]
Despite that it's not a viaversion issue, thank you all for your input, and I am glad I was at least able to narrow it down. Hopefully cosmicguard updates soon to support this so people using their service can play on 1.19.1 again.
