### ISSUE TITLE
ERROR IN Protocol1_19_1To1_19 IN REMAP OF JOIN_GAME (0x23)

### ISSUE THREAD

**Issue by WieszczY85** [ViaVersion/ViaVersion#3055]
### `/viaversion dump` Output

https://dump.viaversion.com/9960ea9103abc1fd3d5f8e8c12f2762230e72b360e4fd527a2a5f5a44095fe0e

### Console Error

```
[04:22:56 INFO] [limboapi]: WieszczY (/146.70.107.137:63501) has connected to the LimboFilter Limbo
[04:22:56 WARN] [viaversion]: ERROR IN Protocol1_19_1To1_19 IN REMAP OF JOIN_GAME (0x23)
[04:22:56 ERROR]: [initial connection] /146.70.107.137:63501: exception encountered in com.velocitypowered.proxy.connection.client.AuthSessionHandler@1d55250f
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_19_1to1_19.Protocol1_19_1To1_19$5 (Anonymous)}
Actual Error:
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:230) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at net.elytrium.limboapi.server.LimboImpl.lambda$spawnPlayer$4(LimboImpl.java:227) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Source 0: com.viaversion.viaversion.protocols.protocol1_19_1to1_19.Protocol1_19_1To1_19$5 (Anonymous)}
Actual Error:
Caused by: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.libs.opennbt.tag.builtin.CompoundTag.get(String)" because the return value of "com.viaversion.viaversion.libs.opennbt.tag.builtin.CompoundTag.get(String)" is null
        at com.viaversion.viaversion.protocols.protocol1_19_1to1_19.Protocol1_19_1To1_19$5.lambda$registerMap$0(Protocol1_19_1To1_19.java:178) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:237) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:48) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[Velocity.jar:3.1.2-SNAPSHOT (git-6be344d9-b162)]
        ... 26 more
[04:22:56 INFO] [limboapi]: WieszczY (/146.70.107.137:63501) has disconnected from the LimboFilter Limbo
[04:22:56 INFO]: [initial connection] /146.70.107.137:63501 has disconnected
>

```

### Bug Description

Connection lost message when trying to enter the server

### Steps to Reproduce

Connection lost message when trying to enter the server

### Expected Behavior

The plugin works as expected

### Additional Server Info

 Velocity 3.1.2-SNAPSHOT (git-6be344d9-b162)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--6be344d9--b162%29-3498db?style=flat-square) </br>![ViaVersion (4.4.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.4.1)-Even%20withmaster-brightgreen?style=flat-square) </br>![ViaBackwards(4.4.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.4.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/)

**Comment by kennytv** [comment]
That means that your Velocity version does not support 1.19.1 clients yet or another plugin is sending bad registry data
