### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by Souipi** [ViaVersion/ViaVersion#3101]
### `/viaversion dump` Output

i can't

### Console Error

[13:52:18] [Server thread/ERROR]: Could not load 'plugins\ViaVersion-4.4.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NegativeArraySizeException: -1
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NegativeArraySizeException: -1
        at com.viaversion.viaversion.util.CommentStore.join(CommentStore.java:249) ~[?:?]
        at com.viaversion.viaversion.util.CommentStore.writeComments(CommentStore.java:183) ~[?:?]
        at com.viaversion.viaversion.util.Config.saveConfig(Config.java:124) ~[?:?]
        at com.viaversion.viaversion.util.Config.loadConfig(Config.java:115) ~[?:?]
        at com.viaversion.viaversion.util.Config.loadConfig(Config.java:66) ~[?:?]
        at com.viaversion.viaversion.util.Config.reloadConfig(Config.java:150) ~[?:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.reloadConfig(AbstractViaConfig.java:101) ~[?:?]
        at com.viaversion.viaversion.bukkit.platform.BukkitViaConfig.<init>(BukkitViaConfig.java:39) ~[?:?]
        at com.viaversion.viaversion.ViaVersionPlugin.<init>(ViaVersionPlugin.java:84) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:94) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 6 more

### Bug Description

Viaversion does not want to run on server startup

### Steps to Reproduce

Start a minecraft server on paper 1.12.2 with the build 1620

### Expected Behavior

The load of viaversion

### Additional Server Info

I use bungee with advancedban, luckperms, skinrestorer and spark

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
Follow the issue template
