### ISSUE TITLE
4.5.0 Snapshot Error shown on startup

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaVersion#3145]
### `/viaversion dump` Output

https://dump.viaversion.com/426ed2a9a9a011b7303e9a5c929e2ce69d53fb27f92d584a9c5f898074cbe746

### Console Error

[12:44:15 INFO]: [ViaVersion] Loading ViaVersion v4.5.0-22w42a-SNAPSHOT
[12:44:15 WARN]: com.viaversion.viaversion.libs.javassist.CannotCompileException: [source error] no such field: minecraftDecoder
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:84)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:50)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtMethod.make(CtMethod.java:140)
[12:44:15 WARN]:        at com.viaversion.viaversion.bukkit.classgenerator.ClassGenerator.addPSCompatibility(ClassGenerator.java:166)
[12:44:15 WARN]:        at com.viaversion.viaversion.bukkit.classgenerator.ClassGenerator.generate(ClassGenerator.java:86)
[12:44:15 WARN]:        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:114)
[12:44:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
[12:44:15 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
[12:44:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[12:44:15 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:44:15 WARN]: Caused by: compile error: no such field: minecraftDecoder
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.MemberResolver.lookupField(MemberResolver.java:321)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.MemberResolver.lookupFieldByJvmName(MemberResolver.java:307)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:904)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:831)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atExpr(TypeChecker.java:605)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.Expr.accept(Expr.java:71)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atCastExpr(TypeChecker.java:572)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.JvstTypeChecker.atCastExpr(JvstTypeChecker.java:116)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.CastExpr.accept(CastExpr.java:59)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:693)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atStmnt(CodeGen.java:360)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.Javac.compileMethod(Javac.java:175)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.Javac.compile(Javac.java:102)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:79)
[12:44:15 WARN]:        ... 9 more
[12:44:15 WARN]: com.viaversion.viaversion.libs.javassist.CannotCompileException: [source error] no such field: minecraftEncoder
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:84)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:50)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtMethod.make(CtMethod.java:140)
[12:44:15 WARN]:        at com.viaversion.viaversion.bukkit.classgenerator.ClassGenerator.addPSCompatibility(ClassGenerator.java:173)
[12:44:15 WARN]:        at com.viaversion.viaversion.bukkit.classgenerator.ClassGenerator.generate(ClassGenerator.java:87)
[12:44:15 WARN]:        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:114)
[12:44:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
[12:44:15 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
[12:44:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[12:44:15 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:44:15 WARN]: Caused by: compile error: no such field: minecraftEncoder
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.MemberResolver.lookupField(MemberResolver.java:321)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.MemberResolver.lookupFieldByJvmName(MemberResolver.java:307)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:904)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:831)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atExpr(TypeChecker.java:605)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.Expr.accept(Expr.java:71)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atCastExpr(TypeChecker.java:572)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.JvstTypeChecker.atCastExpr(JvstTypeChecker.java:116)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.CastExpr.accept(CastExpr.java:59)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:693)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:170)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.CallExpr.accept(CallExpr.java:49)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atStmnt(CodeGen.java:360)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.Javac.compileMethod(Javac.java:175)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.Javac.compile(Javac.java:102)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:79)
[12:44:15 WARN]:        ... 9 more
[12:44:15 WARN]: com.viaversion.viaversion.libs.javassist.CannotCompileException: [source error] cannot find constructor com.viaversion.viaversion.classgenerator.generated.BukkitEncodeHandler(com.viaversion.viaversion.api.connection.UserConnection,io.netty.handler.codec.MessageToByteEncoder)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:84)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:50)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtMethod.make(CtMethod.java:140)
[12:44:15 WARN]:        at com.viaversion.viaversion.bukkit.classgenerator.ClassGenerator.generate(ClassGenerator.java:102)
[12:44:15 WARN]:        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:114)
[12:44:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
[12:44:15 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
[12:44:15 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[12:44:15 WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:44:15 WARN]: Caused by: compile error: cannot find constructor com.viaversion.viaversion.classgenerator.generated.BukkitEncodeHandler(com.viaversion.viaversion.api.connection.UserConnection,io.netty.handler.codec.MessageToByteEncoder)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:777)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.TypeChecker.atNewExpr(TypeChecker.java:171)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.NewExpr.accept(NewExpr.java:75)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:266)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.compileExpr(CodeGen.java:253)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:689)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:443)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atStmnt(CodeGen.java:393)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.Javac.compileMethod(Javac.java:175)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.Javac.compile(Javac.java:102)
[12:44:15 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:79)
[12:44:15 WARN]:        ... 8 more
[12:44:15 INFO]: [ViaVersion] ViaVersion 4.5.0-22w42a-SNAPSHOT is now loaded, injecting!
[12:44:16 INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[12:44:16 INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[12:44:16 INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[12:44:16 INFO]: [ViaVersion] Loading block connection mappings ...
[12:44:16 INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[12:44:16 INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[12:44:16 INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[12:44:17 INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[12:44:17 INFO]: [ViaVersion] Loading 1.17 -> 1.18 mappings...
[12:44:17 INFO]: [ViaVersion] Loading 1.18 -> 1.19 mappings...
[12:44:17 INFO]: [ViaVersion] Loading 1.19 -> 1.19.3 mappings...

### Bug Description

Appears on server startup

### Steps to Reproduce

Zulu JDK 8u312
BurritoSpigot 1.8.8
Latest Via-Dev

### Expected Behavior

no error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--BurritoSpigot--%22700f01e%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.5.0-22w42a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.5.0--22w42a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
As old PS is no longer publicly available, I will not be updating support for it.

**Comment by HowardZHY** [comment]
This is weird, let me find out which commit caused it

PS: old ps can be found at https://github.com/ProtocolSupport/protocolsupport.github.io/tree/master/old/unsupported/ymmv/no_wget_script_for_you

**Comment by kennytv** [comment]
No need to search, it's because of the injection method change

**Comment by HowardZHY** [comment]
wait, although there's an error, it works fine ingame

So plz don't remove ps support, just warn instead as unlikely to provide further tech support

**Comment by HowardZHY** [comment]
the only change is 1.6.4 and below clients will be show as UNKNOWN with /viaver list

**Comment by kennytv** [comment]
The error should have already been fixed by the last commit shortly after the issue was closed, so I guess it's fine then

**Comment by HowardZHY** [comment]
wait, the startup error is this now with latest build
[21:00:06 INFO]: [ProtocolSupport] Using injected ServerConnection
[21:00:07 INFO]: [ViaVersion] Loading ViaVersion v4.5.0-22w42a-SNAPSHOT
[21:00:07 WARN]: com.viaversion.viaversion.libs.javassist.CannotCompileException: [source error] syntax error near "eEncoder<ByteBuf> ne"
[21:00:07 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:84)
[21:00:07 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:50)
[21:00:07 WARN]:        at com.viaversion.viaversion.libs.javassist.CtMethod.make(CtMethod.java:140)
[21:00:07 WARN]:        at com.viaversion.viaversion.bukkit.classgenerator.ClassGenerator.generate(ClassGenerator.java:92)
[21:00:07 WARN]:        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:114)
[21:00:07 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:298)
[21:00:07 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
[21:00:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[21:00:07 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:00:07 WARN]: Caused by: compile error: syntax error near "eEncoder<ByteBuf> ne"
[21:00:07 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.Parser.parseMember1(Parser.java:76)
[21:00:07 WARN]:        at com.viaversion.viaversion.libs.javassist.compiler.Javac.compile(Javac.java:98)
[21:00:07 WARN]:        at com.viaversion.viaversion.libs.javassist.CtNewMethod.make(CtNewMethod.java:79)
[21:00:07 WARN]:        ... 8 more
[21:00:07 INFO]: [ViaVersion] ViaVersion 4.5.0-22w42a-SNAPSHOT is now loaded, injecting!
[21:00:07 INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[21:00:07 INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[21:00:07 INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[21:00:07 INFO]: [ViaVersion] Loading block connection mappings ...
[21:00:08 INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[21:00:08 INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[21:00:08 INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[21:00:08 INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[21:00:08 INFO]: [ViaVersion] Loading 1.17 -> 1.18 mappings...
[21:00:08 INFO]: [ViaVersion] Loading 1.18 -> 1.19 mappings...
[21:00:08 INFO]: [ViaVersion] Loading 1.19 -> 1.19.3 mappings...
