### ISSUE TITLE
Can't use ViaVersion on Bungeecord/Flamecord

### ISSUE THREAD

**Issue by Zhuyuan0907** [ViaVersion/ViaVersion#3159]
### `/viaversion dump` Output

https://dump.viaversion.com/cbbc62644211f53e71198a06deed70ff5ff7c74ee50faacf5d5986663d18ff93

### Console Error

```
[15:05:57 INFO]: Enabled plugin ViaVersion version 4.4.2 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[15:05:57 INFO] [ViaVersion]: ViaVersion detected lowest supported version by the proxy: 1.7-1.7.5 (4)
[15:05:57 INFO] [ViaVersion]: Highest supported version by the proxy: 1.19.1/2 (760)
[15:05:57 ERROR] [ViaVersion]: ************************************************
[15:05:57 ERROR] [ViaVersion]: You are using unsupported software and may encounter unforeseeable issues.
[15:05:57 ERROR] [ViaVersion]: 
[15:05:57 ERROR] [ViaVersion]: We strongly advise against using FlameCord:
[15:05:57 ERROR] [ViaVersion]: You are using proxy software that intentionally breaks ViaVersion. Please use another proxy software or move ViaVersion to each backend server instead of the proxy.
[15:05:57 ERROR] [ViaVersion]: 
[15:05:57 ERROR] [ViaVersion]: We will not provide support in case you encounter issues possibly related to this software.
[15:05:57 ERROR] [ViaVersion]: ************************************************
[15:05:57 ERROR] [ViaVersion]: Error initializing BungeeServerHandler, try updating BungeeCord or ViaVersion!
[15:05:57 ERROR]: java.lang.ClassNotFoundException: net.md_5.bungee.entitymap.EntityMap
[15:05:57 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
[15:05:57 ERROR]:       at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
[15:05:57 ERROR]:       at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[15:05:57 ERROR]:       at java.base/java.lang.Class.forName0(Native Method)
[15:05:57 ERROR]:       at java.base/java.lang.Class.forName(Class.java:375)
[15:05:57 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.<clinit>(BungeeServerHandler.java:73)
[15:05:57 ERROR]:       at com.viaversion.viaversion.bungee.platform.BungeeViaLoader.load(BungeeViaLoader.java:64)
[15:05:57 ERROR]:       at com.viaversion.viaversion.ViaManagerImpl.onServerLoaded(ViaManagerImpl.java:157)
[15:05:57 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[15:05:57 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:05:57 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:05:57 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[15:05:58 INFO] [ViaVersion]: Loading block connection mappings ...
[15:05:58 INFO]: Enabled plugin ViaRewind version 2.0.2 by Gerrygames


[15:06:54 ERROR]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.channelWrapper" is null
[15:06:54 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.checkServerChange(BungeeServerHandler.java:281)
[15:06:54 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.onServerConnected(BungeeServerHandler.java:114)
[15:06:54 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:06:54 ERROR]:       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[15:06:54 ERROR]:       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:06:54 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:06:54 ERROR]:       at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[15:06:54 ERROR]:       at net.md_5.bungee.event.EventBus.post(EventBus.java:50)
[15:06:54 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:510)
[15:06:54 ERROR]:       at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:222)
[15:06:54 ERROR]:       at net.md_5.bungee.protocol.packet.Login.handle(Login.java:228)
[15:06:54 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:129)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:06:54 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:06:54 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:06:54 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:06:54 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336)
[15:06:54 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
[15:06:54 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
[15:06:54 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[15:06:54 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[15:06:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[15:06:54 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[15:06:54 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[15:06:54 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[15:06:54 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[15:06:54 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:06:54 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:06:54 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[15:06:54 WARN] [ViaVersion]: ERROR IN Protocol1_7_6_10TO1_8 IN REMAP OF JOIN_GAME (0x01)
[15:06:54 INFO]: [Zhuyuan_0907] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: JOIN_GAME, Type: Boolean, Data: [Pair{Type|Integer, 7150}, Pair{Type|Unsigned Byte, 0}, Pair{Type|Byte, 0}, Pair{Type|Unsigned Byte, 3}, Pair{Type|Unsigned Byte, 60}, Pair{Type|String, flat}], Source 0: de.gerrygames.viarewind.protocol.protocol1_7_6_10to1_8.packets.PlayerPackets$1 (Anonymous), Packet ID: 1 @ io.netty.handler.codec.MessageToMessageEncoder:107
[15:06:54 WARN]: No client connected for pending server!
```

### Bug Description

use 1.7.10, cannot join the server

### Steps to Reproduce

1.use 1.7.10 2.click the server 3.broken

### Expected Behavior

need's to join server

### Additional Server Info

Bungeecord/Flamecord
ViaVerison
ViaRewind

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.1.8](https://img.shields.io/badge/Platform-1.1.8-3498db?style=flat-square) </br>![Flamecord is not supported](https://img.shields.io/badge/Unsupported%20Platform%20-%20Please%20use%20Waterfall/Bungee%20instead%20or%20put%20all%20Via*%20plugins%20to%20the%20backend%20servers-orange?style=flat-square) </br>![ViaVersion (4.4.2): 14 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.4.2)-14%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.2): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.2)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
