### ISSUE TITLE
connection issue with 1.8 ~ 1.19.2 (1.19.3 is ok)

### ISSUE THREAD

**Issue by adalmo** [ViaVersion/ViaVersion#3164]
### `/viaversion dump` Output

https://dump.viaversion.com/2c1ee5a846e68d1b9b31b678d9dff51ca30dfeae770bbce18e9b5aa0f4c8f15b

### Console Error

[```
Put the paste.gg link or text here.
```
[20:45:56 WARN]: [ViaVersion] ERROR IN Protocol1_18_2To1_19 IN REMAP OF PLAYER_INFO (0x34)
[20:45:56 WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[20:45:56 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[20:45:56 WARN]: Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.EntityPackets1_19$5 (Anonymous), Source 1: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous)
[20:45:56 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:45:56 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:45:56 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:45:56 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[20:45:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[20:45:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[20:45:56 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:459)
[20:45:56 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433)
[20:45:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[20:45:56 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[20:45:56 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[20:45:56 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[20:45:56 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[20:45:56 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[20:45:56 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:45:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[20:45:56 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[20:45:56 WARN]: Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.EntityPackets1_19$5 (Anonymous), Source 1: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous)
[20:45:56 WARN]: Caused by: java.lang.NullPointerException: This packet does not have an input buffer.
[20:45:56 WARN]:        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:132)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181)
[20:45:56 WARN]:        at ViaBackwards-4.5.0.jar//com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.EntityPackets1_19$5.lambda$registerMap$0(EntityPackets1_19.java:214)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.constructPacket(PacketWrapperImpl.java:299)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:253)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send(PacketWrapperImpl.java:241)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.api.protocol.packet.PacketWrapper.send(PacketWrapper.java:179)
[20:45:56 WARN]:        at ViaBackwards-4.5.0.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3.lambda$registerMap$0(EntityPackets1_19_3.java:157)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:60)
[20:45:56 WARN]:        at ViaVersion-4.5.0.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:38)
[20:45:56 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:45:56 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[20:45:56 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[20:45:56 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[20:45:56 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[20:45:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[20:45:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[20:45:56 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:459)
[20:45:56 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433)
[20:45:56 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[20:45:56 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[20:45:56 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[20:45:56 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[20:45:56 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[20:45:56 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[20:45:56 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:45:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[20:45:56 INFO]: Terry lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.EntityPackets1_19$5 (Anonymous), Source 1: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous)
```
### Bug Description

they tried to join with 1.19.2 and other versions but 1.19.3 is fine to use and get disconnected with that msg 

### Steps to Reproduce

login with 1.19.2 (or any others without 1.19.3)
got disconnected with [20:45:56 INFO]: Terry lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.EntityPackets1_19$5 (Anonymous), Source 1: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous)

### Expected Behavior

they can't join with 1.19.2 ~ lower versions

### Additional Server Info

i am using paper#319 + velocity#198 builds and tried to use latest viaversion + viabackward (4.5.1) and same happening

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
Should be fixed by https://github.com/ViaVersion/ViaBackwards/commit/7c2845b884564e731c2d206fa001b306281a6c40
