### ISSUE TITLE
1.19.2 client login failed 

### ISSUE THREAD

**Issue by VIPWYH2004** [ViaVersion/ViaVersion#3180]
### `/viaversion dump` Output

https://dump.viaversion.com/055fd0e3aa625c253a9bc6e609e9d51da333997fdb847e9e976297879d54c145

### Console Error

https://paste.gg/ is maintenance
```
22:35:41 [信息] [WYH2004] <-> ServerConnector [login] has connected
22:35:41 [严重] [WYH2004] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Chat in phase GAME with direction TO_CLIENT
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
    at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Chat in phase GAME with direction TO_CLIENT
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:453)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:691)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 10 more
22:35:41 [信息] [WYH2004] disconnected with: EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Chat in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125
22:35:41 [信息] [WYH2004] -> UpstreamBridge has disconnected
22:35:41 [警告] No client connected for pending server!
22:35:41 [信息] [WYH2004] <-> ServerConnector [login] has disconnected
```

### Bug Description

The player failed to connect to the server using the 1.19.2 client
![screenshots](https://files.wyh2004.top/api/raw/?path=/%E5%9B%BE%E7%89%87/%E7%BD%91%E9%A1%B5%E5%9B%BE%E5%BA%8A/Minecraft20221221225049.png)

### Steps to Reproduce

1. Use [BungeeCord Build #1673](https://ci.md-5.net/job/BungeeCord/1673/) and Spigot 1.8.8
2. login with a 1.19.2 client
3. login into the server.
4. Player login failed 
5. Server throwing exceptional

### Expected Behavior

Login should just login without throwing exceptional 

### Additional Server Info

BungeeCord: Build #1673
Spigot: 1.8.8 latest
ViaVersion: 4.5.1

ViaVersion is only installed in BungeeCord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A41471da%3A1673](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A41471da%3A1673-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by VIPWYH2004** [comment]
The same error occurred with ViaVersion-4.5.2-SNAPSHOT

**Comment by HowardZHY** [comment]
move via to backends.
