### ISSUE TITLE
ERROR IN BaseProtocol1_16 IN REMAP OF 0x02->0x02

### ISSUE THREAD

**Issue by ItsALisName** [ViaVersion/ViaVersion#3189]
### `/viaversion dump` Output

https://dump.viaversion.com/f0f7de44e3fe11996460df1a82233d70bd0507a5b20b41efad7f8901a208719d

### Console Error

[connected player] UncurSempai (/85.174.202.70:15549): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@283ae326
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:230) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:315) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:150) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:75) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 1, widx: 3, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:39) ~[?:?]
        at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:31) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_16.passthroughLoginUUID(BaseProtocol1_16.java:29) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:137) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:237) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:48) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        ... 61 more

### Bug Description

Every time a player logs in (for each player), he is kicked from the server and gives this error, also not always when a player logs in, such moments happen during the game

### Steps to Reproduce

1. Log in to the server with ViaVersion installed on the Velocity core

### Expected Behavior

Fix this error when the player logs on to the server (or when he is already on the server)

### Additional Server Info

Я использую Velocity с установленными на нем плагинами: limboapi, limbofilter

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--c9e0e14e--b201%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--c9e0e14e--b201%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by ItsALisName** [comment]
I specified the old ones at the time, installed the new ones, checked, the same thing

**Comment by ItsALisName** [comment]
I will add a comment, some players kick when any damage is inflicted on them (it is unclear exactly how the players are divided, everyone has the same versions, but only certain ones kick)

**Comment by AVuTuVA** [comment]
Удали ViaVersion с прокси и поставь его на сервер..

**Comment by FormallyMyles** [comment]
This is a conflict from LimboFilter / API, so moving to backend is advised.

**Comment by alongw** [comment]
I also encountered this problem, I am Velocity+paper 1.19.2
Is using ViaVersion-4.5.2-SNAPSHOT
