### ISSUE TITLE
com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3. packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55

### ISSUE THREAD

**Issue by spookymgmt** [ViaVersion/ViaVersion#3193]
### `/viaversion dump` Output

https://dump.viaversion.com/8f41deb02d31d44f6850ad3130707ab2d7e041b272983398e2e953c105c864fb

### Console Error

```
[22:36:08] [Netty Epoll Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[22:36:08] [Netty Epoll Server IO #1/WARN]: Packet Type: PLAYER_INFO, Type: VarInt, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3 (Anonymous), Packet ID: 55
[22:36:08] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(51) + length(1) exceeds writerIndex(51): PooledUnsafeDirectByteBuf(ridx: 51, widx: 51, cap: 256)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:70)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaBackwards-4.5.1.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$3.lambda$registerMap$0(EntityPackets1_19_3.java:146)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:60)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.5.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:38)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at Vulcan-2.7.1 (1).jar//io.github.repooper.packetevents.Vulcan_kw.write(Vulcan_kw.java:60)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at MiniaturePets_v2.8.8-stable.jar//com.kirelcodes.miniaturepets.packetlisteners.PacketHandler.write(PacketHandler.java:41)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at FartherViewDistance-9.7.4 (1).jar//xuan.cat.fartherviewdistance.code.branch.v19.Branch_19_Minecraft$1.write(Branch_19_Minecraft.java:109)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:459)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:433)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[22:36:08] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:36:08] [Server thread/INFO]: Wallace080913 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
```

### Bug Description

Everything will be fine, and then this will completely randomly happen and no one can join the server.

### Steps to Reproduce

Join the server.

### Expected Behavior

Being able to join.

### Additional Server Info

Miniaturepets, Fartherviewdistance show up in the error, but it's neither of those.

I have this issue on my other server with this SAME exact error, and the only plugin in it is vulcan. Vulcan claims its 100% not them.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Pufferfish--53%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Pufferfish--53%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump
