### ISSUE TITLE
GamerProfile error

### ISSUE THREAD

**Issue by OJIEKCAHDP** [ViaVersion/ViaVersion#3202]
### `/viaversion dump` Output

https://dump.viaversion.com/e1430720147676ca6fe10c9f888a813be39073cffb82528489b6391f12c7e330

### Console Error

[22:11:50] [Netty epoll Worker #2/WARN] [viaversion]: ERROR IN BaseProtocol1_16 IN REMAP OF 0x02->0x02
[22:11:50] [Netty epoll Worker #2/INFO] [com.velocitypowered.proxy.connection.client.ConnectedPlayer]: [connected player] _s0r0k1n_ (ip233.ip-217-182-27.eu/217.182.27.233:52273) has disconnected: В вашем подключении произошла внутренняя ошибка.
[22:11:50] [Netty epoll Worker #2/ERROR] [com.velocitypowered.proxy.connection.MinecraftConnection]: [connected player] _s0r0k1n_ (ip233.ip-217-182-27.eu/217.182.27.233:52273): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@1af5a8e2
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:233) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:320) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:151) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:78) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2 (Anonymous), Packet ID: 2
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 1, widx: 3, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:39) ~[?:?]
	at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:31) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181) ~[?:?]
	at com.viaversion.viaversion.protocols.base.BaseProtocol1_16.passthroughLoginUUID(BaseProtocol1_16.java:29) ~[?:?]
	at com.viaversion.viaversion.protocols.base.BaseProtocol1_7$2$1.handle(BaseProtocol1_7.java:137) ~[?:?]
	at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292) ~[?:?]
	at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:237) ~[?:?]
	at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:48) ~[?:?]
	at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:30) ~[?:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[server.jar:3.2.0-SNAPSHOT (git-d9ee34fe-b219)]
	... 61 more

### Bug Description

Happens when you hit a player

### Steps to Reproduce

1. Login to minecraft server
2. Hit player
3. Player disconnected

### Expected Behavior

To prevent the player from being kicked

### Additional Server Info

I use Velocity latest version, and servers 1.12 and 1.19 versions. This bug working in all this versions.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--d9ee34fe--b219%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--d9ee34fe--b219%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by OJIEKCAHDP** [comment]
https://dump.viaversion.com/7336da0930101c1af829901205fc30f3b49b113cec7055e62615c22dba0a7eab

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--d9ee34fe--b219%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--d9ee34fe--b219%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Likely down to Limbo, move your plugins to the backend if you want to continue using them.
