### ISSUE TITLE
Players sometimes can't connect to the server when a bedrock player is on

### ISSUE THREAD

**Issue by cloakfox** [ViaVersion/ViaVersion#3207]
### `/viaversion dump` Output

https://dump.viaversion.com/9e3a0565d5526bda3d30afdef18954ce3b9242221453df2709c239773e11b406

### Console Error

```
https://gist.github.com/cloakfox/b6f8c924203917904fa019df9ef68f9a)
```

### Bug Description

Sometimes when a bedrock user is online in our hub/lobby server, other players can't connect to the server, they get disconnected with the console error above

we use geyser & floodgate to allow bedrock users to join the server, geyser runs on a waterfall (bungee) proxy
Viaversion runs on the paper server

Issue could be plugin related, I've not seen it happen on our other servers, it's just the hub at the moment I think.

### Steps to Reproduce

I have not been able to properly reproduce this with my bedrock alt account, I've experienced the same disconnects  when I catched these errors in console & quickly trying to connect to the lobby whilst the bedrock player that causes it is still online on the server.

1. Login with 1.19.2 client whilst a bedrock user is online

### Expected Behavior

 Being able to join without getting disconnected with a error message

### Additional Server Info

we use geyser & floodgate to allow bedrock users to join the server, geyser runs on a waterfall (bungee) proxy
run paper 1.19.2

currently run latest builds of ViaVersion, ViaBackwards & ViaRewind that are available on jenkins
Running correct version of protocollib too.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--petal--%22cc69154%22%20%28MC%3A%201.19.2%29](https://img.shields.io/badge/Platform-git--petal--%22cc69154%22%20%28MC%3A%201.19.2%29-3498db?style=flat-square) </br>![ViaVersion (4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.5.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.5.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by ShayPunter** [comment]
Just wanted to confirm this is also happening on our instance too with Velocity.

Dump Output: https://dump.viaversion.com/23126efbb354d21ab1eecb59bede879cc2d25b7352145e0ef080ab0b2a4c7293

Error Message:
[00:13:41 WARN] [viaversion]: ERROR IN Protocol1_19_3To1_19_1 IN REMAP OF PLAYER_INFO (0x37)
[00:13:41 ERROR]: [server connection] [B]_OrangesRgood -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@10d77ba
`Packet Type: PLAYER_INFO_UPDATE, Type: VarInt, Data: [Pair{Type|BitSet, {0, 1, 2, 3, 4, 5}}, Pair{Type|VarInt, 1}, Pair{Type|UUID, 00000000-0000-0000-0009-01fa15adc5a9}, Pair{Type|String, [B]_GraveDigger1}, Pair{Type|VarInt, 2}, Pair{Type|String, textures}, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, null}], Source 0: com.viaversion.viaversion.protocols.protocol1_19_3to1_19_1.packets.EntityPackets$3 (Anonymous), Packet ID: 54
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: PLAYER_INFO_UPDATE, Type: VarInt, Data: [Pair{Type|BitSet, {0, 1, 2, 3, 4, 5}}, Pair{Type|VarInt, 1}, Pair{Type|UUID, 00000000-0000-0000-0009-01fa15adc5a9}, Pair{Type|String, [B]_GraveDigger1}, Pair{Type|VarInt, 2}, Pair{Type|String, textures}, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, }, Pair{Type|String, null}], Source 0: com.viaversion.viaversion.protocols.protocol1_19_3to1_19_1.packets.EntityPackets$3 (Anonymous), Packet ID: 54
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(53) + length(1) exceeds writerIndex(53): PooledUnsafeDirectByteBuf(ridx: 53, widx: 53, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45) ~[?:?]
        at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:70) ~[?:?]
        at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135) ~[?:?]
        at com.viaversion.viaversion.protocols.protocol1_19_3to1_19_1.packets.EntityPackets$3.lambda$registerMap$0(EntityPackets.java:138) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:249) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:49) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:31) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        ... 29 more`


Our setup consists of having ViaVersion & ViaBackwards on the proxy and all of the server instances (lobby, creative and survival)

We see the error occurring most when users attempt to connect to the survival server, we have a rate limit on the velocity of 1000ms, and we also appear to see users connecting from various devices, including PC, Xbox & Playstation (via Bedrock Together) and mobiles, I would like to assume the Bedrock Together LAN middleware would be the potential perpetrator in this case. 

@cloakfox can you confirm which clients your users are using to connect?

One thing also worth mentioning, at random times, primarily when errors are being thrown out by ViaVersion, this error crops up for users attempted to connect via Java MC:
`com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.`

Could be unrelated - but worth mentioning as it adds to the data.

Here is the dump for the survival server: https://dump.viaversion.com/9a338cc5a7054c61436b9a1a1442b710b7ec7674eb6bf158b4c198da4e1325d1

No errors are showing up from the survival server side, just users connecting and then instantly being disconnected.

**Comment by Barvalg** [comment]
![Platform: velocity%203.1.2--SNAPSHOT%20%28git--c9e0e14e--b201%29](https://img.shields.io/badge/Platform-velocity%203.1.2--SNAPSHOT%20%28git--c9e0e14e--b201%29-3498db?style=flat-square) </br>![ViaVersion (4.5.1): 7 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.5.1)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.5.1): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.5.1)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by bridgelol** [comment]
Same issue happening on our end, exact same error using latest build.

**Comment by spookymgmt** [comment]
add me on discord, sent you FR, and pinged you in via disc. I have a fix.

**Comment by PedroMPagani** [comment]
Hey @spookymgmt where can I get it:? PedroPJava#0001

**Comment by cloakfox** [comment]
Bump

**Comment by cloakfox** [comment]
Hope these might help, catched a few exceptions in bungee console (that doesn't run geyser, nor viaversion)
https://gist.github.com/cloakfox/05cbca79187b092308602eb74236f0f2

this error is also what players see when they try to connect to the server with a "glitched" bedrock player on

viaversion is run on the spigot/paper servers, not on proxies.

**Comment by FormallyMyles** [comment]
I would suspect this is identical to https://github.com/ViaVersion/ViaBackwards/issues/512 (which @masmc05 has nicely made a plugin that can find invalid profiles), I suspect there is something wrong Geyser/Floodgate side which leads to these profiles being broadcasted to the players.

**Comment by cloakfox** [comment]
> 

This plugin doesn't load on paper 1.19.2 unfortunately
https://gist.github.com/cloakfox/841a1d63cb047117cd4a231bb32f04be

**Comment by bridgelol** [comment]
You have to change the paperweight configuration to 1.19.2 instead and make sure you use the remapped jar. (PacketHelp-unspecified.jar)

**Comment by cloakfox** [comment]
> You have to change the paperweight configuration to 1.19.2 instead and make sure you use the remapped jar. (PacketHelp-unspecified.jar)

where can a server owner download that?

**Comment by JHarris12345** [comment]
I am having the exact same issue

**Comment by SamGamerYT** [comment]
Hello! Quick question, able to share your /viaversion dump file here for the server itself?

**Comment by HowardZHY** [comment]
Close as outdated
