### ISSUE TITLE
SOUND: com.viaversion.viaversion.rewriter.SoundRewriter$1 (Anonymous), Packet ID: 81

### ISSUE THREAD

**Issue by Incluuu** [ViaVersion/ViaVersion#3247]
### `/viaversion dump` Output

dump.viaversion.com

### Console Error

```
[ViaVersion] ERROR IN Protocol1_14To1_13_2 IN REMAP OF SOUND (0x4D)
[13:13:55] [Netty Epoll Server IO #0/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[13:13:55] [Netty Epoll Server IO #0/WARN]: Packet Type: SOUND, Type: VarInt, Index: 1, Data: [], Source 0: com.viaversion.viaversion.rewriter.SoundRewriter$1 (Anonymous), Packet ID: 81
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at me.neznamy.tab.bukkit.Main$5.write(Main.java:339)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:13:55] [Netty Epoll Server IO #0/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[13:13:55] [Netty Epoll Server IO #0/WARN]: Packet Type: SOUND, Type: VarInt, Index: 1, Data: [], Source 0: com.viaversion.viaversion.rewriter.SoundRewriter$1 (Anonymous), Packet ID: 81
[13:13:55] [Netty Epoll Server IO #0/WARN]: Caused by: java.io.IOException: Unable to read type VarInt, found Byte
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:160)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.lambda$map$0(PacketHandlers.java:54)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:389)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:377)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:44)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:249)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at me.neznamy.tab.bukkit.Main$5.write(Main.java:339)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:321)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[13:13:55] [Netty Epoll Server IO #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:13:55] [Server thread/INFO]: lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SOUND, Type: VarInt, Index: 1, Data: [], Source 0: com.viaversion.viaversion.rewriter.SoundRewriter$1 (Anonymous), Packet ID: 81
```

### Bug Description

Join on server 1.12.2 spigot version

### Steps to Reproduce

1. Join on proxy to server 1.12.2 spigot version

### Expected Behavior

This bug should not disconnect players when entering the game, it wasn't there in the previous version of viaversion.

### Additional Server Info

Waterfall without plugins

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Incluuu** [comment]
The player is kicked when they step on the pressure plate with jumppads:
https://www.spigotmc.org/resources/custom-jumppads-1-8-1-19.44876/

**Comment by FormallyMyles** [comment]
Can you provide a valid ViaVersion dump?

**Comment by Incluuu** [comment]
https://dump.viaversion.com/59237692963d2fd3fff288e607c03e3a16ecd2e19367a0c07c6b2599d3456e1d

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1-SNAPSHOT): 3 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.1--SNAPSHOT)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump

**Comment by Incluuu** [comment]
https://dump.viaversion.com/7b6d5175d77972ac58c1dc68f2d1006ca6cbe0ac674f5bccbdb951c980ec5506

**Comment by Barvalg** [comment]
![Platform: git--Paper--1618%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1618%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3): Even with master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Incluuu** [comment]
The problem is still there even in the latest version.
