### ISSUE TITLE
Throws an axception on 1.19.3 (java.lang.IllegalAccessException com.viaversion.viaversion.bukkit.listeners.JoinListener cannot access a member of class net.minecraft.server.network.PlayerConnection)

### ISSUE THREAD

**Issue by danirod12** [ViaVersion/ViaVersion#3249]
### `/viaversion dump` Output

https://dump.viaversion.com/8d64585e572c62dcab6b342b9593c0fd5afa5e941cdf3f185838fa5988f407ba

### Console Error

```
[17:26:42] [Server thread/WARN]: [ViaVersion] You are running a development version of the plugin, please report any bugs to GitHub.
[17:26:42] [User Authenticator #1/INFO]: UUID of player Danirod_Gaming is d90cd4b2-10f5-401d-a09c-7e955d7d053a
[17:26:42] [Server thread/WARN]: [ViaVersion] Could not find Channel for logging-in player d90cd4b2-10f5-401d-a09c-7e955d7d053a
java.lang.IllegalAccessException: class com.viaversion.viaversion.bukkit.listeners.JoinListener cannot access a member of class net.minecraft.server.network.PlayerConnection with modifiers "private final"
        at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674) ~[?:?]
        at java.lang.reflect.Field.checkAccess(Field.java:1102) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:423) ~[?:?]
        at com.viaversion.viaversion.bukkit.listeners.JoinListener.getChannel(JoinListener.java:111) ~[?:?]
        at com.viaversion.viaversion.bukkit.listeners.JoinListener.onJoin(JoinListener.java:81) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:300) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:183) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.server.network.LoginListener.d(LoginListener.java:169) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.server.network.LoginListener.c(LoginListener.java:75) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:279) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:175) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1326) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3678-Spigot-41150f3-968d28d]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Bug Description

An exception in console

### Steps to Reproduce

1. Build and install using BuildTools CraftBukkit version 3678-Spigot-41150f3-968d28d (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)
2. Login to server
3. Get an exception

### Expected Behavior

Do not get an exception

(ViaVer 4.6.0 spams with errors related to protocol, 4.6.1 prints only this error)

### Additional Server Info

Idk how your dump works, my Windows is not 10, but 11

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3678--Spigot--41150f3--968d28d%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-3678--Spigot--41150f3--968d28d%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
Can you try again with the now latest ci build?

**Comment by danirod12** [comment]
The latest build does not contain your commits with possible join 1.19.4 fix. When installing and printing viaver dump it gives the same "git-ViaVersion-4.6.1-SNAPSHOT:b1524642" implementation version

**Comment by kennytv** [comment]
Make sure you're not the victim of caching: https://ci.viaversion.com/job/ViaVersion/675/

**Comment by danirod12** [comment]
Confirm. Issue was fixed. Thank you for fast solution
