### ISSUE TITLE
1.13 client cannot join a 1.19.4 Spigot server that has ViaVersion + ViaBackwards

### ISSUE THREAD

**Issue by KianmehrKM** [ViaVersion/ViaVersion#3252]
### `/viaversion dump` Output

https://dump.viaversion.com/5128cb9abdcbffeb98f0977c48c561ecb993ef627a3749a969c7dc9c38ab459e

### Console Error

```
https://paste.gg/p/anonymous/5a5e167254b34c5aaf743416fb7f2ada
```

### Bug Description

So, me and my friend tried to hook up an old machine, running MC 1.13 to a server we have in Aternos which contains ViaVersion and ViaBackwards. While we try to connect to the server, we are presented with that error.
I was not sure how to solve this error, although I did wipe the playerdata for this and it didn't fix the issue, I was wondering how can I fix this...

### Steps to Reproduce

1. Running a Minecraft client on version 1.13 (older versions such as 1.12 and 1.11 did also have the same effect)
2. Join the Aternos server containing the ViaVersion and ViaBackwards mod.
3. The error would be displayed

### Expected Behavior

I thought it should just join normally as it should but it didn't join, therefore the error was made.

### Additional Server Info

The server uses Spigot 1.19.4, on the hosting platform, Aternos.
It also has EssentialsX and WorldEdit in the mods too.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by KianmehrKM** [comment]
I already have the newest version on board.
This thing is what I also receive on the console constantly, non-stop:
```
[23:38:18] [Craft Scheduler Thread - 3/WARN]: [ViaVersion] Plugin ViaVersion v4.6.0 generated an exception while executing task 5
java.lang.NoSuchMethodError: 'int org.bukkit.inventory.ItemStack.getTypeId()'
	at com.viaversion.viaversion.bukkit.listeners.protocol1_9to1_8.HandItemCache.convert(HandItemCache.java:56) ~[?:?]
	at com.viaversion.viaversion.bukkit.listeners.protocol1_9to1_8.HandItemCache.run(HandItemCache.java:41) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3679-Spigot-41150f3-968d28d]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3679-Spigot-41150f3-968d28d]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaBackwards/commit/11e71b13070fa653a2d0f1cc5b2fe7ebbcf262fe
