### ISSUE TITLE
Viaversion error when join

### ISSUE THREAD

**Issue by zNAFTAz** [ViaVersion/ViaVersion#3276]
### `/viaversion dump` Output

https://dump.viaversion.com/53fc97e05950255a14805fdd194a2c4ba8c448d66f6c0088fa5a200bd7d3285b

### Console Error

[16:57:06] [Server thread/INFO]: VoNhatWang[/103.186.155.72:51101] logged in with entity id 537573 at ([world]11.17882932108477, 67.5, 18.897662281751682)
[16:57:07] [Netty Epoll Server IO #1/ERROR]: [ViaVersion] An error occurred in metadata handler EntityPackets for untracked entity type: Metadata{id=6, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=0}
[16:57:07] [Netty Epoll Server IO #1/ERROR]: [ViaVersion] Full metadata: Metadata{id=0, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=96}
Metadata{id=1, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@326e386d, value=300}
Metadata{id=2, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@3a9adfb5, value=null}
Metadata{id=3, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@7887f50c, value=false}
Metadata{id=4, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@7887f50c, value=false}
Metadata{id=5, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@7887f50c, value=false}
Metadata{id=6, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=0}
Metadata{id=7, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@243b8fe5, value=20.0}
Metadata{id=8, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@326e386d, value=8356754}
Metadata{id=9, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@7887f50c, value=false}
Metadata{id=10, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@326e386d, value=0}
Metadata{id=11, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@243b8fe5, value=0.0}
Metadata{id=12, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@326e386d, value=0}
Metadata{id=13, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=127}
Metadata{id=14, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=1}
Metadata{id=15, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@31c3cf4, value=CompoundTag { {} }}
Metadata{id=16, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@31c3cf4, value=CompoundTag { {} }}
[16:57:07] [Netty Epoll Server IO #1/WARN]: java.lang.ClassCastException: class java.lang.Byte cannot be cast to class java.lang.Integer (java.lang.Byte and java.lang.Integer are in module java.base of loader 'bootstrap')
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_19_3to1_19_1.packets.EntityPackets.lambda$registerRewrites$2(EntityPackets.java:162)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:126)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.rewriter.EntityRewriter$4.lambda$register$0(EntityRewriter.java:381)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:390)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:378)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.github.repooper.packetevents.Vulcan_nw.write(Vulcan_nw.java:60)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:93)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at me.MrGraycat.eGlow.Util.Packets.PipelineInjector$1.write(PipelineInjector.java:87)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at kernitus.plugin.OldCombatMechanics.utilities.packet.mitm.PacketInjector.write(PacketInjector.java:196)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:57:07] [Netty Epoll Server IO #1/ERROR]: [ViaVersion] An error occurred in metadata handler EntityPackets for untracked entity type: Metadata{id=6, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=0}
[16:57:07] [Netty Epoll Server IO #1/ERROR]: [ViaVersion] Full metadata: Metadata{id=0, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=96}
Metadata{id=1, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@326e386d, value=300}
Metadata{id=2, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@3a9adfb5, value=null}
Metadata{id=3, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@7887f50c, value=false}
Metadata{id=4, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@7887f50c, value=false}
Metadata{id=5, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@7887f50c, value=false}
Metadata{id=6, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=0}
Metadata{id=7, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@243b8fe5, value=20.0}
Metadata{id=8, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@326e386d, value=8356754}
Metadata{id=9, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@7887f50c, value=false}
Metadata{id=10, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@326e386d, value=0}
Metadata{id=11, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@243b8fe5, value=0.0}
Metadata{id=12, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@326e386d, value=0}
Metadata{id=13, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=127}
Metadata{id=14, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@21d5b3a2, value=1}
Metadata{id=15, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@31c3cf4, value=CompoundTag { {} }}
Metadata{id=16, metaType=com.viaversion.viaversion.api.minecraft.metadata.MetaType$MetaTypeImpl@31c3cf4, value=CompoundTag { {} }}
[16:57:07] [Netty Epoll Server IO #1/WARN]: java.lang.ClassCastException: class java.lang.Byte cannot be cast to class java.lang.Integer (java.lang.Byte and java.lang.Integer are in module java.base of loader 'bootstrap')
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_19_3to1_19_1.packets.EntityPackets.lambda$registerRewrites$2(EntityPackets.java:162)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:126)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.rewriter.EntityRewriter$4.lambda$register$0(EntityRewriter.java:381)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:390)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:378)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.github.repooper.packetevents.Vulcan_nw.write(Vulcan_nw.java:60)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at me.neznamy.tab.platforms.bukkit.BukkitPipelineInjector$BukkitChannelDuplexHandler.write(BukkitPipelineInjector.java:93)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at me.MrGraycat.eGlow.Util.Packets.PipelineInjector$1.write(PipelineInjector.java:87)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at kernitus.plugin.OldCombatMechanics.utilities.packet.mitm.PacketInjector.write(PacketInjector.java:196)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:57:07] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:57:07] [Server thread/INFO]: [Matrix] (Via) Player VoNhatWang joined with (1.16.x/754) client

### Bug Description

When i join my server then error spam my console

### Steps to Reproduce

1. Login with 1.16.5
2. Version paper 1.12.2

### Expected Behavior

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--4466fe0%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--4466fe0%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(2.0.3): 1 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
You have a plugin sending invalid entity metadata/metadata for an utnracked entity.

**Comment by zNAFTAz** [comment]
> You have a plugin sending invalid entity metadata/metadata for an utnracked entity.

My plugins:
![image](https://user-images.githubusercontent.com/88925538/227771493-ff9c0b3a-6e79-413a-97ba-75d657af6e06.png)

**Comment by FormallyMyles** [comment]
I'd suggest removing plugins & testing on a copy of your server and going from there.

**Comment by zNAFTAz** [comment]
> I'd suggest removing plugins & testing on a copy of your server and going from there.

but I don't understand why, there are times when I stop and start the server and this error no longer occurs

**Comment by zNAFTAz** [comment]
eglow is cause
