### ISSUE TITLE
Folia compatibility

### ISSUE THREAD

**Issue by SlimeDog** [ViaVersion/ViaVersion#3283]
### `/viaversion dump` Output

Cannot, since plugin didn't load

### Console Error

```
[18:39:14] [Server thread/ERROR]: Error occurred while enabling ViaVersion v4.6.2 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:536) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:260) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at com.viaversion.viaversion.ViaVersionPlugin.runAsync(ViaVersionPlugin.java:159) ~[ViaVersion-4.6.2.jar:?]
        at com.viaversion.viaversion.update.UpdateUtil.sendUpdateMessage(UpdateUtil.java:50) ~[ViaVersion-4.6.2.jar:?]
        at com.viaversion.viaversion.ViaManagerImpl.onServerLoaded(ViaManagerImpl.java:116) ~[ViaVersion-4.6.2.jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onEnable(ViaVersionPlugin.java:127) ~[ViaVersion-4.6.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:631) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:542) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:465) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:348) ~[folia-1.19.4.jar:git-Folia-"5b74945"]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
```

### Bug Description

folia-1.19.4.jar:git-Folia-"5b74945"
ViaVersion 4.6.2

On [Hangar](https://hangar.papermc.io/ViaVersion/ViaVersion) ViaVersion claims to support Folia, but see the error above.

### Steps to Reproduce

- Start Folia server
- Read console errors

### Expected Behavior

Plugin should load without error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by SlimeDog** [comment]
It is impossible to provide a dump if the plugin doesn't load.

**Comment by SlimeDog** [comment]
However, dev version works correctly. You might want to load a working version on Hangar.
