### ISSUE TITLE
ViaVersion/ViaBackwards doesn't work on Velocity

### ISSUE THREAD

**Issue by CormacZ** [ViaVersion/ViaVersion#3287]
### `/viaversion dump` Output

```
[21:38:26 ERROR]: An error occurred while running this command.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command viaversion dump for com.velocitypowered.proxy.console.VelocityConsole@62544c48
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command viaversion dump for com.velocitypowered.proxy.console.VelocityConsole@62544c48
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:226) ~[server.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:240) ~[server.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[server.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at com.viaversion.viaversion.api.Via.manager(Via.java:84) ~[?:?]
        at com.viaversion.viaversion.api.Via.getAPI(Via.java:40) ~[?:?]
        at com.viaversion.viaversion.commands.defaultsubs.DumpSubCmd.execute(DumpSubCmd.java:64) ~[?:?]
        at com.viaversion.viaversion.commands.ViaCommandHandler.onCommand(ViaCommandHandler.java:90) ~[?:?]
        at com.viaversion.viaversion.velocity.command.VelocityCommandHandler.execute(VelocityCommandHandler.java:36) ~[?:?]
        at com.viaversion.viaversion.velocity.command.VelocityCommandHandler.execute(VelocityCommandHandler.java:25) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[server.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[server.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:213) ~[server.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:240) ~[server.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
```

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/af7c464d3d3b4018aa0b164ecfcac65d

```
mclo.gs
```
https://mclo.gs/SqSRMdm

### Bug Description

It doesn't load successfully. Instead, it gave me an error and did not work.

### Steps to Reproduce

1. Use Velocity server.
2. Add [ViaVersion-4.6.3-SNAPSHOT.jar](https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.6.3-SNAPSHOT.jar) and [ViaBackwards-4.6.2-SNAPSHOT.jar](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/build/libs/ViaBackwards-4.6.2-SNAPSHOT.jar) into plugin folder.
3. Start the server.

### Expected Behavior

It does load ViaVersion and ViaBackwards, but It gave me a lot of errors, and when testing on a different version, it does not work.

### Additional Server Info

I use Velocity 3.2.0-SNAPSHOT Build #247 and the following plugins is [ViaVersion-4.6.3-SNAPSHOT.jar](https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.6.3-SNAPSHOT.jar) and [ViaBackwards-4.6.2-SNAPSHOT.jar](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/lastSuccessfulBuild/artifact/build/libs/ViaBackwards-4.6.2-SNAPSHOT.jar).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
This sounds like a config failure or you happen to have or something else corrupted the plugins in process, Please attempt to move your via* copies to the backend servers only to see if issues persist.

**Comment by Kichura** [comment]
Well if it works on backend then keep it there as running it on proxy tends to break easily in some form or another.
