### ISSUE TITLE
Server thread/ERROR Could not pass event ServerLoadEvent to Geyser-Spigot v2.1.0

### ISSUE THREAD

**Issue by CamilaTokisaki** [ViaVersion/ViaVersion#3295]
### `/viaversion dump` Output

https://dump.viaversion.com/a2cbcacd388352f473eafef8a2c04547b37044b90b202e4f9536f7c4cae251e9

### Console Error

```
12.04 02:01:43 [Server] Server thread/INFO Enabling Geyser-Spigot v2.1.0-SNAPSHOT
12.04 02:01:43 [Server] Server thread/INFO Server permissions file permissions.yml is empty, ignoring it
12.04 02:01:43 [Server] Server thread/INFO ******************************************
12.04 02:01:43 [Server] Server thread/INFO Loading Geyser version 2.1.0-SNAPSHOT (git-master-0f99abc)
12.04 02:01:43 [Server] Server thread/INFO ******************************************
12.04 02:01:48 [Server] Network Listener - #2/ERROR Failed to start Geyser on 51.89.241.67:25565
12.04 02:01:48 [Server] Server thread/ERROR Could not pass event ServerLoadEvent to Geyser-Spigot v2.1.0-SNAPSHOT
12.04 02:01:48 [Server] INFO org.bukkit.event.EventException: null
12.04 02:01:48 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
12.04 02:01:48 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
12.04 02:01:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
12.04 02:01:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
12.04 02:01:48 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:583) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3521-Spigot-1dffefb-cc7edd6]
12.04 02:01:48 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3521-Spigot-1dffefb-cc7edd6]
12.04 02:01:48 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3521-Spigot-1dffefb-cc7edd6]
12.04 02:01:48 [Server] INFO at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3521-Spigot-1dffefb-cc7edd6]
12.04 02:01:48 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3521-Spigot-1dffefb-cc7edd6]
12.04 02:01:48 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
12.04 02:01:48 [Server] INFO Caused by: java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
12.04 02:01:48 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
12.04 02:01:48 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
12.04 02:01:48 [Server] INFO at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498) ~[?:?]
12.04 02:01:48 [Server] INFO at java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1219) ~[?:?]
12.04 02:01:48 [Server] INFO at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
12.04 02:01:48 [Server] INFO at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
12.04 02:01:48 [Server] INFO at com.nukkitx.network.util.Bootstraps.lambda$allOf$0(Bootstraps.java:111) ~[?:?]
12.04 02:01:48 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:502) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
12.04 02:01:48 [Server] INFO ... 1 more
12.04 02:01:48 [Server] INFO Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
```

### Bug Description

When trying to change auth-type: to offline or floodgate, this error pops up 
If you leave the stock file, there is no error, and the plugin is loaded, but, of course, only the java server is running
At an attempt to change the port on the server port, you get the same situation
I use Shockbyte, the instruction looked, but judging by the instructions they run a stock file (or am I idk)
Troubled with this for 3 hours, tried everything, just 0 ideas

### Steps to Reproduce

1. Spigot 1.19
2. floodgate-spigot
3. ViaVersion-4.6.3-SNAPSHOT
4. Geyser-Spigot 

### Expected Behavior

I hope for your help
Thank you in advance.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3521--Spigot--1dffefb--cc7edd6%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-3521--Spigot--1dffefb--cc7edd6%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.6.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.6.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Camotoy** [comment]
This should have nothing to do with ViaVersion nor with changing your auth-type. You probably don't want to change your `bedrock` `address`, unless you haven't modified that. Talk to the Geyser Discord for further help: https://discord.gg/geysermc
