### ISSUE TITLE
1.19Bukkit can't connect 1.19.x

### ISSUE THREAD

**Issue by yjj71044** [ViaVersion/ViaVersion#3303]
### `/viaversion dump` Output

https://dump.viaversion.com/41db794de5d47f49b4fd2e48dd56f72d52fb417e7c3b36eeb8a93539e8b72e61

### Console Error

[Netty Server IO #2/ERROR]: Invalid signature for profile public key.
Try restarting your game.
net.minecraft.server.network.LoginListener$a: Missing profile public key.
This server requires secure profiles.
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:214) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:240) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at net.minecraft.network.protocol.login.PacketLoginInStart.a(SourceFile:23) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at net.minecraft.network.protocol.login.PacketLoginInStart.a(SourceFile:10) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:180) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:164) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:1) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:90) [spigot-1.19-R0.1-SNAPSHOT.jar:3553-Spigot-14a2382-ef09464]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[15:11:47] [Netty Server IO #2/INFO]: Disconnecting /146.56.166.176:52654: Invalid signature for profile public key.
Try restarting your game.
[15:11:47] [Server thread/INFO]: /146.56.166.176:52654 lost connection: Invalid signature for profile public key.
Try restarting your game.

### Bug Description

1.19 If you open the server using a bucket, you will not be able to connect when you try to connect in version 1.19.3.

### Steps to Reproduce

1. Prepare Spigot bukkit from 1.19 to 1.19.1.
2. Open the server and try to connect to version 1.19.3.
3. I can't connect.

### Expected Behavior

The server cannot be connected, and the word "Invalid signature for profile public key. Try restarting your game." appears.

### Additional Server Info

I'm not using.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3553--Spigot--14a2382--ef09464%20%28MC%3A%201.19%29](https://img.shields.io/badge/Platform-3553--Spigot--14a2382--ef09464%20%28MC%3A%201.19%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FormallyMyles** [comment]
Coped from Discord:

**To resolve the "Missing profile public key" issue:**

1. You need to disable `enforce-secure-profile` in server.properties file via 1.19 or later backend server(s), 

2. If you have velocity as your proxy; ensure that `force-key-authentication` is set to false in the velocity.toml file, *(+ Please try Legacy Forwarding if modern fails)*

3. If you have bungeecord/waterfall as your proxy instead; ensure that `enforce_secure_profile:` is set to false in the bungeecord's/waterfall's config.yml file,

4. Whenever the **Chat messages can't be verified** toast appears after disabling all three, ViaVersion will be unable to remove this but you can install the plugin **FreedomChat** to your 1.19.1+ Paper/Purpur server(s) to counter this problem *(won't work on bungee/velocity itself and 1.3.x of freedomchat only works on 1.19.3, 1.4.x requires 1.19.4 instead)* - This includes player messages be converted into system messages instead,

5. Disabling the enforced secure profiling system **doesn't** pose a security risk nor has anything to do with the `online-mode` boolean in practice, Although we aren't responsible for any issues caused by this entire setup.
