### ISSUE TITLE
ERROR IN Protocol1_19_3To1_19_1 IN REMAP OF DECLARE_COMMANDS (0x0F)

### ISSUE THREAD

**Issue by Earthcomputer** [ViaVersion/ViaVersion#3310]
### `/viaversion dump` Output

Using ViaFabricPlus, couldn't get the dump

### Console Error

```
[18:27:42] [Netty Epoll Client IO #0/WARN]: ERROR IN Protocol1_19_3To1_19_1 IN REMAP OF DECLARE_COMMANDS (0x0F)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.rewriter.CommandRewriter$$Lambda$951/0x00000008010406c0
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.rewriter.CommandRewriter$$Lambda$951/0x00000008010406c0
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 48 out of bounds for length 48
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.data.FullMappingsBase.identifier(FullMappingsBase.java:72)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.rewriter.CommandRewriter.argumentType(CommandRewriter.java:159)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.rewriter.CommandRewriter.lambda$registerDeclareCommands1_19$12(CommandRewriter.java:120)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at de.florianmichael.vialoadingbase.netty.handler.VLBViaDecodeHandler.decode(VLBViaDecodeHandler.java:52)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at de.florianmichael.vialoadingbase.netty.handler.VLBViaDecodeHandler.decode(VLBViaDecodeHandler.java:34)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:27:42] [Netty Epoll Client IO #0/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Bug Description

Having an extra argument type on the server causes the command tree not to be translated and is instead dropped. This causes auto-completion not to work.

### Steps to Reproduce

1. Install a dev build of [Geodesy](https://www.curseforge.com/minecraft/mc-mods/geodesy) (I've attached one for your convenience, renamed to a zip), Fabric API and ViaFabric on a 1.19.2 Fabric server.
2. Connect to the server with a 1.19.4 client.
3. No commands can be auto-completed.
[geodesy-2.1.zip](https://github.com/ViaVersion/ViaVersion/files/11361925/geodesy-2.1.zip)

### Expected Behavior

On a vanilla 1.19.2 client, commands can be completed under these circumstances, although I don't think the specific argument type works.

### Additional Server Info

Fabric server with a dev build of Geodesy installed, which adds a custom argument type which triggers the error.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by SzczurekYT** [comment]
I also have this, caused by my mod, but pretty funny - only in the dev env. When I connect to the server run in intellij the error shows up, but when I connect to a standalone fabric server with this mod, it works as expected.
