### ISSUE TITLE
Error when using the /give command with a specific display

### ISSUE THREAD

**Issue by Sanjino1** [ViaVersion/ViaVersion#3320]
### `/viaversion dump` Output

https://dump.viaversion.com/f0f84d191aa41f9aac051d345360c831ac48f4b0d97eda00bf68f44908623479

### Console Error

[05:23:27 WARN]: ERROR IN Protocol1_19_3To1_19_4 IN REMAP OF WINDOW_ITEMS (0x12)
[05:23:27 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[05:23:27 WARN]: Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)
[05:23:27 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[05:23:27 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[05:23:27 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[05:23:27 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[05:23:27 WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:469)
[05:23:27 WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:443)
[05:23:27 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[05:23:27 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[05:23:27 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[05:23:27 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[05:23:27 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[05:23:27 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[05:23:27 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[05:23:27 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[05:23:27 WARN]: Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)
[05:23:27 WARN]: Caused by: java.lang.ClassCastException: class com.viaversion.viaversion.libs.opennbt.tag.builtin.StringTag cannot be cast to class com.viaversion.viaversion.libs.opennbt.tag.builtin.ListTag (com.viaversion.viaversion.libs.opennbt.tag.builtin.StringTag and com.viaversion.viaversion.libs.opennbt.tag.builtin.ListTag are in unnamed module of loader 'ViaVersion-4.6.2.jar' @7006ffe1)
[05:23:27 WARN]: 	at ViaBackwards-4.6.1.jar//com.viaversion.viabackwards.api.rewriters.ItemRewriter.handleItemToClient(ItemRewriter.java:62)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.rewriter.ItemRewriter$2.lambda$register$0(ItemRewriter.java:79)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:390)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:378)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[05:23:27 WARN]: 	at ViaVersion-4.6.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[05:23:27 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[05:23:27 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[05:23:27 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[05:23:27 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[05:23:27 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[05:23:27 WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:469)
[05:23:27 WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:443)
[05:23:27 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[05:23:27 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[05:23:27 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[05:23:27 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[05:23:27 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[05:23:27 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[05:23:27 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[05:23:27 INFO]: sanjino lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)

### Bug Description

When using the /give command and getting an item with a display that has incorrect syntax, it kicks me out of the server and doesn't let me join again

### Steps to Reproduce

1. Join with the 1.19.1
2. Put the command: /give nick paper{display:{Lore:'{"text":"Tienes que tener 5 slots","color":"white"}'}}
Although it might work with another item and a different description.

### Expected Behavior

It should give me the paper as is, with the incorrect display, so it shouldn't look any different from a regular paper

### Additional Server Info

Server: purpur-1.19.4-1970
Client versión: 1.19.1
ViaVersion-4.6.2
ViaBackwards-4.6.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1970%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Purpur--1970%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.6.2): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
That's not valid lore data, it needs to be `/give nick paper{display:{Lore:'{"text":"Tienes que tener 5 slots","color":"white"}'}}`

**Comment by kennytv** [comment]
Oh right, and -dev versions already have sanity checks to not error there; see https://ci.viaversion.com/
