### ISSUE TITLE
When going from a 1.8 server to a 1.12 server or vise versa it errors

### ISSUE THREAD

**Issue by EthanGarey** [ViaVersion/ViaVersion#3323]
### `/viaversion dump` Output

https://dump.viaversion.com/996946c5ae28653067d00977265bb0db1b0ebf639eca3e0b001f062b05c0a0d9

### Console Error

```
20:30:45 [INFO] [EthanGarey] <-> DownstreamBridge <-> [survival] has disconnected
20:31:20 [INFO] [EthanGarey] <-> ServerConnector [survival] has connected
20:31:20 [SEVERE] java.util.NoSuchElementException: com.viaversion.viaversion.protocols.protocol1_9to1_8.Protocol1_9To1_8
20:31:20 [SEVERE]     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.constructPacket(PacketWrapperImpl.java:307)
20:31:20 [SEVERE]     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send0(PacketWrapperImpl.java:272)
20:31:20 [SEVERE]     at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.send(PacketWrapperImpl.java:260)
20:31:20 [SEVERE]     at com.viaversion.viaversion.api.protocol.packet.PacketWrapper.send(PacketWrapper.java:178)
20:31:20 [SEVERE]     at com.viaversion.viaversion.protocols.protocol1_9to1_8.storage.EntityTracker1_9.sendTeamPacket(EntityTracker1_9.java:325)
20:31:20 [SEVERE]     at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.checkServerChange(BungeeServerHandler.java:270)
20:31:20 [SEVERE]     at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.onServerConnected(BungeeServerHandler.java:113)
20:31:20 [SEVERE]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:31:20 [SEVERE]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
20:31:20 [SEVERE]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:31:20 [SEVERE]     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
20:31:20 [SEVERE]     at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
20:31:20 [SEVERE]     at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
20:31:20 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:413)
20:31:20 [SEVERE]     at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:186)
20:31:20 [SEVERE]     at net.md_5.bungee.protocol.packet.Login.handle(Login.java:228)
20:31:20 [SEVERE]     at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
20:31:20 [SEVERE]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
20:31:20 [SEVERE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
20:31:20 [SEVERE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
20:31:20 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
20:31:20 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
20:31:20 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
20:31:20 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
20:31:20 [SEVERE]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
20:31:20 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
20:31:20 [SEVERE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
20:31:20 [SEVERE]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
20:31:20 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
20:31:20 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
20:31:20 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
20:31:20 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
20:31:20 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)
20:31:20 [INFO] [EthanGarey] <-> DownstreamBridge <-> [lobby1] has disconnected
```

### Bug Description

When you go to a 1.12 server from 1.8 it errors bungeec

### Steps to Reproduce

Log in with 1.19.4

Go to a 1.8 server

use /server to go to a 1.12 server

and error is in bungeecoord console

### Expected Behavior

it should not error AND it also sends me to the server which doesnt make sense

### Additional Server Info

I have viaversion on bungeecoord but not on the sub servers

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A9e5ed82%3A1701](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A9e5ed82%3A1701-3498db?style=flat-square) </br>![Proxy is 3 builds behind](https://img.shields.io/badge/Your%20proxy%20is%203%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.6.2): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.6.2)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Camotoy** [comment]
Your jarfile is likely corrupt - please redownload it.
