### ISSUE TITLE
NoSuchFieldError

### ISSUE THREAD

**Issue by ImYenil** [ViaVersion/ViaVersion#3335]
### `/viaversion dump` Output

https://dump.viaversion.com/9a45b978e2df5e4d4e92b1568f90bf438e4c3b5b555729ce2647b29752bb8799

### Console Error

[16:35:11 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[16:35:11 ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-4.7.0-1.20-rc1-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoSuchFieldError: ACKNOWLEDGE_PLAYER_DIGGING
        at com.viaversion.viabackwards.protocol.protocol1_13_2to1_14.Protocol1_13_2To1_14.registerPackets(Protocol1_13_2To1_14.java:73) ~[ViaBackwards-4.6.1.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:97) ~[ViaVersion-4.7.0-1.20-rc1-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:196) ~[ViaVersion-4.7.0-1.20-rc1-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:190) ~[ViaVersion-4.7.0-1.20-rc1-SNAPSHOT.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:100) ~[ViaBackwards-4.6.1.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:33) ~[ViaBackwards-4.6.1.jar:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:106) ~[ViaVersion-4.7.0-1.20-rc1-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:92) ~[ViaVersion-4.7.0-1.20-rc1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.19.4.jar:git-Paper-547]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.19.4.jar:git-Paper-547]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.19.4.jar:git-Paper-547]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-547]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:431) ~[paper-1.19.4.jar:git-Paper-547]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-547]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-547]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-547]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Bug Description

An error occurs when the plugin is enabled

### Steps to Reproduce

The plugin is activated in version 1.19.4. You can see errors.

### Expected Behavior

It didn't happen in version 1.8.8.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--547%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--547%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0-1.20-rc1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.7.0--1.20--rc1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaRewind(2.0.3): 4 commits behind master](https://img.shields.io/badge/ViaRewind%20(2.0.3)-4%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.6.1): 9 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by FormallyMyles** [comment]
Update ViaBackwards to 4.7.0
