### ISSUE TITLE
CONSOLE ERROR

### ISSUE THREAD

**Issue by HighPriestKing** [ViaVersion/ViaVersion#3339]
### `/viaversion dump` Output

https://dump.viaversion.com/16f6b290d39648477367b3e8ae295e138d9cc0598889852958f30bc28267766b

### Console Error

```
Put the paste.gg link or text here.
```
https://paste.gg/p/anonymous/520b2e2c24e44245943093ad2388099a

### Bug Description

[18:49:12 ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-4.7.0.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoSuchFieldError: ACKNOWLEDGE_PLAYER_DIGGING
        at com.viaversion.viabackwards.protocol.protocol1_13_2to1_14.Protocol1_13_2To1_14.registerPackets(Protocol1_13_2To1_14.java:73) ~[ViaBackwards-4.6.1.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:97) ~[ViaVersion-4.7.0.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:196) ~[ViaVersion-4.7.0.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:190) ~[ViaVersion-4.7.0.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:100) ~[ViaBackwards-4.6.1.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:33) ~[ViaBackwards-4.6.1.jar:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:106) ~[ViaVersion-4.7.0.jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:92) ~[ViaVersion-4.7.0.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.19.4.jar:git-Paper-549]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.19.4.jar:git-Paper-549]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.19.4.jar:git-Paper-549]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-549]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:431) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-549]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-549]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to Reproduce

updated floogdate, geyser, and server jar to waterfall 1.20.0

updated via version, tried normal version and dev version. Same error both times

### Expected Behavior

says plugin doesnt start and asks if its up to date

### Additional Server Info

bungee server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.1--SNAPSHOT%3Aec41547%3A536](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.1--SNAPSHOT%3Aec41547%3A536-3498db?style=flat-square) </br>![ViaVersion (4.7.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.1): 27 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-27%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Update viabackwards from CI.
