### ISSUE TITLE
[ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)

### ISSUE THREAD

**Issue by DarkChromaMC** [ViaVersion/ViaVersion#3347]
### `/viaversion dump` Output

https://dump.viaversion.com/8d2334f6f558ac1aab0221b4244983ef749627d0ef47e1aeb2404c9fc77c78cd

### Console Error

```
[00:10:38] [User Authenticator #353/INFO]: UUID of player joelGroves is aeee4b5f-b818-4ee8-8051-2f2213c75411
[00:10:38] [Netty Epoll Server IO #2/WARN]: [ViaBackwards] Custom worlds heights are NOT SUPPORTED for 1.16 players and older and may lead to errors!
[00:10:38] [Netty Epoll Server IO #2/WARN]: [ViaBackwards] You have min/max set to -64/256
[00:10:38] [Server thread/INFO]: joelGroves[/68.146.104.155:44166] logged in with entity id 3173332 at ([world]3061.6452307425725, 51.0, 12748.386962958526)
[00:10:38] [Netty Epoll Server IO #2/ERROR]: [ViaVersion] Error when trying to parse json: ext":"k"},{"color":"red","text":"a"},{"color":"red","text":"c"},{"color":"red","text":"h"},{"color":"red","text":"u"
[00:10:38] [Netty Epoll Server IO #2/WARN]: [ViaVersion] ERROR IN Protocol1_19_1To1_19_3 IN REMAP OF PLAYER_INFO_UPDATE (0x36)
[00:10:38] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[00:10:38] [Netty Epoll Server IO #2/WARN]: Packet Type: PLAYER_INFO, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$6399/0x0000000801ad40f8, Packet ID: 55
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at Vulcan-2.7.3.jar//io.github.repooper.packetevents.Vulcan_xw.write(Vulcan_xw.java:60)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at TAB-4.0.0-SNAPSHOT.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:112)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at Model-Engine-R3.1.6.jar//com.ticxo.modelengine.nms.v1_19_R3.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:85)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket()
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11()
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[00:10:38] [Netty Epoll Server IO #2/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[00:10:38] [Netty Epoll Server IO #2/WARN]: Packet Type: PLAYER_INFO, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$6399/0x0000000801ad40f8, Packet ID: 55
[00:10:38] [Netty Epoll Server IO #2/WARN]: Caused by: com.viaversion.viaversion.libs.gson.JsonSyntaxException: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.libs.gson.JsonParser.parseReader(JsonParser.java:76)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.libs.gson.JsonParser.parseString(JsonParser.java:51)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:44)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:33)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.api.type.OptionalType.read(OptionalType.java:38)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:145)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaBackwards-4.7.0.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3.lambda$registerPackets$0(EntityPackets1_19_3.java:150)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at Vulcan-2.7.3.jar//io.github.repooper.packetevents.Vulcan_xw.write(Vulcan_xw.java:60)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at TAB-4.0.0-SNAPSHOT.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:112)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at Model-Engine-R3.1.6.jar//com.ticxo.modelengine.nms.v1_19_R3.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:85)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket()
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11()
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[00:10:38] [Netty Epoll Server IO #2/WARN]: Caused by: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6 path $
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.doPeek(JsonReader.java:551)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.libs.gson.stream.JsonReader.peek(JsonReader.java:433)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.7.0.jar//com.viaversion.viaversion.libs.gson.JsonParser.parseReader(JsonParser.java:71)
[00:10:38] [Netty Epoll Server IO #2/WARN]: 	... 67 more
[00:10:38] [Server thread/INFO]: joelGroves lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: PLAYER_INFO, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$6399/0x0000000801ad40f8, Packet ID: 55
[00:10:50] [Craft Scheduler Thread - 4225 - BuycraftX/INFO]: [BuycraftX] Fetching all due players...
[00:10:50] [Craft Scheduler Thread - 4225 - BuycraftX/INFO]: [BuycraftX] Fetched due players (70 found).
[00:10:50] [User Authenticator #353/INFO]: UUID of player joelGroves is aeee4b5f-b818-4ee8-8051-2f2213c75411
[00:10:50] [Server thread/INFO]: joelGroves[/68.146.104.155:55136] logged in with entity id 3173523 at ([world]3061.6452307425725, 51.0, 12748.386962958526)
[00:10:50] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] Error when trying to parse json: ext":"k"},{"color":"red","text":"a"},{"color":"red","text":"c"},{"color":"red","text":"h"},{"color":"red","text":"u"
```
FULL LOG AT https://paste.gg/p/anonymous/bf009df7338c400cb0f164a0d2195093

### Bug Description

After this player joelGroves joined, I noticed console was spammed a lot and I believe players got kicked, and we know players couldn't join afterwards - unless the server was restarted.

The FULL console log is: https://paste.gg/p/anonymous/bf009df7338c400cb0f164a0d2195093

### Steps to Reproduce

I'm unsure as it seemed random?

### Expected Behavior

Joining the server doesn't cause any ViaVersion related console errors and server doesn't crash/stop letting players login.

### Additional Server Info

I just noticed there is now 4.7.1 (currently on 4.7) so I will update too. This console error told me to open a bug report.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PufferfishPlusPurpur--19%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--PufferfishPlusPurpur--19%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 5 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-5%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 3 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-3%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by DarkChromaMC** [comment]
I want to add that I run two identical servers with the only difference is they're running 1.19.2 and not 1.19.4. But this issue only happens on the 1.19.4 server.

**Comment by bobhenl** [comment]
https://github.com/GeyserMC/Floodgate/issues/420 Seems it's the floodgate issue, I've tried mentioned solution & it helps

**Comment by FormallyMyles** [comment]
See above for tracking
