### ISSUE TITLE
ViaVersion Error

### ISSUE THREAD

**Issue by F3F5** [ViaVersion/ViaVersion#3351]
### `/viaversion dump` Output

i cant

### Console Error

```
[Put the paste.gg link or text here.](https://pastes.dev/hV15Oi3ph4)
```

### Bug Description

sturtup error with protocollib. 4.6.2 version works good

### Steps to Reproduce

1.12.2 paper install protocollib and viaversion

### Expected Behavior

.

### Additional Server Info

.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by F3F5** [comment]
[23:30:09 WARN]: [SkinsRestorer] Task #46 for SkinsRestorer v14.2.12 generated an exception
java.lang.NoClassDefFoundError: com/viaversion/viaversion/api/type/types/LongType
        at net.skinsrestorer.bukkit.skinrefresher.SpigotSkinRefresher.lambda$new$0(SpigotSkinRefresher.java:95) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:875) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:806) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:689) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.api.type.types.LongType
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 8 more

**Comment by F3F5** [comment]
> Use the latest builds from the CI.

tested

**Comment by F3F5** [comment]
[23:30:03] [Server thread/ERROR]: Error occurred while enabling ViaBackwards v4.6.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/viaversion/viaversion/api/platform/ViaInjector

**Comment by F3F5** [comment]
> Use the latest builds from the CI.

[23:30:01] [Server thread/ERROR]: Error occurred while enabling ViaVersion v4.7.1-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: ACKNOWLEDGE_PLAYER_DIGGING

**Comment by FormallyMyles** [comment]
> > Use the latest builds from the CI.
> 
> [23:30:01] [Server thread/ERROR]: Error occurred while enabling ViaVersion v4.7.1-SNAPSHOT (Is it up to date?) java.lang.NoSuchFieldError: ACKNOWLEDGE_PLAYER_DIGGING

Update ViaBackwards too

**Comment by F3F5** [comment]
> > > Use the latest builds from the CI.
> > 
> > 
> > [23:30:01] [Server thread/ERROR]: Error occurred while enabling ViaVersion v4.7.1-SNAPSHOT (Is it up to date?) java.lang.NoSuchFieldError: ACKNOWLEDGE_PLAYER_DIGGING
> 
> Update ViaBackwards too

solved, thanks
