### ISSUE TITLE
[22:10:04] [Netty Client IO #6/WARN]: ERROR IN Protocol1_15_2To1_16 IN REMAP OF CHUNK_DATA (0x21)

### ISSUE THREAD

**Issue by Quni1337** [ViaVersion/ViaVersion#3357]
### `/viaversion dump` Output

cannpt

### Console Error

Exception in thread "Thread-13" [22:10:10] [Thread-13/INFO]: [STDERR]: java.lang.NullPointerException
[22:10:10] [Thread-13/INFO]: [STDERR]: 	at why.vishka.Vishka.onWelcomeUI(Vishka.java:84)
[22:10:10] [Thread-13/INFO]: [STDERR]: 	at net.minecraft.client.gui.GuiIngame.lambda$renderGameOverlay$0(GuiIngame.java:290)
[22:10:10] [Thread-13/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
[22:10:22] [Client thread/INFO]: Connecting to mc.reallyworld.ru, 25565
[22:10:23] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_202]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_202]
	at net.minecraft.util.Util.runTask(Util.java:48) [main/:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1057) [main/:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:449) [main/:?]
	at net.minecraft.client.main.Main.main(Main.java:113) [main/:?]
	at Start.main(Start.java:14) [main/:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.handlePlayerPosLook(NetHandlerPlayClient.java:494) ~[main/:?]
	at net.minecraft.network.play.server.SPacketPlayerPosLook.processPacket(SPacketPlayerPosLook.java:68) ~[main/:?]
	at net.minecraft.network.play.server.SPacketPlayerPosLook.processPacket(SPacketPlayerPosLook.java:10) ~[main/:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[main/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
	at net.minecraft.util.Util.runTask(Util.java:47) ~[main/:?]
	... 4 more

### Bug Description

![image](https://github.com/ViaVersion/ViaVersion/assets/116512290/52cd91ba-8dc5-40b6-9ff5-6d88b1c1088e)

### Steps to Reproduce

1. 1.12.2 Client

### Expected Behavior

iam selected 1 16 5 protocol and trying join to the server and... error!

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
