### ISSUE TITLE
[05:18:27 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] ACKNOWLEDGE_PLAYER_DIGGING  ERROR

### ISSUE THREAD

**Issue by ObsidianMC123** [ViaVersion/ViaVersion#3371]
### `/viaversion dump` Output

https://dump.viaversion.com/a8de10500ec6fa4d1d6b0a82b1e4187b5cc71b5f5916ca726412d8946818d551

### Console Error

```
[05:18:27 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] ACKNOWLEDGE_PLAYER_DIGGING initializing ViaVersion v4.7.0 (Is it up to date?)
java.lang.NoSuchFieldError: ACKNOWLEDGE_PLAYER_DIGGING
        at com.viaversion.viabackwards.protocol.protocol1_13_2to1_14.Protocol1_13_2To1_14.registerPackets(Protocol1_13_2To1_14.java:73) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:97) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:196) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:190) ~[?:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:100) ~[?:?]
        at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:33) ~[?:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:106) ~[?:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:92) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Bug Description

[05:18:27 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] ACKNOWLEDGE_PLAYER_DIGGING  ERROR console log error

### Steps to Reproduce

Running server

### Expected Behavior

error log on console while startup

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--794%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Paper--794%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
