### ISSUE TITLE
suppress errors and spam in console when channels fails to start (most features of viaver works)

### ISSUE THREAD

**Issue by LYEddie** [ViaVersion/ViaVersion#3374]
### `/viaversion dump` Output

https://dump.viaversion.com/d6113cbb9408790de1ee2bf86add482920bc54594b81bcd705606e1e5df28d48

### Console Error

https://paste.gg/p/anonymous/c11cda2df3e34278a31360c9fc8d68f7

### Bug Description

almost all viaver features works in target clients, but i want that issues about "[io.netty.channel.ChannelInitializer]: Failed to initialize a channel." be fixed or at least to get a option in config.yml to suppress those warns (i repeat: most features works in target client versions, and protocol-support handles old clients). As we can see, everything begins with me using a funny chinese fork of waterfall (fork of a fork) called Travertine, already outdated but it works flawlessly, (i know about log4j and i fixed that in bungee/spigot), I've been using the proxy for a few months now and everything seems to work fine on the game clients with higher versions, and I use protocol-support (an abandoned plugin) to handle versions older than 1.16 (all good, I can even customize maps of objects and blocks for older versions). the plugin doesn't find the method "net.md_5.bungee.connection.InitialHandler.getRegisteredChannels()" although I don't know if fixing that error would be laborious, and it spams the console 16 stacktraces every 1 minute (personally, I haven't noticed any drops in performance at the time of spam), apart, an error also occurs when a player enters the server:

[21:44:30] [Netty Worker IO Thread #1/INFO]: [/127.0.0.1:55875] <-> InitialHandler has connected
[21:44:30] [Netty Worker IO Thread #1/WARN]: Error dispatching event ServerConnectEvent(player=LYEddie, target=BungeeServerInfo(name=lobby, socketAddress=localhost/127.0.0.1:25560, restricted=false), reason=PLUGIN, request=net.md_5.bungee.api.ServerConnectRequest@218aa123, cancelled=false) to listener com.viaversion.viaversion.bungee.handlers.BungeeServerHandler@21390938
java.lang.NullPointerException: null
	at com.viaversion.viaversion.bungee.handlers.BungeeServerHandler.onServerConnect(BungeeServerHandler.java:104) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at net.md_5.bungee.UserConnection.connect(UserConnection.java:301) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at net.md_5.bungee.UserConnection.connect(UserConnection.java:291) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at net.md_5.bungee.UserConnection.connect(UserConnection.java:265) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at net.md_5.bungee.UserConnection.connect(UserConnection.java:259) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at protocolsupport.protocol.packet.handler.PSInitialHandler.processLoginFinish(PSInitialHandler.java:352) ~[?:?]
	at protocolsupport.protocol.packet.handler.PSInitialHandler$3.lambda$done$0(PSInitialHandler.java:316) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[travertine-1.16-163.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:fe5acbf:163]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[21:44:30] [Netty Worker IO Thread #1/INFO]: [LYEddie|/127.0.0.1:55875] <-> ServerConnector [lobby] has connected

^^^
That definitely seems to be a viaver and protocolsupportbungee conflict, but it doesn't seem to be serious, the login to the server of the player is not canceled and after that, no more errors occur (not counting channel spam). to conclude, it would be great to be able to find the solution, mainly of the spam when certain channels fail to start and the error when a player connects/disconnects, or at least, an option in the configuration of viaversion "config.yml" (in the next build update) to reduce or suppress those annoying messages, if that's not asking too much, i understand that i'm using a strange and old version of waterfall and that it might not be a simple bug, but i would really like to stop this spam, if someone needs a copy of my travertine compilation I will be waiting for your indications (specifically, its download is not available on the papermc page, but at the beginning of this year I managed to find a solution, and I got this link: papermc.io/api/v2/projects/travertine/versions/1.16/builds/170/downloads/travertine-1.16-170.jar also i have the cmds modules).

### Steps to Reproduce

***viaversion and travertine 1.16.4 conflict***
Error dispatching event ServerConnectEvent(player=LYEddie, target=BungeeServerInfo(name=lobby, socketAddress=localhost/127.0.0.1:25560, restricted=false), reason=PLUGIN, request=net.md_5.bungee.api.ServerConnectRequest@218aa123, cancelled=false) to listener com.viaversion.viaversion.bungee.handlers.BungeeServerHandler@21390938
java.lang.NullPointerException: null

***every 1 minute***
 16 stacktraces about "[Netty Worker IO Thread #7/WARN] [io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0x363fbf4d]
java.lang.IllegalArgumentException: handler ~like 24 lines more"

### Expected Behavior

mostly some way, option or fix to hide all that spam, which makes logs to big files in short time when starting proxy, i tried using some plugins like CSF (Console Spam Fix) but it changes nothing

### Additional Server Info

i use spigot 1.16.4 + protocol support 1.16.4-1 on fallback servers and protocol support bungee build77 with via version 4.7.0 for proxies (travertine, fork of waterfall with 1.7 support, build 1.16.4-163): ps for legacy clients and viaver for newers

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ATravertine--Bootstrap%3A1.16--R0.4--SNAPSHOT%3Afe5acbf%3A163](https://img.shields.io/badge/Platform-git%3ATravertine--Bootstrap%3A1.16--R0.4--SNAPSHOT%3Afe5acbf%3A163-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 15 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
> [18:35:51] [main/WARN] [ViaVersion]:    /   |   \         BUNGEECORD IS OUTDATED
[18:35:51] [main/WARN] [ViaVersion]:   /         \   VIAVERSION MAY NOT WORK AS INTENDED
[18:35:52] [main/ERROR] [ViaVersion]: Error initializing BungeeServerHandler, try updating BungeeCord or ViaVersion!

Travertine is no longer supported, unless you get someone to upstream Bungee changes
