### ISSUE TITLE
Crush server | Velocity

### ISSUE THREAD

**Issue by turic24** [ViaVersion/ViaVersion#3408]
### `/viaversion dump` Output

https://dump.viaversion.com/ca79410870a10be76a05f97259f4fcbe5682a2f81ac30a0a2eab3abf0138f3b5

### Console Error

io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$878/0x00007f9c465fdde0, Packet ID: 2
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:233) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:315) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:151) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:78) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at java.lang.Thread.run(Thread.java:1623) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$878/0x00007f9c465fdde0, Packet ID: 2
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 1, widx: 3, cap: 256)
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:38) ~[?:?]
at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:30) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:145) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:191) ~[?:?]
at com.viaversion.viaversion.protocols.base.BaseProtocol1_16.passthroughLoginUUID(BaseProtocol1_16.java:29) ~[?:?]
at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.lambda$registerPackets$0(BaseProtocol1_7.java:128) ~[?:?]
at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:366) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395) ~[?:?]
at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) ~[?:?]
at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[?:?]
at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312) ~[?:?]
at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291) ~[?:?]
at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:236) ~[?:?]
at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:47) ~[?:?]
at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:29) ~[?:?]
at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
... 64 more

### Bug Description

With ViaBackwards my server work good, but when i try viaversion it start crashing( I use dev versions

### Steps to Reproduce

1. download dev versions
2. reboot server
3. check config

### Expected Behavior

i dont know why it start crush

### Additional Server Info

I use last version velocity for 1.19.4 minecraft.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0-23w33a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.8.0--23w33a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.0-23w33a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.8.0--23w33a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by turic24** [comment]
![Screenshot_11](https://github.com/ViaVersion/ViaVersion/assets/129747209/6c732f1f-3de7-40c9-90c3-6e09ac6dc036)

**Comment by FormallyMyles** [comment]
Limbo isn't compatible with Via on Velocity.

**Comment by turic24** [comment]
but how i can protect server without it? Maybe exist alternative variants?
