### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by MaeveLaOuf** [ViaVersion/ViaVersion#3415]
### `/viaversion dump` Output

https://dump.viaversion.com/844f0287e610b5543ffe20cafb67da68c6d48db2f851c254d27de92ec84461cb

### Console Error

```
[02.09 15:53:18.093] INFO: [Proxy-1] [15:53:08 ERROR]: [connected player] Pyedie (/192.168.0.17:60714): unable to connect to server Lobby-1
[02.09 15:53:18.094] INFO: [Proxy-1] io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[02.09 15:53:18.095] INFO: [Proxy-1] Packet Type: GAME_PROFILE, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$1379/0x000000080144c970, Packet ID: 2
[02.09 15:53:18.096] INFO: [Proxy-1]    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.097] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.098] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.099] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.100] INFO: [Proxy-1]    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.100] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.101] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.102] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.103] INFO: [Proxy-1]    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.104] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.105] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.106] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.107] INFO: [Proxy-1]    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.113] INFO: [Proxy-1]    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.114] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.115] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.116] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.117] INFO: [Proxy-1]    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.118] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.119] INFO: [Proxy-1]    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.119] INFO: [Proxy-1]    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.120] INFO: [Proxy-1]    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.122] INFO: [Proxy-1]    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.123] INFO: [Proxy-1]    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.127] INFO: [Proxy-1]    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.129] INFO: [Proxy-1]    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.130] INFO: [Proxy-1]    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.131] INFO: [Proxy-1]    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.132] INFO: [Proxy-1]    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.133] INFO: [Proxy-1]    at java.lang.Thread.run(Thread.java:833) [?:?]
[02.09 15:53:18.133] INFO: [Proxy-1] Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[02.09 15:53:18.134] INFO: [Proxy-1] Packet Type: GAME_PROFILE, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$1379/0x000000080144c970, Packet ID: 2
[02.09 15:53:18.135] INFO: [Proxy-1] Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(65) exceeds writerIndex(24): PooledUnsafeDirectByteBuf(ridx: 2, widx: 24, cap: 256)
[02.09 15:53:18.136] INFO: [Proxy-1]    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.137] INFO: [Proxy-1]    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.137] INFO: [Proxy-1]    at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.139] INFO: [Proxy-1]    at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:54) ~[?:?]
[02.09 15:53:18.143] INFO: [Proxy-1]    at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31) ~[?:?]
[02.09 15:53:18.148] INFO: [Proxy-1]    at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:145) ~[?:?]
[02.09 15:53:18.149] INFO: [Proxy-1]    at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:191) ~[?:?]
[02.09 15:53:18.149] INFO: [Proxy-1]    at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:184) ~[?:?]
[02.09 15:53:18.150] INFO: [Proxy-1]    at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.lambda$registerPackets$0(BaseProtocol1_7.java:127) ~[?:?]
[02.09 15:53:18.151] INFO: [Proxy-1]    at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:341) ~[?:?]
[02.09 15:53:18.152] INFO: [Proxy-1]    at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
[02.09 15:53:18.153] INFO: [Proxy-1]    at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395) ~[?:?]
[02.09 15:53:18.154] INFO: [Proxy-1]    at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) ~[?:?]
[02.09 15:53:18.155] INFO: [Proxy-1]    at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[?:?]
[02.09 15:53:18.161] INFO: [Proxy-1]    at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:312) ~[?:?]
[02.09 15:53:18.162] INFO: [Proxy-1]    at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:291) ~[?:?]
[02.09 15:53:18.164] INFO: [Proxy-1]    at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248) ~[?:?]
[02.09 15:53:18.165] INFO: [Proxy-1]    at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:48) ~[?:?]
[02.09 15:53:18.165] INFO: [Proxy-1]    at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:30) ~[?:?]
[02.09 15:53:18.166] INFO: [Proxy-1]    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
[02.09 15:53:18.167] INFO: [Proxy-1]    ... 29 more
```

### Bug Description

When starting the CloudNet software (starting Proxy, Auth and Lobby), error occurs on the Proxy side.

### Steps to Reproduce

1. Use CloudNet
2. Have ViaVersion and ViaBackwards on thr proxy (For Proxy Velocity 3.2.0-SNAPSHOT (git-19abb909-b265)) (For Server-Side git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

### Expected Behavior

Should be starting with no problems

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): 22 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-22%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.7.0): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by MaeveLaOuf** [comment]
Same problem, all the servers started, but when i try to connect it makes this error
[ViaDump](https://dump.viaversion.com/e2ae1d0c4be7a5bef04eaff13ca6871ccda70f029809c615adc0c21da2a8e650)

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--19abb909--b265%29-3498db?style=flat-square) </br>![ViaVersion (4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.7.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.7.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by FormallyMyles** [comment]
Will be a conflict with one of your velocity plugins. Move ViaVersion to the backend.
