### ISSUE TITLE
cant join from 1.12.2 client to 1.16.5 server

### ISSUE THREAD

**Issue by hun1yy** [ViaVersion/ViaVersion#3423]
### `/viaversion dump` Output

i use it on mcp version

### Console Error

```
[00:59:05] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot assign field "motionX" because "entityplayer" is null
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at net.minecraft.util.Util.runTask(Util.java:48) [src/:?]
        at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1114) [src/:?]
        at net.minecraft.client.Minecraft.run(Minecraft.java:516) [src/:?]
        at net.minecraft.client.main.Main.main(Main.java:115) [src/:?]
        at Start.main(Start.java:12) [src/:?]
Caused by: java.lang.NullPointerException: Cannot assign field "motionX" because "entityplayer" is null
        at net.minecraft.client.network.NetHandlerPlayClient.handlePlayerPosLook(NetHandlerPlayClient.java:752) ~[src/:?]
        at net.minecraft.network.play.server.SPacketPlayerPosLook.processPacket(SPacketPlayerPosLook.java:68) ~[src/:?]
        at net.minecraft.network.play.server.SPacketPlayerPosLook.processPacket(SPacketPlayerPosLook.java:10) ~[src/:?]
        at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[src/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at net.minecraft.util.Util.runTask(Util.java:47) ~[src/:?]
        ... 4 more
[00:59:06] [Netty Client IO #6/WARN]: ERROR IN Protocol1_15_2To1_16 IN REMAP OF CHUNK_DATA (0x21)
[01:01:13] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
![изображение_2023-09-18_010228060](https://github.com/ViaVersion/ViaVersion/assets/134882723/14d9dac3-ea9e-4f85-97da-768ce5d2abdd)

```

### Bug Description

I got error when trying to use 1.16+ protocol on my 1.12.2 mcp version

### Steps to Reproduce

1. set 1.16.5 in slider
2. trying to join mc.reallyworld.ru

### Expected Behavior

I expected what i can join server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Jo0001** [comment]
Please try it with the latest ViaVersion and ViaBackwards (4.8.0) and a normal 1.12.2 client as this is working fine for me

**Comment by izdec8d** [comment]
клент хачей
