### ISSUE TITLE
Incomplete 1.20.2 support?

### ISSUE THREAD

**Issue by MATRIX-feather** [ViaVersion/ViaVersion#3425]
### `/viaversion dump` Output

https://dump.viaversion.com/792fac7fa8814f6fd081f1eb963b8241219426d39fa4f3500454e8e3e76fd49b

### Console Error

Sometimes the server console shows the following message:
```
[12:37:34 INFO]: Player158 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/1 (PacketPlayInTileNBTQuery) was larger than I expected, found 88 bytes extra whilst reading packet 1
```

### Bug Description

Players can't join with 1.20.2

### Steps to Reproduce

1. Install ViaVersion
2. Connect with 1.20.2
3. Get disconnected

### Expected Behavior

Players can play with their 1.20.2 client

### Additional Server Info

The plugin runs on a Waterfall proxy (`Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536`)

And weirdly, this error doesn't appear on our test server, only on the main server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.1--SNAPSHOT%3Aec41547%3A536](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.1--SNAPSHOT%3Aec41547%3A536-3498db?style=flat-square) </br>![Proxy is 1 builds behind](https://img.shields.io/badge/Your%20proxy%20is%201%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by MATRIX-feather** [comment]
With the latest Waterfall, the error message on the backend server doesn't change, and the client displays this message:

![image](https://github.com/ViaVersion/ViaVersion/assets/55654482/5f94dc65-65ae-4b86-887d-c9f0d816fe19)

**Comment by andreypfau** [comment]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: DECLARE_RECIPES, Type: FlatVarIntItem Array, Index: 7, Data: [{VarInt: 903}, {String: minecraft:green_candle}, {String: crafting_shapeless}, {String: dyed_candle}, {VarInt: 2}, {FlatVarIntItem Array: [Lcom.viaversion.viaversion.api.minecraft.item.Item;@37e0340d}], Source 0: com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$$Lambda$629/0x00000008014a1648, Packet ID: 84
Caused by: java.io.IOException: Expected root tag to be a CompoundTag, was 86
	at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:66) ~[?:?]
	at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:46) ~[?:?]
	at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:35) ~[?:?]
	at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:44) ~[?:?]
	at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:30) ~[?:?]
	at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:48) ~[?:?]
	at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:29) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:145) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:191) ~[?:?]
	at com.viaversion.viaversion.rewriter.RecipeRewriter.handleIngredient(RecipeRewriter.java:138) ~[?:?]
	at com.viaversion.viaversion.rewriter.RecipeRewriter.handleIngredients(RecipeRewriter.java:147) ~[?:?]
	at com.viaversion.viaversion.rewriter.RecipeRewriter.handleCraftingShapeless(RecipeRewriter.java:90) ~[?:?]
	at com.viaversion.viaversion.rewriter.RecipeRewriter.handleRecipeType(RecipeRewriter.java:59) ~[?:?]
	at com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets.lambda$registerPackets$0(InventoryPackets.java:81) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:366) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:328) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:307) ~[?:?]
	at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:248) ~[?:?]
	at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:48) ~[?:?]
	at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:30) ~[?:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	... 27 more

**Comment by kennytv** [comment]
Update Waterfall. Although it is worth noting that Bungee also still has issues with 1.20.2 clients.
