### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by DemonDxv** [ViaVersion/ViaVersion#3428]
### `/viaversion dump` Output

https://dump.viaversion.com/25a7647e6f214cb3b31ab78f32f9fe7b09ddcd5f5c4bf740e19f9700ca750ab7

### Console Error

```
[18:22:29 WARN]: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: ENTITY_METADATA, Type: MetaData List, Index: 1, Data: [{Integer: 2147467541}, {MetaData List: [Metadata{id=12, metaType=Int, value=-1700000}, Metadata{id=10, metaType=String, value=null}, Metadata{id=11, metaType=Byte, value=1}]}], Packet ID: 28
[18:22:29 WARN]: Caused by: java.lang.NullPointerException
[18:22:29 WARN]: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: ENTITY_METADATA, Type: MetaData List, Index: 1, Data: [{Integer: 2147467539}, {MetaData List: [Metadata{id=12, metaType=Int, value=-1700000}, Metadata{id=10, metaType=String, value=null}, Metadata{id=11, metaType=Byte, value=1}]}], Packet ID: 28
[18:22:29 WARN]: Caused by: java.lang.NullPointerException
[18:22:29 WARN]: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: ENTITY_METADATA, Type: MetaData List, Index: 1, Data: [{Integer: 2147467537}, {MetaData List: [Metadata{id=12, metaType=Int, value=-1700000}, Metadata{id=10, metaType=String, value=null}, Metadata{id=11, metaType=Byte, value=1}]}], Packet ID: 28
[18:22:29 WARN]: Caused by: java.lang.NullPointerException


[18:21:22 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.WorldPackets$3 (Anonymous)
[18:21:22 WARN]: Caused by: java.lang.NullPointerException
[18:21:22 WARN]:        at com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.WorldPackets$3.lambda$register$0(WorldPackets.java:114)
[18:21:22 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[18:21:22 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:366)
[18:21:22 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[18:21:22 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:395)
[18:21:22 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:45)
[18:21:22 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[18:21:22 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:328)
[18:21:22 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:307)
[18:21:22 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[18:21:22 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[18:21:22 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:21:22 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:21:22 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[18:21:22 WARN]:        at dev.demon.library.listeners.NettyChannelHandler.write(NettyChannelHandler.java:40)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:21:22 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[18:21:22 WARN]:        at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:110)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:21:22 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:21:22 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:21:22 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.write(NetworkManager.java:49)
[18:21:22 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager.lambda$0(NetworkManager.java:132)
[18:21:22 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[18:21:22 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:21:22 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:21:22 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:21:22 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[18:21:22 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:21:22 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:21:22 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[18:21:22 WARN]:        at java.lang.Thread.run(Thread.java:750)
```

### Bug Description

It errors in console randomly, not sure if its from my packet library that I make, but I made sure that my plugins (anticheat) hooks into via version, but for some reason we keep getting these errors.

### Steps to Reproduce

I'm not sure how it happens to be honest with you i think its when a player joins, its kinda random. If you want I could provide you with my packet library if you believe that's what could be causing it.

### Expected Behavior

Should be no console errors.

### Additional Server Info

Running Minecraft 1.8.8 VortexSpigot (had no issues until updating to 4.8.0, was fine on 4.7.0).

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by DemonDxv** [comment]
https://dump.viaversion.com/ee7f84bf63eb983dc9ae721e1e24d542c13ada496b4ae28c0bda9434cbecbff1 error still persists.

**Comment by Barvalg** [comment]
![Platform: 1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-1.8.8--R0.1--SNAPSHOT%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by SladeHazard** [comment]
Same thing happens to me with dev builds installed, if a 1.7 player joins a 1.20.1 pufferfish server console gets spammed with this:

https://hastebin.com/share/wuxanokuta.markdown

**Comment by xXkguyXx** [comment]
Can also confirm issue is present for me on 1.8.8 trying to connect via 1.20.2 client using latest version of waterfall.

**Comment by Jo0001** [comment]
> Can also confirm issue is present for me on 1.8.8 trying to connect via 1.20.2 client using latest version of waterfall proxy and viaversion,

Fresh 1.8.8 server with ViaVersion installed, behind the latest waterfall (no Via!) works fine when joining with 1.20.2
So  it might be one of your plugins sending invalid meta data. I'd suggest to first try it without your custom packet lib



> Same thing happens to me with dev builds installed, if a 1.7 player joins a 1.20.1 pufferfish server console gets spammed with this:
> 
> https://hastebin.com/share/wuxanokuta.markdown

Also works fine for me, so it might be one of your plugins. I'd suggest to try it first without AntiPopup

**Comment by xXkguyXx** [comment]
> > Can also confirm issue is present for me on 1.8.8 trying to connect via 1.20.2 client using latest version of waterfall proxy and viaversion,
> 
> Fresh 1.8.8 server with ViaVersion installed, behind the latest waterfall (no Via!) works fine when joining with 1.20.2 So it might be one of your plugins sending invalid meta data. I'd suggest to first try it without your custom packet lib
> 
> > Same thing happens to me with dev builds installed, if a 1.7 player joins a 1.20.1 pufferfish server console gets spammed with this:
> > https://hastebin.com/share/wuxanokuta.markdown
> 
> Also works fine for me, so it might be one of your plugins. I'd suggest to try it first without AntiPopup

Issue is still present without any plugins on the Minecraft server.

https://dump.viaversion.com/65642bf5e9f1fd210e05127d7c3a2e667ce92f87c8bc9097b9d308343dbcfae1

**Comment by Barvalg** [comment]
![Platform: git--TacoSpigot--d1f8c7a%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--TacoSpigot--d1f8c7a%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by xXkguyXx** [comment]
Issue is resolved with latest waterfall build.
