### ISSUE TITLE
Login with Client 1.20.2 not possible

### ISSUE THREAD

**Issue by Leahcimkrob** [ViaVersion/ViaVersion#3430]
### `/viaversion dump` Output

https://dump.viaversion.com/63cee61c1812b872d101ebc7cf9c401001d12c09de70d42503b0a384e2787422

### Console Error

```
https://gist.github.com/Leahcimkrob/24be0fad486b65a4c4ddb858eb24cfb2
```

### Bug Description

When I try to access the server with version 1.20.2 I get the message connection aborted

I hate this wrangling of authority. You say, Bungee's problem, Bungee says it's your business and I as a dev who would like to use your crap is the idiot. If there are problems, just try to solve them together and not just blame each other. It would help everyone in the MC world.

### Steps to Reproduce

When I try to access the server with version 1.20.2 I get the message connection aborted

### Expected Behavior

When I try to access the server with version 1.20.2 I get the message connection aborted

### Additional Server Info

Via only on Bunfee

Plugins:
BetterSecurity, BungeeChat, BungeePluginManagerPlus, BungeeSpy, BungeeTokens, CensorReloaded, CMIB, CraftingStore, DSGVO, ExceptionAnnouncer, floodgate, Geyser-BungeeCord, LiteBans, LuckPerms, Maintenance, MarriageMaster, NoVPN, NuVotifier, RankGift, RankUpgrade, spark, TAB, UltimateAutoRestartPassthrough, ViaBackwards, ViaVersion, cmd_alert, cmd_find, cmd_kick, cmd_list, cmd_send, cmd_server, reconnect_yaml.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A0509303%3A1738](https://img.shields.io/badge/Platform-git%3ABungeeCord--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A0509303%3A1738-3498db?style=flat-square) </br>![Proxy is 1 builds behind](https://img.shields.io/badge/Your%20proxy%20is%201%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.0): 1 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.0)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Leahcimkrob** [comment]
I use the latest available version

**Comment by kennytv** [comment]
Please try the following two things individually:
- Move Via plugins to the backend servers
- Remove your other Bungee plugins
and see if the issue persists

**Comment by Leahcimkrob** [comment]
The first option doesn't make sense to me, so it's not acceptable, but it has to work like it used to.

We have already tried the second one with the same error.

**Comment by quiquelhappy** [comment]
In my case, the players are getting instantly kicked with the 'Disconnected' message. ViaVersion is installed on the proxy. The following stacktrace is printed there

```
16:53:09 [INFO] [/[REDACTED]] <-> InitialHandler has connected
16:53:10 [INFO] [quiquelhappy] <-> ServerConnector [cool] has connected
16:53:10 [SEVERE] [quiquelhappy] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Login in phase CONFIGURATION with direction TO_CLIENT
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:85)
    at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:152)
    at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:246)
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:194)
    at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Login in phase CONFIGURATION with direction TO_CLIENT
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:824)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:25)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:10)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 42 more
16:53:10 [INFO] [quiquelhappy] disconnected with: EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Login in phase CONFIGURATION with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125
```

It seems like on the 'subservers' (paper), the join event is even triggered and the player appears as connected for a brief moment, showing the 'Player x joined' and 'Player x left' messages.

**Comment by quiquelhappy** [comment]
I've also tried moving ViaVersions to the subservers (removing it from the proxy), and now get the following error:
<img width="811" alt="image" src="https://github.com/ViaVersion/ViaVersion/assets/12534357/fa68ba94-2b94-40b8-87c5-1b3dd13fae03">

**Comment by quiquelhappy** [comment]
It seems it might be related to https://github.com/NEZNAMY/TAB/releases/tag/4.0.4, I'll be testing it in few moments

**Comment by killme** [comment]
After running into this myself, I was able to reproduce this in a newly created testing environment.
(Bungeecord: git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:49e4de7:unknown, ViaVersion: 4.8.0, No other proxy plugins, 1.12.2 backend server)

```
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Login in phase CONFIGURATION with direction TO_CLIENT
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
    at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
    at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
    at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:90)
    at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:171)
    at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:254)
    at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:202)
    at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124)
<SNIP>
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Login in phase CONFIGURATION with direction TO_CLIENT
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:848)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:26)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:10)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 40 more
```

I am not super familiar with how ViaVersion works, *but..* after some debugging
it seems that the upstream (server) and the downstream (client) handler of
BungeeCord are out of sync with each other. `BungeeServerHandler` correctly sets
the protocol of the upstream to 1.12.2 when trying to connect to the first
server, leading to a functional connection to the upstream. But at that point
the downstream handling is in 1.20.2 mode, and is in the configuration phase.
When the upstream handler then tries to complete the initial connection, this
error is thrown, as the Login (or "join game") packet is from the play/game
phase.

To me it seems that there is some code missing to basically fake the
configuration phase to make BungeeCord and the client happy, before the play
phase packets can be processed. But then again, I may be wrong, I am no expert.

I did not test connecting to a 1.20.2 upstream first, and then switching to a
1.12.2 backend. That might work, as that's not hitting this code path, but may
very well still trigger in other ways. In case anyone is trying to find a
workaround.

**Comment by quiquelhappy** [comment]
After updating some of my plugins, and updating both paper and bungeecord, this isn't happening to me anymore

**Comment by Leahcimkrob** [comment]
I still have the problem.
Paper, Geyser, Viaversion, Viarewind and Bungee are up to date
For me it is not a solution to drag the plugins to the backend server, as the advantages of the bungee cord are then lost.

![2023-09-30_09 08 10](https://github.com/ViaVersion/ViaVersion/assets/70509359/f7d69ef2-b949-42e1-ac31-4618d2269550)

**Comment by kennytv** [comment]
There is no benefit at all in running ViaVersion on the proxy other than having to place the jar multiple times. A lot of fixes are only available if run on the backend, and in general running on the proxy requires more complex handling of the client and puts more strain on it

**Comment by Leahcimkrob** [comment]
Nevertheless, it's stupid when you have to update a plugin that previously always ran via the proxy on 6 servers because you can't manage it. Bungeecrod now also works with TAB and Geyser without errors. So it's up to you somewhere why you can no longer come online with smaller versions.

**Comment by Kathezel** [comment]
I always get this error code.

I tested everything on a local server and it worked. After moving it onto a public server (G-Portal) it stop working and I get this error while trying to join.

I tried updating, downgrading, changed varies setting and everything I could find (i guess).

Is someone able to help me?

![image](https://github.com/ViaVersion/ViaVersion/assets/145993790/6d989a65-17ae-4d37-ae15-d65fa89f3090)

**Comment by cwchristerw** [comment]
I can confirm I cannot use Minecraft 1.20.2 to connect Waterfall 1.20 with ViaVersion 4.8.1. Kicked whilst connecting to lobby: Outdated server! I'm still on 1.20.1

**Comment by Kichura** [comment]
Update waterfall.

**Comment by RelumCommunity** [comment]
I got the same problem but in mine it says that i can't connect with a version that is different from 1.18.2. Before the 1.20.2 release of bungee and viaversion this problem wasn't there. The hub is in 1.18.2, the survival is in 1.20.1, if i join with 1.20.1 it's all right, but when i try to join with 1.20.2 via versions says the error above (the version depends obv by the hub version)

**Comment by RelumCommunity** [comment]
> I got the same problem but in mine it says that i can't connect with a version that is different from 1.18.2. Before the 1.20.2 release of bungee and viaversion this problem wasn't there. The hub is in 1.18.2, the survival is in 1.20.1, if i join with 1.20.1 it's all right, but when i try to join with 1.20.2 via versions says the error above (the version depends obv by the hub version)
> 
> Latest version of Via Version (+115) Latest version of Waterfall Latest version of Via Backwards (+65)

To fix the problem the only way is to use via version and via backwards on all server, but before works perfect only on waterfall

**Comment by ShuNeko** [comment]
I have the same problème every i can't connect to my waterfall server in every versions after the update... please patch this ;-; bfore viaversion work perfectly... and when i set the plugin on the Backen server i can't connect on 1.20.2 to i can just connect on 1.20.1 ...

**Comment by kennytv** [comment]
That benefit is to a problem not unique to ViaVersion, and the reason that it runs on the proxy is not to make distribution easier. Large servers should have a templating system to allow for updating processed to be streamlined and not depend on Via running worse in every other way due to constraints that come with a proxy, especially Bungee

Eitherway, please try updating ViaVersion to builds from https://ci.viaversion.com/job/ViaVersion-DEV/ as those have some important fixes to its state handling which should help, and make sure Waterfall and other proxy plugins are up to date as well
