### ISSUE TITLE
1.20.2 can't join paper 1.8.8

### ISSUE THREAD

**Issue by HowardZHY** [ViaVersion/ViaVersion#3453]
### `/viaversion dump` Output

https://dump.viaversion.com/75d091d1d57be2d6340215fa021c90dc95e78ab9bdee74c05bc919aafbd38323

### Console Error

https://mclo.gs/bZry7cx

### Bug Description

1.20.2 can't join paper 1.8.8 with only ViaVersion, the client screen is just disconnected.

### Steps to Reproduce

Paper 1.8.8, only latest Via from modrinth

### Expected Behavior

1.20.2 should join

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PaperSpigot--445%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PaperSpigot--445%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
Another error in another server that's full of plugins:

[22:52:36] [LoginProcessingThread/INFO]: UUID of player HowardZHY is b1fdcdaa-6f1d-380f-87f7-55bcc4eb508a
[22:52:36] [Netty Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_19To1_18_2 IN REMAP OF 0x01->0x01
[22:52:36] [Netty Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: byte[], Index: 3, Data: [{String: }, {byte[]: [B@3b300631}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$8 (Anonymous), Packet ID: 1
[22:52:36] [Netty Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
......
[22:52:36] [Netty Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: byte[], Index: 3, Data: [{String: }, {byte[]: [B@3b300631}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$8 (Anonymous), Packet ID: 1
[22:52:36] [Netty Server IO #1/WARN]: Caused by: java.lang.IllegalArgumentException: Length is fewer than readable bytes
[22:52:36] [Netty Server IO #1/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
[22:52:36] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.api.type.types.ByteArrayType.read(ByteArrayType.java:57)
[22:52:36] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.api.type.types.ByteArrayType.read(ByteArrayType.java:30)
[22:52:36] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:146)
[22:52:36] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:192)
[22:52:36] [Netty Server IO #1/WARN]: 	at com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$8.lambda$register$0(Protocol1_19To1_18_2.java:250)
......
[22:52:36] [Server thread/INFO]: HowardZHY[/192.168.1.102:63468] logged in with entity id 38196 at ([world]3822.5946110641034, 63.5, 1202.2111249502316)
[22:52:37] [Server thread/INFO]: HowardZHY lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: null, Type: byte[], Index: 3, Data: [{String: }, {byte[]: [B@3b300631}], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$8 (Anonymous), Packet ID: 1
[22:52:37] [Server thread/INFO]: HowardZHY left the game.
