### ISSUE TITLE
1.18.2 -> 1.19.4 Action bar remap

### ISSUE THREAD

**Issue by Dablakbandit** [ViaVersion/ViaVersion#3457]
### `/viaversion dump` Output

https://dump.viaversion.com/8f70c013fe869dad7aef7a2b2665ed44e159fd7e02a05202c4064eb1dbd6ef29

### Console Error

[02:54:50 WARN] [ViaVersion]: ERROR IN Protocol1_19To1_18_2 IN REMAP OF ACTIONBAR (0x41)
[02:54:50 ERROR]: [/IP|Dablakbandit] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: ACTIONBAR, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$$Lambda$582/0x000000040136ade8, Packet ID: 64
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:90) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:158) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:294) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:221) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: ACTIONBAR, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$$Lambda$582/0x000000040136ade8, Packet ID: 64
Caused by: java.io.IOException: Unable to read type JsonElement, found String
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:162) ~[?:?]
        at com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2.lambda$registerPackets$0(Protocol1_19To1_18_2.java:130) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:54) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        ... 47 more

### Bug Description

Joining a server with custom hud/title packets sent. 

### Steps to Reproduce

1. Launch 1.19.4
2. Join modpack.au.minescape.me
3. Once loaded into the hub (also 1.18.2 & has a hud) do /server world1

### Expected Behavior

Not being kicked.

### Additional Server Info

Working on viaversion-4.7.0 bungee servers

Backend server sends a packet with the following code:

`playerConnection.a(new PacketPlayOutChat(IChatBaseComponent.ChatSerializer.a(jsonString), ChatMessageType.c, SystemUtils.c));`

jsonString should be valid, I can do more testing to see what message is exactly sent if needed.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Aa5bbdbe%3A543](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Aa5bbdbe%3A543-3498db?style=flat-square) </br>![ViaVersion (4.8.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Dablakbandit** [comment]
Additionally working on git-ViaVersion-4.8.0:489b28e

**Comment by Dablakbandit** [comment]
Getting this error using 1.20.1 client version:

`[03:11:08 WARN] [ViaVersion]: ERROR IN Protocol1_19To1_18_2 IN REMAP OF JOIN_GAME (0x26)
[03:11:08 ERROR]: [/IP|Dablakbandit] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: JOIN_GAME, Type: Integer, Index: 9, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.EntityPackets$5 (Anonymous), Packet ID: 35
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:90) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:158) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:279) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:221) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: JOIN_GAME, Type: Integer, Index: 9, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.packets.EntityPackets$5 (Anonymous), Packet ID: 35
Caused by: java.io.IOException: Unable to read type Integer, found VarInt
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:162) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.lambda$map$0(PacketHandlers.java:54) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:54) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:a5bbdbe:543]
        ... 47 more`

**Comment by Jo0001** [comment]
Does the issue persits with the latest Via builds from ci.viaversion.com? Also try to install Via on all backend servers instead of having it on the proxy

**Comment by Dablakbandit** [comment]
> Does the issue persits with the latest Via builds from ci.viaversion.com? Also try to install Via on all backend servers instead of having it on the proxy

Still the same issue on the bungeecord.
Additionally 1.20.2 just kicks me with "Outdated server! Still on 1.18.2"

Moving viaversion to the backend just gives "Outdated server! Still on 1.18.2" for all versions.

**Comment by kennytv** [comment]
Update Bungee and make sure Via is only running on either backend or proxy (backend preferred), although note that it currently doesn't work properly with 1.20.2 clients and Via. The first error is either oudated Via or something sending packets with the wrong type through Via API
