### ISSUE TITLE
ViaVersion bug. prpbly block slime spawning

### ISSUE THREAD

**Issue by kettlson** [ViaVersion/ViaVersion#3466]
### `/viaversion dump` Output

https://dump.viaversion.com/43b9741a73a3059bc2c39a01afa5230a52259c84f695e6b734a05a10e8043f0f

### Console Error

```
Put the paste.gg link or text here.
```

### Bug Description

![image](https://github.com/ViaVersion/ViaVersion/assets/81298286/bda07621-3020-4854-a0a2-b063f2f1b569)
[latest.log](https://github.com/ViaVersion/ViaVersion/files/12798983/latest.log)
log and bug image uploaded. here u are also plugin list
![image](https://github.com/ViaVersion/ViaVersion/assets/81298286/59260410-099a-4f8c-9290-46b781e85586)

[ViaVersion] ERROR IN Protocol1_20To1_20_2 IN REMAP OF MULTI_BLOCK_CHANGE (0x45)
[03:34:28] [Netty Epoll Server IO #3/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[03:34:28] [Netty Epoll Server IO #3/WARN]: Packet Type: MULTI_BLOCK_CHANGE, Type: BlockChangeRecord Array, Index: 2, Data: [{Long: -255086701838339}], Source 0: com.viaversion.viaversion.rewriter.BlockRewriter$5 (Anonymous), Packet ID: 67
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:34:28] [Netty Epoll Server IO #3/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[03:34:28] [Netty Epoll Server IO #3/WARN]: Packet Type: MULTI_BLOCK_CHANGE, Type: BlockChangeRecord Array, Index: 2, Data: [{Long: -255086701838339}], Source 0: com.viaversion.viaversion.rewriter.BlockRewriter$5 (Anonymous), Packet ID: 67
[03:34:28] [Netty Epoll Server IO #3/WARN]: Caused by: java.lang.ArrayStoreException: com.viaversion.viaversion.api.minecraft.BlockChangeRecord1_16_2
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:48)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:29)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:146)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:192)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.rewriter.BlockRewriter$5.lambda$register$0(BlockRewriter.java:131)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaBackwards-4.8.1-SNAPSHOT.jar//com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2.transform(Protocol1_20To1_20_2.java:145)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at ViaVersion-4.8.1-SNAPSHOT.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:34:28] [Netty Epoll Server IO #3/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:34:28] [Server thread/INFO]: Kettlson lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: MULTI_BLOCK_CHANGE, Type: BlockChangeRecord Array, Index: 2, Data: [{Long: -255086701838339}], Source 0: com.viaversion.viaversion.rewriter.BlockRewriter$5 (Anonymous), Packet ID: 67

### Steps to Reproduce

.

### Expected Behavior

.

### Additional Server Info

up plugin list

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2064%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2064%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>
