### ISSUE TITLE
java.lang.NoSuchMethodError: 'void com.viaversion.viaversion.util.Config.reloadConfig()'

### ISSUE THREAD

**Issue by Manered** [ViaVersion/ViaVersion#3473]
### `/viaversion dump` Output

https://dump.viaversion.com/764ec08f98388b787c723c9c26030ef9f79045b82965225eca9dbea8938fb448

### Console Error

```java
[19:44:10 ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-4.9.0-23w40a-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoSuchMethodError: 'void com.viaversion.viaversion.util.Config.reloadConfig()'
        at com.viaversion.viabackwards.ViaBackwardsConfig.reloadConfig(ViaBackwardsConfig.java:45) ~[ViaBackwards.27448.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:72) ~[ViaBackwards.27448.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:33) ~[ViaBackwards.27448.jar:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:111) ~[ViaVersion-4.9.0-23w40a-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:92) ~[ViaVersion-4.9.0-23w40a-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Bug Description

Instead of using Config.reload() it tries to use Config.reloadConfig() which doesn't exist.

### Steps to Reproduce

1. Turn on server

### Expected Behavior

I'm expecting for this error not to occur obviously.

### Additional Server Info

Purpur, 1.19.4
```java
[19:49:02 INFO]: Bukkit Plugins: (31):
[19:49:02 INFO]:  - AltDetector, BuycraftX, Chunky, CoreProtect, DiSky, FastAsyncWorldEdit, GrimAC, LibsDisguises, LiteBans, LPC
[19:49:02 INFO]:  LuckPerms, Multiverse-Core, packetevents, *PixelMOTD, PlaceholderAPI, ProtocolLib, SkBee, SkQuery, Skript, *skript-placeholders
[19:49:02 INFO]:  spark, SpeedyCrystals, SpeedyKits, SpeedyMisc, SpeedyRegen, SpeedyShieldBreak, SpeedyTiers, TAB, ViaBackwards, ViaVersion
[19:49:02 INFO]:  WorldGuard
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1985%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Purpur--1985%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w40a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w40a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Manered** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/133597204/471fa407-bdfc-485e-a8a5-8372676c2047)
This method is the one that exists, but something tries to access "reloadConfig()" which does not exist.

**Comment by Kichura** [comment]
Update viabackwards and viarewind to the latest dev builds.

**Comment by Manered** [comment]
```
[18:31:54 ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-4.8.1(1).jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: com/viaversion/viaversion/protocols/protocol1_9_1_2to1_9_3_4/types/Chunk1_9_3_4Type
        at com.viaversion.viabackwards.protocol.protocol1_9_4to1_10.Protocol1_9_4To1_10.<init>(Protocol1_9_4To1_10.java:46) ~[ViaBackwards.27448.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:88) ~[ViaBackwards.27448.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:33) ~[ViaBackwards.27448.jar:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:106) ~[ViaVersion-4.8.1(1).jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:92) ~[ViaVersion-4.8.1(1).jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.protocols.protocol1_9_1_2to1_9_3_4.types.Chunk1_9_3_4Type
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 14 more
```

Now I get this. `com/viaversion/viaversion/protocols/protocol1_9_1_2to1_9_3_4/types/Chunk1_9_3_4Type`

**Comment by Manered** [comment]
Fixed.
