### ISSUE TITLE
I cant join witn any version

### ISSUE THREAD

**Issue by Ratioxd** [ViaVersion/ViaVersion#3479]
### `/viaversion dump` Output

https://dump.viaversion.com/fe1f6f017765300c89f1834f757e06217db14041add9eec671a41d5ab372edfa

### Console Error

```
[00:13:47 WARN]: [ViaVersion] ERROR IN Protocol1_8To1_9 IN REMAP OF WINDOW_ITEMS (0x14)
[00:13:47 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[00:13:47 WARN]: Source 0: com.viaversion.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$3 (Anonymous)
[00:13:47 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:13:47 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:13:47 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[00:13:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[00:13:47 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[00:13:47 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[00:13:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[00:13:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[00:13:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[00:13:47 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)
[00:13:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:13:47 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:13:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:13:47 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[00:13:47 WARN]: Source 0: com.viaversion.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$3 (Anonymous)
[00:13:47 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "com.viaversion.viarewind.protocol.protocol1_8to1_9.items.ItemRewriter.ENTITY_NAME_TO_ID" is null
[00:13:47 WARN]:        at ViaRewind-3.0.1-SNAPSHOT.jar//com.viaversion.viarewind.protocol.protocol1_8to1_9.items.ItemRewriter.toClient(ItemRewriter.java:179)
[00:13:47 WARN]:        at ViaRewind-3.0.1-SNAPSHOT.jar//com.viaversion.viarewind.protocol.protocol1_8to1_9.packets.InventoryPackets$3.lambda$register$0(InventoryPackets.java:92)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[00:13:47 WARN]:        at ViaVersion-4.8.1 (1).jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[00:13:47 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:13:47 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[00:13:47 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[00:13:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[00:13:47 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[00:13:47 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[00:13:47 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[00:13:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[00:13:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[00:13:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[00:13:47 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)
[00:13:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:13:47 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:13:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)```


### Bug Description

I wanted to join in a 1.8.9 minecraft but i cant,that was after i reset the server

### Steps to Reproduce

1. Join 35.202.149.137:25565 server
2. You cant join

### Expected Behavior

I expected that i just entered the server 

### Additional Server Info

i use paper 1.20.1

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--214%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--214%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Update everything to -dev builds
