### ISSUE TITLE
java.lang.NoClassDefFoundError: com/viaversion/viaversion/protocols/protocol1_9_1_2to1_9_3_4/types/Chunk1_9_3_4Type

### ISSUE THREAD

**Issue by Manered** [ViaVersion/ViaVersion#3480]
### `/viaversion dump` Output

https://dump.viaversion.com/80a9e11d38874b6b2793f2a14266b4a0b7365aaa9aa5fcda02b66b2138c6ce85

### Console Error

```py
[14:19:32 ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-4.8.1(1).jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: com/viaversion/viaversion/protocols/protocol1_9_1_2to1_9_3_4/types/Chunk1_9_3_4Type
        at com.viaversion.viabackwards.protocol.protocol1_9_4to1_10.Protocol1_9_4To1_10.<init>(Protocol1_9_4To1_10.java:46) ~[ViaBackwards.27448.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:88) ~[ViaBackwards.27448.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:33) ~[ViaBackwards.27448.jar:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:106) ~[ViaVersion-4.8.1(1).jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:92) ~[ViaVersion-4.8.1(1).jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:445) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.protocols.protocol1_9_1_2to1_9_3_4.types.Chunk1_9_3_4Type
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 14 more
```

### Bug Description

![image](https://github.com/ViaVersion/ViaVersion/assets/133597204/f18f54b1-084b-47a3-8452-75534bd2c318)
Plugin commands and config reloading is working fine, but the actual connecting crap doesn't.

### Steps to Reproduce

Login with a version lower than the server's software version.

### Expected Behavior

For it to work, obviously.

### Additional Server Info

Purpur, 1.19.4
```
Bukkit Plugins: (31):
 - AltDetector, BuycraftX, Chunky, CoreProtect, DiSky, FastAsyncWorldEdit, GrimAC, LibsDisguises, LiteBans, LPC
 LuckPerms, Multiverse-Core, packetevents, *PixelMOTD, PlaceholderAPI, ProtocolLib, SkBee, SkQuery, Skript, *skript-placeholders
 spark, SpeedyCrystals, SpeedyKits, SpeedyMisc, SpeedyRegen, SpeedyShieldBreak, SpeedyTiers, TAB, ViaBackwards, ViaVersion
 WorldGuard
```

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--1985%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Purpur--1985%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Manered** [comment]
I'm using the latest ViaVersion from the dev builds, but I guess I should update ViaBackwards. Forgot that existed.

**Comment by Manered** [comment]
Nevermind, viaversion isn't latest (I misclicked on ViaVersion instead of ViaVersion-DEV)
