### ISSUE TITLE
Caused by: com.viaversion.viaversion.exception.InformativeException

### ISSUE THREAD

**Issue by xyfwdy** [ViaVersion/ViaVersion#3488]
### `/viaversion dump` Output

https://dump.viaversion.com/c8af32ea541a226232eacd06a7f9113b713a6242249fde7250ebe493a846b44c

### Console Error

```
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[09:23:55] [Netty Server IO #0/WARN]: Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$6038/0x000001dc7d6abff8, Packet ID: 55
[09:23:55] [Netty Server IO #0/WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3035023) + length(123) exceeds writerIndex(3035039): PooledUnsafeDirectByteBuf(ridx: 3035023, widx: 3035039, cap: 4194304)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:54)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:31)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:146)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaBackwards-4.8.1.jar//com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3.lambda$registerPackets$0(EntityPackets1_19_3.java:129)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[09:23:55] [Netty Server IO #0/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[09:23:55] [Netty Server IO #0/WARN]: 	at SystemChat-1.4.1.jar//me.taucu.systemchat.net.OutboundHandler.write(OutboundHandler.java:61)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[09:23:55] [Netty Server IO #0/WARN]: 	at TAB v4.0.7.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:127)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[09:23:55] [Netty Server IO #0/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[09:23:55] [Netty Server IO #0/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[09:23:55] [Netty Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:495)
[09:23:55] [Netty Server IO #0/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:469)
[09:23:55] [Netty Server IO #0/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[09:23:55] [Netty Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[09:23:55] [Netty Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[09:23:55] [Region Scheduler Thread #0/INFO]: u6 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: PLAYER_INFO, Type: String, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_19_1to1_19_3.packets.EntityPackets1_19_3$$Lambda$6038/0x000001dc7d6abff8, Packet ID: 55
```

### Bug Description

Error when player join server 

### Steps to Reproduce

Its seen fine when I restart server , and I cant reproduce

### Expected Behavior

Player can join server 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Folia--%22edafbce%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Folia--%22edafbce%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Try updating to -dev builds, otherwise you most likely have another plugin sending bad player packets
