### ISSUE TITLE
VIAVERSION NOT WORKD

### ISSUE THREAD

**Issue by bladeRR** [ViaVersion/ViaVersion#3492]
### `/viaversion dump` Output

https://dump.viaversion.com/d4f723d15855a51f6dac591e43126b4ae51cb3a2ba02c9aff995968462bb8c8a

### Console Error

```
Put the paste.gg link or text here.
```
0:24:50 ERROR]: [/187.190.163.90:8790|bladeRR1] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SPAWN_ENTITY, Type: VarInt, Index: 1, Data: [], Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$3 (Anonymous), Packet ID: 0
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:90) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:158) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.ServerConnector.cutThrough(ServerConnector.java:390) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:179) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.protocol.packet.LoginSuccess.handle(LoginSuccess.java:62) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SPAWN_ENTITY, Type: VarInt, Index: 1, Data: [], Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$3 (Anonymous), Packet ID: 0
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45) ~[?:?]
        at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:70) ~[?:?]
        at com.viaversion.viaversion.api.type.types.VarIntType.read(VarIntType.java:29) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:142) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.lambda$map$0(PacketHandlers.java:54) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:54) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        ... 52 more
[20:24:50 INFO]: [bladeRR1] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SPAWN_ENTITY, Type: VarInt, Index: 1, Data: [], Source 0: com.viaversion.viaversion.rewriter.EntityRewriter$3 (Anonymous), Packet ID: 0 @ io.netty.handler.codec.MessageToMessageEncoder:107

### Bug Description

I have viaversion installed on my bungeecord, but no players from 1.20.2 can join the game and people from 1.20 and 1.20.1 can only join the hub, but not the survival.

### Steps to Reproduce

1.- I enter the game
2.- viaversion does not work

### Expected Behavior

who could enter my server in versions 1.20-1.20.1-1.20.2

### Additional Server Info

bungeecord - proxy waterfall 1.20 

AdvancedNMotd-9.2.0.jar

BungeeGuard (1).jar

BungeePackFix-1.1.1.jar

BungeePing.jar

BungeeReconnect.jar

floodgate-bungee.jar

LuckPerms-Bungee-5.4.41 (1).jar

nAntiBot.jar

nLogin.jar

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ac996222%3A548](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3Ac996222%3A548-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w42a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w42a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.0-23w42a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w42a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Move via* to the backend servers as bungee/waterfall is broken.

**Comment by bladeRR** [comment]
> Muévase vía* a los servidores backend cuando el bungee/cascada se rompa.

fail conection / not work

**Comment by Kichura** [comment]
Then you have a third-party plugin that is causing connectivity loss, please do a binary search to see what causes it to fail. *(as latest viaversion seems to work fine)*

**Comment by bladeRR** [comment]
https://mclo.gs/VxSDk94

**Comment by Kichura** [comment]
Remove viaversion from waterfall.

**Comment by bladeRR** [comment]
in version 1.20.2 I can't log in, it says: "conxion failure with the server" and only lets me disconnect, the bad thing is that nothing appears in my log.

**Comment by Kichura** [comment]
Then it's either protocolize or something else is causing the problem to happen.

**Comment by bladeRR** [comment]
in version 1.20 and 1.20.1, I can log in without any problem.

**Comment by bladeRR** [comment]
[21:40:11 INFO]: blade lost connection: Disconnected
[21:40:11 INFO]: blade left the game

**Comment by bladeRR** [comment]
that's all I get on the console when I try to connect on version 1.20.2

**Comment by Kichura** [comment]
Then please perform a binary search as the disconnect logs don't tell us that much.

**Comment by bladeRR** [comment]
I deleted all my plugins, I don't know exactly what I should do or look for now.

**Comment by Kichura** [comment]
did you disable all proxy plugins too? (if yes; then something clearly isn't right)

**Comment by bladeRR** [comment]
no, the bungeecord plugins are in the same place, the hub and survival plugins were deleted, only via version and viabackwards are left.

**Comment by Kichura** [comment]
Then it's either protocolize or BungeePackFix *(likely both)* - otherwise this is all i can figure out from this entire issue.
