### ISSUE TITLE
Bug and Error

### ISSUE THREAD

**Issue by MootComb** [ViaVersion/ViaVersion#3516]
### `/viaversion dump` Output

https://dump.viaversion.com/12f56d04198ea58318f857ec054d7df0b66170ca11158f01d9831b924d0739f2

### Console Error

[18:05:13 WARN]: [ViaVersion] ERROR IN Protocol1_18_2To1_19 IN REMAP OF SPAWN_PARTICLE (0x21)
[18:05:13 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:05:13 WARN]: Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.BlockItemPackets1_19$3 (Anonymous)
[18:05:13 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:05:13 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:05:13 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:05:13 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[18:05:13 WARN]:        at TAB v4.0.7.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:127)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:05:13 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:05:13 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:476)
[18:05:13 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:450)
[18:05:13 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:05:13 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:05:13 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:05:13 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[18:05:13 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:05:13 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:05:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:05:13 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:05:13 WARN]: Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.BlockItemPackets1_19$3 (Anonymous)
[18:05:13 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[18:05:13 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[18:05:13 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[18:05:13 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[18:05:13 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[18:05:13 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195)
[18:05:13 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[18:05:13 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155)
[18:05:13 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[18:05:13 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[18:05:13 WARN]:        at ViaBackwards-4.8.1.jar//com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.BlockItemPackets1_19$3.lambda$register$0(BlockItemPackets1_19.java:123)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[18:05:13 WARN]:        at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[18:05:13 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:05:13 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:05:13 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:05:13 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[18:05:13 WARN]:        at TAB v4.0.7.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:127)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:05:13 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:05:13 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:05:13 WARN]:        at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:476)
[18:05:13 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$11(NetworkManager.java:450)
[18:05:13 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:05:13 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:05:13 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:05:13 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[18:05:13 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:05:13 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:05:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:05:13 INFO]: MootComb9620292 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.BlockItemPackets1_19$3 (Anonymous)

### Bug Description

I was kicked off the server

### Steps to Reproduce

1. Connecting to the server
2. I am being kicked with an error in the console

### Expected Behavior

I shouldn't have been kicked out.

### Additional Server Info

Velocity using.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by MootComb** [comment]
https://dump.viaversion.com/df3590996d0126b30980dd314d255cf2ac321db5459620050f71a2245c4fd921

**Comment by MootComb** [comment]
> ![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://camo.githubusercontent.com/657f64877b920b0ab682d36091bdc2f4f758b44202d3855ee3aed7aa83e4df1b/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3139362532302532384d43253341253230312e32302e312532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.8.1): 2 commits behind master](https://camo.githubusercontent.com/d04692ade77da9f5c916ab5f4333801166a58ce4e50810ae35119638f9c47e88/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e382e31292d32253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265) ![ViaBackwards(4.8.1): 2 commits behind master](https://camo.githubusercontent.com/d485f50625969e33416f543706aea1c831fd1948472744623e744a7488459eda/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e382e31292d32253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump
https://dump.viaversion.com/df3590996d0126b30980dd314d255cf2ac321db5459620050f71a2245c4fd921

**Comment by Barvalg** [comment]
![Platform: git--Paper--196%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--Paper--196%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by HowardZHY** [comment]
Try to use DEV builds: 
https://ci.viaversion.com/job/ViaVersion-DEV/
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/

**Comment by NeOAnderson2005** [comment]
I have this exact same issue and have tried dev builds but the error persists.

**Comment by bessel28** [comment]
I am also experiencing this issue. Also occurs when using the dev builds

**Comment by Kichura** [comment]
1. Update viaversion to the dev builds,
2. If you have any proxy like bungee/velocity - update it too,
3. If the first two suggestions fail; very likely caused by bad third-party plugin, a binary search will be needed for this one.
