### ISSUE TITLE
encounter a strange problem...

### ISSUE THREAD

**Issue by youguo233** [ViaVersion/ViaVersion#3518]
### `/viaversion dump` Output

https://dump.viaversion.com/c29a4516bae16dfeaacc8cb5ed3e5ccad55b38cfa27e374da29acaa1a55025fb

### Console Error

 [ViaVersion] ERROR IN Protocol1_9To1_8 IN REMAP OF ENTITY_METADATA (0x1C)
[16:47:53 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:47:53 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:47:53 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[16:47:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:47:53 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:47:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:47:53 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:47:53 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)
[16:47:53 WARN]: Caused by: java.lang.NullPointerException
[16:47:53 WARN]:        at com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7.lambda$register$0(EntityPackets.java:199)
[16:47:53 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[16:47:53 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[16:47:53 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426)
[16:47:53 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[16:47:53 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[16:47:53 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[16:47:53 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[16:47:53 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[16:47:53 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[16:47:53 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:47:53 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:47:53 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[16:47:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:47:53 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:47:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:47:53 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:47:53 WARN]: [ViaVersion] ERROR IN Protocol1_9To1_8 IN REMAP OF ENTITY_METADATA (0x1C)
[16:47:53 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:47:53 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:47:53 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[16:47:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:47:53 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:47:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:47:53 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:47:53 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7 (Anonymous)
[16:47:53 WARN]: Caused by: java.lang.NullPointerException
[16:47:53 WARN]:        at com.viaversion.viaversion.protocols.protocol1_9to1_8.packets.EntityPackets$7.lambda$register$0(EntityPackets.java:199)
[16:47:53 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[16:47:53 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[16:47:53 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426)
[16:47:53 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[16:47:53 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[16:47:53 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[16:47:53 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[16:47:53 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[16:47:53 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[16:47:53 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[16:47:53 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:238)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[16:47:53 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[16:47:53 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:47:53 WARN]:        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[16:47:53 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310)
[16:47:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[16:47:53 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[16:47:53 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[16:47:53 WARN]:        at java.lang.Thread.run(Unknown Source)

### Bug Description

I couldn't know exactly when it will happen..

From what I saw, it will happen at:

(1) fallback connect to a lobby server when kicked from a game server. And it also cause this fallback-connect to fail (disconnected from proxy)
<img width="1321" alt="image" src="https://github.com/ViaVersion/ViaVersion/assets/62585447/bd9ed043-16d1-4a26-8b8d-6ba7f7f776d1">

(2) suddenly happen, when player is online.

### Steps to Reproduce

sorry...... I can't ensure it

### Expected Behavior

this problem will not cause player to disconnect from proxy

### Additional Server Info

I use latest bungeecord and this following plugins:

BCRedisConnector-1.0-SNAPSHOT.jar
BotSentry-9.5.3-THANATOS-SpigotMC.jar
BungeeAnnouncer-1.2.jar
BungeeControl-1.0-SNAPSHOT.jar
Bungeei.jar
BungeeSystem.jar
ColorMOTD.jar
FastLoginBungee.jar
Report.jar
SafeNET-3.7.jar
servershout-1.0 Release.jar
SkinsRestorer.jar
RedisBungee-0.5.jar
SQL_Lib_bungee.jar

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by youguo233** [comment]
https://dump.viaversion.com/c29a4516bae16dfeaacc8cb5ed3e5ccad55b38cfa27e374da29acaa1a55025fb

**Comment by Barvalg** [comment]
![Platform: git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by youguo233** [comment]
https://dump.viaversion.com/8d8dd1ade8f7e9c98f042ab7eb6b204330917801e40d74b5dff42300aa19c012

**Comment by Barvalg** [comment]
![Platform: git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--db6de12--18fbb24%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.0-23w44a-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w44a--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
This seems to be either caused by a bad third-party plugin or you forgotten to remove viaversion from bungee, can you perform a binary search to see what causes that to happen?
