### ISSUE TITLE
Error when rewriting a SPAWN_PARTICLE packet

### ISSUE THREAD

**Issue by bessel28** [ViaVersion/ViaVersion#3521]
### `/viaversion dump` Output

https://dump.viaversion.com/02b631d05a124abcad4f5ada600022749f73df01d89a30b61e28bc3212562938

### Console Error

```
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SPAWN_PARTICLE, Type: FlatItem, Index: 11, Data: [{Integer: 36}, {Boolean: true}, {Float: 1013.0227}, {Float: 11.0}, {Float: 1989.7}, {Float: 0.3}, {Float: 0.3}, {Float: 0.3}, {Float: 0.1}, {Integer: 2}], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$2 (Anonymous), Packet ID: 34
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:233) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:320) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:151) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:78) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SPAWN_PARTICLE, Type: FlatItem, Index: 11, Data: [{Integer: 36}, {Boolean: true}, {Float: 1013.0227}, {Float: 11.0}, {Float: 1989.7}, {Float: 0.3}, {Float: 0.3}, {Float: 0.3}, {Float: 0.1}, {Integer: 2}], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$2 (Anonymous), Packet ID: 34
Caused by: java.io.IOException: Expected root tag to be a CompoundTag, was 1
        at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:59) ~[?:?]
        at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:45) ~[?:?]
        at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:34) ~[?:?]
        at com.viaversion.viaversion.api.type.types.minecraft.FlatItemType.read(FlatItemType.java:45) ~[?:?]
        at com.viaversion.viaversion.api.type.types.minecraft.FlatItemType.read(FlatItemType.java:31) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:146) ~[?:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.data.ParticleMapping$3.rewrite(ParticleMapping.java:111) ~[?:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.data.ParticleMapping$ParticleData.rewriteData(ParticleMapping.java:187) ~[?:?]
        at com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.PlayerPacket1_13$2.lambda$register$0(PlayerPacket1_13.java:145) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:236) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:47) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:29) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[velocity.jar:3.2.0-SNAPSHOT (git-c7ba5255-b244)]
        ... 54 more
```

### Bug Description

The SPAWN_PARTICLE packet when rewriting an Item Particle (ID 36) throws an exception and kicks all 1.8 players. Tested with the latest dev builds with no change.

### Steps to Reproduce

Log in with 1.8.*
run `/particle item minecraft:apple ~ ~ ~ 0 0 0 1 1 force`
player is disconnected

### Expected Behavior

Player should not be disconnected

### Checklist

- [x] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--c7ba5255--b244%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--c7ba5255--b244%29-3498db?style=flat-square) </br>![Proxy is 50 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2050%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Update velocity.

**Comment by bessel28** [comment]
Still occurs after updating velocity

https://dump.viaversion.com/c3a1d6839e3a600e0c21aec2e5b132eb096c8ca79d61b39dcc35e2559eff1120

**Comment by Barvalg** [comment]
![Platform: velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29](https://img.shields.io/badge/Platform-velocity%203.2.0--SNAPSHOT%20%28git--8dcc7ee3--b294%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.0): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.0)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>
