### ISSUE TITLE
An error occurred in metadata handler EntityPackets1_20 for ITEM_DISPLAY

### ISSUE THREAD

**Issue by LoneDev6** [ViaVersion/ViaVersion#3524]
### `/viaversion dump` Output

https://dump.viaversion.com/ebc5d84aacdeb475bc2eaf2b01877240f5e2962c12923ee15152b197a739228e

### Console Error

```
[21:07:42] [Netty Server IO #2/ERROR]: [ViaVersion] An error occurred in metadata handler EntityPackets1_20 for ITEM_DISPLAY entity type: Metadata{id=12, metaType=MetaType{typeId=26, type=Vector3f}, value=com.viaversion.viaversion.api.minecraft.Vector3f@df4bcb9}
[21:07:42] [Netty Server IO #2/ERROR]: [ViaVersion] Full metadata: Metadata{id=11, metaType=MetaType{typeId=26, type=Vector3f}, value=com.viaversion.viaversion.api.minecraft.Vector3f@708f1f77}
Metadata{id=12, metaType=MetaType{typeId=26, type=Vector3f}, value=com.viaversion.viaversion.api.minecraft.Vector3f@df4bcb9}
Metadata{id=14, metaType=MetaType{typeId=27, type=Quaternion}, value=Quaternion{x=0.0, y=1.0, z=0.0, w=-0.0}}
Metadata{id=15, metaType=MetaType{typeId=0, type=Byte}, value=3}
Metadata{id=16, metaType=MetaType{typeId=1, type=VarInt}, value=15728880}
Metadata{id=17, metaType=MetaType{typeId=3, type=Float}, value=0.05}
Metadata{id=23, metaType=MetaType{typeId=7, type=FlatVarIntItem}, value=Item{identifier=605, amount=4, data=0, tag=null}}
Metadata{id=24, metaType=MetaType{typeId=0, type=Byte}, value=6}
[21:07:42] [Netty Server IO #2/WARN]: java.lang.ClassCastException: class com.viaversion.viaversion.api.minecraft.Vector3f cannot be cast to class com.viaversion.viaversion.api.minecraft.Quaternion (com.viaversion.viaversion.api.minecraft.Vector3f and com.viaversion.viaversion.api.minecraft.Quaternion are in unnamed module of loader 'ViaVersion-4.8.1.jar' @2425c575)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaBackwards-4.8.1.jar//com.viaversion.viabackwards.protocol.protocol1_19_4to1_20.packets.EntityPackets1_20.lambda$registerRewrites$3(EntityPackets1_20.java:145)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:125)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaBackwards-4.8.1.jar//com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.handleMetadata(EntityRewriterBase.java:71)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.rewriter.EntityRewriter$4.lambda$register$0(EntityRewriter.java:391)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[21:07:42] [Netty Server IO #2/WARN]: 	at ViaVersion-4.8.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[21:07:42] [Netty Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[21:07:42] [Netty Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[21:07:42] [Netty Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[21:07:42] [Netty Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[21:07:42] [Netty Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$proxyAction$7(NettyChannelInjector.java:604)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:07:42] [Netty Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:07:42] [Netty Server IO #2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Bug Description

Joining with 1.18.2 client on a 1.20.2 server which has ITEM_DISPLAY entities spawned in the world (real entities, no packets used).

NOTE: I noticed that the client shows entities counter increased in the F3 menu, I have no idea which entities the client has spawned as the ITEM_DISPLAY doesn't even exists in this version, so what entity is ViaVersion sending?

### Steps to Reproduce

1. create a display entity
2. join using 1.18.2 client
3. see the error

### Expected Behavior

No error and no display entity spawned as the client can't handle them.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2082%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2082%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by LoneDev6** [comment]
I am already using the latest builds: 4.8.1.
I now updated Purpur but the issue persists.

**Comment by Kichura** [comment]
Update via* to the dev builds instead - if it fails then itemsadder is causing issues with our plugins. *(assuming you're dev of this)*

**Comment by LoneDev6** [comment]
It's not ItemsAdder, I'm working on a new plugin.
I'm using the Spigot API to spawn ItemDisplay entities, I tested via vanilla commands and also these entities are causing issues.

Using the dev builds have fixed the issue! :D
One limitation is that the display entities are not showing items and they are not correctly shifted using transformations, but it's understandable as the client has no idea on how to spawn and handle them.
Might be worth disabling them by default using a new Viaversion configuration attribute, as they look bugged otherwise.
