### ISSUE TITLE
带有viaversion插件的服务器 重启之后一段时间内玩家无法连接至服务器

### ISSUE THREAD

**Issue by Leoparking** [ViaVersion/ViaVersion#3532]
### `/viaversion dump` Output

https://dump.viaversion.com/295c04c0cd6542b5bc736bb0b201d6161125730aa179be5791f73f56010f4128

### Console Error

[16:16:24 INFO]: UUID of player LeopardKing is da077ff7-b443-3d84-a0ff-5057dbc1b309
[16:16:24 WARN]: [ViaVersion] ERROR IN BaseProtocol1_7 IN REMAP OF LOGIN 0x02->0x02
[16:16:24 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[16:16:24 WARN]: Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$8363.0x00000008021dd418
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[16:16:24 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[16:16:24 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[16:16:24 WARN]:        at TRANSFORMER/minecraft@1.19.4/net.minecraft.network.Connection.m_243087_(Connection.java:224)
[16:16:24 WARN]:        at TRANSFORMER/minecraft@1.19.4/net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:213)
[16:16:24 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:16:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[16:16:24 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[16:16:24 WARN]: Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$8363.0x00000008021dd418
[16:16:24 WARN]: Caused by: java.lang.IllegalArgumentException: UUID string too large
[16:16:24 WARN]:        at java.base/java.util.UUID.fromString1(UUID.java:264)
[16:16:24 WARN]:        at java.base/java.util.UUID.fromString(UUID.java:258)
[16:16:24 WARN]:        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.passthroughLoginUUID(BaseProtocol1_7.java:192)
[16:16:24 WARN]:        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.lambda$registerPackets$0(BaseProtocol1_7.java:126)
[16:16:24 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[16:16:24 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[16:16:24 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[16:16:24 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[16:16:24 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[16:16:24 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[16:16:24 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[16:16:24 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[16:16:24 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.codec@4.1.82.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[16:16:24 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[16:16:24 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[16:16:24 WARN]:        at TRANSFORMER/minecraft@1.19.4/net.minecraft.network.Connection.m_243087_(Connection.java:224)
[16:16:24 WARN]:        at TRANSFORMER/minecraft@1.19.4/net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:213)
[16:16:24 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.transport@4.1.82.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:16:24 WARN]:        at MC-BOOTSTRAP/io.netty.common@4.1.82.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:16:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[16:16:24 WARN]: [HolographicDisplays] Unexpected error while modifying the channel pipeline.
java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.82.Final.jar%23148!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.82.Final.jar%23148!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.82.Final.jar%23148!/:4.1.82.Final]
        at me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.lambda$injectPacketListener$0(VersionNMSManager.java:81) ~[?:?]
        at me.filoghost.holographicdisplays.nms.v1_19_R3.VersionNMSManager.lambda$modifyPipeline$2(VersionNMSManager.java:115) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.82.Final.jar%23145!/:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.82.Final.jar%23145!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.82.Final.jar%23145!/:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [netty-transport-4.1.82.Final.jar%23148!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.82.Final.jar%23145!/:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.82.Final.jar%23145!/:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
[16:16:24 ERROR]: Could not find parent org/bukkit/metadata/MetadataValueAdapter for class org/bukkit/metadata/LazyMetadataValue in classloader jdk.internal.loader.ClassLoaders$AppClassLoader@70dea4e on thread Thread[#24,ForkJoinPool.commonPool-worker-1,5,main]
[16:16:24 ERROR]: An error occurred building event handler
java.lang.ClassNotFoundException: org.bukkit.metadata.MetadataValueAdapter
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar:?]
        at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar:?]
        at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar:?]
        at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar:6.0.5+0+master.c510e2cc]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.6.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.6.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:575) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:138) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:133) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at wtf.choco.veinminer.listener.PlayerDataListener.lambda$onPlayerJoin$2(PlayerDataListener.java:40) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) [?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
[16:16:24 INFO]: LeopardKing lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$8363.0x00000008021dd418
[16:16:24 INFO]: LeopardKing left the game
[16:16:24 WARN]: handleDisconnection() called twice
[16:16:28 WARN]: [Slimefun] 检测到没有安装 SlimeGlue (粘液胶), 你将缺失对一些插件的额外保护检查!
[16:16:28 WARN]: [Slimefun] 下载: https://github.com/Xzavier0722/SlimeGlue
[16:16:46 INFO]: [LiteCustomAnnouncer] 更新检查失败!
[16:19:22 INFO]: UUID of player LeopardKing is da077ff7-b443-3d84-a0ff-5057dbc1b309
[16:19:22 INFO]: LeopardKing joined the game
[16:19:22 INFO]: LeopardKing[/223.74.58.103:59570] logged in with entity id 342 at ([world]17.57606945162586, 81.0, 9.445865210036104)
[16:19:23 WARN]: Invalid channel name received: legacy:fml|hs. Ignoring
[16:19:23 WARN]: Invalid channel name received: legacy:fml|hs. Ignoring

### Bug Description

这是我之前发送的[错误报告](https://github.com/ViaVersion/ViaVersion/issues/3531)
BUG是同一个
得到回复是“不支持mohist”

后来我更换了via插件到最新的alpha版本，问题似乎解决了一点
今天发现，服务器重启之后一段时间内。如果玩家出现无法加入服务器的情况，过段时间玩家尝试重新连接却能正常进入游戏。
![Uploading 无法进入服务器.png…]()

### Steps to Reproduce

1.在正常情况下重启服务器程序，在服务器启动完毕后，如果有玩家尝试加入游戏，会被踢出，原因：

lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$8350.0x00000008021f2f40

### Expected Behavior

我希望viaversion插件可以更快起效，而不是在服务器重启之后的几十分钟甚至相当长的一段时间后 仍处于“内部错误”中

### Additional Server Info

我还使用了Waterfall服务端进行跨越服务器传送，waterfall里面安装了同一个版本的via插件

### Checklist

- [ ] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.19.4--190%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-1.19.4--190%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![Mohist is not supported](https://img.shields.io/badge/Mohist%20is%20not%20supported-orange?style=flat-square) </br>![ViaVersion (4.9.0-23w46a-SNAPSHOT): 6 commits behind dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--23w46a--SNAPSHOT)-6%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(4.9.0-23w46a-SNAPSHOT): 3 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(4.9.0--23w46a--SNAPSHOT)-3%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Once again, Mohist is not supported

**Comment by HowardZHY** [comment]
Via plugins are only running on EITHER the backend servers (e.g. Paper) OR the proxy (e.g. BungeeCord), not on both.

**Comment by MagicTeaMC** [comment]
Use English.

**Comment by Leoparking** [comment]
> 使用英语。

Because my server not only allows different versions of JAVA players to enter the game, but also allows players from the bedrock version to enter, I have left a version on the proxy (such as Bunge Core) to cope with the upward compatibility of the JAVA version, while leaving a version on the backend server (such as Paper) that is compatible with the new and old versions of the JAVA client (geyser will label bedrock players as JAVA1.20.2). After verification, it can be achieved under normal circumstances (outside of this bug) and can be entered into the game using JAVA 1.8-1.20.

However, if the agent (such as Bunge Core) is running, the bedrock version player cannot enter the game (indicating a version mismatch). If it is only running on a backend server (such as Paper), JAVA users cannot enter the game (triggering this bug)

**Comment by HowardZHY** [comment]
> > 使用英语。
> 
> Because my server not only allows different versions of JAVA players to enter the game, but also allows players from the bedrock version to enter, I have left a version on the proxy (such as Bunge Core) to cope with the upward compatibility of the JAVA version, while leaving a version on the backend server (such as Paper) that is compatible with the new and old versions of the JAVA client (geyser will label bedrock players as JAVA1.20.2). After verification, it can be achieved under normal circumstances (outside of this bug) and can be entered into the game using JAVA 1.8-1.20.
> 
> However, if the agent (such as Bunge Core) is running, the bedrock version player cannot enter the game (indicating a version mismatch). If it is only running on a backend server (such as Paper), JAVA users cannot enter the game (triggering this bug)

你唔知Via不可代理及群组两个都装？

**Comment by MagicTeaMC** [comment]
> > 使用英语。
> 
> Because my server not only allows different versions of JAVA players to enter the game, but also allows players from the bedrock version to enter, I have left a version on the proxy (such as Bunge Core) to cope with the upward compatibility of the JAVA version, while leaving a version on the backend server (such as Paper) that is compatible with the new and old versions of the JAVA client (geyser will label bedrock players as JAVA1.20.2). After verification, it can be achieved under normal circumstances (outside of this bug) and can be entered into the game using JAVA 1.8-1.20.
> 
> However, if the agent (such as Bunge Core) is running, the bedrock version player cannot enter the game (indicating a version mismatch). If it is only running on a backend server (such as Paper), JAVA users cannot enter the game (triggering this bug)

you can just use Via* on proxy

**Comment by HowardZHY** [comment]
如果非要Mohist，只在群组装Via，但若有错误不会提供支持，Use as own Risk

**Comment by Leoparking** [comment]
这是我的服务器链接：emc.2m.pub （JAVA），基岩版play.idccap.com:28156此时，它已经恢复正常了

This is my server IP link: emc.2m.pub （JAVA）, bedrock：play.idccap.com:28156
and at this point, it has returned to normal
谢谢建议
