### ISSUE TITLE
agreement 1_9_1_2to1_9_3_4 NoClassDefFoundError

### ISSUE THREAD

**Issue by BingZi-233** [ViaVersion/ViaVersion#3533]
### `/viaversion dump` Output

https://dump.viaversion.com/d4804551c20c69ad989860926d61a9ed4792d45569eafdc4f79ec52271d5ae69

### Console Error

```
[16:29:38] [Server thread/ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-4.8.1.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: com/viaversion/viaversion/protocols/protocol1_9_1_2to1_9_3_4/types/Chunk1_9_3_4Type
	at com.viaversion.viabackwards.protocol.protocol1_9_4to1_10.Protocol1_9_4To1_10.<init>(Protocol1_9_4To1_10.java:46) ~[ViaBackwards-4.7.0.jar:?]
	at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:88) ~[ViaBackwards-4.7.0.jar:?]
	at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:33) ~[ViaBackwards-4.7.0.jar:?]
	at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:106) ~[ViaVersion-4.8.1.jar:?]
	at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:92) ~[ViaVersion-4.8.1.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[paper-1.19.3.jar:git-Paper-448]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.3.jar:git-Paper-448]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:428) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-448]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.protocols.protocol1_9_1_2to1_9_3_4.types.Chunk1_9_3_4Type
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 14 more
```

### Bug Description

- Starting minecraft server version 1.19.3
- This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)

### Steps to Reproduce

- install ViaVersion-4.8.1.jar
- start server
- show log

### Expected Behavior

No Error Message

### Additional Server Info

bungeeCord 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--448%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--448%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.7.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
