### ISSUE TITLE
HELP ERROR VIA-VERSION

### ISSUE THREAD

**Issue by ChiriGamerYT** [ViaVersion/ViaVersion#3535]
### `/viaversion dump` Output

https://dump.viaversion.com/380caa9b7568809c99698b46c4f77ff28be0a5f93b32e9ce9e06a6108f2da731

### Console Error

```
[20:31:38 WARN] [ViaVersion]: ERROR IN Protocol1_19To1_18_2 IN REMAP OF ACTIONBAR (0x41)
[20:31:38 ERROR]: [/90.165.218.196:62473|ChiriGamerYT] -> UpstreamBridge - encountered exception
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: ACTIONBAR, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$$Lambda$1192/0x00007f84d864fb50, Packet ID: 64
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:90) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:158) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:294) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:220) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: ACTIONBAR, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$$Lambda$1192/0x00007f84d864fb50, Packet ID: 64
Caused by: java.io.IOException: Unable to read type JsonElement, found String
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:162) ~[?:?]
        at com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2.lambda$registerPackets$0(Protocol1_19To1_18_2.java:130) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:54) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:320f9e1:554]
        ... 47 more
[20:31:38 INFO]: [ChiriGamerYT] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: ACTIONBAR, Type: JsonElement, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.protocol1_19to1_18_2.Protocol1_19To1_18_2$$Lambda$1192/0x00007f84d864fb50, Packet ID: 64 @ io.netty.handler.codec.MessageToMessageEncoder:107
```

### Bug Description

Wen I go to the server lobby it says an error (only on that server)

### Steps to Reproduce

1. open de server
2. login
3. go to the lobby 2 server
4. it crash

### Expected Behavior

It put a error

### Additional Server Info

bungeecord: via version, via backwars

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554-3498db?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by ChiriGamerYT** [comment]
https://dump.viaversion.com/c3b578b0f19b4f9b9d812343b9406501cbbf483ead49adec544994a3662ee469

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by ChiriGamerYT** [comment]
https://dump.viaversion.com/c3b578b0f19b4f9b9d812343b9406501cbbf483ead49adec544994a3662ee469

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by Kichura** [comment]
Have you tried running via* on the spigot/paper servers instead?

**Comment by ChiriGamerYT** [comment]
yes

**Comment by ChiriGamerYT** [comment]
https://dump.viaversion.com/308298e2ff870eeb1277def0713c52a802062b23af35a70e5ffaef69adc6f9c0

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554-3498db?style=flat-square) </br>![ViaVersion (4.8.1): Even with master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.8.1): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
You did not remove viaversion and viabackwards from waterfall.

**Comment by ChiriGamerYT** [comment]
yes

**Comment by ChiriGamerYT** [comment]
![image](https://github.com/ViaVersion/ViaVersion/assets/142495711/1a81e542-d7a1-4f19-9e0e-bf735dfb8523)

**Comment by kennytv** [comment]
The above should be fixed now
