### ISSUE TITLE
com.viaversion.viaversion.protocols.protocol1_20to1_19_4.packets.InventoryPackets$1

### ISSUE THREAD

**Issue by pixkk** [ViaVersion/ViaVersion#3536]
### `/viaversion dump` Output

https://dump.viaversion.com/257524436e4e6c13fae0f90d9804341cc026bfa0231081c929905238ce71c1a2

### Console Error

```
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_20to1_19_4.packets.InventoryPackets$1 (Anonymous)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:263) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:228) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_20to1_19_4.packets.InventoryPackets$1 (Anonymous)
Caused by: java.lang.IllegalArgumentException: Biome count not set
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        at com.viaversion.viaversion.rewriter.BlockRewriter.lambda$chunkDataHandler1_19$0(BlockRewriter.java:175) ~[?:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:54) ~[?:?]
        at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[waterfall-1.19-516.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:6ca281b:516]
        ... 51 more
[11:04:47 INFO]: [lopkan] disconnected with: EncoderException : com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.protocols.protocol1_20to1_19_4.packets.InventoryPackets$1 (Anonymous) @ io.netty.handler.codec.MessageToMessageEncoder:107
```

### Bug Description

When i try connect to server (purpur 1.16.5) with minecraft 1.20, it give this error.

### Steps to Reproduce

1. Connect to server using minecraft 1.20

### Expected Behavior

I logged into the server.

### Additional Server Info

I`m use waterfall. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A6ca281b%3A516](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.19--R0.1--SNAPSHOT%3A6ca281b%3A516-3498db?style=flat-square) </br>![Proxy is 999 builds behind](https://img.shields.io/badge/Your%20proxy%20is%20999%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.8.1): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
See above

**Comment by pixkk** [comment]
With latest waterfall [ViaVersion-4.9.0-1.20.3-rc1-SNAPSHOT.jar](https://ci.viaversion.com/job/ViaVersion-DEV/lastSuccessfulBuild/artifact/build/libs/ViaVersion-4.9.0-1.20.3-rc1-SNAPSHOT.jar) i can login to server, but can`t open inventory or chests - 
![image](https://github.com/ViaVersion/ViaVersion/assets/30828435/218d4746-de98-467d-bf0a-458aa639fa20)

**Comment by pixkk** [comment]
New dump - https://dump.viaversion.com/c00f7586d2ab7dfbfbbbaeaa9ad31a326925a571f960936103f22d960610dfdb
![image](https://github.com/ViaVersion/ViaVersion/assets/30828435/2144d99e-34b4-41de-ae35-4289c1f9b543)

**Comment by Barvalg** [comment]
![Platform: git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554](https://img.shields.io/badge/Platform-git%3AWaterfall--Bootstrap%3A1.20--R0.2--SNAPSHOT%3A320f9e1%3A554-3498db?style=flat-square) </br>![ViaVersion (4.9.0-1.20.3-rc1-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(4.9.0--1.20.3--rc1--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>

**Comment by kennytv** [comment]
You also need to update ViaBackwards

**Comment by pixkk** [comment]
I have latest 4.8.1 version
![image](https://github.com/ViaVersion/ViaVersion/assets/30828435/c5f88c15-613a-47ec-b2f1-4adabb690f3b)

**Comment by pixkk** [comment]
Problem resolved. I did not know that viabackwards moved to papermc. Updating to latest dev build resolve problem.
