### ISSUE TITLE
All clients kicked when sending iconcrack particle

### ISSUE THREAD

**Issue by Packsolite** [ViaVersion/ViaVersion#3553]
### `/viaversion dump` Output

https://dump.viaversion.com/293676c003c26ceb00f5f9c6528754b5ad80dd0b8a58a26527cb74942e569292

### Console Error

```
[16:35:32] [epollEventLoopGroup-3-13/WARN]: [ViaVersion] ERROR IN Protocol1_13_1To1_13 IN REMAP OF SPAWN_PARTICLE (0x24)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$12 (Anonymous)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at eu.smashmc.language.bukkit.packet.TinyProtocol$1.write(TinyProtocol.java:106)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at eu.smashmc.core.bukkit.packet.TinyProtocol$1.write(TinyProtocol.java:96)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.lambda$dispatchPacket$0(NetworkManager.java:247)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$12 (Anonymous)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.api.type.Type.getBaseClass()" because "type" is null
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:151)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:187)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.rewriter.ItemRewriter.lambda$getSpawnParticleHandler$5(ItemRewriter.java:439)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at eu.smashmc.language.bukkit.packet.TinyProtocol$1.write(TinyProtocol.java:106)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at eu.smashmc.core.bukkit.packet.TinyProtocol$1.write(TinyProtocol.java:96)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.lambda$dispatchPacket$0(NetworkManager.java:247)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[16:35:32] [epollEventLoopGroup-3-13/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Bug Description

When sending the iconcrack_(id)_(data) particle from a 1.8 server all clients recieving the packet will get kicked.

### Steps to Reproduce

1. Setup 1.8.8 server with viaversion
2. Send a particle packet with iconcrack and e.g. a bow item data (261, 0)
3. Get kicked

### Expected Behavior

Not to kick

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--CurrySpigot--unknown%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--CurrySpigot--unknown%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.1): 6 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.1)-6%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by calcastor** [comment]
Saw a similar issue, here is the dump from our end: https://dump.viaversion.com/c6ab29de56f934aa41033b75bb68591592a8ac242e2b99dab572ce38513ddcb5

**Comment by Barvalg** [comment]
![Platform: git--SportPaper--e4cb0d1--P.d7ba9e3--SP.8af79ba--CB.e1ebe52%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--SportPaper--e4cb0d1--P.d7ba9e3--SP.8af79ba--CB.e1ebe52%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.9.2--SNAPSHOT)-Outdated!-red?style=flat-square) </br>![ViaRewind (3.0.5): Error fetching commit data](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Error%20fetching%20commit%20data-lightgray?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
