### ISSUE TITLE
does not allow access to the server

### ISSUE THREAD

**Issue by bulat5280** [ViaVersion/ViaVersion#3573]
### `/viaversion dump` Output

https://dump.viaversion.com/e1de8e10475bbd96f7535188a44633ec6a4a9d0be89ba25358ffd1a17667e3d9

### Console Error

```
[18:32:47 WARN]: [ViaVersion] ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)
[18:32:47 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:32:47 WARN]: Source 0: com.viaversion.viaversion.protocols.protocol1_13to1_12_2.packets.WorldPackets$$Lambda$466/0x00007f86984bf448
[18:32:47 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[18:32:47 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[18:32:47 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[18:32:47 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[18:32:47 WARN]:        at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[18:32:47 WARN]:        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[18:32:47 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[18:32:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[18:32:47 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[18:32:47 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[18:32:47 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Bug Description

it kicks right after logging in to the server, an error on the client: IOException

### Steps to Reproduce

1. log in to the server version 1.12.2 with version 1.16.5

### Expected Behavior

calm login to the server

### Additional Server Info

I use velocity with limboapi, limbofilter, and skinsrestorer plugins installed on it. Plugins are installed on the server: viaversion, viabackwards, viarewind, skinsrestorer, bungeeguard, protocollib, figuresfix, illegalstack, log4jfix.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by bulat5280** [comment]
https://dump.viaversion.com/e1de8e10475bbd96f7535188a44633ec6a4a9d0be89ba25358ffd1a17667e3d9

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 9 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-9%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.9.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by bulat5280** [comment]
https://dump.viaversion.com/a6cee7a92102efbf3837518a1c97813ba71843f1666248268a2748d0c6dadd21

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(3.0.5): Even with master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by Kichura** [comment]
Very likely caused by a third-party plugin, Please do a binary search to see what's causing viaversion to complain about the bad chunk data packets.

**Comment by Jo0001** [comment]
Works fine for me
![grafik](https://github.com/ViaVersion/ViaVersion/assets/47455182/2fb85ecb-7fc5-46bd-9897-e45c92119194)

As already said, please do a binary search to find out which plugin might cause issues/sends the invalid data
