### ISSUE TITLE
Kicking player

### ISSUE THREAD

**Issue by Scorbunny10** [ViaVersion/ViaVersion#3599]
### `/viaversion dump` Output

We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/ab27c25147eac4b052106ba4f7a8092a3eaab79d4c10a545d3d6b357160f15af

### Console Error

Scorbunny_ lost connection: Disconnected
[13:46:42 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[13:46:42 WARN]: Packet Type: MULTI_BLOCK_CHANGE, Type: VarLongBlockChangeRecordType Array, Index: 2, Data: [{LongType: -4398046511098}], Source 0: com.viaversion.viaversion.rewriter.BlockRewriter$5 (Anonymous), Packet ID: 69
[13:46:42 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[13:46:42 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[13:46:42 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[13:46:42 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[13:46:42 WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:237)
[13:46:42 WARN]: 	at net.minecraft.network.NetworkManager.lambda$7(NetworkManager.java:226)
[13:46:42 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[13:46:42 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[13:46:42 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[13:46:42 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[13:46:42 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[13:46:42 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:46:42 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:46:42 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[13:46:42 WARN]: Packet Type: MULTI_BLOCK_CHANGE, Type: VarLongBlockChangeRecordType Array, Index: 2, Data: [{LongType: -4398046511098}], Source 0: com.viaversion.viaversion.rewriter.BlockRewriter$5 (Anonymous), Packet ID: 69
[13:46:42 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[13:46:42 WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[13:46:42 WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[13:46:42 WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[13:46:42 WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[13:46:42 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159)
[13:46:42 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[13:46:42 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104)
[13:46:42 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[13:46:42 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[13:46:42 WARN]: 	at com.viaversion.viaversion.api.type.types.block.VarLongBlockChangeRecordType.read(VarLongBlockChangeRecordType.java:40)
[13:46:42 WARN]: 	at com.viaversion.viaversion.api.type.types.block.VarLongBlockChangeRecordType.read(VarLongBlockChangeRecordType.java:30)
[13:46:42 WARN]: 	at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:48)
[13:46:42 WARN]: 	at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:29)
[13:46:42 WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:142)
[13:46:42 WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:187)
[13:46:42 WARN]: 	at com.viaversion.viaversion.rewriter.BlockRewriter$5.lambda$register$0(BlockRewriter.java:144)
[13:46:42 WARN]: 	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[13:46:42 WARN]: 	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[13:46:42 WARN]: 	at com.viaversion.viaversion.protocols.protocol1_20_2to1_20.Protocol1_20_2To1_20.transform(Protocol1_20_2To1_20.java:207)
[13:46:42 WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[13:46:42 WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[13:46:42 WARN]: 	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[13:46:42 WARN]: 	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[13:46:42 WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[13:46:42 WARN]: 	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[13:46:42 WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[13:46:42 WARN]: 	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[13:46:42 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[13:46:42 WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[13:46:42 WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[13:46:42 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[13:46:42 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[13:46:42 WARN]: 	at net.minecraft.network.NetworkManager.a(NetworkManager.java:237)
[13:46:42 WARN]: 	at net.minecraft.network.NetworkManager.lambda$7(NetworkManager.java:226)
[13:46:42 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[13:46:42 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[13:46:42 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[13:46:42 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[13:46:42 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[13:46:42 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:46:42 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:46:42 INFO]: 
[13:46:42 WARN]: handleDisconnection() called twice

### Bug Description

![javaw_YmqBOwo6tC](https://github.com/ViaVersion/ViaVersion/assets/100584937/3e0e9d5a-c7a9-4c83-8efd-bd5f73c00184)

^^^ Screenshot

### Steps to Reproduce

I'am walk on the spawn and this kick me from the server.
I use 1.20.4 server is on 1.20

### Expected Behavior

This error kick players

### Additional Server Info

No proxy

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3871--Spigot--d2eba2c--3f9263b%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-3871--Spigot--d2eba2c--3f9263b%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 18 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-18%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 11 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-11%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by kennytv** [comment]
Your plugin jar is corrupt

**Comment by Scorbunny10** [comment]
@kennytv  why? Yesterday this works.
