### ISSUE TITLE
Error issue when reading BooleanType data type from MAP_DATA package

### ISSUE THREAD

**Issue by Greentea1337** [ViaVersion/ViaVersion#3607]
### `/viaversion dump` Output

https://dump.viaversion.com/d540e54af19b430cd442abbb1cb326fdafd0f9d986616da84a9620642a8f7990

### Console Error

[14:59:30] [Netty Epoll Server IO #2/WARN]: Packet Type: MAP_DATA, Type: BooleanType, Index: 0, Data: [{VarInt: 1}, {ByteType: 0}, {BooleanType: true}, {BooleanType: false}, {VarInt: 1}, {VarInt: 1}, {ByteType: 22}, {ByteType: 68}, {ByteType: 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$7 (Anonymous), Packet ID: 37
[14:59:30] [Netty Epoll Server IO #2/WARN]: Caused by: java.io.IOException: Unable to read type BooleanType, found OptionalComponentType
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:156)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:187)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaBackwards-4.9.1.jar//com.viaversion.viabackwards.api.rewriters.MapColorRewriter.lambda$getRewriteHandler$0(MapColorRewriter.java:40)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaBackwards-4.9.1.jar//com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$7.lambda$register$1(BlockItemPackets1_17.java:401)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at TAB v4.0.9.jar//me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:59:30] [Netty Epoll Server IO #2/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[14:59:30] [Server thread/INFO]: Jorkis1 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: MAP_DATA, Type: BooleanType, Index: 0, Data: [{VarInt: 1}, {ByteType: 0}, {BooleanType: true}, {BooleanType: false}, {VarInt: 1}, {VarInt: 1}, {ByteType: 22}, {ByteType: 68}, {ByteType: 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$7 (Anonymous), Packet ID: 37
[14:59:30] [Server thread/INFO]: [voicechat] Disconnecting client Jorkis1
[14:59:30] [Server thread/INFO]: Jorkis1 вышел из игры

### Bug Description

Problem kicking a player from the server. His Minecraft version was 1.16.4, ViaVersion used version 4.9.2.

An attempt to send a MAP_DATA packet encountered an error while reading the BooleanType data type.

### Steps to Reproduce

1. Server with version 1.20.2 and viaversion plugin
2. Login to the server with client version 1.16.4
3. The player is kicked with an error

### Expected Behavior

The player cannot log into the server, even if he tries to connect several times

### Additional Server Info

The server runs on paper 1.20.2, the server has the viaversion plugin, as well as some others, no proxies are used

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kennytv** [comment]
> I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.
