### ISSUE TITLE
When quickly switching dimensions between the Nether and the Overworld, the console reports an error and causes the player to leave the game

### ISSUE THREAD

**Issue by CNDogc** [ViaVersion/ViaVersion#3609]
### `/viaversion dump` Output

https://dump.viaversion.com/2a3a411b626d048cb2a5f3a01e5f1c32c59882758baff69fd9e59b28016f429f

### Console Error

ViaVersion] ERROR IN Protocol1_20To1_20_2 IN REMAP OF CHUNK_DATA (0x25) 
[20:26:47 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository 
[20:26:47 WARN]: Packet Type: CHUNK_DATA, Type: ChunkType1_20_2, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.rewriter.BlockItemPacketRewriter1_20_2$$Lambda$7123/0x0000000801b82890, Packet ID: 36 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) 
[20:26:47 WARN]:  at grimac-2.3.46.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) 
[20:26:47 WARN]:  at Vulcan-2.8.1.jar//io.github.repooper.packetevents.Vulcan_KQ.write(Vulcan_KQ.java:60) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) 
[20:26:47 WARN]:  at MythicMobs-5.5.1.jar//io.lumine.mythic.core.volatilecode.v1_20_R2.packets.VolatileChannelHandler.write(VolatileChannelHandler.java:76) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) 
[20:26:47 WARN]:  at GSit-1.7.0.jar//dev.geco.gsit.mcv.v1_20_2.util.PackageUtil$1.write(PackageUtil.java:90) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) 
[20:26:47 WARN]:  at Model-Engine-R3.1.9[tinksp.cn].jar//com.ticxo.modelengine.nms.v1_20_R2.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:83) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) 
[20:26:47 WARN]:  at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) 
[20:26:47 WARN]:  at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) 
[20:26:47 WARN]:  at net.minecraft.network.NetworkManager.c(NetworkManager.java:448) 
[20:26:47 WARN]:  at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433) 
[20:26:47 WARN]:  at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) 
[20:26:47 WARN]:  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) 
[20:26:47 WARN]:  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) 
[20:26:47 WARN]:  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) 
[20:26:47 WARN]:  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) 
[20:26:47 WARN]:  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) 
[20:26:47 WARN]:  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
[20:26:47 WARN]:  at java.base/java.lang.Thread.run(Thread.java:833) 
[20:26:47 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository 
[20:26:47 WARN]: Packet Type: CHUNK_DATA, Type: ChunkType1_20_2, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.rewriter.BlockItemPacketRewriter1_20_2$$Lambda$7123/0x0000000801b82890, Packet ID: 36 
[20:26:47 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(16606) + length(2) exceeds writerIndex(16606): PooledUnsafeDirectByteBuf(ridx: 16606, widx: 16606, cap: 16606) 
[20:26:47 WARN]:  at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) 
[20:26:47 WARN]:  at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.type.types.chunk.ChunkSectionType1_18.read(ChunkSectionType1_18.java:45) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.type.types.chunk.ChunkType1_20_2.read(ChunkType1_20_2.java:58) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.type.types.chunk.ChunkType1_20_2.read(ChunkType1_20_2.java:36) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:142) 
[20:26:47 WARN]:  at ViaBackwards-4.9.1.jar//com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.rewriter.BlockItemPacketRewriter1_20_2.lambda$registerPackets$5(BlockItemPacketRewriter1_20_2.java:113) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) 
[20:26:47 WARN]:  at ViaBackwards-4.9.1.jar//com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.Protocol1_20To1_20_2.transform(Protocol1_20To1_20_2.java:164) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57) 
[20:26:47 WARN]:  at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35) 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) 
[20:26:47 WARN]:  at grimac-2.3.46.jar//ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) 
[20:26:47 WARN]:  at Vulcan-2.8.1.jar//io.github.repooper.packetevents.Vulcan_KQ.write(Vulcan_KQ.java:60) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) 
[20:26:47 WARN]:  at MythicMobs-5.5.1.jar//io.lumine.mythic.core.volatilecode.v1_20_R2.packets.VolatileChannelHandler.write(VolatileChannelHandler.java:76) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) 
[20:26:47 WARN]:  at GSit-1.7.0.jar//dev.geco.gsit.mcv.v1_20_2.util.PackageUtil$1.write(PackageUtil.java:90) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) 
[20:26:47 WARN]:  at Model-Engine-R3.1.9[tinksp.cn].jar//com.ticxo.modelengine.nms.v1_20_R2.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:83) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) 
[20:26:47 WARN]:  at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) 
[20:26:47 WARN]:  at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) 
[20:26:47 WARN]:  at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) 
[20:26:47 WARN]:  at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) 
[20:26:47 WARN]:  at net.minecraft.network.NetworkManager.c(NetworkManager.java:448) 
[20:26:47 WARN]:  at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433) 
[20:26:47 WARN]:  at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) 
[20:26:47 WARN]:  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) 
[20:26:47 WARN]:  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) 
[20:26:47 WARN]:  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) 
[20:26:47 WARN]:  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) 
[20:26:47 WARN]:  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) 
[20:26:47 WARN]:  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
[20:26:47 WARN]:  at java.base/java.lang.Thread.run(Thread.java:833) 
[20:26:47 INFO]: CNDogc lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository 
Packet Type: CHUNK_DATA, Type: ChunkType1_20_2, Index: 1, Data: [], Source 0: com.viaversion.viabackwards.protocol.protocol1_20to1_20_2.rewriter.BlockItemPacketRewriter1_20_2$$Lambda$7123/0x0000000801b82890, Packet ID: 36 
[20:26:47 INFO]: CNDogc left the game 

### Bug Description

When quickly switching dimensions between the Nether and the Overworld, the console reports an error and causes the player to leave the game

### Steps to Reproduce

1After entering the game, walk into the Nether Gate, enter the Nether, and quickly return to the Overworld from the Nether Gate.

### Expected Behavior

Fix this

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Purpur--2095%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Purpur--2095%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 25 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-25%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 15 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-15%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
