### ISSUE TITLE
ViaVersion could not load Plugin

### ISSUE THREAD

**Issue by SkyKingPX** [ViaVersion/ViaVersion#3617]
### `/viaversion dump` Output

Commands does not even work

### Console Error

[12:37:49 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'ViaVersion-4.9.3-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `com.viaversion.viaversion.ViaVersionPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.20.4.jar:git-Paper-349]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.4.jar:git-Paper-349]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.4.jar:git-Paper-349]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.4.jar:git-Paper-349]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-349]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[paper-1.20.4.jar:git-Paper-349]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.4.jar:git-Paper-349]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-349]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-349]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')
        at com.viaversion.viaversion.util.Config.getBoolean(Config.java:168) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.loadFields(AbstractViaConfig.java:139) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.bukkit.platform.BukkitViaConfig.loadFields(BukkitViaConfig.java:44) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.reload(AbstractViaConfig.java:100) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.bukkit.platform.BukkitViaConfig.<init>(BukkitViaConfig.java:39) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.<init>(ViaVersionPlugin.java:81) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 10 more

### Bug Description

I am getting this error while the server is starting ^

### Steps to Reproduce

Download ViaVersion 4.9.3 Snapshot and run it with Paper 1.20.4

### Expected Behavior

Should work...

### Additional Server Info

Paper 1.20.4
Plugins: 
![Screenshot 2024-01-02 124245](https://github.com/ViaVersion/ViaVersion/assets/95442431/d4d8ec97-de58-43ce-97d7-416f4e7589cb)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
Either your jar is corrupted or your config is broken - Update both viaversion and viabackwards to latest CI builds.

**Comment by SkyKingPX** [comment]
> ![Error: Invalid or missing dump](https://camo.githubusercontent.com/7b5e5f80a2824a1bc1a4f504d61a8f91362791850f864896b1ac9c6c0f77a463/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)
And what does this mean???




> Either your jar is corrupted or your config is broken - Update both viaversion and viabackwards to latest CI builds.

I downloaded them from Jenkins

**Comment by Kichura** [comment]
> > ![Error: Invalid or missing dump](https://camo.githubusercontent.com/7b5e5f80a2824a1bc1a4f504d61a8f91362791850f864896b1ac9c6c0f77a463/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4572726f722d496e76616c69642f6d697373696e6725323064756d702d7265643f7374796c653d666c61742d737175617265)
> > And what does this mean???
> 
> > Either your jar is corrupted or your config is broken - Update both viaversion and viabackwards to latest CI builds.
> 
> I downloaded them from Jenkins

Regardless of that sentence, I highly recommend getting new copies just to be sure it isn't some random corruption that just occurred and also get rid of the old jars.

**Comment by x1p** [comment]
One day it loads fine, another day this error appears.

**Comment by Kichura** [comment]
Cannot reproduce here.

**Comment by SkyKingPX** [comment]
I regenerated the configs and now it works. I don’t know why, but it works

**Comment by x1p** [comment]
Unfortunatetly not for me.
Plugin loads and seem to work but I find the latest few builds have too many issues latetly. Each version has issues one way or another. Stable builds work the best for now. Newer is not always better.

```
[13:49:06] [Server thread/INFO]: [ViaVersion] Loading server plugin ViaVersion v4.9.3-SNAPSHOT
[13:49:06] [Server thread/INFO]: [ViaVersion] ViaVersion 4.9.3-SNAPSHOT is now loaded. Registering protocol transformers and injecting...
[13:49:06] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[13:49:07] [Server thread/INFO]: [ViaBackwards] Loading translations...
[13:49:07] [Server thread/ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-4.9.3-769.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/tag/io/NBTIO
	at com.viaversion.viabackwards.api.data.VBMappingDataLoader.<clinit>(VBMappingDataLoader.java:39) ~[ViaBackwards-4.9.2-368.jar:?]
	at com.viaversion.viabackwards.api.rewriters.TranslatableRewriter.loadTranslatables(TranslatableRewriter.java:37) ~[ViaBackwards-4.9.2-368.jar:?]
	at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:90) ~[ViaBackwards-4.9.2-368.jar:?]
	at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:35) ~[ViaBackwards-4.9.2-368.jar:?]
	at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:111) ~[ViaVersion-4.9.3-769.jar:?]
	at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:91) ~[ViaVersion-4.9.3-769.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:528) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.libs.opennbt.tag.io.NBTIO
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 15 more
[13:49:07] [Server thread/INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.102
[13:49:07] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
```

**Comment by Kichura** [comment]
That's not latest, also delete your config aswell just to be sure.

**Comment by x1p** [comment]
True. I didn't think 1 character wouldn't make a real change but the latest (as in buld 771) seems to load fine again.
