### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by josealissonbr** [ViaVersion/ViaVersion#3638]
### `/viaversion dump` Output

https://dump.viaversion.com/552326faa484be3f8299f919eb7d05c91073e9679fa5ed0ab8e7ed649edea629

### Console Error

```
[18:27:19 WARN]: [ViaVersion] ERROR IN Protocol1_13To1_13_1 IN REMAP OF TAB_COMPLETE (0x10)
[18:27:19 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:27:19 WARN]: Packet Type: TAB_COMPLETE, Type: BooleanType, Index: 0, Data: [{VarInt: 1321197387}, {VarInt: 9}, {VarInt: 4}, {VarInt: 1}, {StringType: creative}], Source 0: com.viaversion.viabackwards.protocol.protocol1_13to1_13_1.Protocol1_13To1_13_1$4 (Anonymous), Packet ID: 16
[18:27:19 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:27:19 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:27:19 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:27:19 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:27:19 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[18:27:19 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[18:27:19 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:27:19 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:27:19 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:27:19 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[18:27:19 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:27:19 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:27:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[18:27:19 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[18:27:19 WARN]: Packet Type: TAB_COMPLETE, Type: BooleanType, Index: 0, Data: [{VarInt: 1321197387}, {VarInt: 9}, {VarInt: 4}, {VarInt: 1}, {StringType: creative}], Source 0: com.viaversion.viabackwards.protocol.protocol1_13to1_13_1.Protocol1_13To1_13_1$4 (Anonymous), Packet ID: 16
[18:27:19 WARN]: Caused by: java.io.IOException: Unable to read type BooleanType, found OptionalComponentType
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:156)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:187)
[18:27:19 WARN]:        at ViaBackwards-4.9.1.jar//com.viaversion.viabackwards.protocol.protocol1_13to1_13_1.Protocol1_13To1_13_1$4.lambda$register$0(Protocol1_13To1_13_1.java:139)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[18:27:19 WARN]:        at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[18:27:19 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:27:19 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:27:19 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[18:27:19 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[18:27:19 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[18:27:19 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[18:27:19 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[18:27:19 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:27:19 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:27:19 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:27:19 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[18:27:19 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:27:19 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:27:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
[18:27:19 INFO]: Techprimedev lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: TAB_COMPLETE, Type: BooleanType, Index: 0, Data: [{VarInt: 1321197387}, {VarInt: 9}, {VarInt: 4}, {VarInt: 1}, {StringType: creative}], Source 0: com.viaversion.viabackwards.protocol.protocol1_13to1_13_1.Protocol1_13To1_13_1$4 (Anonymous), Packet ID: 16
```

### Bug Description

just happening

### Steps to Reproduce

Using gamemode 1 on 1.8.9

### Expected Behavior

N/A

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--381%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--381%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 30 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-30%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.0.5): 13 commits behind master](https://img.shields.io/badge/ViaRewind%20(3.0.5)-13%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 17 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
