### ISSUE TITLE
Внутреняя ошибка |  Internal error Player kicks

### ISSUE THREAD

**Issue by Jaypasha** [ViaVersion/ViaVersion#3641]
### `/viaversion dump` Output

https://dump.viaversion.com/87cd6287f8da33bf6f535186729ed426b84ab9349ca274bcac0756d78f0f280e

### Console Error

```
Put the paste.gg link or text here.
```
[12:43:29 INFO]: [connected player] SPERMA_DEDA22823 (/176.124.190.8:49631) has disconnected: В вашем подключении произошла внутренняя ошибка.
[12:43:29 ERROR]: [connected player] SPERMA_DEDA22823 (/176.124.190.8:49631): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@1458ce15
io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$1657/0x00007f0a5993e9e0, Packet ID: 2
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:243) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:338) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:159) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:78) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: GAME_PROFILE, Type: UUID, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.base.BaseProtocol1_7$$Lambda$1657/0x00007f0a5993e9e0, Packet ID: 2
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(8) exceeds writerIndex(3): PooledUnsafeDirectByteBuf(ridx: 1, widx: 3, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]
        at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:38) ~[?:?]
        at com.viaversion.viaversion.api.type.types.UUIDType.read(UUIDType.java:30) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:146) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:192) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_16.passthroughLoginUUID(BaseProtocol1_16.java:29) ~[?:?]
        at com.viaversion.viaversion.protocols.base.BaseProtocol1_7.lambda$registerPackets$0(BaseProtocol1_7.java:126) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:426) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:236) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:47) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:29) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[velocity.jar:3.3.0-SNAPSHOT (git-6fd03d6f-b311)]

### Bug Description

It just kicks at any time, just throws it out due to “Internal error”

### Steps to Reproduce

ViaVersion on the proxy host! 1. go to the server 2. Wait 3. you are being kicked!

### Expected Behavior

Kick

### Additional Server Info

Im use Velocity 3.3.0, server state on 1.18.2(Paper), server minimal join version 1.18.2

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--6fd03d6f--b311%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--6fd03d6f--b311%29-3498db?style=flat-square) </br>![Proxy is 9 builds behind](https://img.shields.io/badge/Your%20proxy%20is%209%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.8.1)-Outdated!-red?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(4.8.1)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>proxy_limbo</details>
