### ISSUE TITLE
Can't connect older versions to 1.20 aternos server

### ISSUE THREAD

**Issue by ZeTaX2002** [ViaVersion/ViaVersion#3655]
### `/viaversion dump` Output

https://dump.viaversion.com/0822cbf0ef3fef88e5e3d7bc41fc70f7e1b4106099e6fa00646d478dca730aec

### Console Error

[Via-Mappingloader-11/ERROR]: [ViaVersion] Error during mapping loading of Protocol1_9_4To1_10
--
31 | java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/NBTIO
32 | at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
33 | at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
34 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
35 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
36 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
37 | at java.lang.Thread.run(Thread.java:840) ~[?:?]
38 | Caused by: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/NBTIO
39 | at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBT(VBMappingDataLoader.java:45) ~[?:?]
40 | at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBTFromDir(VBMappingDataLoader.java:59) ~[?:?]
41 | at com.viaversion.viabackwards.api.data.BackwardsMappings.readNBTFile(BackwardsMappings.java:171) ~[?:?]
42 | at com.viaversion.viaversion.api.data.MappingDataBase.load(MappingDataBase.java:69) ~[?:?]
43 | at com.viaversion.viaversion.api.protocol.AbstractProtocol.loadMappingData(AbstractProtocol.java:176) ~[?:?]
44 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
45 | ... 3 more
46 | Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.libs.opennbt.NBTIO
47 | at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
48 | at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
49 | at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
50 | at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBT(VBMappingDataLoader.java:45) ~[?:?]
51 | at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBTFromDir(VBMappingDataLoader.java:59) ~[?:?]
52 | at com.viaversion.viabackwards.api.data.BackwardsMappings.readNBTFile(BackwardsMappings.java:171) ~[?:?]
53 | at com.viaversion.viaversion.api.data.MappingDataBase.load(MappingDataBase.java:69) ~[?:?]
54 | at com.viaversion.viaversion.api.protocol.AbstractProtocol.loadMappingData(AbstractProtocol.java:176) ~[?:?]
55 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
56 | ... 3 more
57 | [16:52:49] [Server thread/ERROR]: 'com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder.filterFamily(com.viaversion.viaversion.api.minecraft.entities.EntityType)' initializing ViaVersion v4.9.3-SNAPSHOT (Is it up to date?)
58 | java.lang.NoSuchMethodError: 'com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder.filterFamily(com.viaversion.viaversion.api.minecraft.entities.EntityType)'
59 | at com.viaversion.viabackwards.protocol.protocol1_10to1_11.packets.EntityPackets1_11.registerRewrites(EntityPackets1_11.java:233) ~[?:?]
60 | at com.viaversion.viaversion.api.rewriter.RewriterBase.register(RewriterBase.java:37) ~[?:?]
61 | at com.viaversion.viabackwards.protocol.protocol1_10to1_11.Protocol1_10To1_11.registerPackets(Protocol1_10To1_11.java:48) ~[?:?]
62 | at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:98) ~[?:?]
63 | at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:198) ~[?:?]
64 | at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:192) ~[?:?]
65 | at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:98) ~[?:?]
66 | at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:35) ~[?:?]
67 | at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:111) ~[?:?]
68 | at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:91) ~[?:?]
69 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:440) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
70 | at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
71 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
72 | at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
73 | at java.lang.Thread.run(Thread.java:840) ~[?:?]

</body>
</html>
[Via-Mappingloader-11/ERROR]: [ViaVersion] Error during mapping loading of Protocol1_9_4To1_10
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/NBTIO
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:[31](https://aternos.org/log/#L31)5) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:[32](https://aternos.org/log/#L32)0) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/NBTIO
	at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBT(VBMappingDataLoader.java:45) ~[?:?]
	at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBTFromDir(VBMappingDataLoader.java:59) ~[?:?]
	at com.viaversion.viabackwards.api.data.BackwardsMappings.readNBTFile(BackwardsMappings.java:171) ~[?:?]
	at com.viaversion.viaversion.api.data.MappingDataBase.load(MappingDataBase.java:69) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.loadMappingData(AbstractProtocol.java:176) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.libs.opennbt.NBTIO
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBT(VBMappingDataLoader.java:45) ~[?:?]
	at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBTFromDir(VBMappingDataLoader.java:59) ~[?:?]
	at com.viaversion.viabackwards.api.data.BackwardsMappings.readNBTFile(BackwardsMappings.java:171) ~[?:?]
	at com.viaversion.viaversion.api.data.MappingDataBase.load(MappingDataBase.java:69) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.loadMappingData(AbstractProtocol.java:176) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 3 more
[16:52:49] [Server thread/ERROR]: 'com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder.filterFamily(com.viaversion.viaversion.api.minecraft.entities.EntityType)' initializing ViaVersion v4.9.3-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder.filterFamily(com.viaversion.viaversion.api.minecraft.entities.EntityType)'
	at com.viaversion.viabackwards.protocol.protocol1_10to1_11.packets.EntityPackets1_11.registerRewrites(EntityPackets1_11.java:2[33](https://aternos.org/log/#L33)) ~[?:?]
	at com.viaversion.viaversion.api.rewriter.RewriterBase.register(RewriterBase.java:37) ~[?:?]
	at com.viaversion.viabackwards.protocol.protocol1_10to1_11.Protocol1_10To1_11.registerPackets(Protocol1_10To1_11.java:48) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:98) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:198) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:192) ~[?:?]
	at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:98) ~[?:?]
	at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:[35](https://aternos.org/log/#L35)) ~[?:?]
	at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:111) ~[?:?]
	at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:91) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:440) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:[38](https://aternos.org/log/#L38)71-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:219) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3871-Spigot-d2eba2c-3f9263b]
	at java.lang.Thread.run(Thread.java:8[40](https://aternos.org/log/#L40)) ~[?:?]

### Bug Description

My friends are trying to join with 1.12.2 to my 1.20 server version but they can't join. I've installed all the plugins like ViaBackwards, ViaVersions, ViaRewind, etc. Please, i need help

### Steps to Reproduce

. Login in 1.12.2 client
. Try to enter the server
.  Text: Outdated Client! Please use 1.20.1

### Expected Behavior

Players should join the server in every Minecraft version possible

### Additional Server Info

Using Spigot/Bukkit with these plugins: 
BetterTeams.jar
bStats

Clearlag.jar

CMILib1.4.4.6.jar

ConditionalEvents.jar

DecentHolograms-2.8.6.jar

DeluxeHub-3.5.5.jar

DiscordSRV-Build-1.27.0.jar

EconomyShopGUI-6.3.1.jar

EssentialsX-2.20.1.jar
EssentialsXChat-2.20.1.jar

floodgate-spigot.jar

Geyser-Spigot.jar

GeyserSkinManager-Spigot.jar

GSit-1.5.3.jar

HeadsLite-v5.0.jar

images-2.3.2.jar

Jobs5.2.2.2.jar

LoginSecurity-Spigot-3.3.0.jar

LuckPerms-Bukkit-5.4.102.jar

MarriageMaster.jar

multiverse-core-4.3.12.jar

multiverse-inventories-4.2.6.jar

multiverse-netherportals-4.2.3.jar

multiverse-portals-4.2.3.jar
multiverse-portalsGUI.jar

multiverse-signportals-4.2.2.jar

PixelPrinter.jar

PlaceholderAPI-2.11.5.jar
PluginMetrics

ProtectionStones-2.10.4.jar

ProtocolLib.jar
ServersNPC

SkinsRestorer.jar

SternalBoard-2.2.8-all.jar

TabList-bukkit-v5.7.5.jar

Vault.jar

ViaBackwards-4.9.1.jar

ViaCheckConnection-1.2.21.jar
ViaRewind-3.0.6-SNAPSHOT.jar

ViaVersion-4.9.3-SNAPSHOT.jar

ViaVersionStatus-3.13.jar

worldedit-bukkit-7.3.0-beta-03-dist.jar

worldguard-bukkit-7.0.9-dist.jar
znpcs-4.6.jar

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 3871--Spigot--d2eba2c--3f9263b%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-3871--Spigot--d2eba2c--3f9263b%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.1): 20 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
