### ISSUE TITLE
User can't join [1.16.5 client -> 1.20.4 server],

### ISSUE THREAD

**Issue by Cellazelf12** [ViaVersion/ViaVersion#3656]
### `/viaversion dump` Output

https://dump.viaversion.com/04d3d550cabe3457bfcfb17d02ddb34ca5d910035728acde07be3fdca8e2e957

### Console Error

[02:39:22] [Netty Epoll Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_16_4To1_17 IN REMAP OF MAP_DATA (0x27)
[02:39:22] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[02:39:22] [Netty Epoll Server IO #1/WARN]: Packet Type: MAP_DATA, Type: BooleanType, Index: 0, Data: [{VarInt: 0}, {ByteType: 1}, {BooleanType: true}, {BooleanType: false}, {VarInt: 1}, {VarInt: 0}, {ByteType: -2}, {ByteType: 10}, {ByteType: 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$7 (Anonymous), Packet ID: 37
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[02:39:22] [Netty Epoll Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[02:39:22] [Netty Epoll Server IO #1/WARN]: Packet Type: MAP_DATA, Type: BooleanType, Index: 0, Data: [{VarInt: 0}, {ByteType: 1}, {BooleanType: true}, {BooleanType: false}, {VarInt: 1}, {VarInt: 0}, {ByteType: -2}, {ByteType: 10}, {ByteType: 0}], Source 0: com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$7 (Anonymous), Packet ID: 37
[02:39:22] [Netty Epoll Server IO #1/WARN]: Caused by: java.io.IOException: Unable to read type BooleanType, found OptionalComponentType
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:156)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:187)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaBackwards-4.9.1.jar//com.viaversion.viabackwards.api.rewriters.MapColorRewriter.lambda$getRewriteHandler$0(MapColorRewriter.java:40)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaBackwards-4.9.1.jar//com.viaversion.viabackwards.protocol.protocol1_16_4to1_17.packets.BlockItemPackets1_17$7.lambda$register$1(BlockItemPackets1_17.java:401)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:115)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ViaVersion-4.9.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[02:39:22] [Netty Epoll Server IO #1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)

### Bug Description

Users entering with version 1.16.5 cause this error and are also automatically disconnected

### Steps to Reproduce

1. Login with a 1.16.5 client

### Expected Behavior

User can should not disconnect

### Additional Server Info

I also use ViaBackwards

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--368%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--368%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 39 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-39%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 20 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-20%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Cellazelf12** [comment]
[02:47:02 ERROR]: [ViaVersion] Error during mapping loading of Protocol1_9_4To1_10
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/NBTIO
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/viaversion/viaversion/libs/opennbt/NBTIO
        at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBT(VBMappingDataLoader.java:45) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBTFromDir(VBMappingDataLoader.java:59) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viabackwards.api.data.BackwardsMappings.readNBTFile(BackwardsMappings.java:171) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viaversion.api.data.MappingDataBase.load(MappingDataBase.java:71) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.loadMappingData(AbstractProtocol.java:233) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        ... 3 more
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.libs.opennbt.NBTIO
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBT(VBMappingDataLoader.java:45) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viabackwards.api.data.VBMappingDataLoader.loadNBTFromDir(VBMappingDataLoader.java:59) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viabackwards.api.data.BackwardsMappings.readNBTFile(BackwardsMappings.java:171) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viaversion.api.data.MappingDataBase.load(MappingDataBase.java:71) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.loadMappingData(AbstractProtocol.java:233) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        ... 3 more
[02:47:02 ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-4.10.0-24w03a-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoSuchMethodError: 'com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder com.viaversion.viaversion.rewriter.meta.MetaFilter$Builder.filterFamily(com.viaversion.viaversion.api.minecraft.entities.EntityType)'
        at com.viaversion.viabackwards.protocol.protocol1_10to1_11.packets.EntityPackets1_11.registerRewrites(EntityPackets1_11.java:233) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viaversion.api.rewriter.RewriterBase.register(RewriterBase.java:37) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at com.viaversion.viabackwards.protocol.protocol1_10to1_11.Protocol1_10To1_11.registerPackets(Protocol1_10To1_11.java:48) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:98) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:199) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:193) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:98) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:35) ~[ViaBackwards-4.9.1.jar:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:111) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:91) ~[ViaVersion-4.10.0-24w03a-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-368]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-368]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-368]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-368]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[paper-1.20.4.jar:git-Paper-368]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.4.jar:git-Paper-368]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-368]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-368]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by Cellazelf12** [comment]
Solved
