### ISSUE TITLE
Book bug

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaVersion#3676]
### `/viaversion dump` Output

https://dump.viaversion.com/9c3b9a6abb0a80a59d55a6cd2873001017ff1afd5233ec823f369e8f7c8a7a73

### Console Error

```
[22:43:44 ERROR]: [ViaVersion] Error during book conversion
com.viaversion.viaversion.libs.gson.JsonSyntaxException: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $
        at com.viaversion.viaversion.libs.gson.Gson.assertFullConsumption(Gson.java:1148) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:1138) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:1047) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:982) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.mcstructs.text.serializer.TextComponentSerializer.deserialize(TextComponentSerializer.java:244) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.util.ComponentUtil.convertJson(ComponentUtil.java:84) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocols.protocol1_20_3to1_20_2.rewriter.BlockItemPacketRewriter1_20_3.updatePages(BlockItemPacketRewriter1_20_3.java:165) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocols.protocol1_20_3to1_20_2.rewriter.BlockItemPacketRewriter1_20_3.handleItemToClient(BlockItemPacketRewriter1_20_3.java:146) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.rewriter.ItemRewriter.lambda$itemToClientHandler$7(ItemRewriter.java:450) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 9 path $
        at com.viaversion.viaversion.libs.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.stream.JsonReader.peek(JsonReader.java:433) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.Gson.assertFullConsumption(Gson.java:1144) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        ... 45 more
[22:43:45 ERROR]: [ViaVersion] Error during book conversion
com.viaversion.viaversion.libs.gson.JsonSyntaxException: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.viaversion.viaversion.libs.gson.Gson.assertFullConsumption(Gson.java:1148) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:1138) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:1047) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.Gson.fromJson(Gson.java:982) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.mcstructs.text.serializer.TextComponentSerializer.deserialize(TextComponentSerializer.java:244) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.util.ComponentUtil.convertJson(ComponentUtil.java:84) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocols.protocol1_20_3to1_20_2.rewriter.BlockItemPacketRewriter1_20_3.updatePages(BlockItemPacketRewriter1_20_3.java:165) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocols.protocol1_20_3to1_20_2.rewriter.BlockItemPacketRewriter1_20_3.handleItemToClient(BlockItemPacketRewriter1_20_3.java:146) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.rewriter.ItemRewriter.lambda$itemToClientHandler$7(ItemRewriter.java:450) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:57) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.viaversion.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.viaversion.viaversion.libs.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.stream.JsonReader.peek(JsonReader.java:433) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.libs.gson.Gson.assertFullConsumption(Gson.java:1144) ~[ViaVersion-4.9.3-SNAPSHOT.jar:?]
        ... 45 more
```

### Bug Description

![2024-01-31_22 44 54](https://github.com/ViaVersion/ViaVersion/assets/89838384/9456c717-d023-46c9-9cc4-1426186a8142)
↓
![2024-01-31_22 45 02](https://github.com/ViaVersion/ViaVersion/assets/89838384/6da4084c-58d8-4cce-a626-3f3ce91e5e5d)
↓
![2024-01-31_22 45 09](https://github.com/ViaVersion/ViaVersion/assets/89838384/2cff5655-f193-43cb-b2c3-04c23325afa6)

### Steps to Reproduce

Write a book on a 1.20.2 or lower server using the 1.20.4 client.

### Expected Behavior

There should be no errors using the book.

### Additional Server Info

https://github.com/ViaVersion/ViaBackwards/issues/678

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--318%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Paper--318%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.9.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.9.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.9.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.9.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by MixSt** [comment]
Same console spam. Paper 1.20.1 196. ViaVersion-4.9.3-SNAPSHOT https://hastebin.com/share/pezekexobi.php

**Comment by PabuUwU** [comment]
Yup, it's true. I have the same error!

**Comment by kennytv** [comment]
https://github.com/ViaVersion/ViaVersion/commit/87d444a0170975d5e3b9fb49dc06aa20962f2f44
