### ISSUE TITLE
Map data issue 1.16 -> 1.12

### ISSUE THREAD

**Issue by Aseeef** [ViaVersion/ViaVersion#3711]
### `/viaversion dump` Output

https://dump.viaversion.com/4e0ba3322e2cdab29d937e1ea130d62649ff65a0210882f85bbb66e91688a2e2

### Console Error

[23:13:03] [Netty Epoll Server IO #4/WARN]: [ViaVersion] ERROR IN Protocol1_12_2To1_13 IN REMAP OF MAP_DATA (0x26)
[23:13:03] [Netty Epoll Server IO #4/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[23:13:03] [Netty Epoll Server IO #4/WARN]: Packet Type: MAP_DATA, Type: OptionalComponentType, Index: 5, Data: [{VarInt: 319}, {ByteType: 0}, {BooleanType: true}, {VarInt: 1}], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$8 (Anonymous), Packet ID: 36
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.github.repooper.packetevents.Vulcan_ie.write(Vulcan_ie.java:60)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.server.v1_16_R3.NetworkManager.lambda$writePacket$11(NetworkManager.java:485)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:13:03] [Netty Epoll Server IO #4/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:13:03] [Netty Epoll Server IO #4/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[23:13:03] [Netty Epoll Server IO #4/WARN]: Packet Type: MAP_DATA, Type: OptionalComponentType, Index: 5, Data: [{VarInt: 319}, {ByteType: 0}, {BooleanType: true}, {VarInt: 1}], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$8 (Anonymous), Packet ID: 36

### Bug Description

Being with in render distance of a map placed on an item frame causes 1.12 players to crash on a 1.16 server.

### Steps to Reproduce

1. Launch your 1.16 server.
2. Log in on 1.12
3. Generate a map of some part of the world by right clicking the map
4. Place the map inside an item frame

### Expected Behavior

No error/kick

### Additional Server Info

I'm using Tuinity 1.16

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Tuinity--e7660ec%20%28MC%3A%201.16.5%29](https://img.shields.io/badge/Platform-git--Tuinity--e7660ec%20%28MC%3A%201.16.5%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
