### ISSUE TITLE
Map data issue 1.16 -> 1.12

### ISSUE THREAD

**Issue by Aseeef** [ViaVersion/ViaVersion#3714]
### `/viaversion dump` Output

https://dump.viaversion.com/d426565761e95db77f9f8312670a55a0cc684f80db8dd98f1ca24e8a697dd1c4

### Console Error

[14:28:37] [Netty Epoll Server IO #4/WARN]: [ViaVersion] ERROR IN Protocol1_12_2To1_13 IN REMAP OF MAP_DATA (0x26)
[14:28:37] [Netty Epoll Server IO #4/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[14:28:37] [Netty Epoll Server IO #4/WARN]: Packet Type: MAP_DATA, Type: OptionalComponentType, Index: 10, Data: [{VarInt: 2066}, {ByteType: 0}, {BooleanType: true}, {VarInt: 2}], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$8 (Anonymous), Packet ID: 36
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at packetevents-spigot-2.1.0.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.network.NetworkManager.doSendPacket(NetworkManager.java:469)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:438)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:28:37] [Netty Epoll Server IO #4/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:28:37] [Netty Epoll Server IO #4/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[14:28:37] [Netty Epoll Server IO #4/WARN]: Packet Type: MAP_DATA, Type: OptionalComponentType, Index: 10, Data: [{VarInt: 2066}, {ByteType: 0}, {BooleanType: true}, {VarInt: 2}], Source 0: com.viaversion.viabackwards.protocol.protocol1_12_2to1_13.packets.BlockItemPackets1_13$8 (Anonymous), Packet ID: 36

### Bug Description

Being with in render distance of a map placed on an item frame causes 1.12 players to crash on a 1.16 server.

### Steps to Reproduce

1. Launch your 1.16 server.
2. Log in on 1.12
3. Generate a map of some part of the world by right clicking the map
4. Place the map inside an item frame

### Expected Behavior

No error/kick

### Additional Server Info

I'm using Paper 1.19.4

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--550%20%28MC%3A%201.19.4%29](https://img.shields.io/badge/Platform-git--Paper--550%20%28MC%3A%201.19.4%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 51 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-51%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.9.1): 32 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.9.1)-32%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
