### ISSUE TITLE
1.20 Clients can't connect to 1.8 servers

### ISSUE THREAD

**Issue by DungeonHD** [ViaVersion/ViaVersion#3733]
### `/viaversion dump` Output

https://dump.viaversion.com/cb5f35a3f683f92b46a93c086878217a3660e551acc47d4883d3d1c2334c415c

### Console Error

```
[03.03 14:09:10.284] INFO: [Lobby-1] [14:08:47 WARN]: [ViaVersion] ERROR IN Protocol1_20_3To1_20_2 IN REMAP OF BLOCK_ACTION (0x08)
[03.03 14:09:10.284] INFO: [Lobby-1] [14:08:47 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[03.03 14:09:10.284] INFO: [Lobby-1] Packet Type: BLOCK_ACTION, Type: Unsigned Byte, Index: 1, Data: [{PositionType1_14: Position{x=-16, y=68, z=0}}], Source 0: com.viaversion.viaversion.rewriter.BlockRewriter$1 (Anonymous), Packet ID: 8
[03.03 14:09:10.284] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[03.03 14:09:10.284] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[03.03 14:09:10.284] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[03.03 14:09:10.284] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:134)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[03.03 14:09:11.271] INFO: [Lobby-1] [14:08:47 WARN]:   at java.base/java.lang.Thread.run(Thread.java:840)
```

### Bug Description

When im joining with a 1.20 Client i get kicked for "The server you where previously on went down, you have been connected to a fallback server". 
Im running Spigot 1.8.8 and when im using other Versions like 1.19 i didn't get this error.

### Steps to Reproduce

1. Download Cloudnet v3.4
2. Make a Proxy task, select waterfall
3. Make a Lobby task, select spigot-1.8.8
4. Install ViaVersion (Latest from SpigotMC) on your Lobby Server
5. Connect with 1.20.4

### Expected Behavior

I connect to the Hub Server

### Additional Server Info

I use Cloudnet v3.4 with a Waterfall Proxy and spigot for my subservers.
I installed ViaVersion on my Subservers (Lobby-1, etc.)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--21fe707--741a1bd%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--Spigot--21fe707--741a1bd%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (4.9.2): 54 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.9.2)-54%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>tab_warn</details>

**Comment by DungeonHD** [comment]
I downloaded ViaVersion-4.9.3 and the error was fixed. Thanks!
