### ISSUE TITLE
ViaVersion] An error occurred in metadata handler MetadataRewriter1_14To1_13_2 for untracked entity type: Metadata{id=2, metaType=MetaType{typeId=5, type=OptionalComponentType}, value={"extra":[{"color":"red","text":"10 "},{"color":"yellow","text":"saniye sonra üretiliyor"}],"text":""}}

### ISSUE THREAD

**Issue by snellnn** [ViaVersion/ViaVersion#3758]
### `/viaversion dump` Output

https://dump.viaversion.com/acfc80ba6e5d9266dbf3460148e93462228b812632fa60ea9aa680461276b3af

### Console Error

```
Put the mclo.gs link or text here.
```
https://api.mclo.gs/1/raw/2BavY5l
1
java.lang.NullPointerException: null
[18:06:07 ERROR]: [ViaVersion] An error occurred in metadata handler MetadataRewriter1_14To1_13_2 for untracked entity type: Metadata{id=2, metaType=MetaType{typeId=5, type=OptionalComponentType}, value={"extra":[{"color":"yellow","text":"Spawns in "},{"color":"red","text":"10 "},{"color":"yellow","text":"seconds"}],"text":""}}
[18:06:07 ERROR]: [ViaVersion] Full metadata: Metadata{id=2, metaType=MetaType{typeId=5, type=OptionalComponentType}, value={"extra":[{"color":"yellow","text":"Spawns in "},{"color":"red","text":"10 "},{"color":"yellow","text":"seconds"}],"text":""}}
[18:06:07 ERROR]: [ViaVersion] Error: 
java.lang.NullPointerException: null

2

java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.api.minecraft.entities.EntityType.is(com.viaversion.viaversion.api.minecraft.entities.EntityType)" because "type" is null
	at com.viaversion.viaversion.protocols.protocol1_14to1_13_2.metadata.MetadataRewriter1_14To1_13_2.lambda$registerRewrites$11(MetadataRewriter1_14To1_13_2.java:164) ~[?:?]
	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:120) ~[?:?]
	at com.viaversion.viaversion.rewriter.EntityRewriter$4.lambda$register$0(EntityRewriter.java:360) ~[?:?]
	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58) ~[?:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35) ~[?:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1620]
	at me.defender.cosmetics.support.hcore.packet.player.PacketPlayer_v1_12_R1$1.write(PacketPlayer_v1_12_R1.java:66) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[?:?]
	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[18:05:20] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] An error occurred in metadata handler MetadataRewriter1_14To1_13_2 for untracked entity type: Metadata{id=5, metaType=MetaType{typeId=7, type=BooleanType}, value=true}
[18:05:20] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] Full metadata: Metadata{id=5, metaType=MetaType{typeId=7, type=BooleanType}, value=true}
[18:05:20] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] Error: 
java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.api.minecraft.entities.EntityType.is(com.viaversion.viaversion.api.minecraft.entities.EntityType)" because "type" is null
	at com.viaversion.viaversion.protocols.protocol1_14to1_13_2.metadata.MetadataRewriter1_14To1_13_2.lambda$registerRewrites$11(MetadataRewriter1_14To1_13_2.java:164) ~[?:?]
	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:120) ~[?:?]
	at com.viaversion.viaversion.rewriter.EntityRewriter$4.lambda$register$0(EntityRewriter.java:360) ~[?:?]
	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58) ~[?:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35) ~[?:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1620]
	at me.defender.cosmetics.support.hcore.packet.player.PacketPlayer_v1_12_R1$1.write(PacketPlayer_v1_12_R1.java:66) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[?:?]
	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:840) [?:?]
	
	
	3
	[18:05:20] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] An error occurred in metadata handler MetadataRewriter1_14To1_13_2 for untracked entity type: Metadata{id=0, metaType=MetaType{typeId=0, type=ByteType}, value=32}
[18:05:20] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] Full metadata: Metadata{id=0, metaType=MetaType{typeId=0, type=ByteType}, value=32}
Metadata{id=2, metaType=MetaType{typeId=5, type=OptionalComponentType}, value={"extra":[{"color":"red","text":"26 "},{"color":"yellow","text":"saniye sonra üretiliyor"}],"text":""}}
Metadata{id=3, metaType=MetaType{typeId=7, type=BooleanType}, value=true}
Metadata{id=5, metaType=MetaType{typeId=7, type=BooleanType}, value=true}
Metadata{id=11, metaType=MetaType{typeId=0, type=ByteType}, value=24}
[18:05:20] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] Error: 
java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.api.minecraft.entities.EntityType.is(com.viaversion.viaversion.api.minecraft.entities.EntityType)" because "type" is null
	at com.viaversion.viaversion.protocols.protocol1_14to1_13_2.metadata.MetadataRewriter1_14To1_13_2.lambda$registerRewrites$11(MetadataRewriter1_14To1_13_2.java:164) ~[?:?]
	at com.viaversion.viaversion.rewriter.EntityRewriter.handleMetadata(EntityRewriter.java:120) ~[?:?]
	at com.viaversion.viaversion.rewriter.EntityRewriter$4.lambda$register$0(EntityRewriter.java:360) ~[?:?]
	at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:158) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:392) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:423) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:407) ~[?:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:116) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330) ~[?:?]
	at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58) ~[?:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35) ~[?:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) ~[patched_1.12.2.jar:git-Paper-1620]
	at me.defender.cosmetics.support.hcore.packet.player.PacketPlayer_v1_12_R1$1.write(PacketPlayer_v1_12_R1.java:66) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[?:?]
	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215) ~[patched_1.12.2.jar:git-Paper-1620]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) ~[patched_1.12.2.jar:git-Paper-1620]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:840) [?:?]
[18:05:20] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] An error occurred in metadata handler MetadataRewriter1_14To1_13_2 for untracked entity type: Metadata{id=2, metaType=MetaType{typeId=5, type=OptionalComponentType}, value={"extra":[{"color":"red","text":"26 "},{"color":"yellow","text":"saniye sonra üretiliyor"}],"text":""}}
[18:05:20] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] Full metadata: Metadata{id=2, metaType=MetaType{typeId=5, type=OptionalComponentType}, value={"extra":[{"color":"red","text":"26 "},{"color":"yellow","text":"saniye sonra üretiliyor"}],"text":""}}
Metadata{id=3, metaType=MetaType{typeId=7, type=BooleanType}, value=true}
Metadata{id=5, metaType=MetaType{typeId=7, type=BooleanType}, value=true}
Metadata{id=11, metaType=MetaType{typeId=0, type=ByteType}, value=24}
[18:05:20] [Netty Epoll Server IO #0/ERROR]: [ViaVersion] Error: 
java.lang.NullPointerException: Cannot invoke "com.viaversion.viaversion.api.minecraft.entities.EntityType.is(com.viaversion.viaversion.api.minecraft.entities.EntityType)" because "type" is null

### Bug Description

when starting the game Bed Wars there is an error that endlessly spams the console changed java updated the plugin does not help version 1.12.2 what do we do?

### Steps to Reproduce

When we run out of water and are thrown into the arena, there's an error.

### Expected Behavior

.

### Additional Server Info

.
[latest.log](https://github.com/ViaVersion/ViaVersion/files/14744789/latest.log)

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment]
This issue looks very similar to #3760.

**Comment by snellnn** [comment]
ета проблема была иза плагина Citizens
 но я ее исправил

**Comment by snellnn** [comment]
> Эта проблема очень похожа на #3760 .

This problem was caused by the Citizens plugin.
but I fixed it
