### ISSUE TITLE
ERROR IN Protocol1_18_2To1_19 IN REMAP OF RESPAWN (0x3B)

### ISSUE THREAD

**Issue by FlanZCode** [ViaVersion/ViaVersion#3855]
### `/viaversion dump` Output

https://dump.viaversion.com/21b1e36d05466baf413a775f7afe7938c3590d70514142a3e91df8dea040f771

### Console Error

```
[21:17:18] [Server thread/INFO]: EnzoMC0002 was slain by Husk
[21:17:20] [Netty Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_18_2To1_19 IN REMAP OF RESPAWN (0x3B)
[21:17:20] [Netty Server IO #1/WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[21:17:20] [Netty Server IO #1/WARN]: Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.EntityPackets1_19$4 (Anonymous)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[21:17:20] [Netty Server IO #1/WARN]:   at net.minecraft.network.NetworkManager$2.write(NetworkManager.java:543)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[21:17:20] [Netty Server IO #1/WARN]:   at net.minecraft.network.NetworkManager.c(NetworkManager.java:366)
[21:17:20] [Netty Server IO #1/WARN]:   at net.minecraft.network.NetworkManager.lambda$sendPacket$12(NetworkManager.java:359)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:17:20] [Netty Server IO #1/WARN]:   at java.base/java.lang.Thread.run(Thread.java:1570)
[21:17:20] [Netty Server IO #1/WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[21:17:20] [Netty Server IO #1/WARN]: Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.EntityPackets1_19$4 (Anonymous)
[21:17:20] [Netty Server IO #1/WARN]: Caused by: java.lang.IllegalArgumentException: Could not find dimension overworld in dimension registry
[21:17:20] [Netty Server IO #1/WARN]:   at com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.EntityPackets1_19$4.lambda$register$0(EntityPackets1_19.java:186)
[21:17:20] [Netty Server IO #1/WARN]:   at com.viaversion.viaversion.api.protocol.remapper.PacketHandlers.handle(PacketHandlers.java:178)
[21:17:20] [Netty Server IO #1/WARN]:   at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:399)
[21:17:20] [Netty Server IO #1/WARN]:   at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[21:17:20] [Netty Server IO #1/WARN]:   at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:120)
[21:17:20] [Netty Server IO #1/WARN]:   at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:330)
[21:17:20] [Netty Server IO #1/WARN]:   at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308)
[21:17:20] [Netty Server IO #1/WARN]:   at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[21:17:20] [Netty Server IO #1/WARN]:   at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[21:17:20] [Netty Server IO #1/WARN]:   at net.minecraft.network.NetworkManager$2.write(NetworkManager.java:543)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[21:17:20] [Netty Server IO #1/WARN]:   at net.minecraft.network.NetworkManager.c(NetworkManager.java:366)
[21:17:20] [Netty Server IO #1/WARN]:   at net.minecraft.network.NetworkManager.lambda$sendPacket$12(NetworkManager.java:359)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:17:20] [Server thread/INFO]: EnzoMC0002 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Source 0: com.viaversion.viabackwards.protocol.protocol1_18_2to1_19.packets.EntityPackets1_19$4 (Anonymous)
[21:17:20] [Netty Server IO #1/WARN]:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:17:20] [Netty Server IO #1/WARN]:   at java.base/java.lang.Thread.run(Thread.java:1570)
[21:17:20] [Server thread/INFO]: EnzoMC0002 left the game
```

### Bug Description

I use viaversion, viabackward, viarewind, play in 1.8.9 with a 1.20.6 server and get kill by a spider, after that I got kick. I didn't install via* on bungee, only on spigot and I don't think geyser is releated to that (I try to get kill by a spider on my bedrock account and it didn't do anything, just get kill and respawn)

### Steps to Reproduce

Login with 1.8.9
Use Via* on 1.20.6 on spigot with bungee and geyser
get kill by a spider on java

### Expected Behavior

Not getting kick

### Additional Server Info

I use spigot, bungee and geyser

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 4149--Spigot--e2c1eee--4e7d749%20%28MC%3A%201.20.6%29](https://img.shields.io/badge/Platform-4149--Spigot--e2c1eee--4e7d749%20%28MC%3A%201.20.6%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump and the issue will be reopened</h3>
