### ISSUE TITLE
It seems incompatible with LimboApi

### ISSUE THREAD

**Issue by 3154311518** [ViaVersion/ViaVersion#3871]
### `/viaversion dump` Output

https://dump.viaversion.com/fe8c252ea2d99cb581e797683426f8ba51a073926589f3de2760e36e68ef08e7

### Console Error

[04:09:11 ERROR]: [connected player] 9990302 (/120.235.215.214:63544): exception encountered in com.velocitypowered.proxy.connection.client.
ClientPlaySessionHandler@3e0aeea1
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Invalid token
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55
f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.3.0-SNAPSHOT
 (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.3.0-SNAPSHOT
(git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.3.0-SNAPSHOT (git-a
fd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.3.0-SNAPSHOT (git-a
fd8b55f-b390)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390
)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.3.0-SNAPSHOT
 (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.3.0-SNAPSHOT
(git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.3.0-SNAPSHOT (git-a
fd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.3.0-SNAPSHOT (git-a
fd8b55f-b390)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390
)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity.jar:3.3.0-SNAPSHOT
 (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity.jar:3.3.0-SNAPSHOT
(git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity.jar:3.3.0-SNAPSHOT (git-a
fd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity.jar:3.3.0-SNAPSHOT (git-a
fd8b55f-b390)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)
]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:249) ~[velocity.jar:3.3.0-SNAPSHOT
 (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleUnknown(BackendPlaySessionHandler.java:407) ~[veloci
ty.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:161) ~[velocity.jar:3.3.0-SNAPSHOT
(git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNA
PSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNA
PSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPS
HOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57) ~[velocity.jar:3.3.0-SN
APSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.3.0-SNA
PSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNA
PSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPS
HOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:78) ~[velocity.jar:3.3.0-SNAPSHOT (git-
afd8b55f-b390)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity.jar:3.3.0-SNAPSHOT (gi
t-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.3.0-SNA
PSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.3.0-SNA
PSHOT (git-afd8b55f-b390)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.3.0-SNAPS
HOT (git-afd8b55f-b390)]
        at com.viaversion.viaversion.connection.UserConnectionImpl.lambda$sendRawPacket$1(UserConnectionImpl.java:168) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.sendRawPacket(UserConnectionImpl.java:173) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.sendRawPacket(UserConnectionImpl.java:155) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.lambda$send0$0(PacketWrapperImpl.java:281) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55
f-b390)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd
8b55f-b390)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.3.0-SNAPSHOT
(git-afd8b55f-b390)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-a
fd8b55f-b390)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f
-b390)]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid token
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:322) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:308) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformOutgoing(UserConnection.java:236) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:47) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler.encode(VelocityEncodeHandler.java:29) ~[?:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f
-b390)]
        ... 45 more

### Bug Description

Use 1.8.8 client to enter 1.12.2 server

### Steps to Reproduce

Install LimboApi plugin

Then use the 1.8.8 client to enter the higher version server

### Expected Behavior

Connection made successfully

### Additional Server Info

Proxy Velocity3.3 Plugin: Viaversion Viarewind Viabackwards LimboApi
Server PaperSpigot1.12.2 Plugin: none

I deleted the LimboApi plugin and players can use the 1.8.8 client to enter the server.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--afd8b55f--b390%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--afd8b55f--b390%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
It's because viaversion has no clue how to handle limboAPI and it's related plugins, Please move them to the spigot/paper servers instead.
