### ISSUE TITLE
[1.20.3->1.20.5] firework_rocket show_item bug

### ISSUE THREAD

**Issue by Pantera07** [ViaVersion/ViaVersion#3877]
### `/viaversion dump` Output

https://dump.viaversion.com/62ab6e3722a2d5f4ee4af160c4f1ebabbdfb03cd8773f0adad892eea188c8a9d

### Console Error

```
[19:49:44 WARN]: [ViaVersion] (1.20.3->1.20.5) Error writing components in show_item!
java.lang.IllegalArgumentException: Value out of range: 2
        at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.ComponentRewriter1_20_5.convertUnsignedByte(ComponentRewriter1_20_5.java:1054) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.ComponentRewriter1_20_5.convertFireworks(ComponentRewriter1_20_5.java:807) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.ComponentRewriter1_20_5.toTag(ComponentRewriter1_20_5.java:305) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.ComponentRewriter1_20_5.handleHoverEvent(ComponentRewriter1_20_5.java:250) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processCompoundTag(ComponentRewriter.java:288) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processTag(ComponentRewriter.java:260) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.passthroughAndProcess(ComponentRewriter.java:166) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35) ~[ViaVersion-5.0.0-SNAPSHOT.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:449) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:434) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Bug Description

firework_rocket show_item bug

### Steps to Reproduce

try show_item
```
/tellraw @p {"hoverEvent":{"action":"show_item","value":"{id: \"minecraft:shulker_box\", tag: {BlockEntityTag: {id: \"minecraft:shulker_box\", Items: [{Slot: 0b, Count: 1b, tag: {Fireworks: {Flight: 2b}}, id: \"minecraft:firework_rocket\"}, {Slot: 26b, Count: 1b, tag: {Fireworks: {Flight: 3b}}, id: \"minecraft:firework_rocket\"}]}}, Count: 1b}"},"text":"Test"}
```
```
/tellraw @p {"hoverEvent":{"action":"show_item","value":"{id:\"minecraft:firework_rocket\",Count:1b,tag:{Fireworks:{Flight:2b}}}"},"text":"Test"}
```

### Expected Behavior

show_item should work fine without errors.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--496%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--496%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): Even with dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-Even%20with%20dev-brightgreen?style=flat-square) </br>
