### ISSUE TITLE
Window click error

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#3879]
### `/viaversion dump` Output

https://dump.viaversion.com/4534248a2fc5764fb19a3e93141d53da48215e740cdd4d1a086a1780776aa464

### Console Error

```
[17:36:09] [Netty Epoll Server IO #5/WARN]: [ViaVersion] ERROR IN Protocol1_20_5To1_20_3 IN REMAP OF CLICK_WINDOW (0x0E)
[17:36:09] [Netty Epoll Server IO #5/WARN]: io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[17:36:09] [Netty Epoll Server IO #5/WARN]: Packet Type: CLICK_WINDOW, Type: ItemType1_20_5, Index: 9, Data: [{Unsigned Byte: 0}, {VarInt: 673}, {ShortType: 30}, {ByteType: 0}, {VarInt: 0}, {VarInt: 1}, {ShortType: 30}, {ItemType1_20_2: Item{identifier=0, amount=61, data=0, tag={}}}], Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$10 (Anonymous), Packet ID: 13
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:36:09] [Netty Epoll Server IO #5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

### Bug Description

This error spammed and someone's item vanished. I unfortunately have no idea how to replicate this or why it occured but I am hoping the error alone is enough to fix it

### Steps to Reproduce

Sorry, no clue :(

### Expected Behavior

No error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Axolotl--%22f699bcf%22%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Axolotl--%22f699bcf%22%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaVersion%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards(4.10.2): 2 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.10.2)-2%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(3.1.2): Even with master](https://img.shields.io/badge/ViaRewind%20(3.1.2)-Even%20with%20master-brightgreen?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
