### ISSUE TITLE
Viaversion not working

### ISSUE THREAD

**Issue by Amirmg086** [ViaVersion/ViaVersion#3887]
### `/viaversion dump` Output

[14:27:25 ERROR]: [ViaVersion] Error when posting ViaVersion dump java.net.ConnectException: Connection timed out: connect         at sun.nio.ch.Net.connect0(Native Method) ~[?:?]         at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]         at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]         at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]         at java.net.Socket.connect(Socket.java:633) ~[?:?]         at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]         at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]         at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]         at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]         at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]         at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]         at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401) ~[?:?]         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220) ~[?:?]         at com.viaversion.viaversion.util.DumpUtil.lambda$postDump$0(DumpUtil.java:94) ~[ViaVersion-4.10.2 (2).jar:?]         at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]         at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]         at java.lang.Thread.run(Thread.java:833) ~[?:?] [14:27:40 ERROR]: [ViaVersion] Error when posting ViaVersion dump java.net.ConnectException: Connection timed out: connect         at sun.nio.ch.Net.connect0(Native Method) ~[?:?]         at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]         at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]         at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]         at java.net.Socket.connect(Socket.java:633) ~[?:?]         at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[?:?]         at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[?:?]         at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]         at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]         at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]         at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]         at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401) ~[?:?]         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220) ~[?:?]         at com.viaversion.viaversion.util.DumpUtil.lambda$postDump$0(DumpUtil.java:94) ~[ViaVersion-4.10.2 (2).jar:?]         at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]         at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]         at java.lang.Thread.run(Thread.java:833) ~[?:?] [14:27:40 INFO]: Failed to dump, please check the console for more information

### Console Error

```
[14:24:24 INFO]: [ViaVersion] Loading server plugin ViaVersion v4.10.2
[14:24:24 INFO]: [ViaVersion] ViaVersion 4.10.2 is now loaded. Registering protocol transformers and injecting...
[14:24:26 INFO]: [ViaBackwards] Loading translations...
[14:24:27 INFO]: [ViaBackwards] Registering protocols...
[14:24:27 ERROR]: [ViaVersion] Error initializing plugin 'ViaVersion-4.10.2 (2).jar' in folder 'plugins' (Is it up to date?)
java.lang.IllegalStateException: Ids have not been initialized yet (type PUFFERFISH)
        at com.viaversion.viaversion.api.minecraft.entities.EntityTypes1_15.getId(EntityTypes1_15.java:226) ~[ViaVersion-4.10.2 (2).jar:?]
        at com.viaversion.viabackwards.api.rewriters.EntityRewriterBase.mapEntityTypeWithData(EntityRewriterBase.java:158) ~[ViaBackwards-4.10.2 (1).jar:?]
        at com.viaversion.viabackwards.protocol.protocol1_14_4to1_15.packets.EntityPackets1_15.registerRewrites(EntityPackets1_15.java:203) ~[ViaBackwards-4.10.2 (1).jar:?]
        at com.viaversion.viaversion.api.rewriter.RewriterBase.register(RewriterBase.java:37) ~[ViaVersion-4.10.2 (2).jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.callRegister(AbstractProtocol.java:222) ~[ViaVersion-4.10.2 (2).jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.registerPackets(AbstractProtocol.java:205) ~[ViaVersion-4.10.2 (2).jar:?]
        at com.viaversion.viabackwards.api.BackwardsProtocol.registerPackets(BackwardsProtocol.java:49) ~[ViaBackwards-4.10.2 (1).jar:?]
        at com.viaversion.viabackwards.protocol.protocol1_14_4to1_15.Protocol1_14_4To1_15.registerPackets(Protocol1_14_4To1_15.java:56) ~[ViaBackwards-4.10.2 (1).jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:100) ~[ViaVersion-4.10.2 (2).jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:201) ~[ViaVersion-4.10.2 (2).jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:195) ~[ViaVersion-4.10.2 (2).jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:116) ~[ViaBackwards-4.10.2 (1).jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:37) ~[ViaBackwards-4.10.2 (1).jar:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:114) ~[ViaVersion-4.10.2 (2).jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:85) ~[ViaVersion-4.10.2 (2).jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Bug Description

players can join 

### Steps to Reproduce

cant join with <1.20.4

### Expected Behavior

cant join with <1.20.4

### Additional Server Info

cant join with <1.20.4

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
You have a mismatched or outdated ViaBackwards

**Comment by Amirmg086** [comment]
this last version 4.10.2

**Comment by Amirmg086** [comment]
> You have a mismatched or outdated ViaBackwards

i have last version 
Help Please

**Comment by kennytv** [comment]
Join the Discord for more help, but this is almost definitely related to a bad setup

**Comment by Amirmg086** [comment]
> Join the Discord for more help, but this is almost definitely related to a bad setup

i cant get dump
https://dump.viaversion.com/af595593a0af706c7854ca18c6a4ac67eab969ae16c45c4ccdd2cd470edd4839

**Comment by Barvalg** [comment]
![Platform: git--Paper--496%20%28MC%3A%201.20.4%29](https://img.shields.io/badge/Platform-git--Paper--496%20%28MC%3A%201.20.4%29-3498db?style=flat-square) </br>![ViaVersion (4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.10.3-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(4.10.3--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>
