### ISSUE TITLE
Show item issue

### ISSUE THREAD

**Issue by JHarris12345** [ViaVersion/ViaVersion#3929]
### `/viaversion dump` Output

https://dump.viaversion.com/de5e517e0f93a10c2eeb9c47d70f38e2f01bdf5586241376dcc8cb500f0231bb

### Console Error

```
[14:36:11 WARN]: [ViaVersion] (1.20.3->1.20.5) Error writing components in show_item!
java.lang.IllegalArgumentException: Missing id tag in nbt: {Invisible:0b,Marker:0b,NoBasePlate:0b,ShowArms:0b,Small:0b}
        at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.ComponentRewriter1_20_5.convertNbtWithId(ComponentRewriter1_20_5.java:1093) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.ComponentRewriter1_20_5.convertEntityData(ComponentRewriter1_20_5.java:732) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.ComponentRewriter1_20_5.toTag(ComponentRewriter1_20_5.java:305) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.ComponentRewriter1_20_5.handleHoverEvent(ComponentRewriter1_20_5.java:250) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processCompoundTag(ComponentRewriter.java:288) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processTag(ComponentRewriter.java:260) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processListTag(ComponentRewriter.java:266) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processCompoundTag(ComponentRewriter.java:283) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processTag(ComponentRewriter.java:260) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processListTag(ComponentRewriter.java:266) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processCompoundTag(ComponentRewriter.java:283) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.processTag(ComponentRewriter.java:260) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.rewriter.ComponentRewriter.passthroughAndProcess(ComponentRewriter.java:166) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35) ~[ViaVersion-5.0.0-SNAPSHOT (2).jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.github.repooper.packetevents.Vulcan_ie.write(Vulcan_ie.java:60) ~[Vulcan-2.8.5.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at dev.geco.gsit.mcv.v1_20_2.util.PackageUtil$1.write(PackageUtil.java:90) ~[GSit-1.7.0.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at me.neznamy.tab.shared.features.injection.NettyPipelineInjector$TabChannelDuplexHandler.write(NettyPipelineInjector.java:115) ~[TAB v4.1.4.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:77) ~[TradeSystem_v2.5.3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:77) ~[TradeSystem_v2.5.3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib (5).jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:448) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$10(Connection.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib (5).jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Bug Description

I have no idea how to replicate it. It just got spammed and I saw it

### Steps to Reproduce

No idea

### Expected Behavior

No error

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Axolotl--%22f699bcf%22%20%28MC%3A%201.20.2%29](https://img.shields.io/badge/Platform-git--Axolotl--%22f699bcf%22%20%28MC%3A%201.20.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaVersion%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaBackwards(5.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaBackwards%20(5.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br>![ViaRewind(4.0.0-SNAPSHOT): 1 commits behind dev](https://img.shields.io/badge/ViaRewind%20(4.0.0--SNAPSHOT)-1%20commit(s)%20behind%20dev-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>
