### ISSUE TITLE
I can't join to the server

### ISSUE THREAD

**Issue by demekk** [ViaVersion/ViaVersion#3943]
### `/viaversion dump` Output

https://dump.viaversion.com/a0302b717b8a5e782156ee532883b99cb7ac0d411964b6ae963804da25413699

### Console Error

[20:23:55 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues and follow the issue template
{Packet Type: DECLARE_RECIPES, Type: FlatVarIntItem Array, Data: [Pair{Type|VarInt, 524}, Pair{Type|String, minecraft:piston}, Pair{Type|String, crafting_shaped}, Pair{Type|VarInt, 3}, Pair{Type|VarInt, 3}, Pair{Type|String, }, Pair{Type|FlatVarIntItem Array, [Lcom.viaversion.viaversion.api.minecraft.item.Item;@64a54c21}], Source 0: com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2 (Anonymous), Packet ID: 84}
Actual Error:
[20:23:55 WARN]: Caused by: java.io.IOException: Expected root tag to be a CompoundTag, was 6
[20:23:55 WARN]:        at com.viaversion.viaversion.libs.opennbt.NBTIO.readTag(NBTIO.java:179)
[20:23:55 WARN]:        at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:52)
[20:23:55 WARN]:        at com.viaversion.viaversion.api.type.types.minecraft.NBTType.read(NBTType.java:36)
[20:23:55 WARN]:        at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:44)
[20:23:55 WARN]:        at com.viaversion.viaversion.api.type.types.minecraft.FlatVarIntItemType.read(FlatVarIntItemType.java:30)
[20:23:55 WARN]:        at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:49)
[20:23:55 WARN]:        at com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:30)
[20:23:55 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:135)
[20:23:55 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:181)
[20:23:55 WARN]:        at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.data.RecipeRewriter1_13_2.handleCraftingShaped(RecipeRewriter1_13_2.java:56)
[20:23:55 WARN]:        at com.viaversion.viaversion.rewriter.RecipeRewriter.handle(RecipeRewriter.java:43)
[20:23:55 WARN]:        at com.viaversion.viaversion.protocols.protocol1_13_1to1_13.packets.InventoryPackets$2.lambda$registerMap$0(InventoryPackets.java:90)
[20:23:55 WARN]:        at com.viaversion.viaversion.api.protocol.remapper.PacketRemapper.remap(PacketRemapper.java:158)
[20:23:55 WARN]:        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:324)
[20:23:55 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:371)
[20:23:55 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:359)
[20:23:55 WARN]:        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:46)
[20:23:55 WARN]:        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:123)
[20:23:55 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:313)
[20:23:55 WARN]:        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:292)
[20:23:55 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:90)
[20:23:55 WARN]:        at com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:83)
[20:23:55 WARN]:        at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
[20:23:55 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:23:55 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[20:23:55 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:531)
[20:23:55 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:72)
[20:23:55 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:271)
[20:23:55 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[20:23:55 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:277)
[20:23:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[20:23:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[20:23:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[20:23:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[20:23:55 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[20:23:55 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[20:23:55 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[20:23:55 WARN]: [server-bukkit-platform] removed: bonzai16
[20:23:55 WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[20:23:55 WARN]:        at net.minecraft.server.v1_13_R1.NetworkManager.lambda$4(NetworkManager.java:199)
[20:23:55 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:354)
[20:23:55 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[20:23:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[20:23:55 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[20:23:55 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[20:23:55 WARN]:        at java.lang.Thread.run(Unknown Source)

### Bug Description

When I am joining to the server this error seen

### Steps to Reproduce

I am joining on 1.16.5 minecraft version and server engine is 1.13, ViaVersion 4.4.0

### Expected Behavior

I cant join to the server

### Additional Server Info

Server engine version 1.13, ViaVersion 4.4.0

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Spigot--fe3ab0d--162bda9%20%28MC%3A%201.13%29](https://img.shields.io/badge/Platform-git--Spigot--fe3ab0d--162bda9%20%28MC%3A%201.13%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(4.4.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
This ain't the past anymore - Update viaversion to 5.0.0 and protocollib to latest CI build. *(and also server to 1.13.2 to make it stable)*
