### ISSUE TITLE
Error reading NBT in show_item with custom enchantment NBT

### ISSUE THREAD

**Issue by skbeh** [ViaVersion/ViaVersion#4051]
### `/viaversion dump` Output

https://dump.viaversion.com/71828bfbfa99e58f3f35f4d6b2cabacea5084dc6d715eaf9864c3adf003a279b

### Console Error

https://mclo.gs/t3JBLyq

### Bug Description

Just console errors, no observable behavior.

### Steps to Reproduce

1. Login with a client with version equal or higher than 1.13 to a 1.8 server.
2. Run `give %player_name% iron_sword 1 0 {ench:[{id:16,lvl:1}]}` in the server console. The issue can not be reproduced if the command is executed in game.
3. Watch the log and see the exception.

### Expected Behavior

The exception should not appear.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--PandaSpigot--%220764ac6%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PandaSpigot--%220764ac6%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.1): 27 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.1)-27%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaRewind(4.0.1): 17 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.1)-17%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by skbeh** [comment]
https://dump.viaversion.com/71828bfbfa99e58f3f35f4d6b2cabacea5084dc6d715eaf9864c3adf003a279b

**Comment by Barvalg** [comment]
![Platform: git--PandaSpigot--%220764ac6%22%20%28MC%3A%201.8.8%29](https://img.shields.io/badge/Platform-git--PandaSpigot--%220764ac6%22%20%28MC%3A%201.8.8%29-3498db?style=flat-square) </br>![ViaVersion (5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.2-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaBackwards%20(5.0.2--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by skbeh** [comment]
@kennytv Still some issues with 5.0.2 on a 1.21 client.

```log
Description: Packet handling error

io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:system_chat'
	at net.minecraft.class_9136.method_56425(class_9136.java:38)
	at net.minecraft.class_9136.decode(class_9136.java:14)
	at net.minecraft.class_2543.decode(class_2543.java:31)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: io.netty.handler.codec.DecoderException: Failed to decode: Failed to parse either. First: Failed to parse either. First: Not a string; Second: Not a list: {translate:"death.attack.mob.item",with:[{clickEvent:{action:"suggest_command",value:"/msg foo "},hoverEvent:{action:"show_entity",contents:{id:[I;1486251287,198852190,-2006621937,1421353322],name:"foo",type:"pig"}},insertion:"foo",text:"foo"},{clickEvent:{action:"suggest_command",value:"/msg bar "},hoverEvent:{action:"show_entity",contents:{id:[I;-1166407521,-169785078,-1979681654,389492979],name:"bar",type:"pig"}},insertion:"bar",text:"bar"},{color:"aqua",extra:[{italic:1b,text:"Custom Iron Sword"},{"":"]"}],hoverEvent:{action:"show_item",contents:{components:{custom_data:{DuelsKitContent:"true",Enchantments:[{id:"unbreaking",lvl:3s}],"VV|Protocol1_12_2To1_13":14,"VV|Protocol1_20_3To1_20_5":1b,display:{Name:'{"text":"Custom Iron Sword"}',"VV|Protocol1_12_2To1_13|Name":"Custom Iron Sword"}},custom_name:'"Custom Iron Sword"',enchantments:{levels:{unbreaking:3}},food:{can_always_eat:1b,eat_seconds:3600.0f,nutrition:0,saturation_modifier:0.0f}},count:0,id:"minecraft:iron_sword"}},text:"["}]}; Second: No matching codec found {translate:"death.attack.mob.item",with:[{clickEvent:{action:"suggest_command",value:"/msg foo "},hoverEvent:{action:"show_entity",contents:{id:[I;1486251287,198852190,-2006621937,1421353322],name:"foo",type:"pig"}},insertion:"foo",text:"foo"},{clickEvent:{action:"suggest_command",value:"/msg bar "},hoverEvent:{action:"show_entity",contents:{id:[I;-1166407521,-169785078,-1979681654,389492979],name:"bar",type:"pig"}},insertion:"bar",text:"bar"},{color:"aqua",extra:[{italic:1b,text:"Custom Iron Sword"},{"":"]"}],hoverEvent:{action:"show_item",contents:{components:{custom_data:{DuelsKitContent:"true",Enchantments:[{id:"unbreaking",lvl:3s}],"VV|Protocol1_12_2To1_13":14,"VV|Protocol1_20_3To1_20_5":1b,display:{Name:'{"text":"Custom Iron Sword"}',"VV|Protocol1_12_2To1_13|Name":"Custom Iron Sword"}},custom_name:'"Custom Iron Sword"',enchantments:{levels:{unbreaking:3}},food:{can_always_eat:1b,eat_seconds:3600.0f,nutrition:0,saturation_modifier:0.0f}},count:0,id:"minecraft:iron_sword"}},text:"["}]}
	at net.minecraft.class_9135$6.method_56900(class_9135.java:273)
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
	at net.minecraft.class_9135$6.method_56901(class_9135.java:273)
	at net.minecraft.class_9135$6.decode(class_9135.java:268)
	at net.minecraft.class_9139$12.decode(class_9139.java:149)
	at net.minecraft.class_9139$9.method_56441(class_9139.java:91)
	at net.minecraft.class_9139$9.decode(class_9139.java:87)
	at net.minecraft.class_9136.method_56425(class_9136.java:36)
	... 37 more
```

Formatted json:
```json
{
    translate:"death.attack.mob.item",
    with:[
        {
            clickEvent:{
                action:"suggest_command",
                value:"/msg foo "
            },
            hoverEvent:{
                action:"show_entity",
                contents:{
                    id:[
                        I;1486251287,
                        198852190,
                        -2006621937,
                        1421353322
                    ],
                    name:"foo",
                    type:"pig"
                }
            },
            insertion:"foo",
            text:"foo"
        },
        {
            clickEvent:{
                action:"suggest_command",
                value:"/msg bar "
            },
            hoverEvent:{
                action:"show_entity",
                contents:{
                    id:[
                        I;-1166407521,
                        -169785078,
                        -1979681654,
                        389492979
                    ],
                    name:"bar",
                    type:"pig"
                }
            },
            insertion:"bar",
            text:"bar"
        },
        {
            color:"aqua",
            extra:[
                {
                    italic:1b,
                    text:"Custom Iron Sword"
                },
                {
                    "":"]"
                }
            ],
            hoverEvent:{
                action:"show_item",
                contents:{
                    components:{
                        custom_data:{
                            DuelsKitContent:"true",
                            Enchantments:[
                                {
                                    id:"unbreaking",
                                    lvl:3s
                                }
                            ],
                            "VV|Protocol1_12_2To1_13":14,
                            "VV|Protocol1_20_3To1_20_5":1b,
                            display:{
                                Name:'{"text":"Custom Iron Sword"}',
                                "VV|Protocol1_12_2To1_13|Name":"Custom Iron Sword"
                            }
                        },
                        custom_name:'"Custom Iron Sword"',
                        enchantments:{
                            levels:{
                                unbreaking:3
                            }
                        },
                        food:{
                            can_always_eat:1b,
                            eat_seconds:3600.0f,
                            nutrition:0,
                            saturation_modifier:0.0f
                        }
                    },
                    count:0,
                    id:"minecraft:iron_sword"
                }
            },
            text:"["
        }
    ]
}; Second:No matching codec found{
    translate:"death.attack.mob.item",
    with:[
        {
            clickEvent:{
                action:"suggest_command",
                value:"/msg foo "
            },
            hoverEvent:{
                action:"show_entity",
                contents:{
                    id:[
                        I;1486251287,
                        198852190,
                        -2006621937,
                        1421353322
                    ],
                    name:"foo",
                    type:"pig"
                }
            },
            insertion:"foo",
            text:"foo"
        },
        {
            clickEvent:{
                action:"suggest_command",
                value:"/msg bar "
            },
            hoverEvent:{
                action:"show_entity",
                contents:{
                    id:[
                        I;-1166407521,
                        -169785078,
                        -1979681654,
                        389492979
                    ],
                    name:"bar",
                    type:"pig"
                }
            },
            insertion:"bar",
            text:"bar"
        },
        {
            color:"aqua",
            extra:[
                {
                    italic:1b,
                    text:"Custom Iron Sword"
                },
                {
                    "":"]"
                }
            ],
            hoverEvent:{
                action:"show_item",
                contents:{
                    components:{
                        custom_data:{
                            DuelsKitContent:"true",
                            Enchantments:[
                                {
                                    id:"unbreaking",
                                    lvl:3s
                                }
                            ],
                            "VV|Protocol1_12_2To1_13":14,
                            "VV|Protocol1_20_3To1_20_5":1b,
                            display:{
                                Name:'{"text":"Custom Iron Sword"}',
                                "VV|Protocol1_12_2To1_13|Name":"Custom Iron Sword"
                            }
                        },
                        custom_name:'"Custom Iron Sword"',
                        enchantments:{
                            levels:{
                                unbreaking:3
                            }
                        },
                        food:{
                            can_always_eat:1b,
                            eat_seconds:3600.0f,
                            nutrition:0,
                            saturation_modifier:0.0f
                        }
                    },
                    count:0,
                    id:"minecraft:iron_sword"
                }
            },
            text:"["
        }
    ]
}
```
