### ISSUE TITLE
Your updated version 5.0.1 is useless at all.

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [ViaVersion/ViaVersion#4059]
### `/viaversion dump` Output

[22:58:57 ERROR]: [ViaVersion] Error when posting ViaVersion dump java.net.ConnectException: Connection timed out: connect         at sun.nio.ch.Net.connect0(Native Method) ~[?:?]         at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]         at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]         at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]         at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]         at java.net.Socket.connect(Unknown Source) ~[?:?]         at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]         at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:?]         at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]         at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]         at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source) ~[?:?]         at com.viaversion.viaversion.util.DumpUtil.lambda$postDump$0(DumpUtil.java:94) ~[[跨越版本]ViaVersion-5.0.1.jar:?]         at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]         at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-318]         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]         at java.lang.Thread.run(Unknown Source) ~[?:?] [22:58:57 INFO]: Failed to dump, please check the console for more information [22:59:18 ERROR]: [ViaVersion] Failed to capture further info java.net.ConnectException: Connection timed out: connect         at sun.nio.ch.Net.connect0(Native Method) ~[?:?]         at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]         at sun.nio.ch.Net.connect(Unknown Source) ~[?:?]         at sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[?:?]         at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]         at java.net.Socket.connect(Unknown Source) ~[?:?]         at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) ~[?:?]         at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) ~[?:?]         at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]         at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]         at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]         at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]         at com.viaversion.viaversion.util.DumpUtil.printFailureInfo(DumpUtil.java:125) ~[[跨越版本]ViaVersion-5.0.1.jar:?]         at com.viaversion.viaversion.util.DumpUtil.lambda$postDump$0(DumpUtil.java:117) ~[[跨越版本]ViaVersion-5.0.1.jar:?]         at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]         at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-318]         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]         at java.lang.Thread.run(Unknown Source) ~[?:?]

### Console Error

Nothing

### Bug Description

When I tried to transfer from another server to this server, I was prompted that I was not 1.20.2, so I was not allowed to enter? You ViaBack eat for nothing?？？！

### Steps to Reproduce

1. install Viaback on paper-1.20.2-318.

2. Go in, and then I am very angry.
3. 
![image](https://github.com/user-attachments/assets/04a072f0-2060-421a-9836-88baabb22687)

### Expected Behavior

Enter as usual
I just want to get into the server. Is it that hard?

### Additional Server Info

[23:02:12 INFO]: Server Plugins (31):
[23:02:12 INFO]: Bukkit Plugins:
[23:02:12 INFO]:  - AnimatedScoreboard, AuthMe, ChestCommands, *ChineseNickName, Citizens, CMILib, *CommandNPC, ConsoleSpamFix, CoreProtect, dynmap
[23:02:12 INFO]:  Essentials, HideAndSeek, HolographicDisplays, LaggRemover, LibsDisguises, *LiteCustomAnnouncer, LuckPerms, Multiverse-Core, NoSpawnChunks, PlaceholderAPI
[23:02:12 INFO]:  PlugManX, ProtocolLib, Residence, *Shift_Menu, SkinsRestorer, TabTPS, TrChat, Vault, ViaBackwards, ViaVersion
[23:02:12 INFO]:  WorldEdit

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>
