### ISSUE TITLE
ViaVersion 5.0.3/4 does not start on Bungeecord/Waterfall

### ISSUE THREAD

**Issue by IceTecX** [ViaVersion/ViaVersion#4086]
### `/viaversion dump` Output

– Command not found – (Because not started)

### **Bungeecord (1857):**

```
[WARNING] Error loading plugin ViaVersion
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:341)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:284)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 13 more
```

_--> The same behavior can be observed under Waterfall._

### Bug Description

The current version and some previous versions of the plugin do not start correctly under Waterfall/Bungeecord. 
The errors are visible in the specified log.
Java 17 is used and the Bungeecord and Waterfall versions are always the latest.

### Steps to Reproduce

Take a fresh Bungeecord server and try to start the plugin with it. Java 17 should be used. No other Java version has been tested.
The plugin will not start successfully under Waterfall either.
If a much older version of the plugin is used, the start will succeed.

### Expected Behavior

The latest versions cannot be started when used under Bungeecord/Waterfall. The use under a normal spigot or paper server seems to work.
It was not run on both the proxy and the sub-server at the same time.

It should be possible to use it both independently on the proxy and independently on a spigot or paper server.

### Additional Server Info

The current bungee cord version and the current waterfall version were used for testing. As well as a current paper version. The versions were used unchanged and no other plugins were installed.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by kennytv** [comment]
See the 5.0.0 announcement and https://hangar.papermc.io/ViaVersion/ViaBungee, Bungee support was moved to an addon and doesn't properly work anymore. Ideally you should either switch to Velocity or move Via plugins to the backend servers
