### ISSUE TITLE
Internal Exception:io. netty.handler.codec.EncoderException:com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repositorySource O: com.viaversion.viaversion.rewriter.ItemRewriter$2 (Anonymous)

### ISSUE THREAD

**Issue by ServertheLord** [ViaVersion/ViaVersion#4096]
### `/viaversion dump` Output

https: //dump.viaversion.com/d5003dfe69dc63d3e60ae67c1265249a2e42f60c65a58eccb72a2bba67d0615c

### Console Error

[09:36:53 WARN]: java.net.SocketException: Connection reset
[09:36:53 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
[09:36:53 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
[09:36:53 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
[09:36:53 WARN]:        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
[09:36:53 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:
489)
[09:36:53 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord
.java:483)
[09:36:53 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.jav
a:160)
[09:36:53 WARN]:        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[09:36:53 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
[09:36:53 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java
:1421)
[09:36:53 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[09:36:53 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[09:36:53 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:
586)
[09:36:53 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(AbstractDelegateHttpsURLConnection.java:187)
[09:36:53 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLCon
nectionImpl.java:141)
[09:36:53 WARN]:        at EssentialsX-2.20.1.jar//com.earth2me.essentials.updatecheck.UpdateChecker.tryRe
questWithFallback(UpdateChecker.java:159)
[09:36:53 WARN]:        at EssentialsX-2.20.1.jar//com.earth2me.essentials.updatecheck.UpdateChecker.lambd
a$fetchLatestRelease$1(UpdateChecker.java:98)
[09:36:53 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:79)
[09:36:53 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[09:36:53 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerRepo
rtingWrapper.java:22)
[09:36:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1144)
[09:36:53 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:642)
[09:36:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Bug Description

I get an error when using VIA 5.0.3 and using 1.20.4 to enter a server with 1.21.1

### Steps to Reproduce

1.Use 1.20.4 to go to 1.21.1

### Expected Behavior

It should work fine

### Additional Server Info

Viaversion:VIA VB VR
Server version:1.21.1
BC:yes

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by FlorianMichael** [comment]
Try to update ViaBackwards
