### ISSUE TITLE
After the player exits the Nether, they are forcibly disconnected from the server

### ISSUE THREAD

**Issue by ShaoM7918** [ViaVersion/ViaVersion#4101]
### `/viaversion dump` Output

https://dump.viaversion.com/37872814399b05d2fbb40b443ee5becbe60ba6c819d8c4aa7a77811f61f9c979

### Console Error

```
[13:27:02 WARN] [viaversion]: ERROR IN Protocol1_20_3To1_20_5 IN REMAP OF LEVEL_CHUNK_WITH_LIGHT (0x25)
[13:27:02 ERROR]: [server connection] ShaoM7918 -> server2: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@211e46cb
io.netty.handler.codec.DecoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: LEVEL_CHUNK_WITH_LIGHT, Type: ChunkType1_20_2, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.BlockItemPacketRewriter1_20_5$$Lambda/0x000002c901d4a120, Packet ID: 39
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: LEVEL_CHUNK_WITH_LIGHT, Type: ChunkType1_20_2, Index: 1, Data: [], Source 0: com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.BlockItemPacketRewriter1_20_5$$Lambda/0x000002c901d4a120, Packet ID: 39
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(16618) + length(2) exceeds writerIndex(16618): PooledUnsafeDirectByteBuf(ridx: 16618, widx: 16618, cap: 16618)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        at com.viaversion.viaversion.api.type.types.chunk.ChunkSectionType1_18.read(ChunkSectionType1_18.java:45) ~[?:?]
        at com.viaversion.viaversion.api.type.types.chunk.ChunkType1_20_2.read(ChunkType1_20_2.java:59) ~[?:?]
        at com.viaversion.viaversion.api.type.types.chunk.ChunkType1_20_2.read(ChunkType1_20_2.java:37) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:140) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:185) ~[?:?]
        at com.viaversion.viaversion.rewriter.BlockRewriter.handleChunk1_19(BlockRewriter.java:248) ~[?:?]
        at com.viaversion.viaversion.protocols.v1_20_3to1_20_5.rewriter.BlockItemPacketRewriter1_20_5.lambda$registerPackets$0(BlockItemPacketRewriter1_20_5.java:142) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405) ~[?:?]
        at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337) ~[?:?]
        at com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313) ~[?:?]
        at com.viaversion.viaversion.api.connection.UserConnection.transformIncoming(UserConnection.java:246) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:48) ~[?:?]
        at com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler.decode(VelocityDecodeHandler.java:30) ~[?:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity-3.3.0-SNAPSHOT-415.jar:3.3.0-SNAPSHOT (git-00ed2284-b415)]
        ... 31 more
```

### Bug Description

1. Causing players to leave the server
2. This seems to be a probabilistic error, but the likelihood of the error occurring is generally higher than the likelihood of it not occurring.
3. Since this seems to be an issue related to lighting, I should mention that there are light source blocks near the Nether portal in the Overworld.

### Steps to Reproduce

1. Log in using the 1.20.6 client.
2. Enter the Nether.
3. Upon exiting the Nether, the player will be forcibly disconnected from the current server.

### Expected Behavior

When leaving the Nether, the player should return to the Overworld instead of being directly logged out of the server.

### Additional Server Info

1. I am using the Velocity proxy server.
2. The Paper server version is 1.20.4, and I am joining with version 1.20.6.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--00ed2284--b415%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--00ed2284--b415%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>

**Comment by ShaoM7918** [comment]
## Reproducing the error
https://github.com/user-attachments/assets/81b671c0-e7eb-47e9-b0e5-795239d1dafa

The above translations were all provided by ChatGPT.

**Comment by Godl1nk** [comment]
was this ever fixed

**Comment by kennytv** [comment]
I assume this would have been another plugin sending bad packets/modifying chunk data asynchronously
