### ISSUE TITLE
'void com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerMerchantOffers1_20_5(com.viaversion.viaversion.api.protocol.packet.ClientboundPacketType, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type)' initializing ViaVersion v5.0.4-SNAPSHOT (Is it up to date?)

### ISSUE THREAD

**Issue by madnessman666** [ViaVersion/ViaVersion#4107]
### `/viaversion dump` Output

https://dump.viaversion.com/28007da544155299b8c919ff7891b874150474dab12e4fa571329d3dd6c22d19

### Console Error

```
 [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_12_R1.CraftServer] 'void com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerMerchantOffers1_20_5(com.viaversion.viaversion.api.protocol.packet.ClientboundPacketType, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type)' initializing ViaVersion v5.0.4-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'void com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerMerchantOffers1_20_5(com.viaversion.viaversion.api.protocol.packet.ClientboundPacketType, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type)'
	at com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerPackets(BlockItemPacketRewriter1_21.java:82) ~[?:?]
	at com.viaversion.viaversion.api.rewriter.RewriterBase.register(RewriterBase.java:36) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.callRegister(AbstractProtocol.java:228) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.registerPackets(AbstractProtocol.java:212) ~[?:?]
	at com.viaversion.viabackwards.api.BackwardsProtocol.registerPackets(BackwardsProtocol.java:49) ~[?:?]
	at com.viaversion.viabackwards.protocol.v1_21to1_20_5.Protocol1_21To1_20_5.registerPackets(Protocol1_21To1_20_5.java:68) ~[?:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:106) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:203) ~[?:?]
	at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:197) ~[?:?]
	at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:143) ~[?:?]
	at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:38) ~[?:?]
	at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:115) ~[?:?]
	at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:323) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

### Bug Description

When viaversion has loaded and started injecting i got this error.

### Steps to Reproduce

1. Just start server.

### Expected Behavior

I expected normal work of plugin. I installed snapshot build because viaversion 5.0.3 randomly disconnects me with error.

### Additional Server Info

I have a velocity on which i did't installed viaversion. 

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--1620%20%28MC%3A%201.12.2%29](https://img.shields.io/badge/Platform-git--Paper--1620%20%28MC%3A%201.12.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.4-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.4--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.0.3): 12 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-12%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>mixed_via</details>
