### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Dianelito** [ViaVersion/ViaVersion#4119]
### `/viaversion dump` Output

https://dump.viaversion.com/dc2950c928838928d037c316831e58d99d6d4ee012f78e213863bf93f07aa604

### Console Error

[06:30:59 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[06:30:59 WARN]: [ViaVersion] There is a newer plugin version available: 5.0.3, you're on: 5.0.2
[06:30:59 WARN]: Failed to check for updates. HTTP response code: 404
[06:31:54 WARN]: [ViaVersion] ERROR IN Protocol1_21To1_20_5 IN REMAP OF UPDATE_ATTRIBUTES (0x75)
[06:31:54 WARN]: [ViaVersion] ERROR IN Protocol1_21To1_20_5 IN REMAP OF UPDATE_ATTRIBUTES (0x75)
[06:31:54 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[06:31:54 WARN]: Source 0: com.viaversion.viabackwards.protocol.v1_21to1_20_5.Protocol1_21To1_20_5$$Lambda/0x00007ff2b0042758
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[06:31:54 WARN]: at net.minecraft.network.Connection$2.write(Connection.java:771)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[06:31:54 WARN]: at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[06:31:54 WARN]: at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[06:31:54 WARN]: at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
[06:31:54 WARN]: at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
[06:31:54 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[06:31:54 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[06:31:54 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[06:31:54 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[06:31:54 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[06:31:54 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:31:54 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[06:31:54 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[06:31:54 WARN]: Source 0: com.viaversion.viabackwards.protocol.v1_21to1_20_5.Protocol1_21To1_20_5$$Lambda/0x00007ff2b0042758
[06:31:54 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[06:31:54 WARN]: at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[06:31:54 WARN]: at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[06:31:54 WARN]: at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[06:31:54 WARN]: at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[06:31:54 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[06:31:54 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[06:31:54 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[06:31:54 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[06:31:54 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.protocols.v1_20_5to1_21.Protocol1_20_5To1_21.mapAttributeId(Protocol1_20_5To1_21.java:173)
[06:31:54 WARN]: at ViaBackwards-5.0.2.jar//com.viaversion.viabackwards.protocol.v1_21to1_20_5.Protocol1_21To1_20_5.lambda$registerPackets$2(Protocol1_21To1_20_5.java:169)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[06:31:54 WARN]: at net.minecraft.network.Connection$2.write(Connection.java:771)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[06:31:54 WARN]: at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[06:31:54 WARN]: at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[06:31:54 WARN]: at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
[06:31:54 WARN]: at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
[06:31:54 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[06:31:54 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[06:31:54 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[06:31:54 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[06:31:54 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[06:31:54 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:31:54 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[06:31:54 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[06:31:54 WARN]: Source 0: com.viaversion.viabackwards.protocol.v1_21to1_20_5.Protocol1_21To1_20_5$$Lambda/0x00007ff2b0042758
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[06:31:54 WARN]: at net.minecraft.network.Connection$2.write(Connection.java:771)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[06:31:54 WARN]: at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[06:31:54 WARN]: at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[06:31:54 WARN]: at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
[06:31:54 WARN]: at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
[06:31:54 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[06:31:54 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[06:31:54 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[06:31:54 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[06:31:54 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[06:31:54 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:31:54 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
[06:31:54 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[06:31:54 WARN]: Source 0: com.viaversion.viabackwards.protocol.v1_21to1_20_5.Protocol1_21To1_20_5$$Lambda/0x00007ff2b0042758
[06:31:54 WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[06:31:54 WARN]: at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846)
[06:31:54 WARN]: at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338)
[06:31:54 WARN]: at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516)
[06:31:54 WARN]: at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471)
[06:31:54 WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[06:31:54 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[06:31:54 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[06:31:54 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[06:31:54 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.protocols.v1_20_5to1_21.Protocol1_20_5To1_21.mapAttributeId(Protocol1_20_5To1_21.java:173)
[06:31:54 WARN]: at ViaBackwards-5.0.2.jar//com.viaversion.viabackwards.protocol.v1_21to1_20_5.Protocol1_21To1_20_5.lambda$registerPackets$2(Protocol1_21To1_20_5.java:169)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:405)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:369)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:337)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:313)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[06:31:54 WARN]: at ViaVersion-5.0.2.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140)
[06:31:54 WARN]: at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[06:31:54 WARN]: at net.minecraft.network.Connection$2.write(Connection.java:771)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[06:31:54 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[06:31:54 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[06:31:54 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[06:31:54 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[06:31:54 WARN]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:31:54 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)

### Bug Description

solo estuve dentro y lo mando

### Steps to Reproduce

solo estuve dentro y lo mando

### Expected Behavior

puse nomas un bloque

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: 1.21--2279--9e444c5%20%28MC%3A%201.21%29](https://img.shields.io/badge/Platform-1.21--2279--9e444c5%20%28MC%3A%201.21%29-3498db?style=flat-square) </br>![ViaVersion: Outdated](https://img.shields.io/badge/ViaVersion%20(5.0.2)-Outdated!-red?style=flat-square) </br>![ViaRewind(4.0.2): 7 commits behind master](https://img.shields.io/badge/ViaRewind%20(4.0.2)-7%20commit(s)%20behind%20master-yellow?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.2)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>broken_jar</details>
