### ISSUE TITLE
Error Viaversion server BungeeCord 

### ISSUE THREAD

**Issue by Zenooooox** [ViaVersion/ViaVersion#4125]
### `/viaversion dump` Output

dont work

### Console Error

Error loading plugin ViaVersion
java.lang.UnsupportedClassVersionError: com/viaversion/viaversion/ViaVersionPlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 59.0
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
    at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:341)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:284)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Bug Description

My server are in 1.16.3 and when i launch my bungee console the console said me that and i tried to install the viaversion java 8

### Steps to Reproduce

Launch the Bungee console

### Expected Behavior

qddsqdssdsq

### Additional Server Info

I use BungeeCord

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Kichura** [comment]
1. Your java version is too old, Must be version 17 or later.
2. Bungeecord by default is no longer supported, Move ViaVersion to the spigot/paper servers or migrate to velocity.
