### ISSUE TITLE
ProxyInitializeEvent

### ISSUE THREAD

**Issue by Cengiouwe** [ViaVersion/ViaVersion#4194]
### `/viaversion dump` Output

https://dump.viaversion.com/a78c5e8fe642f78972a3dc54c12041fa2ad3166a41a2a830eaef151374326c8f

### Console Error

```
[18:59:50 ERROR]: Couldn't pass ProxyInitializeEvent to viaversion 5.0.5
java.lang.NoSuchMethodError: 'void com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerMerchantOffers1_20_5(com.viaversion.viaversion.api.protocol.packet.ClientboundPacketType, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type)'
        at com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerPackets(BlockItemPacketRewriter1_21.java:82) ~[?:?]
        at com.viaversion.viaversion.api.rewriter.RewriterBase.register(RewriterBase.java:36) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.callRegister(AbstractProtocol.java:228) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.registerPackets(AbstractProtocol.java:212) ~[?:?]
        at com.viaversion.viabackwards.api.BackwardsProtocol.registerPackets(BackwardsProtocol.java:49) ~[?:?]
        at com.viaversion.viabackwards.protocol.v1_21to1_20_5.Protocol1_21To1_20_5.registerPackets(Protocol1_21To1_20_5.java:68) ~[?:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:106) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:205) ~[?:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:199) ~[?:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:143) ~[?:?]
        at com.viaversion.viabackwards.VelocityPlugin.lambda$onProxyStart$0(VelocityPlugin.java:54) ~[?:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:115) ~[?:?]
        at com.viaversion.viaversion.VelocityPlugin.onProxyLateInit(VelocityPlugin.java:112) ~[?:?]
        at com.viaversion.viaversion.Lmbda$8.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-78f6cfc2-b433)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.3.0-SNAPSHOT (git-78f6cfc2-b433)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.3.0-SNAPSHOT (git-78f6cfc2-b433)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

### Bug Description

Couldn't pass ProxyInitializeEvent to viaversion 5.0.5 so players can't join the server.

### Steps to Reproduce

1. download 5.05 on velocity and restart the server after that

### Expected Behavior

That players can join

### Additional Server Info

Velocity.

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: velocity%203.3.0--SNAPSHOT%20%28git--78f6cfc2--b433%29](https://img.shields.io/badge/Platform-velocity%203.3.0--SNAPSHOT%20%28git--78f6cfc2--b433%29-3498db?style=flat-square) </br>![Proxy is 12 builds behind](https://img.shields.io/badge/Your%20proxy%20is%2012%20build(s)%20behind.%20Please%20update%20to%20the%20latest%20version-orange?style=flat-square) </br>![ViaVersion (5.0.5): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.3)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>mixed_via</details>
