### ISSUE TITLE
com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerMerchantOffers1_20_5

### ISSUE THREAD

**Issue by More678** [ViaVersion/ViaVersion#4196]
### `/viaversion dump` Output

https://dump.viaversion.com/38ccae20b8deba987801fa9ced0d2a4903e54fd9d0fedf969b15c157feced97d

### Console Error

```
[00:50:29 ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] 'void com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerMerchantOffers1_20_5(com.viaversion.viaversion.api.protocol.packet.ClientboundPacketType, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type)' initializing ViaVersion v5.0.5 (Is it up to date?)
java.lang.NoSuchMethodError: 'void com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerMerchantOffers1_20_5(com.viaversion.viaversion.api.protocol.packet.ClientboundPacketType, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type, com.viaversion.viaversion.api.type.Type)'
        at com.viaversion.viabackwards.protocol.v1_21to1_20_5.rewriter.BlockItemPacketRewriter1_21.registerPackets(BlockItemPacketRewriter1_21.java:77) ~[ViaBackwards-5.0.0.jar:?]
        at com.viaversion.viaversion.api.rewriter.RewriterBase.register(RewriterBase.java:36) ~[ViaVersion-5.0.5.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.callRegister(AbstractProtocol.java:228) ~[ViaVersion-5.0.5.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.registerPackets(AbstractProtocol.java:212) ~[ViaVersion-5.0.5.jar:?]
        at com.viaversion.viabackwards.api.BackwardsProtocol.registerPackets(BackwardsProtocol.java:49) ~[ViaBackwards-5.0.0.jar:?]
        at com.viaversion.viabackwards.protocol.v1_21to1_20_5.Protocol1_21To1_20_5.registerPackets(Protocol1_21To1_20_5.java:65) ~[ViaBackwards-5.0.0.jar:?]
        at com.viaversion.viaversion.api.protocol.AbstractProtocol.initialize(AbstractProtocol.java:106) ~[ViaVersion-5.0.5.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:205) ~[ViaVersion-5.0.5.jar:?]
        at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocol(ProtocolManagerImpl.java:199) ~[ViaVersion-5.0.5.jar:?]
        at com.viaversion.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:143) ~[ViaBackwards-5.0.0.jar:?]
        at com.viaversion.viabackwards.BukkitPlugin.lambda$new$0(BukkitPlugin.java:38) ~[ViaBackwards-5.0.0.jar:?]
        at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:115) ~[ViaVersion-5.0.5.jar:?]
        at com.viaversion.viaversion.ViaVersionPlugin.onLoad(ViaVersionPlugin.java:84) ~[ViaVersion-5.0.5.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-272]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-272]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
 
```

### Bug Description

When I try to connect to the server, I will need to wait for about 45 seconds

### Steps to Reproduce

ViaVersion 5.0.5
Java 17.0.12
Minecraft Paper 1.18.2
Ubuntu 22.04

### Expected Behavior

wait

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--272%20%28MC%3A%201.18.2%29](https://img.shields.io/badge/Platform-git--Paper--272%20%28MC%3A%201.18.2%29-3498db?style=flat-square) </br>![ViaVersion (5.0.5): Even with master](https://img.shields.io/badge/ViaVersion%20(5.0.5)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards: Outdated](https://img.shields.io/badge/ViaBackwards%20(5.0.0)-Outdated!-red?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3><br><details><summary></summary>mixed_via</details>
