### ISSUE TITLE
Unable to log in with version 1.21.2/3

### ISSUE THREAD

**Issue by tommasov03** [ViaVersion/ViaVersion#4230]
### `/viaversion dump` Output

https://dump.viaversion.com/76e033e06450908b39856b46a96953a6a75f1eeaac406e7789c1804e6559b773

### Console Error

[01:48:07] [User Authenticator #1/INFO]: UUID of player test7367583 is 341a31f4-ad2c-42b9-af6d-1d85adac6535
[01:48:07] [Server thread/INFO]: test7367583[/2.42.61.112:57718] logged in with entity id 579 at ([hubCentrale]0.5, 60.0, 0.5)
[01:48:08] [Netty Epoll Server IO #3/WARN]: [ViaVersion] ERROR IN Protocol1_20_2To1_20_3 IN REMAP OF SET_OBJECTIVE (0x5A)
[01:48:08] [Netty Epoll Server IO #3/WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.interactiveboard.utility.nms.handler.PacketHandler$$Lambda/0x00007f289a7b7a50@4c0a6bef
com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SET_OBJECTIVE, Index: 3, Type: ComponentType, Data: [{StringType: }, {ByteType: 0}], Packet ID: 92, Source 0: com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3$$Lambda/0x00007f2898ffe460
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(5) + length(32) exceeds writerIndex(19): PooledUnsafeDirectByteBuf(ridx: 5, widx: 19, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:43) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.type.types.ComponentType.read(ComponentType.java:34) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.readFromBuffer(PacketWrapperImpl.java:142) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:136) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3.convertComponent(Protocol1_20_2To1_20_3.java:347) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3.lambda$registerPackets$1(Protocol1_20_2To1_20_3.java:111) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:413) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.transformPacket(ViaTransformedSender.kt:41) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.sendPackets(ViaTransformedSender.kt:55) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.strategy.ViaPacketStrategy.sendPackets(ViaPacketStrategy.kt:8) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.scheduleSendPackets$lambda$2(PacketHandler.kt:123) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.onLoop$lambda$1(PacketHandler.kt:113) ~[InteractiveBoard 2.1.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:48:08] [Netty Epoll Server IO #3/WARN]: [ViaVersion] ERROR IN Protocol1_20_2To1_20_3 IN REMAP OF SET_OBJECTIVE (0x5A)
[01:48:08] [Netty Epoll Server IO #3/WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.interactiveboard.utility.nms.handler.PacketHandler$$Lambda/0x00007f289a7b7a50@7207765c
com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SET_OBJECTIVE, Index: 1, Type: StringType, Data: [], Packet ID: 92, Source 0: com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3$$Lambda/0x00007f2898ffe460
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(110) exceeds writerIndex(19): PooledUnsafeDirectByteBuf(ridx: 2, widx: 19, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.readFromBuffer(PacketWrapperImpl.java:142) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:190) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3.lambda$registerPackets$1(Protocol1_20_2To1_20_3.java:108) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:413) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.transformPacket(ViaTransformedSender.kt:41) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.sendPackets(ViaTransformedSender.kt:55) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.strategy.ViaPacketStrategy.sendPackets(ViaPacketStrategy.kt:8) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.scheduleSendPackets$lambda$2(PacketHandler.kt:123) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.onLoop$lambda$1(PacketHandler.kt:113) ~[InteractiveBoard 2.1.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:48:08] [Netty Epoll Server IO #3/WARN]: [ViaVersion] ERROR IN Protocol1_20_2To1_20_3 IN REMAP OF SET_OBJECTIVE (0x5A)
[01:48:08] [Netty Epoll Server IO #3/WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.interactiveboard.utility.nms.handler.PacketHandler$$Lambda/0x00007f289a7b7a50@678625be
com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SET_OBJECTIVE, Index: 1, Type: StringType, Data: [], Packet ID: 92, Source 0: com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3$$Lambda/0x00007f2898ffe460
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(219) exceeds writerIndex(20): PooledUnsafeDirectByteBuf(ridx: 3, widx: 20, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.readFromBuffer(PacketWrapperImpl.java:142) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:190) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3.lambda$registerPackets$1(Protocol1_20_2To1_20_3.java:108) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:413) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.transformPacket(ViaTransformedSender.kt:41) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.sendPackets(ViaTransformedSender.kt:55) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.strategy.ViaPacketStrategy.sendPackets(ViaPacketStrategy.kt:8) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.scheduleSendPackets$lambda$2(PacketHandler.kt:123) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.onLoop$lambda$1(PacketHandler.kt:113) ~[InteractiveBoard 2.1.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:48:08] [Netty Epoll Server IO #3/WARN]: [ViaVersion] ERROR IN Protocol1_20_2To1_20_3 IN REMAP OF SET_OBJECTIVE (0x5A)
[01:48:08] [Netty Epoll Server IO #3/WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.interactiveboard.utility.nms.handler.PacketHandler$$Lambda/0x00007f289a7b7a50@7eaa81af
com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SET_OBJECTIVE, Index: 1, Type: StringType, Data: [], Packet ID: 92, Source 0: com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3$$Lambda/0x00007f2898ffe460
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(218) exceeds writerIndex(35): PooledUnsafeDirectByteBuf(ridx: 3, widx: 35, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.readFromBuffer(PacketWrapperImpl.java:142) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:190) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3.lambda$registerPackets$1(Protocol1_20_2To1_20_3.java:108) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:413) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.transformPacket(ViaTransformedSender.kt:41) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.sendPackets(ViaTransformedSender.kt:55) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.strategy.ViaPacketStrategy.sendPackets(ViaPacketStrategy.kt:8) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.scheduleSendPackets$lambda$2(PacketHandler.kt:123) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.onLoop$lambda$1(PacketHandler.kt:113) ~[InteractiveBoard 2.1.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:48:08] [Netty Epoll Server IO #3/WARN]: [ViaVersion] ERROR IN Protocol1_20_2To1_20_3 IN REMAP OF SET_OBJECTIVE (0x5A)
[01:48:08] [Netty Epoll Server IO #3/WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.interactiveboard.utility.nms.handler.PacketHandler$$Lambda/0x00007f289a7b7a50@2e9f2fc2
com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SET_OBJECTIVE, Index: 1, Type: StringType, Data: [], Packet ID: 92, Source 0: com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3$$Lambda/0x00007f2898ffe460
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(109) exceeds writerIndex(34): PooledUnsafeDirectByteBuf(ridx: 2, widx: 34, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:55) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.readFromBuffer(PacketWrapperImpl.java:142) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:190) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3.lambda$registerPackets$1(Protocol1_20_2To1_20_3.java:108) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:413) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.transformPacket(ViaTransformedSender.kt:41) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.sendPackets(ViaTransformedSender.kt:55) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.strategy.ViaPacketStrategy.sendPackets(ViaPacketStrategy.kt:8) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.scheduleSendPackets$lambda$2(PacketHandler.kt:123) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.onLoop$lambda$1(PacketHandler.kt:113) ~[InteractiveBoard 2.1.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:48:08] [Netty Epoll Server IO #3/WARN]: [ViaVersion] ERROR IN Protocol1_20_2To1_20_3 IN REMAP OF SET_OBJECTIVE (0x5A)
[01:48:08] [Netty Epoll Server IO #3/WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.interactiveboard.utility.nms.handler.PacketHandler$$Lambda/0x00007f289a7b7a50@6e2cf99
com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
Packet Type: SET_OBJECTIVE, Index: 1, Type: StringType, Data: [], Packet ID: 92, Source 0: com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3$$Lambda/0x00007f2898ffe460
Caused by: java.lang.IndexOutOfBoundsException: index: 3, length: 489 (expected: range(0, 256))
	at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:481) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:130) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1270) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246) ~[netty-buffer-4.1.87.Final.jar:4.1.87.Final]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:54) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.readFromBuffer(PacketWrapperImpl.java:142) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.passthrough(PacketWrapperImpl.java:190) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocols.v1_20_2to1_20_3.Protocol1_20_2To1_20_3.lambda$registerPackets$1(Protocol1_20_2To1_20_3.java:108) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:413) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410) ~[ViaVersion-5.1.1-SNAPSHOT.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.transformPacket(ViaTransformedSender.kt:41) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.integrations.via.ViaTransformedSender.sendPackets(ViaTransformedSender.kt:55) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.strategy.ViaPacketStrategy.sendPackets(ViaPacketStrategy.kt:8) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.scheduleSendPackets$lambda$2(PacketHandler.kt:123) ~[InteractiveBoard 2.1.0.jar:?]
	at com.interactiveboard.utility.nms.handler.PacketHandler.onLoop$lambda$1(PacketHandler.kt:113) ~[InteractiveBoard 2.1.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:48:08] [Server thread/INFO]: test7367583 lost connection: Disconnected

### Bug Description

Unable to log in with version 1.21.2/3

### Steps to Reproduce

Enter with version 1.21.2/3 of the game

### Expected Behavior

That you could enter with the latest versions

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by tommasov03** [comment]
> ![Platform: git--UniverseSpigot--%220275a0e%22%20%28MC%3A%201.20.1%29](https://camo.githubusercontent.com/056ac00d2ffee06e9ba6a98c0263762c64679dd754fd9cfbc465449d5bea5544/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d556e697665727365537069676f742d2d253232303237356130652532322532302532384d43253341253230312e32302e312532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (5.1.1-SNAPSHOT): Even with master](https://camo.githubusercontent.com/e7f0db24fa8bb9cbce5453e4f285ae9e21210d4d82eb49a240fd4321f6e4bb89/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028352e312e312d2d534e415053484f54292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaRewind(4.0.3): Even with master](https://camo.githubusercontent.com/b6657dc5b1cb2293f5fccd8d47c408b25f5eecdf297fd88306f0afefc228cde9/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f566961526577696e6425323028342e302e33292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaBackwards(5.1.1-SNAPSHOT): 1 commits behind master](https://camo.githubusercontent.com/50c5523041430c561456dd9f169de64098f128d2512510327f1487f3e28f113d/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028352e312e312d2d534e415053484f54292d31253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please update **all** Via* plugins from https://ci.viaversion.com/.In case the issue still persists send the new dump and the issue will be reopened

https://dump.viaversion.com/89f33113ad77fdc45e60a563f7cf5787d9b39f234021b44a58754db98552b001

**Comment by Barvalg** [comment]
![Platform: git--UniverseSpigot--%220275a0e%22%20%28MC%3A%201.20.1%29](https://img.shields.io/badge/Platform-git--UniverseSpigot--%220275a0e%22%20%28MC%3A%201.20.1%29-3498db?style=flat-square) </br>![ViaVersion (5.1.1-SNAPSHOT): Even with master](https://img.shields.io/badge/ViaVersion%20(5.1.1--SNAPSHOT)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaRewind(4.0.3): Even with master](https://img.shields.io/badge/ViaRewind%20(4.0.3)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(5.1.1-SNAPSHOT): 1 commits behind master](https://img.shields.io/badge/ViaBackwards%20(5.1.1--SNAPSHOT)-1%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please update **all** Via* plugins from [https://ci.viaversion.com/](https://ci.viaversion.com/).In case the issue still persists send the new dump and the issue will be reopened</h3>

**Comment by Kichura** [comment]
Caused by InteractiveBoard sending bad objective changes to server.
