### ISSUE TITLE
lost connection: Internal Exception: io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by pmaroun** [ViaVersion/ViaVersion#4288]
### `/viaversion dump` Output

n/a

### Console Error

```
[16:27:18 WARN]: [ViaVersion] ERROR IN Protocol1_21To1_20_5 IN REMAP OF CONTAINER_SET_SLOT (0x15)
[16:27:18 WARN]: io.netty.handler.codec.EncoderException: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[16:27:18 WARN]: Packet Type: CONTAINER_SET_SLOT, Index: 4, Type: ItemType1_20_5, Data: [{Unsigned Byte: -2}, {VarInt: 0}, {ShortType: 2}], Packet ID: 21, Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$$Lambda/0x000071c691150db8
[16:27:18 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:27:18 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:27:18 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:27:18 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[16:27:18 WARN]:        at net.minecraft.network.Connection$2.write(Connection.java:762)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[16:27:18 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[16:27:18 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
[16:27:18 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
[16:27:18 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:27:18 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:27:18 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:27:18 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[16:27:18 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:27:18 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:27:18 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[16:27:18 WARN]: Caused by: com.viaversion.viaversion.exception.InformativeException: Please report this on the Via support Discord or open an issue on the relevant GitHub repository
[16:27:18 WARN]: Packet Type: CONTAINER_SET_SLOT, Index: 4, Type: ItemType1_20_5, Data: [{Unsigned Byte: -2}, {VarInt: 0}, {ShortType: 2}], Packet ID: 21, Source 0: com.viaversion.viaversion.rewriter.ItemRewriter$$Lambda/0x000071c691150db8
[16:27:18 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(14) + length(1) exceeds writerIndex(14): PooledUnsafeDirectByteBuf(ridx: 14, widx: 14, cap: 256)
[16:27:18 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[16:27:18 WARN]:        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.VarIntType.readPrimitive(VarIntType.java:45)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:49)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.StringType.read(StringType.java:32)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.minecraft.item.data.StatePropertyMatcher$1.read(StatePropertyMatcher.java:37)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.minecraft.item.data.StatePropertyMatcher$1.read(StatePropertyMatcher.java:34)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:49)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:30)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.minecraft.item.data.BlockPredicate$1.read(BlockPredicate.java:41)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.minecraft.item.data.BlockPredicate$1.read(BlockPredicate.java:37)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:49)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.ArrayType.read(ArrayType.java:30)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.minecraft.item.data.AdventureModePredicate$1.read(AdventureModePredicate.java:34)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.minecraft.item.data.AdventureModePredicate$1.read(AdventureModePredicate.java:31)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.item.StructuredDataType.readData(StructuredDataType.java:65)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.item.StructuredDataType.read(StructuredDataType.java:57)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.item.ItemType1_20_5.readData(ItemType1_20_5.java:68)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.item.ItemType1_20_5.read(ItemType1_20_5.java:55)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.type.types.item.ItemType1_20_5.read(ItemType1_20_5.java:38)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.readFromBuffer(PacketWrapperImpl.java:142)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.read(PacketWrapperImpl.java:136)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.rewriter.ItemRewriter.passthroughClientboundItem(ItemRewriter.java:455)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.rewriter.ItemRewriter.lambda$registerSetSlot1_17_1$4(ItemRewriter.java:160)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.api.protocol.AbstractProtocol.transform(AbstractProtocol.java:413)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.protocol.packet.PacketWrapperImpl.apply(PacketWrapperImpl.java:410)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.protocol.ProtocolPipelineImpl.transform(ProtocolPipelineImpl.java:122)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transform(UserConnectionImpl.java:347)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.connection.UserConnectionImpl.transformClientbound(UserConnectionImpl.java:323)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:58)
[16:27:18 WARN]:        at ViaVersion-5.1.1.jar//com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:35)
[16:27:18 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:27:18 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:27:18 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[16:27:18 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[16:27:18 WARN]:        at net.minecraft.network.Connection$2.write(Connection.java:762)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[16:27:18 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[16:27:18 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[16:27:18 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:513)
[16:27:18 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498)
[16:27:18 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[16:27:18 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[16:27:18 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[16:27:18 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[16:27:18 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[16:27:18 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:27:18 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```

### Bug Description

Installed and configured on the latest version of paper today.  
Using this version:   https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.1.1/PAPER/ViaVersion-5.1.1.jar
Using Forge client 1.20.1.

### Steps to Reproduce

Son just playing a game with forge 1.20.1 client.  He has been kicked off the server 3 times this afternoon as a result of this

### Expected Behavior

does not kick a player off the server

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. Velocity), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Error: Invalid or missing dump](https://img.shields.io/badge/Error-Invalid/missing%20dump-red?style=flat-square) </br>

**Comment by Jo0001** [comment]
Please follow the issue template
